--
-- Copyright 2005-2013 The Kuali Foundation
--
-- Licensed under the Educational Community License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.opensource.org/licenses/ecl2.php
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('notsys','RELOAD_ACTION_LIST12184880071431001','true',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','ACTION_LIST_SIZE_NEW','10',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','ACTION_REQUESTED_COL_SHOW_NEW','yes',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','CLEAR_FYI_COL_SHOW_NEW','yes',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DATE_CREATED_COL_SHOW_NEW','yes',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DELEGATOR_COL_SHOW_NEW','yes',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DELEGATOR_FILTER','Secondary Delegators on Action List Page',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DOCUMENT_STATUS_COLOR_A','white',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DOCUMENT_STATUS_COLOR_C','white',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DOCUMENT_STATUS_COLOR_D','white',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DOCUMENT_STATUS_COLOR_E','white',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DOCUMENT_STATUS_COLOR_F','white',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DOCUMENT_STATUS_COLOR_I','white',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DOCUMENT_STATUS_COLOR_P','white',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DOCUMENT_STATUS_COLOR_R','white',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DOCUMENT_STATUS_COLOR_S','white',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DOCUMENT_STATUS_COLOR_X','white',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DOCUMENT_STATUS_COL_SHOW_NEW','yes',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DOC_TYPE_COL_SHOW_NEW','yes',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DocSearch.LastSearch.Holding0','{"dateCreatedFrom":1225778400000,"documentStatuses":[],"documentStatusCategories":[],"documentAttributeValues":{},"additionalDocumentTypeNames":[]}',10);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DocSearch.LastSearch.Holding1','{"dateCreatedFrom":1225778400000,"documentStatuses":[],"documentStatusCategories":[],"documentAttributeValues":{},"additionalDocumentTypeNames":[]}',10);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DocSearch.LastSearch.Holding2','{"dateCreatedFrom":1228111200000,"documentStatuses":[],"documentStatusCategories":[],"documentAttributeValues":{},"additionalDocumentTypeNames":[]}',10);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DocSearch.LastSearch.Holding3','{"dateCreatedFrom":1225515600000,"documentStatuses":[],"documentStatusCategories":[],"documentAttributeValues":{},"additionalDocumentTypeNames":[]}',10);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DocSearch.LastSearch.Holding4','{"dateCreatedFrom":1229925600000,"documentStatuses":[],"documentStatusCategories":[],"documentAttributeValues":{},"additionalDocumentTypeNames":[]}',10);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DocSearch.LastSearch.Order','DocSearch.LastSearch.Holding4,DocSearch.LastSearch.Holding3,DocSearch.LastSearch.Holding2,DocSearch.LastSearch.Holding1,DocSearch.LastSearch.Holding0',50);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','EMAIL_NOTIFICATION','immediate',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','EMAIL_NOTIFY_PRIMARY','yes',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','EMAIL_NOTIFY_SECONDARY','no',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','INITIATOR_COL_SHOW_NEW','yes',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','LAST_APPROVED_DATE_COL_SHOW_NEW','no',2);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','OPEN_ITEMS_NEW_WINDOW','yes',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','REFRESH_RATE','15',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','RELOAD_ACTION_LIST12222681199221040','true',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','RELOAD_ACTION_LIST12258344986401220','true',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','RELOAD_ACTION_LIST12258351399061221','true',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','RELOAD_ACTION_LIST12258354130781222','true',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','RELOAD_ACTION_LIST12258358639841223','true',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','TITLE_COL_SHOW_NEW','yes',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DocSearch.NamedSearch.FindStaff','yes',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DocSearch.NamedSearch.FindStudent','yes',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DocSearch.NamedSearch.FindAlumni','yes',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','USE_OUT_BOX','yes',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','WORKGROUP_REQUEST_COL_SHOW_NEW','yes',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('doug','RELOAD_ACTION_LIST12228720516001099','true',1);
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('edna','RELOAD_ACTION_LIST12228712966521080','true',1);
