package org.kuali.ole.deliver.checkout

import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.util.NoticeInfo
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.DroolsResponse


rule "Renewal Policy STKS/QU"
agenda-group "renewal validation"
activation-group "renewal validation"
when

$l: OleLoanDocument()

$n: NoticeInfo()

 $d : DroolsResponse()

$p: OlePatronDocument(getBorrowerTypeCode() in
("QUNLIM_ACD","QUNLIM_PHD","QUNLIM_NONUC"))

$i: OleItemRecordForCirc(getItemType() in ("stks","games","mus"),
getItemLocation() not in ("Resup", "ResupC","ResupD","ResupE","ResupS"))

then

$d.setRuleMatched(true);
$l.setCirculationPolicyId("Renewal Policy STKS/QU");
$l.loanPeriod(OLEConstants.FIXED_DUE_DATE,null); // This method takes due date and recall period as arguments.
$n.setNoticeType(DroolsConstants.REGULAR_LOANS_NOTICE_CONFIG);
 end

 
