package org.kuali.ole.deliver.checkout

import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.util.NoticeInfo
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.bo.OleDeliverRequestBo
import org.kuali.ole.deliver.util.ErrorMessage
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.DroolsResponse


rule "Circ Policy STKS/Q for Renewal"
agenda-group "renewal validation"
activation-group "renewal validation"
when

 $d : DroolsResponse()

$l: OleLoanDocument(Integer.valueOf(getNumberOfRenewals()) < 3)

$n: NoticeInfo()

$p: OlePatronDocument(getBorrowerTypeCode() in
("QCOL","QGRAD","QDEPT","QNONDEG","QNONUC","QNONUC25","QSTF","QOTHER","QALUM25"))

$i: OleItemRecordForCirc(getItemType() in ("stks","games","mus"),
getItemLocation() not in ("Resup", "ResupC","ResupD","ResupE","ResupS"),
$dr:getOleDeliverRequestBo(), null== $dr, $dr.getRequestTypeCode() in ("Recall/Hold Request", "Hold/Hold Request", "Page/Hold Request", "ASR Request"))


then

$d.setRuleMatched(true);
$l.loanPeriod(OLEConstants.FIXED_DUE_DATE,null); // This method takes due date and recall period as arguments.
 end

 rule "Circ Policy STKS/Q for Renewal for renewal item count greater than 3"
 agenda-group "renewal validation"
 activation-group "renewal validation"
 when

 $l: OleLoanDocument(Integer.valueOf(getNumberOfRenewals()) >= 3)

 $d : DroolsResponse()

 $n: NoticeInfo()

 $p: OlePatronDocument(getBorrowerTypeCode() in
 ("QCOL","QGRAD","QDEPT","QNONDEG","QNONUC","QNONUC25","QSTF","QOTHER","QALUM25"))

 $i: OleItemRecordForCirc(getItemType() in ("stks","games","mus"),
 getItemLocation() not in ("Resup", "ResupC","ResupD","ResupE","ResupS"))
 

 then
 
$d.setRuleMatched(true);
 $d.addErrorMessage("Patron has more than allowed limit of renewals");
 $d.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION);
 $l.loanPeriod(OLEConstants.FIXED_DUE_DATE,null); // This method takes due date and recall period as arguments.
  end