package org.kuali.ole.deliver.checkout

import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.util.NoticeInfo
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.bo.OleDeliverRequestBo
import org.kuali.ole.deliver.util.ErrorMessage
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.DroolsResponse

rule "Circ Policy STKS/QU for Renewal with existing request"
agenda-group "renewal validation"
activation-group "renewal validation"
when

 $d : DroolsResponse()

$l: OleLoanDocument()

$n: NoticeInfo()

$p: OlePatronDocument()

$i: OleItemRecordForCirc($dr:getOleDeliverRequestBo(), null!= $dr)

then

$d.setRuleMatched(true);
 $d.addErrorMessage("The item cannot be renewed because it has been requested.");
 $d.addErrorMessageCode("ErrorMessageFromRule");
 end


rule "Renewal Policy STKS/QU"
agenda-group "renewal validation"
activation-group "renewal validation"
when

$l: OleLoanDocument()

$n: NoticeInfo()

 $d : DroolsResponse()

$p: OlePatronDocument(getBorrowerTypeCode() in
("QUNLIM_ACD","QUNLIM_PHD","QUNLIM_NONUC"))

$i: OleItemRecordForCirc(getItemType() in ("stks","games","mus"),
getItemLocation() not in ("Resup", "ResupC","ResupD","ResupE","ResupS"),
$dr:getOleDeliverRequestBo(), null== $dr)

then

$d.setRuleMatched(true);
$l.setCirculationPolicyId("Renewal Policy STKS/QU");
$l.loanPeriod(OLEConstants.FIXED_DUE_DATE,null); // This method takes due date and recall period as arguments.
end








 
