package org.kuali.ole.deliver.checkout

import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "Renewal Policy Set Wanted for Reserve"
agenda-group "renewal validation"
activation-group "renewal validation"
when

$l: OleLoanDocument()
$n: NoticeInfo()
 $d : DroolsResponse()

$i: OleItemRecordForCirc(getItemLocation() in ("Resup", "ResupC","ResupD","ResupE","ResupS"))


then
$d.setRuleMatched(true);
$d.addErrorMessage("Items wanted for reserve may not be renewed");
 end

