package org.kuali.ole.deliver.rules.chicago.general_checks

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.DroolsResponse
import java.util.Date
import org.kuali.ole.deliver.drools.DroolsConstants


rule "Is Patron with General Block For vufind"
agenda-group "lookup-user-vufind"
when
$p : OlePatronDocument(isGeneralBlock())
$d : DroolsResponse()
then
$d.addErrorMessage("Patron is blocked");
end

rule "Is Patron Expired For vufind"
agenda-group "lookup-user-vufind"
when
$p : OlePatronDocument(getExpirationDate() != null, $e: getExpirationDate(), $e < currentDateForVuFind())
$d : DroolsResponse()
then
$d.addErrorMessage("Patron has expired");
end

rule "Is Patron Active For vufind"
agenda-group "lookup-user-vufind"
when
$p : OlePatronDocument(!isActiveIndicator())
$d : DroolsResponse()
then
$d.addErrorMessage("Patron is Inactive");
end

rule "Activation Date for Patron For vufind"
agenda-group "lookup-user-vufind"
when
$p : OlePatronDocument(getActivationDate()!= null, $e: getActivationDate(), $e >= currentDateForVuFind())
$d : DroolsResponse()
then
$d.addErrorMessage("Patron has an invalid activation date");
end

rule "Check All Charges For vufind"
agenda-group "lookup-user-vufind"
when
$p: OlePatronDocument(getAllCharges() > 149 )
$d: DroolsResponse()
then
$d.addErrorMessage("Patron's overall charges greater than $149");
end

rule "Check Overdue fine For vufind"
agenda-group "lookup-user-vufind"
when
$p: OlePatronDocument(getOverdueFineAmount() > 49 )
$d: DroolsResponse()
then
$d.addErrorMessage("Patron has overdue fines greater than $49");
end

rule "Check Replacement fine For vufind"
agenda-group "lookup-user-vufind"
when
$p: OlePatronDocument(getReplacementFineAmount() > 49 )
$d: DroolsResponse()
then
$d.addErrorMessage("Patron has replacement fees greater than $49");
end

function Date currentDateForVuFind(){
    Date date = new Date(System.currentTimeMillis());
    return date;
}


