package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.util.NoticeInfo
import org.kuali.ole.docstore.engine.service.storage.rdbms.pojo.ItemRecord
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.drools.DroolsConstants;


rule "Courtsey Notice Policy Set ITS ADP"
agenda-group "notice generation"
activation-group "notice generation"
when
$n: NoticeInfo(getNoticeType() == DroolsConstants.ITS_ADP_LOANS_NOTICE_CONFIG)
$i: ItemRecord(getDueDateTime()!= null)
then
$n.addInfo(OLEConstants.NOTICE_COURTESY, DroolsConstants.INTERVAL_TO_GENERATE_NOTICE_FOR_COURTESY, "1");
$n.addInfo(OLEConstants.NOTICE_OVERDUE, DroolsConstants.NUMBER_OF_OVERDUE_NOTICES_TO_BE_SENT, "6");
$n.addInfo(OLEConstants.NOTICE_OVERDUE, DroolsConstants.INTERVAL_TO_GENERATE_NOTICE_FOR_OVERDUE, "2");
$n.addInfo(OLEConstants.NOTICE_OVERDUE, DroolsConstants.REPLACEMENT_BILL_AMT, "90");
 end
