jq(document).ready(function(){
    jq("#donorName_control").attr('maxlength','255');
});
jq(document).click(function(){
    jq("#donorName_control").attr('maxlength','255');
});
jq(document).keypress(function(){
    jq("#donorName_control").attr('maxlength','255');
});
