////
//// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
//// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
//// Any modifications to this file will be lost upon recompilation of the source schema.
//// Generated on: 2012.03.15 at 02:03:46 PM IST
////
//
//
//package org.kuali.ole.docstore.model.xmlpojo.security.patron.oleml;
//
//import com.thoughtworks.xstream.annotations.XStreamAlias;
//import com.thoughtworks.xstream.annotations.XStreamImplicit;
//
//import javax.xml.bind.annotation.*;
//import javax.xml.datatype.XMLGregorianCalendar;
//import java.util.ArrayList;
//import java.util.List;
//
//
///**
// * This is an address with the other attributes that make it useful.
// *                 Inactivated indicates that the library has forced the address to deactivate
// *                 manually, rather than because the dates are invalid. Some other validation will be
// *                 necessary for addresses. More than one address can be primary, as long as their date
// *                 ranges do not intersect.
// *
// * <p>Java class for addressWithDates complex type.
// *
// * <p>The following schema fragment specifies the expected content contained within this class.
// *
// * <pre>
// * &lt;complexType name="addressWithDates">
// *   &lt;complexContent>
// *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
// *       &lt;sequence>
// *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
// *         &lt;choice maxOccurs="unbounded">
// *           &lt;element name="postalAddress" type="{http://ole.kuali.org/standards/ole-patron}postalAddress"/>
// *           &lt;element name="emailAddress" type="{http://ole.kuali.org/standards/ole-patron}emailAddress"/>
// *           &lt;element name="telephoneNumber" type="{http://ole.kuali.org/standards/ole-patron}telephoneNumber"/>
// *         &lt;/choice>
// *         &lt;element name="activeDates" type="{http://ole.kuali.org/standards/ole-patron}beginEndDate" minOccurs="0"/>
// *         &lt;element name="inactivated" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
// *         &lt;element name="validated" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
// *       &lt;/sequence>
// *       &lt;attribute name="primary" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
// *     &lt;/restriction>
// *   &lt;/complexContent>
// * &lt;/complexType>
// * </pre>
// *
// *
// * @author Rajesh Chowdary K
// * @created Mar 15, 2012
// */
//
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "addressWithDates", propOrder = {
//    "type",
//    "postalAddressOrEmailAddressOrTelephoneNumber",
//    "activeDates",
//    "inactivated",
//    "validated"
//})
//
//@XStreamAlias("addressWithDates")
//public class AddressWithDates {
//
//    @XmlElement(required = true)
//    protected String type;
//
//    @XmlElements({
//        @XmlElement(name = "telephoneNumber", type = TelephoneNumber.class),
//        @XmlElement(name = "emailAddress", type = EmailAddress.class),
//        @XmlElement(name = "postalAddress", type = PostalAddress.class)
//    })
//
//    @XStreamImplicit
//    protected List<Object> postalAddressOrEmailAddressOrTelephoneNumber = new ArrayList<Object>();
//
//    protected PostalAddress postalAddress;
//
//    protected EmailAddress emailAddress;
//
//    protected TelephoneNumber telephoneNumber;
//
//    protected BeginEndDate activeDates;
//
//    protected String inactivated;
//
//    protected String validated;
//    @XmlAttribute(required = true)
//    protected boolean primary;
//
//
//    public PostalAddress getPostalAddress() {
//        return postalAddress;
//    }
//
//    public void setPostalAddress(PostalAddress postalAddress) {
//        this.postalAddress = postalAddress;
//    }
//
//    public EmailAddress getEmailAddress() {
//        return emailAddress;
//    }
//
//    public void setEmailAddress(EmailAddress emailAddress) {
//        this.emailAddress = emailAddress;
//    }
//
//    public TelephoneNumber getTelephoneNumber() {
//        return telephoneNumber;
//    }
//
//    public void setTelephoneNumber(TelephoneNumber telephoneNumber) {
//        this.telephoneNumber = telephoneNumber;
//    }
//
//    /**
//     * Gets the value of the type property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getType() {
//        return type;
//    }
//
//    /**
//     * Sets the value of the type property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setType(String value) {
//        this.type = value;
//    }
//
//    /**
//     * Gets the value of the postalAddressOrEmailAddressOrTelephoneNumber property.
//     *
//     * <p>
//     * This accessor method returns a reference to the live list,
//     * not a snapshot. Therefore any modification you make to the
//     * returned list will be present inside the JAXB object.
//     * This is why there is not a <CODE>set</CODE> method for the postalAddressOrEmailAddressOrTelephoneNumber property.
//     *
//     * <p>
//     * For example, to add a new item, do as follows:
//     * <pre>
//     *    getPostalAddressOrEmailAddressOrTelephoneNumber().add(newItem);
//     * </pre>
//     *
//     *
//     * <p>
//     * Objects of the following type(s) are allowed in the list
//     * {@link TelephoneNumber }
//     * {@link EmailAddress }
//     * {@link PostalAddress }
//     *
//     *
//     */
//
//    public List<Object> getPostalAddressOrEmailAddressOrTelephoneNumber() {
//        return this.postalAddressOrEmailAddressOrTelephoneNumber;
//    }
//
//    /**
//     * Gets the value of the activeDates property.
//     *
//     * @return
//     *     possible object is
//     *     {@link BeginEndDate }
//     *
//     */
//    public BeginEndDate getActiveDates() {
//        return activeDates;
//    }
//
//    /**
//     * Sets the value of the activeDates property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link BeginEndDate }
//     *
//     */
//    public void setActiveDates(BeginEndDate value) {
//        this.activeDates = value;
//    }
//
//    /**
//     * Gets the value of the inactivated property.
//     *
//     * @return
//     *     possible object is
//     *     {@link XMLGregorianCalendar }
//     *
//     */
//    public String getInactivated() {
//        return inactivated;
//    }
//
//    /**
//     * Sets the value of the inactivated property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link XMLGregorianCalendar }
//     *
//     */
//    public void setInactivated(String value) {
//        this.inactivated = value;
//    }
//
//    /**
//     * Gets the value of the validated property.
//     *
//     * @return
//     *     possible object is
//     *     {@link XMLGregorianCalendar }
//     *
//     */
//    public String getValidated() {
//        return validated;
//    }
//
//    /**
//     * Sets the value of the validated property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link XMLGregorianCalendar }
//     *
//     */
//    public void setValidated(String value) {
//        this.validated = value;
//    }
//
//    /**
//     * Gets the value of the primary property.
//     *
//     */
//    public boolean isPrimary() {
//        return primary;
//    }
//
//    /**
//     * Sets the value of the primary property.
//     *
//     */
//    public void setPrimary(boolean value) {
//        this.primary = value;
//    }
//
//}
