////
//// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
//// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
//// Any modifications to this file will be lost upon recompilation of the source schema.
//// Generated on: 2012.03.15 at 02:03:46 PM IST
////
//
//
//package org.kuali.ole.docstore.model.xmlpojo.security.patron.oleml;
//
//import com.thoughtworks.xstream.annotations.XStreamAlias;
//
//import javax.xml.bind.annotation.XmlEnum;
//import javax.xml.bind.annotation.XmlEnumValue;
//import javax.xml.bind.annotation.XmlType;
//
//
///**
// * <p>Java class for barcodeStatuses.
// *
// * <p>The following schema fragment specifies the expected content contained within this class.
// * <p>
// * <pre>
// * &lt;simpleType name="barcodeStatuses">
// *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
// *     &lt;enumeration value="Active"/>
// *     &lt;enumeration value="Lost"/>
// *     &lt;enumeration value="Stolen"/>
// *   &lt;/restriction>
// * &lt;/simpleType>
// * </pre>
// *
// * @author Rajesh Chowdary K
// * @created Mar 15, 2012
// */
//
//@XmlType(name = "barcodeStatuses")
//@XmlEnum
//@XStreamAlias("barcodeStatuses")
//public enum BarcodeStatuses {
//
//    @XmlEnumValue("Active")
//    ACTIVE("Active"),
//    @XmlEnumValue("Lost")
//    LOST("Lost"),
//    @XmlEnumValue("Stolen")
//    STOLEN("Stolen");
//    private final String value;
//
//    BarcodeStatuses(String v) {
//        value = v;
//    }
//
//    public String value() {
//        return value;
//    }
//
//    public static BarcodeStatuses fromValue(String v) {
//        for (BarcodeStatuses c: BarcodeStatuses.values()) {
//            if (c.value.equals(v)) {
//                return c;
//            }
//        }
//        throw new IllegalArgumentException(v);
//    }
//
//}
