////
//// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
//// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
//// Any modifications to this file will be lost upon recompilation of the source schema.
//// Generated on: 2012.03.15 at 02:03:46 PM IST
////
//
//
//package org.kuali.ole.docstore.model.xmlpojo.security.patron.oleml;
//
//import com.thoughtworks.xstream.annotations.XStreamAlias;
//
//import javax.xml.bind.annotation.XmlAccessType;
//import javax.xml.bind.annotation.XmlAccessorType;
//import javax.xml.bind.annotation.XmlElement;
//import javax.xml.bind.annotation.XmlType;
//import javax.xml.datatype.XMLGregorianCalendar;
//
//
///**
// *  General type for start and end dates. They use dates, not date/times.
// *                 They correspond to library service days, not moments in time. note that
// *                 activationDate is required, so to be open-ended at the beginning you have to put a
// *                 date in the past in; expiration date is optional, so to be always active after the
// *                 date you leave it out.
// *
// * <p>Java class for beginEndDate complex type.
// *
// * <p>The following schema fragment specifies the expected content contained within this class.
// *
// * <pre>
// * &lt;complexType name="beginEndDate">
// *   &lt;complexContent>
// *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
// *       &lt;sequence>
// *         &lt;element name="beginDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
// *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
// *       &lt;/sequence>
// *     &lt;/restriction>
// *   &lt;/complexContent>
// * &lt;/complexType>
// * </pre>
// *
// *
// * @author Rajesh Chowdary K
// * @created Mar 15, 2012
// */
//
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "beginEndDate", propOrder = {
//    "beginDate",
//    "endDate"
//})
//@XStreamAlias("activeDates")
//public class BeginEndDate {
//
//    @XmlElement(required = true)
//
//    protected String beginDate;
//
//    protected String endDate;
//
//    /**
//     * Gets the value of the beginDate property.
//     *
//     * @return
//     *     possible object is
//     *     {@link XMLGregorianCalendar }
//     *
//     */
//    public String getBeginDate() {
//        return beginDate;
//    }
//
//    /**
//     * Sets the value of the beginDate property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link XMLGregorianCalendar }
//     *
//     */
//    public void setBeginDate(String value) {
//        this.beginDate = value;
//    }
//
//    /**
//     * Gets the value of the endDate property.
//     *
//     * @return
//     *     possible object is
//     *     {@link XMLGregorianCalendar }
//     *
//     */
//    public String getEndDate() {
//        return endDate;
//    }
//
//    /**
//     * Sets the value of the endDate property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link XMLGregorianCalendar }
//     *
//     */
//    public void setEndDate(String value) {
//        this.endDate = value;
//    }
//
//}
