////
//// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
//// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
//// Any modifications to this file will be lost upon recompilation of the source schema.
//// Generated on: 2012.03.15 at 02:03:46 PM IST
////
//
//
//package org.kuali.ole.docstore.model.xmlpojo.security.patron.oleml;
//
//import com.thoughtworks.xstream.annotations.XStreamAlias;
//
//import javax.xml.bind.annotation.XmlAccessType;
//import javax.xml.bind.annotation.XmlAccessorType;
//import javax.xml.bind.annotation.XmlElement;
//import javax.xml.bind.annotation.XmlType;
//
//
///**
// * <p>Java class for identification complex type.
// *
// * <p>The following schema fragment specifies the expected content contained within this class.
// *
// * <pre>
// * &lt;complexType name="identification">
// *   &lt;complexContent>
// *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
// *       &lt;sequence>
// *         &lt;element name="identificationType" type="{http://www.w3.org/2001/XMLSchema}string"/>
// *         &lt;element name="identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
// *         &lt;element name="identifier2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
// *         &lt;element name="context" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
// *         &lt;element name="salt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
// *       &lt;/sequence>
// *     &lt;/restriction>
// *   &lt;/complexContent>
// * &lt;/complexType>
// * </pre>
// *
// *
// * @author Rajesh Chowdary K
// * @created Mar 15, 2012
// */
//
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "identification", propOrder = {
//    "identificationType",
//    "identifier",
//    "identifier2",
//    "context",
//    "salt"
//})
//
//@XStreamAlias("identification")
//public class Identification {
//
//    @XmlElement(required = true)
//    protected String identificationType;
//    @XmlElement(required = true)
//    protected String identifier;
//    protected String identifier2;
//    protected String context;
//    protected String salt;
//
//    /**
//     * Gets the value of the identificationType property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getIdentificationType() {
//        return identificationType;
//    }
//
//    /**
//     * Sets the value of the identificationType property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setIdentificationType(String value) {
//        this.identificationType = value;
//    }
//
//    /**
//     * Gets the value of the identifier property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getIdentifier() {
//        return identifier;
//    }
//
//    /**
//     * Sets the value of the identifier property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setIdentifier(String value) {
//        this.identifier = value;
//    }
//
//    /**
//     * Gets the value of the identifier2 property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getIdentifier2() {
//        return identifier2;
//    }
//
//    /**
//     * Sets the value of the identifier2 property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setIdentifier2(String value) {
//        this.identifier2 = value;
//    }
//
//    /**
//     * Gets the value of the context property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getContext() {
//        return context;
//    }
//
//    /**
//     * Sets the value of the context property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setContext(String value) {
//        this.context = value;
//    }
//
//    /**
//     * Gets the value of the salt property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getSalt() {
//        return salt;
//    }
//
//    /**
//     * Sets the value of the salt property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setSalt(String value) {
//        this.salt = value;
//    }
//
//}
