////
//// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
//// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
//// Any modifications to this file will be lost upon recompilation of the source schema.
//// Generated on: 2012.03.15 at 02:03:46 PM IST
////
//
//
//package org.kuali.ole.docstore.model.xmlpojo.security.patron.oleml;
//
//import com.thoughtworks.xstream.annotations.XStreamAlias;
//
//import javax.xml.bind.annotation.XmlAccessType;
//import javax.xml.bind.annotation.XmlAccessorType;
//import javax.xml.bind.annotation.XmlElement;
//import javax.xml.bind.annotation.XmlType;
//
//
///**
// * The patron name with free-text prefix, suffix and middle name. For
// *                 entities that don't have structured names, or in cases where the name is not
// *                 structured in the load, use the surname field.
// *
// * <p>Java class for name complex type.
// *
// * <p>The following schema fragment specifies the expected content contained within this class.
// *
// * <pre>
// * &lt;complexType name="name">
// *   &lt;complexContent>
// *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
// *       &lt;sequence>
// *         &lt;element name="prefix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
// *         &lt;element name="first" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
// *         &lt;element name="middle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
// *         &lt;element name="surname" type="{http://www.w3.org/2001/XMLSchema}string"/>
// *         &lt;element name="suffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
// *       &lt;/sequence>
// *     &lt;/restriction>
// *   &lt;/complexContent>
// * &lt;/complexType>
// * </pre>
// *
// *
// * @author Rajesh Chowdary K
// * @created Mar 15, 2012
// */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "name", propOrder = {
//    "prefix",
//    "first",
//    "middle",
//    "surname",
//    "suffix"
//})
//@XStreamAlias("name")
//public class Name {
//
//    protected String prefix;
//    protected String first;
//    protected String middle;
//    @XmlElement(required = true)
//    protected String surname;
//    protected String suffix;
//
//    /**
//     * Gets the value of the prefix property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getPrefix() {
//        return prefix;
//    }
//
//    /**
//     * Sets the value of the prefix property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setPrefix(String value) {
//        this.prefix = value;
//    }
//
//    /**
//     * Gets the value of the first property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getFirst() {
//        return first;
//    }
//
//    /**
//     * Sets the value of the first property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setFirst(String value) {
//        this.first = value;
//    }
//
//    /**
//     * Gets the value of the middle property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getMiddle() {
//        return middle;
//    }
//
//    /**
//     * Sets the value of the middle property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setMiddle(String value) {
//        this.middle = value;
//    }
//
//    /**
//     * Gets the value of the surname property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getSurname() {
//        return surname;
//    }
//
//    /**
//     * Sets the value of the surname property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setSurname(String value) {
//        this.surname = value;
//    }
//
//    /**
//     * Gets the value of the suffix property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getSuffix() {
//        return suffix;
//    }
//
//    /**
//     * Sets the value of the suffix property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setSuffix(String value) {
//        this.suffix = value;
//    }
//
//     @Override
//    public String toString() {
//         StringBuilder sb = new StringBuilder();
//         sb.append(first +" ");
//         sb.append(middle + " ");
//         sb.append(surname);
//         return sb.toString();
//     }
//}
