////
//// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
//// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
//// Any modifications to this file will be lost upon recompilation of the source schema.
//// Generated on: 2012.03.15 at 02:03:46 PM IST
////
//
//
//package org.kuali.ole.docstore.model.xmlpojo.security.patron.oleml;
//
//import com.thoughtworks.xstream.annotations.XStreamAlias;
//
//import javax.xml.bind.annotation.*;
//import javax.xml.datatype.XMLGregorianCalendar;
//
//
///**
// *  RecordNumber holds the database-level ID. This could be the same as
// *                 the LoadID. Active dates are the allowed and expire dates for the patron. Most circ
// *                 activity will be blocked before and after the activeDates--the exact rules for that
// *                 need to be established. The purge date is the date the system will purge/hide the
// *                 patron. Photo is just a URL. Other elements are annotated where they are defined.
// *
// *
// * <p>Java class for patron complex type.
// *
// * <p>The following schema fragment specifies the expected content contained within this class.
// *
// * <pre>
// * &lt;complexType name="patron">
// *   &lt;complexContent>
// *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
// *       &lt;sequence>
// *         &lt;element name="recordNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
// *         &lt;element name="activeDates" type="{http://ole.kuali.org/standards/ole-patron}beginEndDate"/>
// *         &lt;element name="purgeDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
// *         &lt;element name="name" type="{http://ole.kuali.org/standards/ole-patron}name"/>
// *         &lt;element name="borrowerType" type="{http://www.w3.org/2001/XMLSchema}string"/>
// *         &lt;element name="barcode" type="{http://ole.kuali.org/standards/ole-patron}barcode"/>
// *         &lt;element name="historicalBarcodes" type="{http://ole.kuali.org/standards/ole-patron}barcodes" minOccurs="0"/>
// *         &lt;element name="addresses" type="{http://ole.kuali.org/standards/ole-patron}addresses"/>
// *         &lt;element name="isGenerallyBlocked" type="{http://ole.kuali.org/standards/ole-patron}isGenerallyBlocked"/>
// *         &lt;element name="patronLevelPolicies" type="{http://ole.kuali.org/standards/ole-patron}patronLevelPolicies"/>
// *         &lt;element name="affiliations" type="{http://ole.kuali.org/standards/ole-patron}affiliations" minOccurs="0"/>
// *         &lt;element name="identifications" type="{http://ole.kuali.org/standards/ole-patron}identifications" minOccurs="0"/>
// *         &lt;element name="notes" type="{http://ole.kuali.org/standards/ole-patron}notes" minOccurs="0"/>
// *         &lt;element name="photo" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
// *       &lt;/sequence>
// *     &lt;/restriction>
// *   &lt;/complexContent>
// * &lt;/complexType>
// * </pre>
// *
// *
// * @author Rajesh Chowdary K
// * @created Mar 15, 2012
// */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "patron", propOrder = {
//    "recordNumber",
//    "activeDates",
//    "purgeDate",
//    "name",
//    "borrowerType",
//    "barcode",
//    "historicalBarcodes",
//    "addresses",
//    "isGenerallyBlocked",
//    "patronLevelPolicies",
//    "affiliations",
//    "identifications",
//    "notes",
//    "photo"
//})
//@XStreamAlias("patron")
//public class Patron {
//
//    protected String recordNumber;
//    @XmlElement(required = true)
//    protected BeginEndDate activeDates;
//    @XmlElement(required = true)
//
//   protected String purgeDate;
//    @XmlElement(required = true)
//    protected Name name;
//    @XmlElement(required = true)
//    protected String borrowerType;
//    @XmlElement(required = true)
//    protected Barcode barcode;
//    protected Barcodes historicalBarcodes;
//    @XmlElement(required = true)
//    protected Addresses addresses;
//    @XmlElement(defaultValue = "false")
//    protected boolean isGenerallyBlocked;
//    @XmlElement(required = true)
//    protected PatronLevelPolicies patronLevelPolicies;
//    protected Affiliations affiliations;
//    protected Identifications identifications;
//    protected Notes notes;
//    @XmlSchemaType(name = "anyURI")
//    protected String photo;
//
//
//
//    /**
//     * Gets the value of the recordNumber property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getRecordNumber() {
//        System.out.println("get in patron recordNumber");
//        return recordNumber;
//    }
//
//    /**
//     * Sets the value of the recordNumber property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setRecordNumber(String value) {
//        this.recordNumber = value;
//    }
//
//    /**
//     * Gets the value of the activeDates property.
//     *
//     * @return
//     *     possible object is
//     *     {@link BeginEndDate }
//     *
//     */
//    public BeginEndDate getActiveDates() {
//        return activeDates;
//    }
//
//    /**
//     * Sets the value of the activeDates property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link BeginEndDate }
//     *
//     */
//    public void setActiveDates(BeginEndDate value) {
//        this.activeDates = value;
//    }
//
//   /**
//     * Gets the value of the purgeDate property.
//     *
//     * @return
//     *     possible object is
//     *     {@link XMLGregorianCalendar }
//     *
//     */
//    public String getPurgeDate() {
//        return purgeDate;
//    }
//
//    /**
//     * Sets the value of the purgeDate property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link XMLGregorianCalendar }
//     *
//     */
//    public void setPurgeDate(String value) {
//        this.purgeDate = value;
//    }
//
//    /**
//     * Gets the value of the name property.
//     *
//     * @return
//     *     possible object is
//     *     {@link Name }
//     *
//     */
//    public Name getName() {
//        return name;
//    }
//
//    /**
//     * Sets the value of the name property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link Name }
//     *
//     */
//    public void setName(Name value) {
//        this.name = value;
//    }
//
//    /**
//     * Gets the value of the borrowerType property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getBorrowerType() {
//        return borrowerType;
//    }
//
//    /**
//     * Sets the value of the borrowerType property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setBorrowerType(String value) {
//        this.borrowerType = value;
//    }
//
//    /**
//     * Gets the value of the barcode property.
//     *
//     * @return
//     *     possible object is
//     *     {@link Barcode }
//     *
//     */
//    public Barcode getBarcode() {
//        return barcode;
//    }
//
//    /**
//     * Sets the value of the barcode property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link Barcode }
//     *
//     */
//    public void setBarcode(Barcode value) {
//        this.barcode = value;
//    }
//
//    /**
//     * Gets the value of the historicalBarcodes property.
//     *
//     * @return
//     *     possible object is
//     *     {@link Barcodes }
//     *
//     */
//    public Barcodes getHistoricalBarcodes() {
//        return historicalBarcodes;
//    }
//
//    /**
//     * Sets the value of the historicalBarcodes property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link Barcodes }
//     *
//     */
//    public void setHistoricalBarcodes(Barcodes value) {
//        this.historicalBarcodes = value;
//    }
//
//    /**
//     * Gets the value of the addresses property.
//     *
//     * @return
//     *     possible object is
//     *     {@link Addresses }
//     *
//     */
//    public Addresses getAddresses() {
//        return addresses;
//    }
//
//    /**
//     * Sets the value of the addresses property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link Addresses }
//     *
//     */
//    public void setAddresses(Addresses value) {
//        this.addresses = value;
//    }
//
//    /**
//     * Gets the value of the isGenerallyBlocked property.
//     *
//     */
//    public boolean isIsGenerallyBlocked() {
//        return isGenerallyBlocked;
//    }
//
//    /**
//     * Sets the value of the isGenerallyBlocked property.
//     *
//     */
//    public void setIsGenerallyBlocked(boolean value) {
//        this.isGenerallyBlocked = value;
//    }
//
//    /**
//     * Gets the value of the patronLevelPolicies property.
//     *
//     * @return
//     *     possible object is
//     *     {@link PatronLevelPolicies }
//     *
//     */
//    public PatronLevelPolicies getPatronLevelPolicies() {
//        return patronLevelPolicies;
//    }
//
//    /**
//     * Sets the value of the patronLevelPolicies property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link PatronLevelPolicies }
//     *
//     */
//    public void setPatronLevelPolicies(PatronLevelPolicies value) {
//        this.patronLevelPolicies = value;
//    }
//
//    /**
//     * Gets the value of the affiliations property.
//     *
//     * @return
//     *     possible object is
//     *     {@link Affiliations }
//     *
//     */
//    public Affiliations getAffiliations() {
//        return affiliations;
//    }
//
//    /**
//     * Sets the value of the affiliations property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link Affiliations }
//     *
//     */
//    public void setAffiliations(Affiliations value) {
//        this.affiliations = value;
//    }
//
//    /**
//     * Gets the value of the identifications property.
//     *
//     * @return
//     *     possible object is
//     *     {@link Identifications }
//     *
//     */
//    public Identifications getIdentifications() {
//        return identifications;
//    }
//
//    /**
//     * Sets the value of the identifications property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link Identifications }
//     *
//     */
//    public void setIdentifications(Identifications value) {
//        this.identifications = value;
//    }
//
//    /**
//     * Gets the value of the notes property.
//     *
//     * @return
//     *     possible object is
//     *     {@link Notes }
//     *
//     */
//    public Notes getNotes() {
//        return notes;
//    }
//
//    /**
//     * Sets the value of the notes property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link Notes }
//     *
//     */
//    public void setNotes(Notes value) {
//        this.notes = value;
//    }
//
//    /**
//     * Gets the value of the photo property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getPhoto() {
//        return photo;
//    }
//
//    /**
//     * Sets the value of the photo property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setPhoto(String value) {
//        this.photo = value;
//    }
//
//}
