////
//// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
//// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
//// Any modifications to this file will be lost upon recompilation of the source schema.
//// Generated on: 2012.03.15 at 02:03:46 PM IST
////
//
//
//package org.kuali.ole.docstore.model.xmlpojo.security.patron.oleml;
//
//import com.thoughtworks.xstream.annotations.XStreamAlias;
//
//import javax.xml.bind.annotation.XmlAccessType;
//import javax.xml.bind.annotation.XmlAccessorType;
//import javax.xml.bind.annotation.XmlElement;
//import javax.xml.bind.annotation.XmlType;
//
//
///**
// *  These three privileges are set for individual patrons, as well as in
// *                 policies. We may have more individual-patron level policies in the
// *                 future.
// *
// * <p>Java class for patronLevelPolicies complex type.
// *
// * <p>The following schema fragment specifies the expected content contained within this class.
// *
// * <pre>
// * &lt;complexType name="patronLevelPolicies">
// *   &lt;complexContent>
// *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
// *       &lt;sequence>
// *         &lt;element name="hasDeliveryPrivilege" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
// *         &lt;element name="hasPagingPrivilege" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
// *         &lt;element name="receivesCourtesyNotice" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
// *       &lt;/sequence>
// *     &lt;/restriction>
// *   &lt;/complexContent>
// * &lt;/complexType>
// * </pre>
// *
// *
// * @author Rajesh Chowdary K
// * @created Mar 15, 2012
// */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "patronLevelPolicies", propOrder = {
//    "hasDeliveryPrivilege",
//    "hasPagingPrivilege",
//    "receivesCourtesyNotice"
//})
//@XStreamAlias("patronLevelPolicies")
//public class PatronLevelPolicies {
//
//    @XmlElement(defaultValue = "false")
//    protected boolean hasDeliveryPrivilege;
//    @XmlElement(defaultValue = "false")
//    protected boolean hasPagingPrivilege;
//    @XmlElement(defaultValue = "false")
//    protected boolean receivesCourtesyNotice;
//
//    /**
//     * Gets the value of the hasDeliveryPrivilege property.
//     *
//     */
//    public boolean isHasDeliveryPrivilege() {
//        return hasDeliveryPrivilege;
//    }
//
//    /**
//     * Sets the value of the hasDeliveryPrivilege property.
//     *
//     */
//    public void setHasDeliveryPrivilege(boolean value) {
//        this.hasDeliveryPrivilege = value;
//    }
//
//    /**
//     * Gets the value of the hasPagingPrivilege property.
//     *
//     */
//    public boolean isHasPagingPrivilege() {
//        return hasPagingPrivilege;
//    }
//
//    /**
//     * Sets the value of the hasPagingPrivilege property.
//     *
//     */
//    public void setHasPagingPrivilege(boolean value) {
//        this.hasPagingPrivilege = value;
//    }
//
//    /**
//     * Gets the value of the receivesCourtesyNotice property.
//     *
//     */
//    public boolean isReceivesCourtesyNotice() {
//        return receivesCourtesyNotice;
//    }
//
//    /**
//     * Sets the value of the receivesCourtesyNotice property.
//     *
//     */
//    public void setReceivesCourtesyNotice(boolean value) {
//        this.receivesCourtesyNotice = value;
//    }
//
//}
