////
//// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
//// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
//// Any modifications to this file will be lost upon recompilation of the source schema.
//// Generated on: 2012.03.15 at 02:03:46 PM IST
////
//
//
//package org.kuali.ole.docstore.model.xmlpojo.security.patron.oleml;
//
//import com.thoughtworks.xstream.annotations.XStreamAlias;
//import com.thoughtworks.xstream.annotations.XStreamImplicit;
//
//import javax.xml.bind.annotation.XmlAccessType;
//import javax.xml.bind.annotation.XmlAccessorType;
//import javax.xml.bind.annotation.XmlElement;
//import javax.xml.bind.annotation.XmlType;
//import java.util.ArrayList;
//import java.util.List;
//
//
///**
// * One address line is required; the rest is optional. Some systems can
// *                 only put address data in address lines 1-4, without populating the city, state,
// *                 postal, country fields. Non-USA addresses sometimes don't have state and/or postal
// *                 code, so none of these are required except for the first address
// *                 line.
// *
// * <p>Java class for postalAddress complex type.
// *
// * <p>The following schema fragment specifies the expected content contained within this class.
// *
// * <pre>
// * &lt;complexType name="postalAddress">
// *   &lt;complexContent>
// *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
// *       &lt;sequence>
// *         &lt;element name="attention" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
// *         &lt;element name="addressLine" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="4"/>
// *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
// *         &lt;element name="stateProvince" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
// *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
// *         &lt;element name="postalCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
// *       &lt;/sequence>
// *     &lt;/restriction>
// *   &lt;/complexContent>
// * &lt;/complexType>
// * </pre>
// *
// *
// * @author Rajesh Chowdary K
// * @created Mar 15, 2012
// */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "postalAddress", propOrder = {
//    "attention",
//    "addressLine",
//    "city",
//    "stateProvince",
//    "country",
//    "postalCode"
//})
//@XStreamAlias("postalAddress")
//public class PostalAddress {
//
//    protected String attention;
//    @XmlElement(required = true)
//    @XStreamImplicit
//    protected List<String> addressLine;
//    protected String city;
//    protected String stateProvince;
//    protected String country;
//    protected String postalCode;
//
//    /**
//     * Gets the value of the attention property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getAttention() {
//        return attention;
//    }
//
//    /**
//     * Sets the value of the attention property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setAttention(String value) {
//        this.attention = value;
//    }
//
//    /**
//     * Gets the value of the addressLine property.
//     *
//     * <p>
//     * This accessor method returns a reference to the live list,
//     * not a snapshot. Therefore any modification you make to the
//     * returned list will be present inside the JAXB object.
//     * This is why there is not a <CODE>set</CODE> method for the addressLine property.
//     *
//     * <p>
//     * For example, to add a new item, do as follows:
//     * <pre>
//     *    getAddressLine().add(newItem);
//     * </pre>
//     *
//     *
//     * <p>
//     * Objects of the following type(s) are allowed in the list
//     * {@link String }
//     *
//     *
//     */
//    public List<String> getAddressLine() {
//        if (addressLine == null) {
//            addressLine = new ArrayList<String>();
//        }
//        return this.addressLine;
//    }
//
//    /**
//     * Gets the value of the city property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getCity() {
//        return city;
//    }
//
//    /**
//     * Sets the value of the city property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setCity(String value) {
//        this.city = value;
//    }
//
//    /**
//     * Gets the value of the stateProvince property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getStateProvince() {
//        return stateProvince;
//    }
//
//    /**
//     * Sets the value of the stateProvince property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setStateProvince(String value) {
//        this.stateProvince = value;
//    }
//
//    /**
//     * Gets the value of the country property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getCountry() {
//        return country;
//    }
//
//    /**
//     * Sets the value of the country property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setCountry(String value) {
//        this.country = value;
//    }
//
//    /**
//     * Gets the value of the postalCode property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getPostalCode() {
//        return postalCode;
//    }
//
//    /**
//     * Sets the value of the postalCode property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setPostalCode(String value) {
//        this.postalCode = value;
//    }
//
//}
