package org.kuali.ole.deliver.checkout

import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.util.NoticeInfo
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ErrorMessage
import org.kuali.ole.deliver.drools.DroolsConstants


rule "Circ Policy STKS/Q for Renewal"
agenda-group "renewal validation"
activation-group "renewal validation"
when

$l: OleLoanDocument()

$n: NoticeInfo()

$p: OlePatronDocument(getBorrowerTypeCode() in
("QCOL","QGRAD","QDEPT","QNONDEG","QNONUC","QNONUC25","QSTF,","QOTHER","QALUM25"))

$i: OleItemRecordForCirc(getItemType() in ("stks","games"))

then
$l.loanPeriod("1-D",null); // This method takes due date and recall period as arguments.
$n.setLoanType(DroolsConstants.SHORT_TERM_LOANS_NOTICE_CONFIG);
 end
