TRUNCATE TABLE OLE_DS_DOC_FORMAT_T
/
INSERT INTO OLE_DS_DOC_FORMAT_T (DISPLAY_LABEL,DESCRIPTION,DOC_FORMAT_ID,NAME,DOC_TYPE_ID,OBJ_ID,VER_NBR)
  VALUES ('MARC','',1,'marc',1,'8a1e31e8-e5ab-4edd-aab5-4h3e49fe5e1c',1)
/
INSERT INTO OLE_DS_DOC_FORMAT_T (DISPLAY_LABEL,DESCRIPTION,DOC_FORMAT_ID,NAME,DOC_TYPE_ID,OBJ_ID,VER_NBR)
  VALUES ('Dublin Core','',2,'dublin',1,'8a2e31e8-e5bc-4edd-aab5-4g3e49fe5e1c',1)
/
INSERT INTO OLE_DS_DOC_FORMAT_T (DISPLAY_LABEL,DESCRIPTION,DOC_FORMAT_ID,NAME,DOC_TYPE_ID,OBJ_ID,VER_NBR)
  VALUES ('Dublin Unqualified','',3,'dublinunq',1,'8a3e31e8-e5cd-4edd-aab5-3h3e49fe5e1c',1)
/
INSERT INTO OLE_DS_DOC_FORMAT_T (DISPLAY_LABEL,DESCRIPTION,DOC_FORMAT_ID,NAME,DOC_TYPE_ID,OBJ_ID,VER_NBR)
  VALUES ('ONIXPL','',4,'onixpl',2,'8a4e31e8-e5de-4edd-aab5-3d3e49fe5e1c',1)
/
INSERT INTO OLE_DS_DOC_FORMAT_T (DISPLAY_LABEL,DESCRIPTION,DOC_FORMAT_ID,NAME,DOC_TYPE_ID,OBJ_ID,VER_NBR)
  VALUES ('PDF','',5,'pdf',2,'8a4e31e8-e5ef-4edd-aab5-3d3e49fe5e1c',1)
/
INSERT INTO OLE_DS_DOC_FORMAT_T (DISPLAY_LABEL,DESCRIPTION,DOC_FORMAT_ID,NAME,DOC_TYPE_ID,OBJ_ID,VER_NBR)
  VALUES ('DOC','',6,'doc',2,'8a4e31e8-e5f8-4edd-aab5-3d3e49fe5e1c',1)
/
INSERT INTO OLE_DS_DOC_FORMAT_T (DISPLAY_LABEL,DESCRIPTION,DOC_FORMAT_ID,NAME,DOC_TYPE_ID,OBJ_ID,VER_NBR)
  VALUES ('XSLT','',7,'xslt',2,'8a4e31e8-e592-4edd-aab5-3d3e49fe5e1c',1)
/
INSERT INTO OLE_DS_DOC_FORMAT_T (DISPLAY_LABEL,DESCRIPTION,DOC_FORMAT_ID,NAME,DOC_TYPE_ID,OBJ_ID,VER_NBR)
  VALUES ('OLEML','',8,'oleml',3,'8a4e31e8-e570-4edd-aab5-3d3e49fe5e1c',1)
/
INSERT INTO OLE_DS_DOC_FORMAT_T (DISPLAY_LABEL,DESCRIPTION,DOC_FORMAT_ID,NAME,DOC_TYPE_ID,OBJ_ID,VER_NBR)
  VALUES ('OLEML','',9,'oleml',4,'8a4e31e8-e518-4edd-aab5-3d3e49fe5e1c',1)
/
INSERT INTO OLE_DS_DOC_FORMAT_T (DISPLAY_LABEL,DESCRIPTION,DOC_FORMAT_ID,NAME,DOC_TYPE_ID,OBJ_ID,VER_NBR)
  VALUES ('OLEML','',10,'oleml',5,'8a4e31e8-e518-4edd-aab5-3d3e49fe5e1c',1)
/
