TRUNCATE TABLE OLE_BAT_PRCS_TYP_T
/
INSERT INTO OLE_BAT_PRCS_TYP_T (ACTIVE_IND,OBJ_ID,OLE_BAT_PRCS_TYP_CODE,OLE_BAT_PRCS_TYP_ID,OLE_BAT_PRCS_TYP_NM,VER_NBR)
  VALUES ('Y','1','ord_rec','12','Order Record Import',1)
/
INSERT INTO OLE_BAT_PRCS_TYP_T (ACTIVE_IND,OBJ_ID,OLE_BAT_PRCS_TYP_CODE,OLE_BAT_PRCS_TYP_ID,OLE_BAT_PRCS_TYP_NM,VER_NBR)
  VALUES ('Y','5','inv_ing','13','Invoice Import',1)
/
INSERT INTO OLE_BAT_PRCS_TYP_T (ACTIVE_IND,OBJ_ID,OLE_BAT_PRCS_TYP_CODE,OLE_BAT_PRCS_TYP_ID,OLE_BAT_PRCS_TYP_NM,VER_NBR)
  VALUES ('Y','6','bat_del','14','Batch Delete',1)
/
INSERT INTO OLE_BAT_PRCS_TYP_T (ACTIVE_IND,OBJ_ID,OLE_BAT_PRCS_TYP_CODE,OLE_BAT_PRCS_TYP_ID,OLE_BAT_PRCS_TYP_NM,VER_NBR)
  VALUES ('Y','7','bat_exp','15','Batch Export',1)
/
INSERT INTO OLE_BAT_PRCS_TYP_T (ACTIVE_IND,OBJ_ID,OLE_BAT_PRCS_TYP_CODE,OLE_BAT_PRCS_TYP_ID,OLE_BAT_PRCS_TYP_NM,VER_NBR)
  VALUES ('Y','3','pat_ing','16','Patron Import',1)
/
INSERT INTO OLE_BAT_PRCS_TYP_T (ACTIVE_IND,OBJ_ID,OLE_BAT_PRCS_TYP_CODE,OLE_BAT_PRCS_TYP_ID,OLE_BAT_PRCS_TYP_NM,VER_NBR)
  VALUES ('Y','2','imp_bib','17','Bib Import',1)
/
INSERT INTO OLE_BAT_PRCS_TYP_T (ACTIVE_IND,OBJ_ID,OLE_BAT_PRCS_TYP_CODE,OLE_BAT_PRCS_TYP_ID,OLE_BAT_PRCS_TYP_NM,VER_NBR)
  VALUES ('Y','4','loc_ing','18','Location Import',1)
/
INSERT INTO OLE_BAT_PRCS_TYP_T (ACTIVE_IND,OBJ_ID,OLE_BAT_PRCS_TYP_CODE,OLE_BAT_PRCS_TYP_ID,OLE_BAT_PRCS_TYP_NM,VER_NBR)
  VALUES ('Y','8','clm_rep','19','Claim Report',1)
/
INSERT INTO OLE_BAT_PRCS_TYP_T (ACTIVE_IND,OBJ_ID,OLE_BAT_PRCS_TYP_CODE,OLE_BAT_PRCS_TYP_ID,OLE_BAT_PRCS_TYP_NM,VER_NBR)
  VALUES ('Y','9','ser_imp','20','Serial Record Import',1)
/
INSERT INTO OLE_BAT_PRCS_TYP_T (ACTIVE_IND,OBJ_ID,OLE_BAT_PRCS_TYP_CODE,OLE_BAT_PRCS_TYP_ID,OLE_BAT_PRCS_TYP_NM,VER_NBR)
  VALUES ('Y','10','gokb_imp','21','GOKB Import',1)
/
INSERT INTO OLE_BAT_PRCS_TYP_T (ACTIVE_IND,OBJ_ID,OLE_BAT_PRCS_TYP_CODE,OLE_BAT_PRCS_TYP_ID,OLE_BAT_PRCS_TYP_NM,VER_NBR)
  VALUES ('Y','11','edi_exp','22','EDI Export',1)
/
INSERT INTO OLE_BAT_PRCS_TYP_T (ACTIVE_IND,OBJ_ID,OLE_BAT_PRCS_TYP_CODE,OLE_BAT_PRCS_TYP_ID,OLE_BAT_PRCS_TYP_NM,VER_NBR)
  VALUES ('Y','12','fund_imp','23','Fund Record Import',1)
/
