TRUNCATE TABLE OLE_NOTICE_TYPE_CONFIG_T
/
INSERT INTO OLE_NOTICE_TYPE_CONFIG_T (NOTICE_TYPE_CONFIG_ID,CIRC_POLICY_ID,NOTICE_TYPE)
  VALUES (1,'Check out Circ Policy Set BOOK for Max Loaned Items less than 3','REGULAR_LOANS_NOTICE')
/
INSERT INTO OLE_NOTICE_TYPE_CONFIG_T (NOTICE_TYPE_CONFIG_ID,CIRC_POLICY_ID,NOTICE_TYPE)
  VALUES (2,'Circ Policy BOOK for Renewal','REGULAR_LOANS_NOTICE')
/
INSERT INTO OLE_NOTICE_TYPE_CONFIG_T (NOTICE_TYPE_CONFIG_ID,CIRC_POLICY_ID,NOTICE_TYPE)
  VALUES (3,'Circ Policy BOOK for Renewal for renewal item count greater than 3','REGULAR_LOANS_NOTICE')
/
INSERT INTO OLE_NOTICE_TYPE_CONFIG_T (NOTICE_TYPE_CONFIG_ID,CIRC_POLICY_ID,NOTICE_TYPE)
  VALUES (4,'Circ Policy BOOK for Renewal with existing request','REGULAR_LOANS_NOTICE')
/
INSERT INTO OLE_NOTICE_TYPE_CONFIG_T (NOTICE_TYPE_CONFIG_ID,CIRC_POLICY_ID,NOTICE_TYPE)
  VALUES (5,'Check out Circ Policy Set BOOK for Max Loaned Items Greater than 3','REGULAR_LOANS_NOTICE')
/
INSERT INTO OLE_NOTICE_TYPE_CONFIG_T (NOTICE_TYPE_CONFIG_ID,CIRC_POLICY_ID,NOTICE_TYPE)
  VALUES (6,'No Circulation Policy Set Found','SHORT_TERM_LOANS_TERM_NOTICE')
/
