TRUNCATE TABLE OLE_DLVR_STAT_CAT_T
/
INSERT INTO OLE_DLVR_STAT_CAT_T (OBJ_ID,OLE_DLVR_STAT_CAT_CD,OLE_DLVR_STAT_CAT_DESC,OLE_DLVR_STAT_CAT_ID,OLE_DLVR_STAT_CAT_NM,ROW_ACT_IND,VER_NBR)
  VALUES ('dbaf6385-abe2-8slk-id63-1fdt8530bf6','SAMPLE','Sample','1','Sample','Y',1)
/
