TRUNCATE TABLE OLE_BAT_PRCS_FLE_TYP_T
/
INSERT INTO OLE_BAT_PRCS_FLE_TYP_T (ACT_IND,FLE_TYP_DESC,FLE_TYP_ID,FLE_TYP_NM,OBJ_ID,VER_NBR)
  VALUES ('Y','XML','4','XML','1','1')
/
INSERT INTO OLE_BAT_PRCS_FLE_TYP_T (ACT_IND,FLE_TYP_DESC,FLE_TYP_ID,FLE_TYP_NM,OBJ_ID,VER_NBR)
  VALUES ('Y','EDI','5','EDI','2','1')
/
INSERT INTO OLE_BAT_PRCS_FLE_TYP_T (ACT_IND,FLE_TYP_DESC,FLE_TYP_ID,FLE_TYP_NM,OBJ_ID,VER_NBR)
  VALUES ('Y','MRC','6','MRC','3','1')
/
