TRUNCATE TABLE OLE_DLVR_RQST_TYP_T
/
INSERT INTO OLE_DLVR_RQST_TYP_T (OBJ_ID,OLE_RQST_TYP_CD,OLE_RQST_TYP_DESC,OLE_RQST_TYP_ID,OLE_RQST_TYP_NM,ROW_ACT_IND,VER_NBR)
  VALUES ('1','Recall/Delivery Request','Recall Request','1','Recall/Delivery Request','Y',1)
/
INSERT INTO OLE_DLVR_RQST_TYP_T (OBJ_ID,OLE_RQST_TYP_CD,OLE_RQST_TYP_DESC,OLE_RQST_TYP_ID,OLE_RQST_TYP_NM,ROW_ACT_IND,VER_NBR)
  VALUES ('2','Recall/Hold Request','Recall/Hold Request','2','Recall/Hold Request','Y',1)
/
INSERT INTO OLE_DLVR_RQST_TYP_T (OBJ_ID,OLE_RQST_TYP_CD,OLE_RQST_TYP_DESC,OLE_RQST_TYP_ID,OLE_RQST_TYP_NM,ROW_ACT_IND,VER_NBR)
  VALUES ('3','Hold/Delivery Request','Hold Request','3','Hold/Delivery Request','Y',1)
/
INSERT INTO OLE_DLVR_RQST_TYP_T (OBJ_ID,OLE_RQST_TYP_CD,OLE_RQST_TYP_DESC,OLE_RQST_TYP_ID,OLE_RQST_TYP_NM,ROW_ACT_IND,VER_NBR)
  VALUES ('4','Hold/Hold Request','Hold/Hold Request','4','Hold/Hold Request','Y',1)
/
INSERT INTO OLE_DLVR_RQST_TYP_T (OBJ_ID,OLE_RQST_TYP_CD,OLE_RQST_TYP_DESC,OLE_RQST_TYP_ID,OLE_RQST_TYP_NM,ROW_ACT_IND,VER_NBR)
  VALUES ('5','Page/Delivery Request','Page Request','5','Page/Delivery Request','Y',1)
/
INSERT INTO OLE_DLVR_RQST_TYP_T (OBJ_ID,OLE_RQST_TYP_CD,OLE_RQST_TYP_DESC,OLE_RQST_TYP_ID,OLE_RQST_TYP_NM,ROW_ACT_IND,VER_NBR)
  VALUES ('6','Page/Hold Request','Page/Hold Request','6','Page/Hold Request','Y',1)
/
INSERT INTO OLE_DLVR_RQST_TYP_T (OBJ_ID,OLE_RQST_TYP_CD,OLE_RQST_TYP_DESC,OLE_RQST_TYP_ID,OLE_RQST_TYP_NM,ROW_ACT_IND,VER_NBR)
  VALUES ('7','Copy Request','Copy Request','7','Copy Request','Y',1)
/
INSERT INTO OLE_DLVR_RQST_TYP_T (OBJ_ID,OLE_RQST_TYP_CD,OLE_RQST_TYP_DESC,OLE_RQST_TYP_ID,OLE_RQST_TYP_NM,ROW_ACT_IND,VER_NBR)
  VALUES ('8','In Transit Request','In Transit Request','8','In Transit Request','Y',1)
/
INSERT INTO OLE_DLVR_RQST_TYP_T (OBJ_ID,OLE_RQST_TYP_CD,OLE_RQST_TYP_DESC,OLE_RQST_TYP_ID,OLE_RQST_TYP_NM,ROW_ACT_IND,VER_NBR)
  VALUES ('9','ASR Request','ASR Request','9','ASR Request','Y',1)
/
