TRUNCATE TABLE OLE_BAT_PRCS_DT_MAP_T
/
INSERT INTO OLE_BAT_PRCS_DT_MAP_T (OLE_BAT_PRCS_DT_MAP_ID,OLE_BAT_PRCS_DT_MAP_OPTN_NUM,BAT_PRCS_PRF_ID,OBJ_ID,VER_NBR)
  VALUES ('1',0,'12','1',1)
/
INSERT INTO OLE_BAT_PRCS_DT_MAP_T (OLE_BAT_PRCS_DT_MAP_ID,OLE_BAT_PRCS_DT_MAP_OPTN_NUM,BAT_PRCS_PRF_ID,OBJ_ID,VER_NBR)
  VALUES ('2',0,'12','1',1)
/
INSERT INTO OLE_BAT_PRCS_DT_MAP_T (OLE_BAT_PRCS_DT_MAP_ID,OLE_BAT_PRCS_DT_MAP_OPTN_NUM,BAT_PRCS_PRF_ID,OBJ_ID,VER_NBR)
  VALUES ('3',0,'12','1',1)
/
INSERT INTO OLE_BAT_PRCS_DT_MAP_T (OLE_BAT_PRCS_DT_MAP_ID,OLE_BAT_PRCS_DT_MAP_OPTN_NUM,BAT_PRCS_PRF_ID,OBJ_ID,VER_NBR)
  VALUES ('4',0,'14','1',1)
/
INSERT INTO OLE_BAT_PRCS_DT_MAP_T (OLE_BAT_PRCS_DT_MAP_ID,OLE_BAT_PRCS_DT_MAP_OPTN_NUM,BAT_PRCS_PRF_ID,OBJ_ID,VER_NBR)
  VALUES ('5',0,'16','1',1)
/
INSERT INTO OLE_BAT_PRCS_DT_MAP_T (OLE_BAT_PRCS_DT_MAP_ID,OLE_BAT_PRCS_DT_MAP_OPTN_NUM,BAT_PRCS_PRF_ID,OBJ_ID,VER_NBR)
  VALUES ('6',0,'18','1',1)
/
INSERT INTO OLE_BAT_PRCS_DT_MAP_T (OLE_BAT_PRCS_DT_MAP_ID,OLE_BAT_PRCS_DT_MAP_OPTN_NUM,BAT_PRCS_PRF_ID,OBJ_ID,VER_NBR)
  VALUES ('7',0,'6','1',1)
/
INSERT INTO OLE_BAT_PRCS_DT_MAP_T (OLE_BAT_PRCS_DT_MAP_ID,OLE_BAT_PRCS_DT_MAP_OPTN_NUM,BAT_PRCS_PRF_ID,OBJ_ID,VER_NBR)
  VALUES ('8',0,'5','1',1)
/
INSERT INTO OLE_BAT_PRCS_DT_MAP_T (OLE_BAT_PRCS_DT_MAP_ID,OLE_BAT_PRCS_DT_MAP_OPTN_NUM,BAT_PRCS_PRF_ID,OBJ_ID,VER_NBR)
  VALUES ('9',0,'21','1',1)
/
