TRUNCATE TABLE OLE_CLNDR_EXP_TYP_T
/
INSERT INTO OLE_CLNDR_EXP_TYP_T (EXP_TYP_ID,EXP_TYP_CODE,EXP_TYP_NAME,VER_NBR,OBJ_ID,EXP_TYP_IND)
  VALUES ('1000','HDY','Holiday',1,'OLECALEXPTYP100','Y')
/
INSERT INTO OLE_CLNDR_EXP_TYP_T (EXP_TYP_ID,EXP_TYP_CODE,EXP_TYP_NAME,VER_NBR,OBJ_ID,EXP_TYP_IND)
  VALUES ('1001','PDY','Partial',2,'OLECALEXPTYP101','Y')
/
