TRUNCATE TABLE OLE_BAT_PRCS_MNTN_FIELD_T
/
INSERT INTO OLE_BAT_PRCS_MNTN_FIELD_T (OLE_BAT_FIELD_ID,OLE_BAT_FIELD_DISPLY_NM,OLE_BAT_FIELD_NM,OLE_BAT_FIELD_TYP,ACT_IND,OBJ_ID,VER_NBR)
  VALUES ('1','Bib Local Id','LocalId_search','String','Y','1','1')
/
INSERT INTO OLE_BAT_PRCS_MNTN_FIELD_T (OLE_BAT_FIELD_ID,OLE_BAT_FIELD_DISPLY_NM,OLE_BAT_FIELD_NM,OLE_BAT_FIELD_TYP,ACT_IND,OBJ_ID,VER_NBR)
  VALUES ('2','Bib Status','Status_search','String','Y','1','1')
/
INSERT INTO OLE_BAT_PRCS_MNTN_FIELD_T (OLE_BAT_FIELD_ID,OLE_BAT_FIELD_DISPLY_NM,OLE_BAT_FIELD_NM,OLE_BAT_FIELD_TYP,ACT_IND,OBJ_ID,VER_NBR)
  VALUES ('3','Bib Status Updated Date','statusUpdatedOn','Date','Y','1','1')
/
INSERT INTO OLE_BAT_PRCS_MNTN_FIELD_T (OLE_BAT_FIELD_ID,OLE_BAT_FIELD_DISPLY_NM,OLE_BAT_FIELD_NM,OLE_BAT_FIELD_TYP,ACT_IND,OBJ_ID,VER_NBR)
  VALUES ('4','Date Updated(of Bib, Holdings or Item)','dateUpdated','Date','Y','1','1')
/
INSERT INTO OLE_BAT_PRCS_MNTN_FIELD_T (OLE_BAT_FIELD_ID,OLE_BAT_FIELD_DISPLY_NM,OLE_BAT_FIELD_NM,OLE_BAT_FIELD_TYP,ACT_IND,OBJ_ID,VER_NBR)
  VALUES ('5','Date Entered(of Bib, Holdings or Item)','dateEntered','Date','Y','1','1')
/
INSERT INTO OLE_BAT_PRCS_MNTN_FIELD_T (OLE_BAT_FIELD_ID,OLE_BAT_FIELD_DISPLY_NM,OLE_BAT_FIELD_NM,OLE_BAT_FIELD_TYP,ACT_IND,OBJ_ID,VER_NBR)
  VALUES ('6','Created By(of Bib, Holdings or Item)','createdBy','String','Y','1','1')
/
INSERT INTO OLE_BAT_PRCS_MNTN_FIELD_T (OLE_BAT_FIELD_ID,OLE_BAT_FIELD_DISPLY_NM,OLE_BAT_FIELD_NM,OLE_BAT_FIELD_TYP,ACT_IND,OBJ_ID,VER_NBR)
  VALUES ('7','Updated By(of Bib, Holdings or Item)','updatedBy','String','Y','1','1')
/
INSERT INTO OLE_BAT_PRCS_MNTN_FIELD_T (OLE_BAT_FIELD_ID,OLE_BAT_FIELD_DISPLY_NM,OLE_BAT_FIELD_NM,OLE_BAT_FIELD_TYP,ACT_IND,OBJ_ID,VER_NBR)
  VALUES ('8','Staff Only(of Bib, Holdings or Item)','staffOnlyFlag','String','Y','1','1')
/
INSERT INTO OLE_BAT_PRCS_MNTN_FIELD_T (OLE_BAT_FIELD_ID,OLE_BAT_FIELD_DISPLY_NM,OLE_BAT_FIELD_NM,OLE_BAT_FIELD_TYP,ACT_IND,OBJ_ID,VER_NBR)
  VALUES ('9','Bib Local Id From File','LocalId_display','String','Y','1','1')
/
