TRUNCATE TABLE OLE_LIC_WRK_FLW_TYP_T
/
INSERT INTO OLE_LIC_WRK_FLW_TYP_T (LIC_WRK_FLW_TYP_CD,LIC_WRK_FLW_TYP_DESC,LIC_WRK_FLW_TYP_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('ADDUM','Addendum','Addendum','3abe4cf4-4410-4f26-au49-0338aad4f445','Y',1)
/
INSERT INTO OLE_LIC_WRK_FLW_TYP_T (LIC_WRK_FLW_TYP_CD,LIC_WRK_FLW_TYP_DESC,LIC_WRK_FLW_TYP_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('APPO','Approval Only','Approval Only','3abe4cf4-4410-4ap6-a949-0338aad4f445','Y',1)
/
INSERT INTO OLE_LIC_WRK_FLW_TYP_T (LIC_WRK_FLW_TYP_CD,LIC_WRK_FLW_TYP_DESC,LIC_WRK_FLW_TYP_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('FAPP','Full Approval','Full Approval','ea63bf90-1db8-48d8-fbe1-7ee1f31ef176','Y',1)
/
INSERT INTO OLE_LIC_WRK_FLW_TYP_T (LIC_WRK_FLW_TYP_CD,LIC_WRK_FLW_TYP_DESC,LIC_WRK_FLW_TYP_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('INN','In Negotiation','In Negotiation','ec379e7e-b22e-44e4-8in3-c646dc076635','Y',1)
/
INSERT INTO OLE_LIC_WRK_FLW_TYP_T (LIC_WRK_FLW_TYP_CD,LIC_WRK_FLW_TYP_DESC,LIC_WRK_FLW_TYP_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('IPS','In Process','In Process','dd5fb5c2-7c7d-466e-b8ip-2e49a5e37d23','Y',1)
/
INSERT INTO OLE_LIC_WRK_FLW_TYP_T (LIC_WRK_FLW_TYP_CD,LIC_WRK_FLW_TYP_DESC,LIC_WRK_FLW_TYP_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('LIRC','License Received','License Received','1fdeirb8-ad6c-4e23-bb6c-0a2c82a169e4','Y',1)
/
INSERT INTO OLE_LIC_WRK_FLW_TYP_T (LIC_WRK_FLW_TYP_CD,LIC_WRK_FLW_TYP_DESC,LIC_WRK_FLW_TYP_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('LND','License Needed','License Needed','e508cln3-7fc7-4ea1-9362-01b6fd11f061','Y',1)
/
INSERT INTO OLE_LIC_WRK_FLW_TYP_T (LIC_WRK_FLW_TYP_CD,LIC_WRK_FLW_TYP_DESC,LIC_WRK_FLW_TYP_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('LRTD','License Requested','License Requested','dc6lr911-4dac-4709-8551-61e4471bf89c','Y',1)
/
INSERT INTO OLE_LIC_WRK_FLW_TYP_T (LIC_WRK_FLW_TYP_CD,LIC_WRK_FLW_TYP_DESC,LIC_WRK_FLW_TYP_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('REWAL','Renewal','Renewal','3abe4cf4-re10-4f26-a949-0338aad4f445','Y',1)
/
INSERT INTO OLE_LIC_WRK_FLW_TYP_T (LIC_WRK_FLW_TYP_CD,LIC_WRK_FLW_TYP_DESC,LIC_WRK_FLW_TYP_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('RVWO','Review Only','Review Only','3abe4cf4-4410-4f26-avm9-0338aad4f445','Y',1)
/
INSERT INTO OLE_LIC_WRK_FLW_TYP_T (LIC_WRK_FLW_TYP_CD,LIC_WRK_FLW_TYP_DESC,LIC_WRK_FLW_TYP_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('SIGO','Signatory Only','Signatory Only','18b86si7-2e45-4293-8459-755953a8765d','Y',1)
/
