TRUNCATE TABLE OLE_CAT_LOC_COUNTRY_CD_T
/
INSERT INTO OLE_CAT_LOC_COUNTRY_CD_T (LOC_COUNTRY_CD,LOC_COUNTRY_CD_ID,LOC_COUNTRY_NM,LOC_COUNTRY_REGION_NM,LOC_COUNTRY_SEQUENCE_NM,OBJ_ID,ROW_ACT_IND,SRC,SRC_DT,VER_NBR)
  VALUES ('aa',1,'Albania','Europe','Reunion','4dcdf94f-fc19-40f4-86b6-9a3a66d42bda','Y','http://www.loc.gov/marc/countries',STR_TO_DATE( '20120405120000', '%Y%m%d%H%i%s' ),3)
/
INSERT INTO OLE_CAT_LOC_COUNTRY_CD_T (LOC_COUNTRY_CD,LOC_COUNTRY_CD_ID,LOC_COUNTRY_NM,LOC_COUNTRY_REGION_NM,LOC_COUNTRY_SEQUENCE_NM,OBJ_ID,ROW_ACT_IND,SRC,SRC_DT,VER_NBR)
  VALUES ('in',2,'India','Asia','Reunion','8bcdf94f-fc19-40f4-86b6-9a3a66d42bda','Y','http://www.loc.gov/marc/countries',STR_TO_DATE( '20120405120000', '%Y%m%d%H%i%s' ),3)
/
