TRUNCATE TABLE OLE_DS_SEARCH_FACET_SIZE_T
/
INSERT INTO OLE_DS_SEARCH_FACET_SIZE_T (DOC_SEARCH_FACET_SIZE_ID,SHORT_SIZE,LONG_SIZE,OBJ_ID,VER_NBR)
  VALUES (1,5,50,'7a1e31e8-e5ab-4edd-aab5-4h3e49fe5e1h',1)
/
