TRUNCATE TABLE OLE_DESC_USER_PREF_T
/
INSERT INTO OLE_DESC_USER_PREF_T (CALL_NUM_1,CALL_NUM_2,CALL_NUM_3,CLASSIFICATION_SCHEME,IMPORT_STATUS,IMPORT_TYPE,OBJ_ID,PERM_LOC,PREF_ID,PREF_NAME,PROTECTED_TAGS,REMOVAL_TAGS,TEMP_LOC,USER_ID,USER_ROLE,VER_NBR)
  VALUES ('050','065','020','LCC','None','newImport','1','',1,'Admin Import','','','','admin','admin',1)
/
