TRUNCATE TABLE OLE_BAT_PRF_DEL_FLD_T
/
INSERT INTO OLE_BAT_PRF_DEL_FLD_T (BAT_PRF_DEL_ID,BAT_PRCS_PRF_ID,BAT_PRF_DEL_TAG,BAT_PRF_DEL_IND1,BAT_PRF_DEL_IND2,BAT_PRF_DEL_SUBFLD,BAT_PRF_DEL_SUB_CNTN,OBJ_ID,VER_NBR)
  VALUES ('1','10','200','','','','','1',2)
/
INSERT INTO OLE_BAT_PRF_DEL_FLD_T (BAT_PRF_DEL_ID,BAT_PRCS_PRF_ID,BAT_PRF_DEL_TAG,BAT_PRF_DEL_IND1,BAT_PRF_DEL_IND2,BAT_PRF_DEL_SUBFLD,BAT_PRF_DEL_SUB_CNTN,OBJ_ID,VER_NBR)
  VALUES ('2','11','250','','','a','','1',2)
/
INSERT INTO OLE_BAT_PRF_DEL_FLD_T (BAT_PRF_DEL_ID,BAT_PRCS_PRF_ID,BAT_PRF_DEL_TAG,BAT_PRF_DEL_IND1,BAT_PRF_DEL_IND2,BAT_PRF_DEL_SUBFLD,BAT_PRF_DEL_SUB_CNTN,OBJ_ID,VER_NBR)
  VALUES ('3','12','230','2','1','a','','1',1)
/
INSERT INTO OLE_BAT_PRF_DEL_FLD_T (BAT_PRF_DEL_ID,BAT_PRCS_PRF_ID,BAT_PRF_DEL_TAG,BAT_PRF_DEL_IND1,BAT_PRF_DEL_IND2,BAT_PRF_DEL_SUBFLD,BAT_PRF_DEL_SUB_CNTN,OBJ_ID,VER_NBR)
  VALUES ('4','12','500','2','1','b','','1',1)
/
INSERT INTO OLE_BAT_PRF_DEL_FLD_T (BAT_PRF_DEL_ID,BAT_PRCS_PRF_ID,BAT_PRF_DEL_TAG,BAT_PRF_DEL_IND1,BAT_PRF_DEL_IND2,BAT_PRF_DEL_SUBFLD,BAT_PRF_DEL_SUB_CNTN,OBJ_ID,VER_NBR)
  VALUES ('5','12','245','','','a','','1',1)
/
INSERT INTO OLE_BAT_PRF_DEL_FLD_T (BAT_PRF_DEL_ID,BAT_PRCS_PRF_ID,BAT_PRF_DEL_TAG,BAT_PRF_DEL_IND1,BAT_PRF_DEL_IND2,BAT_PRF_DEL_SUBFLD,BAT_PRF_DEL_SUB_CNTN,OBJ_ID,VER_NBR)
  VALUES ('6','13','400','','','a','','1',1)
/
INSERT INTO OLE_BAT_PRF_DEL_FLD_T (BAT_PRF_DEL_ID,BAT_PRCS_PRF_ID,BAT_PRF_DEL_TAG,BAT_PRF_DEL_IND1,BAT_PRF_DEL_IND2,BAT_PRF_DEL_SUBFLD,BAT_PRF_DEL_SUB_CNTN,OBJ_ID,VER_NBR)
  VALUES ('7','14','500','','','a','','2',1)
/
INSERT INTO OLE_BAT_PRF_DEL_FLD_T (BAT_PRF_DEL_ID,BAT_PRCS_PRF_ID,BAT_PRF_DEL_TAG,BAT_PRF_DEL_IND1,BAT_PRF_DEL_IND2,BAT_PRF_DEL_SUBFLD,BAT_PRF_DEL_SUB_CNTN,OBJ_ID,VER_NBR)
  VALUES ('8','15','550','','','a','','1',1)
/
INSERT INTO OLE_BAT_PRF_DEL_FLD_T (BAT_PRF_DEL_ID,BAT_PRCS_PRF_ID,BAT_PRF_DEL_TAG,BAT_PRF_DEL_IND1,BAT_PRF_DEL_IND2,BAT_PRF_DEL_SUBFLD,BAT_PRF_DEL_SUB_CNTN,OBJ_ID,VER_NBR)
  VALUES ('9','16','460','','','a','','1',1)
/
INSERT INTO OLE_BAT_PRF_DEL_FLD_T (BAT_PRF_DEL_ID,BAT_PRCS_PRF_ID,BAT_PRF_DEL_TAG,BAT_PRF_DEL_IND1,BAT_PRF_DEL_IND2,BAT_PRF_DEL_SUBFLD,BAT_PRF_DEL_SUB_CNTN,OBJ_ID,VER_NBR)
  VALUES ('10','17','470','','','a','','1',1)
/
INSERT INTO OLE_BAT_PRF_DEL_FLD_T (BAT_PRF_DEL_ID,BAT_PRCS_PRF_ID,BAT_PRF_DEL_TAG,BAT_PRF_DEL_IND1,BAT_PRF_DEL_IND2,BAT_PRF_DEL_SUBFLD,BAT_PRF_DEL_SUB_CNTN,OBJ_ID,VER_NBR)
  VALUES ('11','18','570','','','a','','1',1)
/
