TRUNCATE TABLE OLE_DLVR_LOAN_TERM_UNIT_T
/
INSERT INTO OLE_DLVR_LOAN_TERM_UNIT_T (LOAN_TERM_UNIT_CD,LOAN_TERM_UNIT_ID,LOAN_TERM_UNIT_NM,OBJ_ID,VER_NBR)
  VALUES ('MINUTE','1','Minutes','4dcdf94f-fc19-40f4-86b6-9a3a66d42bda',1)
/
INSERT INTO OLE_DLVR_LOAN_TERM_UNIT_T (LOAN_TERM_UNIT_CD,LOAN_TERM_UNIT_ID,LOAN_TERM_UNIT_NM,OBJ_ID,VER_NBR)
  VALUES ('DAY','2','Days','4dcdf94f-fc19-40f4-86b6-9a3a66d42bda',1)
/
INSERT INTO OLE_DLVR_LOAN_TERM_UNIT_T (LOAN_TERM_UNIT_CD,LOAN_TERM_UNIT_ID,LOAN_TERM_UNIT_NM,OBJ_ID,VER_NBR)
  VALUES ('HOUR','3','Hours','4dcdf94f-fc19-40f4-86b6-9a3a66d42bda',1)
/
INSERT INTO OLE_DLVR_LOAN_TERM_UNIT_T (LOAN_TERM_UNIT_CD,LOAN_TERM_UNIT_ID,LOAN_TERM_UNIT_NM,OBJ_ID,VER_NBR)
  VALUES ('WEEK','4','Weeks','4dcdf94f-fc19-40f4-86b6-9a3a66d42bda',1)
/
INSERT INTO OLE_DLVR_LOAN_TERM_UNIT_T (LOAN_TERM_UNIT_CD,LOAN_TERM_UNIT_ID,LOAN_TERM_UNIT_NM,OBJ_ID,VER_NBR)
  VALUES ('UNSPECIFIED','5','Unspecified','4dcdf94f-fc19-40f4-86b6-9a3a66d42bda',1)
/
INSERT INTO OLE_DLVR_LOAN_TERM_UNIT_T (LOAN_TERM_UNIT_CD,LOAN_TERM_UNIT_ID,LOAN_TERM_UNIT_NM,OBJ_ID,VER_NBR)
  VALUES ('NONCIRC','6','Non-circulating','4dcdf94f-fc19-40f4-86b6-9a3a66d42bda',1)
/
INSERT INTO OLE_DLVR_LOAN_TERM_UNIT_T (LOAN_TERM_UNIT_CD,LOAN_TERM_UNIT_ID,LOAN_TERM_UNIT_NM,OBJ_ID,VER_NBR)
  VALUES ('FIXEDDATE','7','Fixed date','4dcdf94f-fc19-40f4-86b6-9a3a66d42bda',1)
/
INSERT INTO OLE_DLVR_LOAN_TERM_UNIT_T (LOAN_TERM_UNIT_CD,LOAN_TERM_UNIT_ID,LOAN_TERM_UNIT_NM,OBJ_ID,VER_NBR)
  VALUES ('MONTH','8','Months','4dcdf94f-fc19-40f4-86b6-9a3a66d42bda',1)
/
