package org.kuali.ole.deliver.rules.demo.fines

import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ItemFineRate
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.bo.PatronBillPayment


rule "Requested Items Daily fines"
agenda-group "fine validation"
activation-group "fine validation"
when

$l: OleLoanDocument(isItemHasRequest())

$f: ItemFineRate()

$i: OleItemRecordForCirc(getItemType() in ("API","BOOK","AV","AUDIOCD","CURRICULUM"),
getItemLibraryLocation() in ("LSC","B-EDUC","B-HPER","DLL","SCL","DOCS"))

$p: OlePatronDocument(getBorrowerTypeCode() in ("ALUM","AVR","FAC","FACR","GRAD","GUEST","RES","STAFF","UGRAD"))

then
$f.setFineRate(5.00);
$f.setMaxFine(120.00);
$f.setInterval("D"); //Options are H-Hours; D-Days

end



 rule "Items Daily fines"
 agenda-group "fine validation"
 activation-group "fine validation"
 when

 $l: OleLoanDocument(!isItemHasRequest())

 $f: ItemFineRate()

 $i: OleItemRecordForCirc(getItemType() in ("API","BOOK","AV","AUDIOCD","CURRICULUM"),
 getItemLibraryLocation() in ("LSC","B-EDUC","B-HPER","DLL","SCL","DOCS"))

 $p: OlePatronDocument(getBorrowerTypeCode() in ("ALUM","AVR","FAC","FACR","GRAD","GUEST","RES","STAFF","UGRAD"))

 then
 $f.setFineRate(3.00);
 $f.setMaxFine(120.00);
 $f.setInterval("D"); //Options are H-Hours; D-Days

  end