package org.kuali.ole.deliver.rules.demo.checkin


import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OleCirculationDesk
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.deliver.drools.DroolsConstants



 rule "Recently returned Check based on shelving lag time"
agenda-group "checkin-validation-for-loan"
activation-group "checkin-validation-for-loan"

when
$c: OleCirculationDesk( $c.getShelvingLagTimeInt() > 0)
$i: OleItemRecordForCirc(null!= isCheckinLocationSameAsHomeLocation(),isCheckinLocationSameAsHomeLocation(),
$r:getOleDeliverRequestBo(), null== $r,
$s: getItemStatusRecord(),null != $s, !$s.getCode().equals("INTRANSIT-PER-STAFF-REQUEST"))
$d : DroolsResponse()


then
$i.setItemStatusToBeUpdatedTo("RECENTLY-RETURNED");
$i.updateCheckinCount();
$d.setRuleMatched(true);
$d.getDroolsExchange().addToContext(DroolsConstants.SHOW_LOCATION_POPUP, true);
 end

 rule "Available Check based on shelving lag time"
agenda-group "checkin-validation-for-loan"
activation-group "checkin-validation-for-loan"

when
$c: OleCirculationDesk( $c.getShelvingLagTimeInt() == 0)
$i: OleItemRecordForCirc(null!= isCheckinLocationSameAsHomeLocation(),isCheckinLocationSameAsHomeLocation(),
$r:getOleDeliverRequestBo(), null== $r,
$s: getItemStatusRecord(),null != $s, !$s.getCode().equals("INTRANSIT-PER-STAFF-REQUEST"))
$d : DroolsResponse()

then
$i.setItemStatusToBeUpdatedTo("AVAILABLE");
$i.updateCheckinCount();
$d.setRuleMatched(true);
$d.getDroolsExchange().addToContext(DroolsConstants.SHOW_LOCATION_POPUP, true);
 end

rule "InTransitCheck for item location mapped to circulation desk"
agenda-group "checkin-validation-for-loan"
activation-group "checkin-validation-for-loan"

when

$i: OleItemRecordForCirc(null!= isCheckinLocationSameAsHomeLocation(),!isCheckinLocationSameAsHomeLocation(),
    isLocationMappedToCirculationDesk(),
$r:getOleDeliverRequestBo(), null== $r,
$s: getItemStatusRecord(),null != $s, !$s.getCode().equals("INTRANSIT-PER-STAFF-REQUEST"))
$d : DroolsResponse()

then
$i.setItemStatusToBeUpdatedTo("INTRANSIT");
$i.updateCheckinCount();
$d.setRuleMatched(true);
$d.getDroolsExchange().addToContext(DroolsConstants.PRINT_SLIP_FLAG, true);
end

rule "InTransitCheck for item location not mapped to circulation desk"
agenda-group "checkin-validation-for-loan"
activation-group "checkin-validation-for-loan"

when

$i: OleItemRecordForCirc(null!= isCheckinLocationSameAsHomeLocation(),!isCheckinLocationSameAsHomeLocation(),
    !isLocationMappedToCirculationDesk(),
$r:getOleDeliverRequestBo(), null== $r,
$s: getItemStatusRecord(),null != $s, !$s.getCode().equals("INTRANSIT-PER-STAFF-REQUEST"))
$d : DroolsResponse()

then
$i.setItemStatusToBeUpdatedTo("INTRANSIT");
$i.updateCheckinCount();
$d.setRuleMatched(true);
$d.getDroolsExchange().addToContext(DroolsConstants.PRINT_SLIP_FLAG, true);
$d.getDroolsExchange().addToContext(DroolsConstants.ROUTE_TO_LOCATION_SELECTOR, true);
 end



