package org.kuali.ole.deliver.rules.chicago.ncip
import org.kuali.ole.deliver.bo.OleDeliverRequestBo
import org.kuali.ole.deliver.bo.OleDroolsHoldResponseBo
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.util.NoticeInfo


rule "RQ-FORD-STANDARDLOAN ls than 10 RC"
agenda-group "place-request"
when
$p : OlePatronDocument(getBorrowerTypeCode() in ("FQFACULTY"))
$dr: OleDeliverRequestBo(getItemType() in ("STANDARDLOAN"),
    getItemLibrary() in ("FORD"),
    getRequestTypeCode() in ("Recall/Hold Request","Recall/Delivery Request"),getRecallRequestCount() < 10)
$d : DroolsResponse()
$n : NoticeInfo()
then
$d.setRuleMatched(true);
$n.setNoticeType(OLEConstants.NOTICE_RECALL);
$d.getDroolsExchange().addToContext("requestExpirationDays",90);
$d.getDroolsExchange().addToContext("minimumLoanPeriod","14-D");
$d.getDroolsExchange().addToContext("recallLoanPeriod","7-D");
end



rule "RQ-FORD-STANDARDLOAN gr than 10 RC"
agenda-group "place-request"
when
$p : OlePatronDocument(getBorrowerTypeCode() in ("FQFACULTY"))
$dr: OleDeliverRequestBo(getItemType() in ("STANDARDLOAN"),
    getItemLibrary() in ("FORD"),
    getRequestTypeCode() in ("Recall/Hold Request","Recall/Delivery Request"),getRecallRequestCount() >= 10)
$d : DroolsResponse()
$n : NoticeInfo()
then
$d.addErrorMessage("Hold Requests exceeds the maximum (10).");
$d.addOverridePermissions(OLEConstants.GENERAL_BLOCK);
end


