package org.kuali.ole.deliver.rules.request
import org.kuali.ole.deliver.bo.OleDeliverRequestBo
import org.kuali.ole.deliver.bo.OleDroolsHoldResponseBo
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.util.NoticeInfo


rule "RQ-FORD-UG-STDLOAN-RC"
agenda-group "place-request"
activation-group "place-request"
when
$d : DroolsResponse()
$n : NoticeInfo()

$p : OlePatronDocument(getBorrowerTypeCode() in ("UG"))
$dr: OleDeliverRequestBo(getItemType() in ("STANDARDLOAN"),
getRequestTypeCode() in ("Recall/Hold Request"),
    getItemLibrary() in ("FORD"))

then
$d.setRuleMatched(true);
$n.setNoticeType("NO-RC-FORD-STANDARDLOAN");
$d.getDroolsExchange().addToContext("requestExpirationDays",90);
$d.getDroolsExchange().addToContext("minimumLoanPeriod","14-D");
$d.getDroolsExchange().addToContext("recallLoanPeriod","7-D");
end

