package org.kuali.ole.deliver.rules.chicago.ncip
import org.kuali.ole.deliver.bo.OleDeliverRequestBo
import org.kuali.ole.deliver.bo.OleDroolsHoldResponseBo
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.util.NoticeInfo


rule "Circulation Policy Set 2 Validation for Request with recall count of less than 10"
agenda-group "place-request"
when
$p : OlePatronDocument(getBorrowerTypeCode() in ("FQ-Faculty"))
$dr: OleDeliverRequestBo(getItemType() in ("STANDARD-LOAN",),
    getItemLibrary() in ("FORD"),
    getRequestTypeCode() in ("Recall/Hold Request","Recall/Delivery Request"),getRecallRequestCount() < 10)
$d : DroolsResponse()
$n : NoticeInfo()
then
$d.setRuleMatched(true);
$n.setNoticeType(OLEConstants.NOTICE_RECALL);
$d.getDroolsExchange().addToContext("requestExpirationDays",90);
$d.getDroolsExchange().addToContext("minimumLoanPeriod","14-D");
$d.getDroolsExchange().addToContext("recallLoanPeriod","7-D");
end



rule "Circulation Policy Set 2 Validation for Request with recall count of less than 10"
agenda-group "place-request"
when
$p : OlePatronDocument(getBorrowerTypeCode() in ("FQ-Faculty"))
$dr: OleDeliverRequestBo(getItemType() in ("STANDARD-LOAN",),
    getItemLibrary() in ("FORD"),
    getRequestTypeCode() in ("Recall/Hold Request","Recall/Delivery Request"),getRecallRequestCount() >= 10)
$d : DroolsResponse()
$n : NoticeInfo()
then
$d.addErrorMessage("Hold Requests exceeds the maximum (2).");
$d.addOverridePermissions(OLEConstants.GENERAL_BLOCK);
end



