package org.kuali.ole.deliver.checkout

import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ItemFineRate
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.bo.PatronBillPayment


rule "Requested Items daily fines"
agenda-group "fine validation"
activation-group "fine validation"
when

$l: OleLoanDocument(isItemHasRequest())

$f: ItemFineRate()

$i: OleItemRecordForCirc(getItemType() in ("res168","stks7","buo","bordirc","stks14","stks"),
getItemLibraryLocation() in ("JRL","JCL","ASR","DLL","Eck","SSAd"))

$p: OlePatronDocument(getBorrowerTypeCode() in ("QCOL","QGRAD","QNONDEG","QNONUC","QNONUC25","QSTF","QOTHER",
                                                 "QUNLIM_ACD","QUNLIM_PHD", "QUNLIM_NONUC","NWU","UIC","ACCESS","QALUM25"))

then
$f.setFineRate(5.00);
$f.setMaxFine(120.00);
$f.setInterval("D"); //Options are H-Hours; D-Days

 end


rule "Items daily fines"
agenda-group "fine validation"
activation-group "fine validation"
when

 $l: OleLoanDocument(!isItemHasRequest())

$f: ItemFineRate()

$i: OleItemRecordForCirc(getItemType() in ("res168","stks7","buo","bordirc","stks14","stks"),
getItemLibraryLocation() in ("JRL","JCL","ASR","DLL","Eck","SSAd"))

 $p: OlePatronDocument(getBorrowerTypeCode() in ("QCOL","QGRAD","QNONDEG","QNONUC","QNONUC25","QSTF","QOTHER",
                                                 "QUNLIM_ACD","QUNLIM_PHD", "QUNLIM_NONUC","NWU","UIC","ACCESS","QALUM25"))

then
$f.setFineRate(3.00);
$f.setMaxFine(120.00);
$f.setInterval("D"); //Options are H-Hours; D-Days

 end