package org.kuali.ole.deliver.checkout

import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ItemFineRate
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.bo.PatronBillPayment



rule "ITS IPD fines"
agenda-group "fine validation"
activation-group "fine validation"
when



$f: ItemFineRate()

$i: OleItemRecordForCirc(getItemType() in ("its8ipd"))


then
$f.setFineRate(20.00);
$f.setMaxFine(900.00);
$f.setInterval("H"); //Options are H-Hours; D-Days

 end

