package org.kuali.ole.deliver.checkout

import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ItemFineRate
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.bo.PatronBillPayment



rule "ITS 10 fines"
agenda-group "fine validation"
activation-group "fine validation"
when



$f: ItemFineRate()

$i: OleItemRecordForCirc(getItemType() in ("its2adp","its8adp"),
getItemLibraryLocation() in ("ITS"))


then
$f.setFineRate(10.00);
$f.setMaxFine(90.00);
$f.setInterval("H"); //Options are H-Hours; D-Days

 end

