package org.kuali.ole.deliver.checkout

import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ItemFineRate
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.bo.PatronBillPayment

 rule "Items hourly fines "
 agenda-group "fine validation"
 activation-group "fine validation"
 when

 $l: OleLoanDocument($r:getOleDeliverRequestBo(), null == $r)

 $f: ItemFineRate()

 $i: OleItemRecordForCirc(getItemType() in ("res2","res4","res24","res48","res72"),
 getItemLibraryLocation() in ("JRL","JCL","ASR","DLL","Eck","SSAd"))

 $p: OlePatronDocument(getBorrowerTypeCode() in ("QCOL","QGRAD","QNONDEG","QNONUC","QNONUC25","QSTF","QOTHER",
 "QUNLIM_ACD","QUNLIM_PHD","QUNLIM_NONUC","NWU","UIC","ACCESS","QALUM25"))

 then
 $f.setFineRate(3.00);
 $f.setMaxFine(100.00);
 $f.setInterval("H"); //Options are H-Hours; D-Days

  end
