--  *********************************************************************
--  Update Database Script
--  *********************************************************************
--  Change Log: org/kuali/ole/1.5.5/db.changelog-20141015.xml
--  *********************************************************************

--  Lock Database
--  Changeset org/kuali/ole/1.5.5/db.changelog-20141015.xml::OLE_LOAD_KRCR_PARM_T_FINE::ole
SET sql_mode='NO_BACKSLASH_ESCAPES'
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'INCLUDE_NON_WORKING_HRS_FOR_FINE_CAL', 'a2896a15-add0-4f4a-88dc-58f4fa3fbf40', '1', 'CONFG', 'true', 'This is for configuring the including non working hrs for fine calculation.', 'A', 'OLE')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'NCIP_BIB_ITEM_INFORMATION', '1233445445', '1', 'CONFG', 'select oit.HOLDINGS_ID, oit.ITEM_TYPE_ID as ITEM_TYPE_ID,oit.CALL_NUMBER as ITEM_CALL_NUMBER,oit.ENUMERATION as ITEM_VOLUME_NUMBER ,oit.COPY_NUMBER as ITEM_COPY_NUMBER,oit.LOCATION as ITEM_LOCATION, oht.LOCATION as HOLDINGS_LOCATION, oht.CALL_NUMBER as HOLDINGS_CALL_NUMBER, oht.COPY_NUMBER as HOLDINGS_COPY_NUMBER, obt.TITLE as TITLE, obt.AUTHOR as AUTHOR  from OLE_DS_ITEM_T oit, OLE_DS_HOLDINGS_T oht, OLE_DS_BIB_INFO_T obt where oit.BARCODE= ? and oit.HOLDINGS_ID=oht.HOLDINGS_ID and oht.BIB_ID =obt.BIB_ID', 'ncip query for fetching item information.', 'A', 'OLE')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'NCIP_BIB_ITEM_INFORMATION_FINE', '1233445446', '1', 'CONFG', 'select oit.HOLDINGS_ID, oit.ITEM_STATUS_ID as ITEM_STATUS_ID,oit.ITEM_TYPE_ID as ITEM_TYPE_ID,oit.CALL_NUMBER as ITEM_CALL_NUMBER,oit.ENUMERATION as ITEM_VOLUME_NUMBER ,oit.COPY_NUMBER as ITEM_COPY_NUMBER,oit.LOCATION as ITEM_LOCATION, oht.LOCATION as HOLDINGS_LOCATION, oht.CALL_NUMBER as HOLDINGS_CALL_NUMBER, oht.COPY_NUMBER as HOLDINGS_COPY_NUMBER, obt.TITLE as TITLE, obt.AUTHOR as AUTHOR  from OLE_DS_ITEM_T oit, OLE_DS_HOLDINGS_T oht, OLE_DS_BIB_INFO_T obt where oit.BARCODE= ? and oit.HOLDINGS_id=oht.HOLDINGS_ID and oht.BIB_ID =obt.BIB_ID', 'ncip query for fine.', 'A', 'OLE')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'NCIP_BIB_ITEM_INFORMATION_HOLD', '1233445447', '1', 'CONFG', 'select oit.HOLDINGS_ID, oit.ITEM_STATUS_ID as ITEM_STATUS_ID,oit.ITEM_TYPE_ID as ITEM_TYPE_ID,oit.CALL_NUMBER as ITEM_CALL_NUMBER,oit.ENUMERATION as ITEM_VOLUME_NUMBER ,oit.COPY_NUMBER as ITEM_COPY_NUMBER,oit.LOCATION as ITEM_LOCATION, oht.LOCATION as HOLDINGS_LOCATION, oht.CALL_NUMBER as HOLDINGS_CALL_NUMBER, oht.COPY_NUMBER as HOLDINGS_COPY_NUMBER, obt.TITLE as TITLE, obt.AUTHOR as AUTHOR  from OLE_DS_ITEM_T oit, OLE_DS_HOLDINGS_T oht, OLE_DS_BIB_INFO_T obt where oit.BARCODE= ? and oit.HOLDINGS_id=oht.HOLDINGS_ID and oht.BIB_ID=obt.BIB_ID', 'ncip query for holding', 'A', 'OLE')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-SYS', 'Batch', 'ACTN_LIST_BATCH_DOC_TYP_CD', 'ffd3a3d1-f168-4b5b-8d41-0870982c860d', '12', 'CONFG', '	"*', 'Document Type for the action to be taken', 'A', 'OLE')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-SYS', 'Batch', 'ACTN_LIST_BATCH_PRNPL_NM', '01125394-0ca5-44c1-a0c6-8e1a981110a9', '13', 'CONFG', '26031', 'Principal ID on whose action list actions need to be taken on.', 'A', 'OLE')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-SYS', 'Batch', 'ACTN_LIST_BATCH_RQST_CD', 'e3c94c1b-e1ee-486e-b781-5c4695726083', '18', 'CONFG', 'C', 'Request Code for the action that needs to be taken (K-Ack, A-Approve, F-FYI, C-Complete)', 'A', 'OLE')
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_LOAD_KRCR_PARM_T_FINE', 'ole', 'org/kuali/ole/1.5.5/db.changelog-20141015.xml', NOW(), 1, '7:9e17cc197dbbf3c51d98c173d10efe13', 'sql, loadData', '', 'EXECUTED', '3.2.0')
/

--  Changeset org/kuali/ole/1.5.5/db.changelog-20141015.xml::OLE_DLVR_LOAN_NOTICE_T_INDX::ole
CREATE INDEX ODLN_LOAN_ID_INDX ON ole.OLE_DLVR_LOAN_NOTICE_T(LOAN_ID)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_LOAN_NOTICE_T_INDX', 'ole', 'org/kuali/ole/1.5.5/db.changelog-20141015.xml', NOW(), 2, '7:28c56a2ddfa54e47e654bd9fcc9b9be1', 'createIndex', '', 'EXECUTED', '3.2.0')
/

--  Changeset org/kuali/ole/1.5.5/db.changelog-20141015.xml::OLE_DS_BIB_INFO_T::ole
CREATE TABLE ole.OLE_DS_BIB_INFO_T (BIB_ID_STR VARCHAR(20) NULL, BIB_ID INT NULL, TITLE VARCHAR(4000) NULL, AUTHOR VARCHAR(4000) NULL, PUBLISHER VARCHAR(4000) NULL, ISXN VARCHAR(100) NULL)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DS_BIB_INFO_T', 'ole', 'org/kuali/ole/1.5.5/db.changelog-20141015.xml', NOW(), 3, '7:9762cdc894d4bdd3697b70cf0545cad4', 'createTable', '', 'EXECUTED', '3.2.0')
/

--  Changeset org/kuali/ole/1.5.5/db.changelog-20141015.xml::OLE_DS_BIB_INFO_T_PK::ole
ALTER TABLE ole.OLE_DS_BIB_INFO_T ADD PRIMARY KEY (BIB_ID_STR)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DS_BIB_INFO_T_PK', 'ole', 'org/kuali/ole/1.5.5/db.changelog-20141015.xml', NOW(), 4, '7:5c65f46d27fa664989af33181d450fa1', 'addPrimaryKey', '', 'EXECUTED', '3.2.0')
/

--  Changeset org/kuali/ole/1.5.5/db.changelog-20141015.xml::OLE_DS_BIB_INFO_T_INDX::ole
CREATE INDEX BIB_ID_INDX ON ole.OLE_DS_BIB_INFO_T(BIB_ID)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DS_BIB_INFO_T_INDX', 'ole', 'org/kuali/ole/1.5.5/db.changelog-20141015.xml', NOW(), 5, '7:abe38ba9f9e68c993dbb1728ac041999', 'createIndex', '', 'EXECUTED', '3.2.0')
/

--  Release Database Lock
--  Release Database Lock
