--  *********************************************************************
--  Update Database Script
--  *********************************************************************
--  Change Log: org/kuali/ole/3.0.16/db.changelog-20190305.xml
--  *********************************************************************

--  Lock Database
--  Changeset org/kuali/ole/3.0.16/db.changelog-20190305.xml::OLE_KRIM_PERM_T_mysql::ole
SET sql_mode='NO_BACKSLASH_ESCAPES'
/

INSERT INTO KRIM_PERM_T (PERM_ID, OBJ_ID, VER_NBR, PERM_TMPL_ID, NMSPC_CD, NM, DESC_TXT, ACTV_IND) VALUES ('OLELOAN1013', 'OLELOAN1013', '1', '56', 'OLE-DLVR', 'Override Renew', 'Allows users to override and Renew an Item.', 'Y')
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_KRIM_PERM_T_mysql', 'ole', 'org/kuali/ole/3.0.16/db.changelog-20190305.xml', NOW(), 1, '7:f5f74a44985d771a8827504582d99ece', 'sql, loadData', '', 'EXECUTED', '3.2.0')
/

--  Changeset org/kuali/ole/3.0.16/db.changelog-20190305.xml::OLE_DUE_DATE_HISTORY_T::ole
CREATE TABLE ole.OLE_DUE_DATE_HISTORY_T (DUE_DATE_ID VARCHAR(40) NULL, LOAN_ID VARCHAR(40) NULL, PTRN_BARCODE VARCHAR(100) NULL, ITEM_BARCODE VARCHAR(100) NULL, CURR_DUE_DT_TIME TIMESTAMP NULL, PAST_DUE_DT_TIME TIMESTAMP NULL, OPTR_ID VARCHAR(40) NULL, UPDATED_DT_TIME TIMESTAMP NULL)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DUE_DATE_HISTORY_T', 'ole', 'org/kuali/ole/3.0.16/db.changelog-20190305.xml', NOW(), 2, '7:d956eb47ece794808e92c32e76d5d89b', 'createTable', '', 'EXECUTED', '3.2.0')
/

--  Changeset org/kuali/ole/3.0.16/db.changelog-20190305.xml::OLE_DUE_DATE_HISTORY_TP1::ole
ALTER TABLE ole.OLE_DUE_DATE_HISTORY_T ADD PRIMARY KEY (DUE_DATE_ID)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DUE_DATE_HISTORY_TP1', 'ole', 'org/kuali/ole/3.0.16/db.changelog-20190305.xml', NOW(), 3, '7:69222127bd45e97e6c42a0966aa032c0', 'addPrimaryKey', '', 'EXECUTED', '3.2.0')
/

--  Changeset org/kuali/ole/3.0.16/db.changelog-20190305.xml::OLE_DUE_DATE_HISTORY_S::ole
CREATE TABLE ole.OLE_DUE_DATE_HISTORY_S (ID BIGINT(19) NULL)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DUE_DATE_HISTORY_S', 'ole', 'org/kuali/ole/3.0.16/db.changelog-20190305.xml', NOW(), 4, '7:77667c87caab84198ee97cff0582dc30', 'createTable', '', 'EXECUTED', '3.2.0')
/

--  Changeset org/kuali/ole/3.0.16/db.changelog-20190305.xml::OLE_DUE_DATE_HISTORY_S_PK::ole
ALTER TABLE ole.OLE_DUE_DATE_HISTORY_S ADD PRIMARY KEY (ID)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DUE_DATE_HISTORY_S_PK', 'ole', 'org/kuali/ole/3.0.16/db.changelog-20190305.xml', NOW(), 5, '7:2a4c0f8365563d97dfdeb1420a7e962e', 'addPrimaryKey', '', 'EXECUTED', '3.2.0')
/

--  Changeset org/kuali/ole/3.0.16/db.changelog-20190305.xml::OLE_DUE_DATE_HISTORY_S_AUTOINCREMENT::ole
ALTER TABLE ole.OLE_DUE_DATE_HISTORY_S MODIFY ID BIGINT(19) AUTO_INCREMENT
/

ALTER TABLE ole.OLE_DUE_DATE_HISTORY_S AUTO_INCREMENT=1
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DUE_DATE_HISTORY_S_AUTOINCREMENT', 'ole', 'org/kuali/ole/3.0.16/db.changelog-20190305.xml', NOW(), 6, '7:b85638b3a8a8071255ea7f628fec9708', 'addAutoIncrement', '', 'EXECUTED', '3.2.0')
/

--  Release Database Lock
--  Release Database Lock
