--
-- Copyright 2005-2014 The Kuali Foundation
--
-- Licensed under the Educational Community License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.opensource.org/licenses/ecl2.php
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

TRUNCATE TABLE PUR_OWNR_TYP_T
/
INSERT INTO PUR_OWNR_TYP_T (DOBJ_MAINT_CD_ACTV_IND,OBJ_ID,VER_NBR,VNDR_OWNR_CD,VNDR_OWNR_CTGRY_ALLW_IND,VNDR_OWNR_DESC)
  VALUES ('Y','4FF9C3BA-7A5F-41D6-5116-F5D3520F1E01',3,'CP','Y','CORPORATION')
/
INSERT INTO PUR_OWNR_TYP_T (DOBJ_MAINT_CD_ACTV_IND,OBJ_ID,VER_NBR,VNDR_OWNR_CD,VNDR_OWNR_CTGRY_ALLW_IND,VNDR_OWNR_DESC)
  VALUES ('Y','F05D0C9F-E081-3A49-0523-7695AC21F95F',3,'ET','N','ESTATE/TRUST')
/
INSERT INTO PUR_OWNR_TYP_T (DOBJ_MAINT_CD_ACTV_IND,OBJ_ID,VER_NBR,VNDR_OWNR_CD,VNDR_OWNR_CTGRY_ALLW_IND,VNDR_OWNR_DESC)
  VALUES ('Y','42BDF52E-F60A-A2A1-8F72-1D0E416BDBCF',2,'GV','N','GOVERNMENT')
/
INSERT INTO PUR_OWNR_TYP_T (DOBJ_MAINT_CD_ACTV_IND,OBJ_ID,VER_NBR,VNDR_OWNR_CD,VNDR_OWNR_CTGRY_ALLW_IND,VNDR_OWNR_DESC)
  VALUES ('Y','E0494681-68EF-C724-F2B6-8895983C411E',4,'ID','Y','INDIVIDUAL/SOLE PROPRIETOR')
/
INSERT INTO PUR_OWNR_TYP_T (DOBJ_MAINT_CD_ACTV_IND,OBJ_ID,VER_NBR,VNDR_OWNR_CD,VNDR_OWNR_CTGRY_ALLW_IND,VNDR_OWNR_DESC)
  VALUES ('Y','FE8C2761-1713-87CA-4401-C9607F2C3021',1,'NP','Y','NON-PROFIT')
/
INSERT INTO PUR_OWNR_TYP_T (DOBJ_MAINT_CD_ACTV_IND,OBJ_ID,VER_NBR,VNDR_OWNR_CD,VNDR_OWNR_CTGRY_ALLW_IND,VNDR_OWNR_DESC)
  VALUES ('Y','645C0A4E-3135-7945-8FE4-9C48961C0196',1,'PT','Y','PARTNERSHIP/LLC/LLP')
/
