package org.kuali.ole.deliver.checkout

import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ErrorMessage
import org.kuali.ole.deliver.util.NoticeInfo
import org.kuali.ole.deliver.drools.DroolsConstants


rule "Check out Circ Policy Set ASR/BUO"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument();

$n: NoticeInfo()

$p: OlePatronDocument(getBorrowerTypeCode() in ("QCOL","QGRAD","QDEPT","QNONDEG","QNONUC","QNONUC25","QSTF,","QOTHER",
"QUNLIM_ACD","QUNLIM_PHD","QUNLIM_NONUC","INDEF_FAC","INDEF_ACD","INDEF_DEPT","INDEF_NONUC","INDEF_TRU","NWU","UIC","MANB"))

$i: OleItemRecordForCirc(getItemType() in ("buo"),
getItemLibraryLocation() in ("ASR"))

then
$l.setCirculationPolicyId("Check out Circ Policy Set ASR/BUO");
$l.loanPeriod("1-D",null); // This method takes due date and recall period as arguments.
$n.setLoanType(DroolsConstants.SHORT_TERM_LOANS_NOTICE_CONFIG);
 end