package org.kuali.ole.deliver.checkout

import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ErrorMessage


rule "Check out Circ Policy Set BIND"
agenda-group "checkout validation"
activation-group "checkout validation"
when

$p: OleLoanDocument(getBorrowerTypeCode() in ("BIND"),
getItemLibrary() in ("JRL","JCL","ASR","DLL","Eck","SSAd"))

then
$p.setCirculationPolicyId("Check out Circ Policy Set BIND");
$p.loanPeriod(null,null);
 end
