package org.kuali.ole.deliver.checkout

import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ErrorMessage
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo


rule "Check out Circ Policy Set BORDIR"
agenda-group "checkout validation"
activation-group "checkout validation"
when

$l: OleLoanDocument();

$n: NoticeInfo()

$p: OlePatronDocument(getBorrowerTypeCode() in ("BORDIR"))

$i: OleItemRecordForCirc(getItemType() in ("stks","stks14","stks7"),
getItemLibraryLocation() in ("JRL","JCL","ASR","DLL","Eck","SSAd"),
getItemLocation() not in ("Resup", "ResupC","ResupD","ResupE","ResupS"))

then
$l.setCirculationPolicyId("Check out Circ Policy Set BORDIR");
$l.loanPeriod("112-D",null); // This method takes due date and recall period as arguments.
$n.setLoanType(DroolsConstants.REGULAR_LOANS_NOTICE_CONFIG);
 end