package org.kuali.ole.deliver.checkout

import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ErrorMessage
import org.kuali.ole.deliver.util.NoticeInfo


rule "Check out Circ Policy Set GBCART"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$p: OleLoanDocument(getBorrowerTypeCode() in ("GBCART"),
getItemLibrary() in ("JRL","JCL","ASR","DLL","Eck","SSAd"))

then
$p.setCirculationPolicyId("Check out Circ Policy Set GBCART");
$p.loanPeriod(null,null);
 end
