package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ErrorMessage
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "Check out Circ Policy Set STKS/Q"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("UGRAD","QGRAD","QSTF"))
$i: OleItemRecordForCirc (getItemType() in ("stks","games"),
getItemLibraryLocation() in ("JRL","JCL","ASR","DLL","Eck","SSAd"))
then
$l.setCirculationPolicyId("Check out Circ Policy Set STKS/Q");
$l.loanPeriod(OLEConstants.FIXED_DUE_DATE, "7-D");
$n.setLoanType(DroolsConstants.REGULAR_LOANS_NOTICE_CONFIG);
 end