package org.kuali.ole.deliver.checkout

import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ErrorMessage
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

 rule "Check out Circ Policy Set STKS/I"
agenda-group "checkout validation"
activation-group "checkout validation"
when

$l: OleLoanDocument()

$n: NoticeInfo()

$p: OlePatronDocument(getBorrowerTypeCode() in ("INDEF_FAC","INDEF_ACD","INDEF_DEPT"))

$i: OleItemRecordForCirc(getItemType() in ("stks","games","mus"),
getItemLibraryLocation() in ("JRL","JCL","ASR","DLL","Eck","SSAd"),
!getItemLocation().equals("Rec"))

then
$l.setCirculationPolicyId("Check out Circ Policy Set STKS/I");
$l.loanPeriod(null,"7-D"); // This method takes due date and recall period as arguments.
$n.setLoanType(DroolsConstants.REGULAR_LOANS_NOTICE_CONFIG);
 end
