package org.kuali.ole.deliver.rules.chicago.ncip
import org.kuali.ole.deliver.bo.OleDeliverRequestBo
import org.kuali.ole.deliver.bo.OleDroolsHoldResponseBo
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.util.NoticeInfo


rule "Circulation Policy Set 1 Validation for Request for recall"
agenda-group "place-request"
when
$p : OlePatronDocument(getBorrowerTypeCode() in ("UGRAD","GRAD"))
$dr: OleDeliverRequestBo(getItemType() in ("BOOK","MAGAZINE"),
getRequestTypeCode() in ("Recall/Hold Request","Recall/Delivery Request"),
    getItemLibrary() in ("B-EDUC", "JRL", "B-HPER", "B-BUSSPEA", "ASR"))

$d : DroolsResponse()
$n : NoticeInfo()
then
$d.setRuleMatched(true);
$d.getDroolsExchange().addToContext("requestExpirationDays",45);
$n.setNoticeType(OLEConstants.NOTICE_RECALL);
$d.getDroolsExchange().addToContext("minimumLoanPeriod","1-D");
$d.getDroolsExchange().addToContext("recallLoanPeriod","7-D");
end



rule "Circulation Policy Set 1 Validation for Request for hold"
agenda-group "place-request"
when
$p : OlePatronDocument(getBorrowerTypeCode() in ("UGRAD","GRAD"))
$dr: OleDeliverRequestBo(getItemType() in ("BOOK", "MAGAZINE"),
getRequestTypeCode() in ("Hold/Hold Request","Hold/Delivery Request"),
    getItemLibrary() in ("B-EDUC", "JRL", "B-HPER", "B-BUSSPEA", "ASR"))

$d : DroolsResponse()
$n : NoticeInfo()
then
$d.setRuleMatched(true);
$d.getDroolsExchange().addToContext("requestExpirationDays",45);
end



rule "Circulation Policy Set 1 Validation for Request for page"
agenda-group "place-request"
activation-group "place-request"
when
$p : OlePatronDocument(getBorrowerTypeCode() in ("UGRAD","GRAD"))
$dr: OleDeliverRequestBo(getItemType() in ("BOOK","MAGAZINE"),
getRequestTypeCode() in ("Page/Hold Request","Page/Delivery Request"),
    getItemLibrary() in ("B-EDUC", "JRL", "B-HPER", "B-BUSSPEA", "ASR"))


$d : DroolsResponse()
$n : NoticeInfo()
then
$d.setRuleMatched(true);
$d.getDroolsExchange().addToContext("requestExpirationDays",45);
end

rule "Circulation Policy Set 1 Validation for Request for copy"
agenda-group "place-request"
when
$p : OlePatronDocument(getBorrowerTypeCode() in ("UGRAD","GRAD"))
$dr: OleDeliverRequestBo(getItemType() in ("BOOK","MAGAZINE"),
getRequestTypeCode() in ("Page/Hold Request","Page/Delivery Request"),
    getItemLibrary() in ("B-EDUC", "JRL", "B-HPER", "B-BUSSPEA", "ASR"))


$d : DroolsResponse()
$n : NoticeInfo()
then
$d.setRuleMatched(true);
$d.getDroolsExchange().addToContext("requestExpirationDays",45);
end

rule "Circulation Policy Set 1 Validation for Request for ASR"
agenda-group "place-request"
activation-group "place-request"
when

$dr:OleDeliverRequestBo(getRequestTypeCode() in ("ASR Request"),
    getItemLibrary() in ("ASR"))

$d : DroolsResponse()
$n : NoticeInfo()
then
$d.setRuleMatched(true);
$d.getDroolsExchange().addToContext("requestExpirationDays",45);
end


