package org.kuali.ole.deliver.rules.chicago.ncip
import org.kuali.ole.deliver.bo.OleDeliverRequestBo
import org.kuali.ole.deliver.bo.OleDroolsHoldResponseBo
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.util.NoticeInfo


rule "Circulation Policy Set 1 Validation for Request for recall count less than 3"
agenda-group "place-request"
when
$p : OlePatronDocument(getBorrowerTypeCode() in ("UGRAD","GRAD"))
$dr: OleDeliverRequestBo(getItemType() in ("BOOK","MAGAZINE"),
getRequestTypeCode() in ("Recall/Hold Request","Recall/Delivery Request"),getRecallRequestCount() < 3,
    getItemLibrary() in ("B-EDUC", "JRL", "B-HPER", "B-BUSSPEA", "ASR"))

$d : DroolsResponse()
$n : NoticeInfo()
then
$d.setRuleMatched(true);
$n.setNoticeType(OLEConstants.NOTICE_RECALL);
$d.getDroolsExchange().addToContext("requestExpirationDays",10);
$d.getDroolsExchange().addToContext("minimumLoanPeriod","1-H");
$d.getDroolsExchange().addToContext("recallLoanPeriod","3-D");
end

rule "Circulation Policy Set 1 Validation for Request for recall count greater than 3"
agenda-group "place-request"
when
$p : OlePatronDocument(getBorrowerTypeCode() in ("UGRAD","GRAD"))
$dr: OleDeliverRequestBo(getItemType() in ("BOOK", "MAGAZINE"),
getRequestTypeCode() in ("Recall/Hold Request","Recall/Delivery Request"),getRecallRequestCount() >= 3,
    getItemLibrary() in ("B-EDUC", "JRL", "B-HPER", "B-BUSSPEA", "ASR"))

$d : DroolsResponse()
$n : NoticeInfo()
then
$d.addErrorMessage("Recall Requests exceeds the maximum (2).");
$d.addOverridePermissions(OLEConstants.GENERAL_BLOCK);
end



rule "Circulation Policy Set 1 Validation for Request for hold count less than 3"
agenda-group "place-request"
when
$p : OlePatronDocument(getBorrowerTypeCode() in ("UGRAD","GRAD"))
$dr: OleDeliverRequestBo(getItemType() in ("BOOK", "MAGAZINE"),
getRequestTypeCode() in ("Hold/Hold Request","Hold/Delivery Request"),getHoldRequestCount() < 3,
    getItemLibrary() in ("B-EDUC", "JRL", "B-HPER", "B-BUSSPEA", "ASR"))

$d : DroolsResponse()
$n : NoticeInfo()
then
$d.setRuleMatched(true);
$d.getDroolsExchange().addToContext("requestExpirationDays",10);
end

rule "Circulation Policy Set 1 Validation for Request for hold count greater than 3"
agenda-group "place-request"
when
$p : OlePatronDocument(getBorrowerTypeCode() in ("UGRAD","GRAD"))
$dr: OleDeliverRequestBo(getItemType() in ("BOOK","MAGAZINE"),
getRequestTypeCode() in ("Hold/Hold Request","Hold/Delivery Request"),getHoldRequestCount() >= 3,
    getItemLibrary() in ("B-EDUC", "JRL", "B-HPER", "B-BUSSPEA", "ASR"))

$d : DroolsResponse()
$n : NoticeInfo()
then
$d.addErrorMessage("Hold Requests exceeds the maximum (2).");
$d.addOverridePermissions(OLEConstants.GENERAL_BLOCK);
end





rule "Circulation Policy Set 1 Validation for Request for page count less than 3"
agenda-group "place-request"
when
$p : OlePatronDocument(getBorrowerTypeCode() in ("UGRAD","GRAD"))
$dr: OleDeliverRequestBo(getItemType() in ("BOOK","MAGAZINE"),
getRequestTypeCode() in ("Page/Hold Request","Page/Delivery Request"),getPageRequestCount() < 3,
    getItemLibrary() in ("B-EDUC", "JRL", "B-HPER", "B-BUSSPEA", "ASR"))

$d : DroolsResponse()
$n : NoticeInfo()
then
$d.setRuleMatched(true);
$d.getDroolsExchange().addToContext("requestExpirationDays",10);
end

rule "Circulation Policy Set 1 Validation for Request for page count greater than 3"
agenda-group "place-request"
when
$p : OlePatronDocument(getBorrowerTypeCode() in ("UGRAD","GRAD"))
$dr: OleDeliverRequestBo(getItemType() in ("BOOK","MAGAZINE"),
getRequestTypeCode() in ("Page/Hold Request","Page/Delivery Request"),getPageRequestCount() >= 3,
    getItemLibrary() in ("B-EDUC", "JRL", "B-HPER", "B-BUSSPEA", "ASR"))

$d : DroolsResponse()
$n : NoticeInfo()
then
$d.addErrorMessage("Page Requests exceeds the maximum (2).");
$d.addOverridePermissions(OLEConstants.GENERAL_BLOCK);
end

rule "Circulation Policy Set 1 Validation for Request for copy count less than 3"
agenda-group "place-request"
when
$p : OlePatronDocument(getBorrowerTypeCode() in ("UGRAD","GRAD"))
$dr: OleDeliverRequestBo(getItemType() in ("BOOK","MAGAZINE"),
getRequestTypeCode() in ("Copy Request"),getCopyRequestCount() < 3,
    getItemLibrary() in ("B-EDUC", "JRL", "B-HPER", "B-BUSSPEA", "ASR"))

$d : DroolsResponse()
$n : NoticeInfo()
then
$d.setRuleMatched(true);
$d.getDroolsExchange().addToContext("requestExpirationDays",10);
end

rule "Circulation Policy Set 1 Validation for Request for copy count greater than 3"
agenda-group "place-request"
when
$p : OlePatronDocument(getBorrowerTypeCode() in ("UGRAD","GRAD"))
$dr: OleDeliverRequestBo(getItemType() in ("BOOK","MAGAZINE"),
getRequestTypeCode() in ("Copy Request"),getCopyRequestCount() >= 3,
    getItemLibrary() in ("B-EDUC", "JRL", "B-HPER", "B-BUSSPEA", "ASR"))

$d : DroolsResponse()
$n : NoticeInfo()
then
$d.addErrorMessage("Copy Requests exceeds the maximum (2).");
$d.addOverridePermissions(OLEConstants.GENERAL_BLOCK);
end


rule "Circulation Policy Set 1 Validation for Request for ASR count less than 3"
agenda-group "place-request"
when
$p : OlePatronDocument(getBorrowerTypeCode() in ("UGRAD","GRAD"))
$dr: OleDeliverRequestBo(getItemType() in ("BOOK", "stks", "MAGAZINE","res2"),
getRequestTypeCode() in ("ASR Request"),getAsrRequestCount() < 3,
    getItemLibrary() in ("ASR"))

$d : DroolsResponse()
$n : NoticeInfo()
then
$d.setRuleMatched(true);
$d.getDroolsExchange().addToContext("requestExpirationDays",10);
end

rule "Circulation Policy Set 1 Validation for Request for ASR count greater than 3"
agenda-group "place-request"
when
$p : OlePatronDocument(getBorrowerTypeCode() in ("UGRAD","GRAD"))
$dr: OleDeliverRequestBo(getItemType() in ("BOOK", "stks", "MAGAZINE","res2"),
getRequestTypeCode() in ("ASR Request"),getAsrRequestCount() >= 3,
    getItemLibrary() in ("ASR"))
$d : DroolsResponse()
$n : NoticeInfo()
then
$d.addErrorMessage("ASR Requests exceeds the maximum (2).");
$d.addOverridePermissions(OLEConstants.GENERAL_BLOCK);
end
