TRUNCATE TABLE KREW_RULE_TMPL_OPTN_T
/
INSERT INTO KREW_RULE_TMPL_OPTN_T (KEY_CD,RULE_TMPL_ID,RULE_TMPL_OPTN_ID,VAL,VER_NBR)
  VALUES ('D','1016','2000','K',1)
/
INSERT INTO KREW_RULE_TMPL_OPTN_T (KEY_CD,RULE_TMPL_ID,RULE_TMPL_OPTN_ID,VAL,VER_NBR)
  VALUES ('A','1016','2001','true',1)
/
INSERT INTO KREW_RULE_TMPL_OPTN_T (KEY_CD,RULE_TMPL_ID,RULE_TMPL_OPTN_ID,VAL,VER_NBR)
  VALUES ('K','1016','2002','true',1)
/
INSERT INTO KREW_RULE_TMPL_OPTN_T (KEY_CD,RULE_TMPL_ID,RULE_TMPL_OPTN_ID,VAL,VER_NBR)
  VALUES ('F','1016','2003','true',1)
/
INSERT INTO KREW_RULE_TMPL_OPTN_T (KEY_CD,RULE_TMPL_ID,RULE_TMPL_OPTN_ID,VAL,VER_NBR)
  VALUES ('C','1016','2004','true',1)
/
INSERT INTO KREW_RULE_TMPL_OPTN_T (KEY_CD,RULE_TMPL_ID,RULE_TMPL_OPTN_ID,VAL,VER_NBR)
  VALUES ('I','1016','2005','some instructions',1)
/
