-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: bootstrap_other_data.xml
-- *********************************************************************

-- Lock Database
-- Changeset bootstrap_other_data.xml::ALTER_SESSIONS_FOR_ORACLE_ONLY::ole
ALTER SESSION SET NLS_DATE_FORMAT = 'RRMMDDHH24MISS'
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('ALTER_SESSIONS_FOR_ORACLE_ONLY', 'ole', 'bootstrap_other_data.xml', SYSTIMESTAMP, 1, '7:2dfaea691acb2a83438e5bdd35f24058', 'sql', '', 'EXECUTED', '3.2.0')
/

-- Changeset bootstrap_other_data.xml::KREW_PPL_FLW_T::ole
INSERT INTO KREW_PPL_FLW_T (PPL_FLW_ID, NM, NMSPC_CD, TYP_ID, ACTV, VER_NBR, DESC_TXT) VALUES ('OLE10000', 'Full Approval', 'OLE-LIC', NULL, 'Y', '1', 'Full Approval People Flow for  License')
/

INSERT INTO KREW_PPL_FLW_T (PPL_FLW_ID, NM, NMSPC_CD, TYP_ID, ACTV, VER_NBR, DESC_TXT) VALUES ('OLE10001', 'Signatory Only', 'OLE-LIC', NULL, 'Y', '1', 'Signatory People Flow for  License')
/

INSERT INTO KREW_PPL_FLW_T (PPL_FLW_ID, NM, NMSPC_CD, TYP_ID, ACTV, VER_NBR, DESC_TXT) VALUES ('OLE10002', 'Review Only', 'OLE-LIC', NULL, 'Y', '1', 'Review People Flow for License')
/

INSERT INTO KREW_PPL_FLW_T (PPL_FLW_ID, NM, NMSPC_CD, TYP_ID, ACTV, VER_NBR, DESC_TXT) VALUES ('OLE10003', 'Approval Only', 'OLE-LIC', NULL, 'Y', '1', 'Approval People Flow for License')
/

INSERT INTO KREW_PPL_FLW_T (PPL_FLW_ID, NM, NMSPC_CD, TYP_ID, ACTV, VER_NBR, DESC_TXT) VALUES ('OLE10004', 'Renewal', 'OLE-LIC', NULL, 'Y', '1', 'Renewal People Flow for License')
/

INSERT INTO KREW_PPL_FLW_T (PPL_FLW_ID, NM, NMSPC_CD, TYP_ID, ACTV, VER_NBR, DESC_TXT) VALUES ('OLE10005', 'Addendum', 'OLE-LIC', NULL, 'Y', '1', 'Addendum People Flow for License')
/

INSERT INTO KREW_PPL_FLW_T (PPL_FLW_ID, NM, NMSPC_CD, TYP_ID, ACTV, VER_NBR, DESC_TXT) VALUES ('OLE10006', 'Request Approval', 'OLE', NULL, 'Y', '1', 'Request Approval People Flow')
/

INSERT INTO KREW_PPL_FLW_T (PPL_FLW_ID, NM, NMSPC_CD, TYP_ID, ACTV, VER_NBR, DESC_TXT) VALUES ('OLE10007', 'Acquisition Approval', 'OLE', NULL, 'Y', '1', 'Acquisition Approval for EResource')
/

INSERT INTO KREW_PPL_FLW_T (PPL_FLW_ID, NM, NMSPC_CD, TYP_ID, ACTV, VER_NBR, DESC_TXT) VALUES ('OLE10008', 'Cataloger Approval', 'OLE', NULL, 'Y', '1', 'Cataloger Approval for EResource')
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('KREW_PPL_FLW_T', 'ole', 'bootstrap_other_data.xml', SYSTIMESTAMP, 2, '7:3faf3ae7a57519400050c0a93f83c684', 'loadData', '', 'EXECUTED', '3.2.0')
/

-- Changeset bootstrap_other_data.xml::OLE_E_RES_STAT_T::ole
INSERT INTO OLE_E_RES_STAT_T (E_RES_STAT_ID, E_RES_STAT_NM, E_RES_STAT_DESC, OBJ_ID, VER_NBR, ROW_ACT_IND) VALUES ('1', 'In-Process', 'Status of E-Res Record', 'OLEERS119', '1', 'Y')
/

INSERT INTO OLE_E_RES_STAT_T (E_RES_STAT_ID, E_RES_STAT_NM, E_RES_STAT_DESC, OBJ_ID, VER_NBR, ROW_ACT_IND) VALUES ('2', 'Trial', 'Status of E-Res Record', 'OLEERS120', '1', 'Y')
/

INSERT INTO OLE_E_RES_STAT_T (E_RES_STAT_ID, E_RES_STAT_NM, E_RES_STAT_DESC, OBJ_ID, VER_NBR, ROW_ACT_IND) VALUES ('3', 'Ordered', 'Status of E-Res Record', 'OLEERS121', '1', 'Y')
/

INSERT INTO OLE_E_RES_STAT_T (E_RES_STAT_ID, E_RES_STAT_NM, E_RES_STAT_DESC, OBJ_ID, VER_NBR, ROW_ACT_IND) VALUES ('4', 'Invoiced', 'Status of E-Res Record', 'OLEERS122', '1', 'Y')
/

INSERT INTO OLE_E_RES_STAT_T (E_RES_STAT_ID, E_RES_STAT_NM, E_RES_STAT_DESC, OBJ_ID, VER_NBR, ROW_ACT_IND) VALUES ('5', 'Active', 'Status of E-Res Record', 'OLEERS123', '1', 'Y')
/

INSERT INTO OLE_E_RES_STAT_T (E_RES_STAT_ID, E_RES_STAT_NM, E_RES_STAT_DESC, OBJ_ID, VER_NBR, ROW_ACT_IND) VALUES ('6', 'Canceled', 'Status of E-Res Record', 'OLEERS124', '1', 'Y')
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_E_RES_STAT_T', 'ole', 'bootstrap_other_data.xml', SYSTIMESTAMP, 3, '7:1cc33008043896ed508627d10964096d', 'loadData', '', 'EXECUTED', '3.2.0')
/

-- Changeset bootstrap_other_data.xml::FS_OPTION_T::ole
INSERT INTO FS_OPTION_T (UNIV_FISCAL_YR, OBJ_ID, VER_NBR, ACT_FIN_BAL_TYP_CD, BDGT_CHK_BALTYP_CD, BDGT_CHK_OPTN_CD, UNIV_FSCYR_STRT_YR, UNIV_FSCYR_STRT_MO, FOBJTP_INC_CSH_CD, FOBJTP_XPND_EXP_CD, FOBJTP_XPNDNEXP_CD, FOBJTP_EXPNXPND_CD, FOBJ_TYP_ASSET_CD, FOBJ_TYP_LBLTY_CD, FOBJ_TYP_FNDBAL_CD, EXT_ENC_FBALTYP_CD, INT_ENC_FBALTYP_CD, PRE_ENC_FBALTYP_CD, ELIM_FINBAL_TYP_CD, FOBJTP_INC_NCSH_CD, FOBJTP_CSH_NINC_CD, UNIV_FIN_COA_CD, UNIV_FISCAL_YR_NM, FIN_BEGBALLOAD_IND, CSTSHR_ENCUM_FIN_BAL_TYP_CD, BASE_BDGT_FIN_BAL_TYP_CD, MO_BDGT_FIN_BAL_TYP_CD, FIN_OBJECT_TYP_TRNFR_INC_CD, FIN_OBJECT_TYP_TRNFR_EXP_CD, NMNL_FIN_BAL_TYP_CD) VALUES ('2012', '8d98ae-d6bc-4443-8e9b-66cca04c8aa2', '2', 'AC', 'CB', 'Y', '2011', '07', 'IN', 'EX', 'EE', 'ES', 'AS', 'LI', 'FB', 'EX', 'IE', 'PE', 'TR', 'IC', 'CH', '01', '2011-2012', 'N', 'CE', 'BB', 'MB', 'TI', 'TE', 'NB')
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('FS_OPTION_T', 'ole', 'bootstrap_other_data.xml', SYSTIMESTAMP, 4, '7:26468aa0a4a7aae7ca255480a0c98bd7', 'loadData', '', 'EXECUTED', '3.2.0')
/

-- Changeset bootstrap_other_data.xml::FP_FSCL_YR_CTRL_T::ole
INSERT INTO FP_FSCL_YR_CTRL_T (UNIV_FISCAL_YR, FS_FUNC_CTRL_CD, OBJ_ID, VER_NBR, FS_FUNC_ACTIVE_IND) VALUES ('2012', 'BAACTV', 'b5eabbf0-409b-45a6-ac10-90e44da193c', '1', 'Y')
/

INSERT INTO FP_FSCL_YR_CTRL_T (UNIV_FISCAL_YR, FS_FUNC_CTRL_CD, OBJ_ID, VER_NBR, FS_FUNC_ACTIVE_IND) VALUES ('2012', 'BASEAD', 'b66990e6-e580-4630-96d2-9d7ca0a0d96', '1', 'Y')
/

INSERT INTO FP_FSCL_YR_CTRL_T (UNIV_FISCAL_YR, FS_FUNC_CTRL_CD, OBJ_ID, VER_NBR, FS_FUNC_ACTIVE_IND) VALUES ('2012', 'BCACTV', 'fb6b743d-dc23-4a2a-a7a8-f6c75c85bc8', '1', 'Y')
/

INSERT INTO FP_FSCL_YR_CTRL_T (UNIV_FISCAL_YR, FS_FUNC_CTRL_CD, OBJ_ID, VER_NBR, FS_FUNC_ACTIVE_IND) VALUES ('2012', 'BCGENE', 'f86a0e21-8666-48f8-a146-94935b0279d', '1', 'N')
/

INSERT INTO FP_FSCL_YR_CTRL_T (UNIV_FISCAL_YR, FS_FUNC_CTRL_CD, OBJ_ID, VER_NBR, FS_FUNC_ACTIVE_IND) VALUES ('2012', 'BCUPDT', 'de154131-455d-4abd-8160-36085ec5a05', '1', 'Y')
/

INSERT INTO FP_FSCL_YR_CTRL_T (UNIV_FISCAL_YR, FS_FUNC_CTRL_CD, OBJ_ID, VER_NBR, FS_FUNC_ACTIVE_IND) VALUES ('2012', 'BSSYNC', '2863e8e7-4af4-4a2b-9a62-d6f119084ae', '1', 'Y')
/

INSERT INTO FP_FSCL_YR_CTRL_T (UNIV_FISCAL_YR, FS_FUNC_CTRL_CD, OBJ_ID, VER_NBR, FS_FUNC_ACTIVE_IND) VALUES ('2012', 'CSFUPD', '57e0b46f-fbc6-4e4e-ae6b-469d9adf6b6', '1', 'Y')
/

INSERT INTO FP_FSCL_YR_CTRL_T (UNIV_FISCAL_YR, FS_FUNC_CTRL_CD, OBJ_ID, VER_NBR, FS_FUNC_ACTIVE_IND) VALUES ('2012', 'PSSYNC', '751a5ef8-cf76-49d8-85ed-691b6b68551', '1', 'Y')
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('FP_FSCL_YR_CTRL_T', 'ole', 'bootstrap_other_data.xml', SYSTIMESTAMP, 5, '7:1197dc0b30124babdf61989776de1aef', 'loadData', '', 'EXECUTED', '3.2.0')
/

-- Changeset bootstrap_other_data.xml::FP_FUNC_CTRL_CD_T::ole
INSERT INTO FP_FUNC_CTRL_CD_T (FS_FUNC_CTRL_CD, OBJ_ID, VER_NBR, FS_FUNC_DFLT_IND, FS_FUNC_DESC) VALUES ('BAACTV', '1362A7CFD659B972E043814FD881B972', '1', 'N', 'Budget Adjustements Allowed')
/

INSERT INTO FP_FUNC_CTRL_CD_T (FS_FUNC_CTRL_CD, OBJ_ID, VER_NBR, FS_FUNC_DFLT_IND, FS_FUNC_DESC) VALUES ('BASEAD', '1362A7CFD65AB972E043814FD881B972', '1', 'N', 'Base Adjustments Allowed')
/

INSERT INTO FP_FUNC_CTRL_CD_T (FS_FUNC_CTRL_CD, OBJ_ID, VER_NBR, FS_FUNC_DFLT_IND, FS_FUNC_DESC) VALUES ('BCACTV', '1362A7CFD65BB972E043814FD881B972', '1', 'N', 'Budget Construction Active')
/

INSERT INTO FP_FUNC_CTRL_CD_T (FS_FUNC_CTRL_CD, OBJ_ID, VER_NBR, FS_FUNC_DFLT_IND, FS_FUNC_DESC) VALUES ('BCGENE', '1362A7CFD65CB972E043814FD881B972', '1', 'N', 'Budget Construction Genesis Executing')
/

INSERT INTO FP_FUNC_CTRL_CD_T (FS_FUNC_CTRL_CD, OBJ_ID, VER_NBR, FS_FUNC_DFLT_IND, FS_FUNC_DESC) VALUES ('BCUPDT', '1362A7CFD65EB972E043814FD881B972', '1', 'N', 'Budget Construction Updates Allowed')
/

INSERT INTO FP_FUNC_CTRL_CD_T (FS_FUNC_CTRL_CD, OBJ_ID, VER_NBR, FS_FUNC_DFLT_IND, FS_FUNC_DESC) VALUES ('BSSYNC', '1362A7CFD65DB972E043814FD881B972', '1', 'N', 'Batch Sync BC with PeopleSoft')
/

INSERT INTO FP_FUNC_CTRL_CD_T (FS_FUNC_CTRL_CD, OBJ_ID, VER_NBR, FS_FUNC_DFLT_IND, FS_FUNC_DESC) VALUES ('CSFUPD', '1362A7CFD65FB972E043814FD881B972', '1', 'N', 'Calculated Salary Found Updates Allowed')
/

INSERT INTO FP_FUNC_CTRL_CD_T (FS_FUNC_CTRL_CD, OBJ_ID, VER_NBR, FS_FUNC_DFLT_IND, FS_FUNC_DESC) VALUES ('PSSYNC', '1362A7CFD660B972E043814FD881B972', '1', 'N', 'Synchronize BC with PeopleSoft')
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('FP_FUNC_CTRL_CD_T', 'ole', 'bootstrap_other_data.xml', SYSTIMESTAMP, 6, '7:6145e4afe32490ed2da78282026a92ce', 'loadData', '', 'EXECUTED', '3.2.0')
/

-- Changeset bootstrap_other_data.xml::SH_ACCT_PERIOD_T::ole
INSERT INTO SH_ACCT_PERIOD_T (UNIV_FISCAL_YR, UNIV_FISCAL_PRD_CD, OBJ_ID, VER_NBR, UNIV_FISCAL_PRD_NM, ROW_ACTV_IND, BDGT_ROLLOVER_CD, UNIV_FSCPD_END_DT) VALUES ('2012', '01', '788d325b-ec82-40b1-87a4-463c8bb7ea3', '2', 'JULY 2011', 'Y', 'N', '110731000000')
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('SH_ACCT_PERIOD_T', 'ole', 'bootstrap_other_data.xml', SYSTIMESTAMP, 7, '7:b1c38c986218a3433ed2d604378405f8', 'loadData', '', 'EXECUTED', '3.2.0')
/

-- Release Database Lock
-- Release Database Lock
