package org.kuali.ole.deliver.rules.demo.general.sip_two

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.DroolsResponse
import java.util.Date
import org.kuali.ole.deliver.drools.DroolsConstants


rule "Is Patron with General Block For sip2"
agenda-group "lookup-user-sip2"
when
$p : OlePatronDocument(isGeneralBlock())
$d : DroolsResponse()
then
$d.addErrorMessage("Patron is blocked");
end

rule "Is Patron Expired For sip2"
agenda-group "lookup-user-sip2"
when
$p : OlePatronDocument(getExpirationDate() != null, $e: getExpirationDate(), $e < today())
$d : DroolsResponse()
then
$d.addErrorMessage("Patron has expired");
end

rule "Is Patron Active For sip2"
agenda-group "lookup-user-sip2"
when
$p : OlePatronDocument(!isActiveIndicator())
$d : DroolsResponse()
then
$d.addErrorMessage("Patron is Inactive");
end

rule "Activation Date for Patron For sip2"
agenda-group "lookup-user-sip2"
when
$p : OlePatronDocument(getActivationDate()!= null, $e: getActivationDate(), $e >= today())
$d : DroolsResponse()
then
$d.addErrorMessage("Patron has an invalid activation date");
end

rule "Check All Charges For sip2"
agenda-group "lookup-user-sip2"
when
$p: OlePatronDocument(getAllCharges() > 149 )
$d: DroolsResponse()
then
$d.addErrorMessage("Patron's overall charges greater than $149");
end

rule "Check Overdue fine For sip2"
agenda-group "lookup-user-sip2"
when
$p: OlePatronDocument(getOverdueFineAmount() > 49 )
$d: DroolsResponse()
then
$d.addErrorMessage("Patron has overdue fines greater than $49");
end

rule "Check Replacement fine For sip2"
agenda-group "lookup-user-sip2"
when
$p: OlePatronDocument(getReplacementFineAmount() > 49 )
$d: DroolsResponse()
then
$d.addErrorMessage("Patron has replacement fees greater than $49");
end

function Date today(){
    Date date = new Date(System.currentTimeMillis());
    return date;
}


