package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.util.NoticeInfo
import org.kuali.ole.docstore.engine.service.storage.rdbms.pojo.ItemRecord
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.drools.DroolsConstants;


rule "Courtsey Notice Policy Set STKS/Q"
agenda-group "notice generation"
when
$n: NoticeInfo(getLoanType() == DroolsConstants.SHORT_TERM_LOANS_NOTICE_CONFIG)
$i: ItemRecord(getDueDateTime()!= null)
then
$n.addInfo(OLEConstants.COURTESY_NOTICE, DroolsConstants.INTERVAL_TO_GENERATE_NOTICE_FOR_COURTSEY, "1");
 end


rule "Overdue Notice Policy Set STKS/Q"
agenda-group "notice generation"
when
$n: NoticeInfo(getLoanType() == DroolsConstants.SHORT_TERM_LOANS_NOTICE_CONFIG)
$i: ItemRecord(getDueDateTime()!= null, !getClaimsReturnedFlag())
then
$n.addInfo(OLEConstants.OVERDUE_NOTICE, DroolsConstants.NUMBER_OF_OVERDUE_NOTICES_TO_BE_SENT, "6");
$n.addInfo(OLEConstants.OVERDUE_NOTICE, DroolsConstants.INTERVAL_TO_GENERATE_NOTICE_FOR_OVERDUE, "2");
$n.addInfo(OLEConstants.OVERDUE_NOTICE, DroolsConstants.REPLACEMENT_BILL_AMT, "150");
 end