package org.kuali.ole.deliver.rules.demo.fines

import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ItemFineRate
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.bo.PatronBillPayment



rule "Items Daily fines "
agenda-group "fine validation"
activation-group "fine validation"
when

$f: ItemFineRate()

$i: OleItemRecordForCirc(getItemType() in ("BOOK"),
getItemLibraryLocation() in ("B-EDUC"))

$p: OlePatronDocument(getBorrowerTypeCode() in ("UGRAD"))

then
$f.setFineRate(5.00);
$f.setMaxFine(120.00);
$f.setInterval("D"); //Options are H-Hours; D-Days

end

