package org.kuali.ole.deliver.rules.demo.notices

import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.util.NoticeInfo
import org.kuali.ole.docstore.engine.service.storage.rdbms.pojo.ItemRecord
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.drools.DroolsConstants;


  rule "Courtesy Notice Policy For Place Request"
  agenda-group "notice generation"
  activation-group "notice generation"
  when
  $n: NoticeInfo(getNoticeType() == OLEConstants.NOTICE_RECALL)
  $i: ItemRecord(getDueDateTime()!= null)
  then
  $n.addInfo(OLEConstants.RECALL_COURTESY_NOTICE, DroolsConstants.INTERVAL_TO_GENERATE_NOTICE_FOR_COURTESY, "3");
  $n.addInfo(OLEConstants.RECALL_COURTESY_NOTICE, OLEConstants.COURTESY_NOTICE_CONTENT_CONFIG_NAME,"Courtesy Notice");
   $n.addInfo(OLEConstants.RECALL_OVERDUE_NOTICE, DroolsConstants.NUMBER_OF_OVERDUE_NOTICES_TO_BE_SENT, "6");
   $n.addInfo(OLEConstants.RECALL_OVERDUE_NOTICE, DroolsConstants.INTERVAL_TO_GENERATE_NOTICE_FOR_OVERDUE, "1,2,3,4,5,6,7");
   $n.addInfo(OLEConstants.RECALL_OVERDUE_NOTICE, OLEConstants.OVERDUE_NOTICE_CONTENT_CONFIG_NAME,"Recall Overdue Notice");
   $n.addInfo(OLEConstants.RECALL_LOST_NOTICE, DroolsConstants.REPLACEMENT_BILL_AMT, "150");
   $n.addInfo(OLEConstants.RECALL_LOST_NOTICE, OLEConstants.LOST_NOTICE_CONTENT_CONFIG_NAME,"Lost Notice");
   $n.setIntervalType("D");
   end



