
package org.kuali.ole.select.testing;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 */
@WebService(name = "preOrderService", targetNamespace = "http://service.select.ole.kuali.org/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface PreOrderService {


    /**
     * @param title
     * @param author
     * @param edition
     * @param series
     * @param publisher
     * @param placeOfPublication
     * @param yearOfPublication
     * @param standardNumber
     * @param typeOfStandardNumber
     * @param routeRequestorReceipt
     * @param requestorsNote
     * @param requestorsFirstName
     * @param requestorsLastName
     * @param requestorsAddress1
     * @param requestorsAddress2
     * @param requestorsCity
     * @param requestorsState
     * @param requestorsZipCode
     * @param requestorsCountryCode
     * @param requestorsPhone
     * @param requestorsEmail
     * @param requestorsSMS
     * @param requestorType
     * @return returns java.lang.String
     * @throws WSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://service.select.ole.kuali.org/")
    @RequestWrapper(localName = "createPreOrderForForm", targetNamespace = "http://service.select.ole.kuali.org/", className = "org.kuali.ole.select.testing.CreatePreOrderForForm")
    @ResponseWrapper(localName = "createPreOrderForFormResponse", targetNamespace = "http://service.select.ole.kuali.org/", className = "org.kuali.ole.select.testing.CreatePreOrderForFormResponse")


    public String createPreOrderForForm(
            @WebParam(name = "title", targetNamespace = "http://service.select.ole.kuali.org/")
            String title,
            @WebParam(name = "author", targetNamespace = "http://service.select.ole.kuali.org/")
            String author,
            @WebParam(name = "edition", targetNamespace = "http://service.select.ole.kuali.org/")
            String edition,
            @WebParam(name = "series", targetNamespace = "http://service.select.ole.kuali.org/")
            String series,
            @WebParam(name = "publisher", targetNamespace = "http://service.select.ole.kuali.org/")
            String publisher,
            @WebParam(name = "placeOfPublication", targetNamespace = "http://service.select.ole.kuali.org/")
            String placeOfPublication,
            @WebParam(name = "yearOfPublication", targetNamespace = "http://service.select.ole.kuali.org/")
            String yearOfPublication,
            @WebParam(name = "standardNumber", targetNamespace = "http://service.select.ole.kuali.org/")
            String standardNumber,
            @WebParam(name = "typeOfStandardNumber", targetNamespace = "http://service.select.ole.kuali.org/")
            String typeOfStandardNumber,
            /*
             * @WebParam(name = "routeRequestorReceipt", targetNamespace = "http://service.select.ole.kuali.org/") String
             * routeRequestorReceipt,
             */
            @WebParam(name = "requestorsNote", targetNamespace = "http://service.select.ole.kuali.org/")
            String requestorsNote,
            /*
             * @WebParam(name = "requestorsFirstName", targetNamespace = "http://service.select.ole.kuali.org/") String
             * requestorsFirstName,
             * @WebParam(name = "requestorsLastName", targetNamespace = "http://service.select.ole.kuali.org/") String
             * requestorsLastName,
             * @WebParam(name = "requestorsAddress1", targetNamespace = "http://service.select.ole.kuali.org/") String
             * requestorsAddress1,
             * @WebParam(name = "requestorsAddress2", targetNamespace = "http://service.select.ole.kuali.org/") String
             * requestorsAddress2,
             * @WebParam(name = "requestorsCity", targetNamespace = "http://service.select.ole.kuali.org/") String requestorsCity,
             * @WebParam(name = "requestorsState", targetNamespace = "http://service.select.ole.kuali.org/") String requestorsState,
             * @WebParam(name = "requestorsZipCode", targetNamespace = "http://service.select.ole.kuali.org/") String
             * requestorsZipCode,
             * @WebParam(name = "requestorsCountryCode", targetNamespace = "http://service.select.ole.kuali.org/") String
             * requestorsCountryCode,
             * @WebParam(name = "requestorsPhone", targetNamespace = "http://service.select.ole.kuali.org/") String requestorsPhone,
             * @WebParam(name = "requestorsEmail", targetNamespace = "http://service.select.ole.kuali.org/") String requestorsEmail,
             * @WebParam(name = "requestorsSMS", targetNamespace = "http://service.select.ole.kuali.org/") String requestorsSMS,
             */
            @WebParam(name = "requestorType", targetNamespace = "http://service.select.ole.kuali.org/")
            String requestorType,
            @WebParam(name = "requestorId", targetNamespace = "http://service.select.ole.kuali.org/") String requestorId)
            throws WSException_Exception
    ;

    /**
     * @param openUrlString
     * @param routeRequestorReceipt
     * @param requestorsNote
     * @param requestorsFirstName
     * @param requestorsLastName
     * @param requestorsAddress1
     * @param requestorsAddress2
     * @param requestorsCity
     * @param requestorsState
     * @param requestorsZipCode
     * @param requestorsCountryCode
     * @param requestorsPhone
     * @param requestorsEmail
     * @param requestorsSMS
     * @param requestorType
     * @return returns java.lang.String
     * @throws WSException_Exception
     */


    @WebMethod
    @WebResult(targetNamespace = "http://service.select.ole.kuali.org/")
    @RequestWrapper(localName = "createPreOrderForOpenURL", targetNamespace = "http://service.select.ole.kuali.org/", className = "org.kuali.ole.select.testing.CreatePreOrderForOpenURL")
    @ResponseWrapper(localName = "createPreOrderForOpenURLResponse", targetNamespace = "http://service.select.ole.kuali.org/", className = "org.kuali.ole.select.testing.CreatePreOrderForOpenURLResponse")
    public String createPreOrderForOpenURL(
            @WebParam(name = "openUrlString", targetNamespace = "http://service.select.ole.kuali.org/")
            String arg0,
            @WebParam(name = "routeRequestorReceipt", targetNamespace = "http://service.select.ole.kuali.org/")
            String arg1,
            @WebParam(name = "requestorsNote", targetNamespace = "http://service.select.ole.kuali.org/")
            String arg2,
            /*
             * @WebParam(name = "requestorsFirstName", targetNamespace = "http://service.select.ole.kuali.org/") String arg3,
             * @WebParam(name = "requestorsLastName", targetNamespace = "http://service.select.ole.kuali.org/") String arg4,
             * @WebParam(name = "requestorsAddress1", targetNamespace = "http://service.select.ole.kuali.org/") String arg5,
             * @WebParam(name = "requestorsAddress2", targetNamespace = "http://service.select.ole.kuali.org/") String arg6,
             * @WebParam(name = "requestorsCity", targetNamespace = "http://service.select.ole.kuali.org/") String arg7,
             * @WebParam(name = "requestorsState", targetNamespace = "http://service.select.ole.kuali.org/") String arg8,
             * @WebParam(name = "requestorsZipCode", targetNamespace = "http://service.select.ole.kuali.org/") String arg9,
             * @WebParam(name = "requestorsCountryCode", targetNamespace = "http://service.select.ole.kuali.org/") String arg10,
             * @WebParam(name = "requestorsPhone", targetNamespace = "http://service.select.ole.kuali.org/") String arg11,
             * @WebParam(name = "requestorsEmail", targetNamespace = "http://service.select.ole.kuali.org/") String arg12,
             * @WebParam(name = "requestorsSMS", targetNamespace = "http://service.select.ole.kuali.org/") String arg13,
             */
            @WebParam(name = "requestorType", targetNamespace = "http://service.select.ole.kuali.org/")
            String arg3,
            @WebParam(name = "requestorId", targetNamespace = "http://service.select.ole.kuali.org/") String arg4)
            throws WSException_Exception
    ;

    /**
     * @param citationString
     * @param routeRequestorReceipt
     * @param requestorsNote
     * @param requestorsFirstName
     * @param requestorsLastName
     * @param requestorsAddress1
     * @param requestorsAddress2
     * @param requestorsCity
     * @param requestorsState
     * @param requestorsZipCode
     * @param requestorsCountryCode
     * @param requestorsPhone
     * @param requestorsEmail
     * @param requestorsSMS
     * @param requestorType
     * @return returns java.lang.String
     * @throws WSException_Exception
     */

    @WebMethod
    @WebResult(targetNamespace = "http://service.select.ole.kuali.org/")
    @RequestWrapper(localName = "createPreOrderForCitation", targetNamespace = "http://service.select.ole.kuali.org/", className = "org.kuali.ole.select.testing.CreatePreOrderForCitation")
    @ResponseWrapper(localName = "createPreOrderForCitationResponse", targetNamespace = "http://service.select.ole.kuali.org/", className = "org.kuali.ole.select.testing.CreatePreOrderForCitationResponse")
    public String createPreOrderForCitation(
            @WebParam(name = "citationString", targetNamespace = "http://service.select.ole.kuali.org/")
            String arg0,
            @WebParam(name = "routeRequestorReceipt", targetNamespace = "http://service.select.ole.kuali.org/")
            String arg1,
            @WebParam(name = "requestorsNote", targetNamespace = "http://service.select.ole.kuali.org/")
            String arg2,
            /*
             * @WebParam(name = "requestorsFirstName", targetNamespace = "http://service.select.ole.kuali.org/") String arg3,
             * @WebParam(name = "requestorsLastName", targetNamespace = "http://service.select.ole.kuali.org/") String arg4,
             * @WebParam(name = "requestorsAddress1", targetNamespace = "http://service.select.ole.kuali.org/") String arg5,
             * @WebParam(name = "requestorsAddress2", targetNamespace = "http://service.select.ole.kuali.org/") String arg6,
             * @WebParam(name = "requestorsCity", targetNamespace = "http://service.select.ole.kuali.org/") String arg7,
             * @WebParam(name = "requestorsState", targetNamespace = "http://service.select.ole.kuali.org/") String arg8,
             * @WebParam(name = "requestorsZipCode", targetNamespace = "http://service.select.ole.kuali.org/") String arg9,
             * @WebParam(name = "requestorsCountryCode", targetNamespace = "http://service.select.ole.kuali.org/") String arg10,
             * @WebParam(name = "requestorsPhone", targetNamespace = "http://service.select.ole.kuali.org/") String arg11,
             * @WebParam(name = "requestorsEmail", targetNamespace = "http://service.select.ole.kuali.org/") String arg12,
             * @WebParam(name = "requestorsSMS", targetNamespace = "http://service.select.ole.kuali.org/") String arg13,
             */
            @WebParam(name = "requestorType", targetNamespace = "http://service.select.ole.kuali.org/")
            String arg3,
            @WebParam(name = "requestorId", targetNamespace = "http://service.select.ole.kuali.org/") String arg4)
            throws WSException_Exception
    ;

}
