
package org.kuali.ole.select.testing;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 */
@WebServiceClient(name = "preOrderService", targetNamespace = "http://service.select.ole.kuali.org/", wsdlLocation = "http://localhost:8080/ole-local/remoting/preOrderService?wsdl")
public class PreOrderService_Service
        extends Service {

    private final static URL PREORDERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.kuali.ole.select.testing.PreOrderService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            // baseUrl = org.kuali.ole.select.testing.PreOrderService_Service.class.getResource(".");
            url = new URL("http://localhost:8080/ole-local/remoting/preOrderService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/ole-local/remoting/preOrderService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PREORDERSERVICE_WSDL_LOCATION = url;
    }

    public PreOrderService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PreOrderService_Service() {
        super(PREORDERSERVICE_WSDL_LOCATION, new QName("http://service.select.ole.kuali.org/", "preOrderService"));
    }

    /**
     * @return returns PreOrderService
     */
    @WebEndpoint(name = "preOrderServicePort")
    public PreOrderService getPreOrderServicePort() {
        return super.getPort(new QName("http://service.select.ole.kuali.org/", "preOrderServicePort"), PreOrderService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns PreOrderService
     */
    @WebEndpoint(name = "preOrderServicePort")
    public PreOrderService getPreOrderServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.select.ole.kuali.org/", "preOrderServicePort"), PreOrderService.class, features);
    }

}
