
package org.kuali.ole.select.testing;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 */
@WebFault(name = "Exception", targetNamespace = "http://service.select.ole.kuali.org/")
public class WSException_Exception
        extends java.lang.Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     */
    private org.kuali.ole.select.testing.WSException faultInfo;

    /**
     * @param message
     * @param faultInfo
     */
    public WSException_Exception(String message, org.kuali.ole.select.testing.WSException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * @param message
     * @param faultInfo
     * @param cause
     */
    public WSException_Exception(String message, org.kuali.ole.select.testing.WSException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * @return returns fault bean: org.kuali.ole.select.testing.Exception
     */
    public org.kuali.ole.select.testing.WSException getFaultInfo() {
        return faultInfo;
    }

}
