

ALTER TABLE OLE_DS_BIB_HOLDINGS_T
    ADD CONSTRAINT BIB_HOLD_HOLD_CNSTRT FOREIGN KEY (HOLDINGS_ID)
    REFERENCES OLE_DS_HOLDINGS_T (HOLDINGS_ID)
/

ALTER TABLE OLE_DS_BIB_HOLDINGS_T
    ADD CONSTRAINT BIB_HOL_BIB_CNSTRT FOREIGN KEY (BIB_ID)
    REFERENCES OLE_DS_BIB_T (BIB_ID)
/




ALTER TABLE OLE_DS_HOLDINGS_COVERAGE_T
    ADD CONSTRAINT HOLDINGS_COVERAGE_CONSTRAINT FOREIGN KEY (HOLDINGS_ID)
    REFERENCES OLE_DS_HOLDINGS_T (HOLDINGS_ID)
/


ALTER TABLE OLE_DS_EXT_OWNERSHIP_NOTE_T
    ADD CONSTRAINT EXT_NOTE_CONSTRAINT FOREIGN KEY (EXT_OWNERSHIP_ID)
    REFERENCES OLE_DS_EXT_OWNERSHIP_T (EXT_OWNERSHIP_ID)
/


ALTER TABLE OLE_DS_EXT_OWNERSHIP_T
    ADD CONSTRAINT EXT_OWNERSHIP_CONSTRAINT FOREIGN KEY (HOLDINGS_ID)
    REFERENCES OLE_DS_HOLDINGS_T (HOLDINGS_ID)
/


ALTER TABLE OLE_DS_ITM_FORMER_IDENTIFIER_T
    ADD CONSTRAINT FORMER_CONSTRAINT FOREIGN KEY (ITEM_ID)
    REFERENCES OLE_DS_ITEM_T (ITEM_ID)
/



ALTER TABLE OLE_DS_ACCESS_LOCATION_T
    ADD CONSTRAINT ACCESS_LOC_CONSTRAINT FOREIGN KEY (HOLDINGS_ID)
    REFERENCES OLE_DS_HOLDINGS_T (HOLDINGS_ID)
/

ALTER TABLE OLE_DS_ACCESS_LOCATION_T
    ADD CONSTRAINT ACCESS_LOCN_CODE_CONSTRAINT FOREIGN KEY (ACCESS_LOCATION_CODE_ID)
    REFERENCES OLE_DS_ACCESS_LOCATION_CODE_T (ACCESS_LOCATION_CODE_ID)
/


ALTER TABLE OLE_DS_HOLDINGS_URI_T
    ADD CONSTRAINT ACCESS_URI_CONSTRAINT FOREIGN KEY (HOLDINGS_ID)
    REFERENCES OLE_DS_HOLDINGS_T (HOLDINGS_ID)
/


ALTER TABLE OLE_DS_HOLDINGS_DONOR_T
    ADD CONSTRAINT HOLDINGS_DONOR_CONSTRAINT FOREIGN KEY (HOLDINGS_ID)
    REFERENCES OLE_DS_HOLDINGS_T (HOLDINGS_ID)
/


ALTER TABLE OLE_DS_HOLDINGS_NOTE_T
    ADD CONSTRAINT HOLDINGS_NOTE_CONSTRAINT FOREIGN KEY (HOLDINGS_ID)
    REFERENCES OLE_DS_HOLDINGS_T (HOLDINGS_ID)
/


ALTER TABLE OLE_DS_HOLDINGS_STAT_SEARCH_T
    ADD CONSTRAINT HOLDINGS_STAT_SEARCH_CONST FOREIGN KEY (HOLDINGS_ID)
    REFERENCES OLE_DS_HOLDINGS_T (HOLDINGS_ID)
/


ALTER TABLE OLE_DS_ITEM_HOLDINGS_T
    ADD CONSTRAINT ITEM_HOLD_HOLD_CNSTRT FOREIGN KEY (HOLDINGS_ID)
    REFERENCES OLE_DS_HOLDINGS_T (HOLDINGS_ID)
/

ALTER TABLE OLE_DS_ITEM_HOLDINGS_T
    ADD CONSTRAINT ITEM_HOL_ITEM_CNSTRT FOREIGN KEY (ITEM_ID)
    REFERENCES OLE_DS_ITEM_T (ITEM_ID)
/


ALTER TABLE OLE_DS_HOLDINGS_T
    ADD CONSTRAINT HOLDINGS_BIB_CONSTRAINT FOREIGN KEY (BIB_ID)
    REFERENCES OLE_DS_BIB_T (BIB_ID)
/


ALTER TABLE OLE_DS_ITEM_DONOR_T
    ADD CONSTRAINT ITEM_DONOR_CONSTRAINT FOREIGN KEY (ITEM_ID)
    REFERENCES OLE_DS_ITEM_T (ITEM_ID)
/


ALTER TABLE OLE_DS_ITEM_NOTE_T
    ADD CONSTRAINT ITEM_NOTE_CONSTRAINT FOREIGN KEY (ITEM_ID)
    REFERENCES OLE_DS_ITEM_T (ITEM_ID)
/


ALTER TABLE OLE_DS_ITEM_STAT_SEARCH_T
    ADD CONSTRAINT ITEM_STAT_SEARCH_CONSTRAINT FOREIGN KEY (ITEM_ID)
    REFERENCES OLE_DS_ITEM_T (ITEM_ID)
/


ALTER TABLE OLE_DS_ITEM_T
    ADD CONSTRAINT HIGH_DENSITY_CONSTRAINT FOREIGN KEY (HIGH_DENSITY_STORAGE_ID)
    REFERENCES OLE_DS_HIGH_DENSITY_STORAGE_T (HIGH_DENSITY_STORAGE_ID)
/

ALTER TABLE OLE_DS_ITEM_T
    ADD CONSTRAINT ITEM_HOLDINGS_CONSTRAINT FOREIGN KEY (HOLDINGS_ID)
    REFERENCES OLE_DS_HOLDINGS_T (HOLDINGS_ID)
/


ALTER TABLE OLE_DS_LOC_CHECKIN_COUNT_T
    ADD CONSTRAINT LOCATION_COUNT_CONSTRAINT FOREIGN KEY (ITEM_ID)
    REFERENCES OLE_DS_ITEM_T (ITEM_ID)
/


ALTER TABLE OLE_DS_PERPETUAL_ACCESS_T
    ADD CONSTRAINT HOLDINGS_PER_ACC_CONSTRAINT FOREIGN KEY (HOLDINGS_ID)
    REFERENCES OLE_DS_HOLDINGS_T (HOLDINGS_ID)
/



ALTER TABLE OLE_ITM_CLM_RTND_HSTRY_T
    ADD CONSTRAINT OLE_ITM_CLM_RTND_HSTRY_FK FOREIGN KEY (ITEM_ID)
    REFERENCES OLE_DS_ITEM_T (ITEM_ID)
/



ALTER TABLE OLE_DS_DMGD_ITM_HSTRY_T
    ADD CONSTRAINT ITEM_DAMAGED_CONSTRAINT FOREIGN KEY (ITEM_ID)
    REFERENCES OLE_DS_ITEM_T (ITEM_ID)
/


ALTER TABLE OLE_MISS_PCE_ITM_HSTRY_T
    ADD CONSTRAINT ITEM_MISS_PCE_CNSRT FOREIGN KEY (ITEM_ID)
    REFERENCES OLE_DS_ITEM_T (ITEM_ID)
/


