-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: org/kuali/ole/2.0/db.changelog-20141229.xml
-- *********************************************************************

-- Lock Database
-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_PKG_T::ole
CREATE TABLE ole.OLE_GOKB_PKG_T (GOKB_PKG_ID NUMBER(10), PKG_NAME VARCHAR2(1000), VARIANT_NAME VARCHAR2(4000), PKG_STATUS VARCHAR2(20), PKG_SCOPE VARCHAR2(20), BREAKABLE VARCHAR2(10), FXD VARCHAR2(10), AVLBLE VARCHAR2(10), DATE_CREATED date, DATE_UPDATED date, VER_NBR DECIMAL(8), OBJ_ID VARCHAR2(36))
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_PKG_T', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 1, '7:edf59a3f8138bb2ec7caeb0cd9cef297', 'createTable', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_PKG_T_PK::ole
ALTER TABLE ole.OLE_GOKB_PKG_T ADD CONSTRAINT OLE_GOKB_PKG_T_PK PRIMARY KEY (GOKB_PKG_ID)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_PKG_T_PK', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 2, '7:5e78675e903727d7b8951e3e7c356b09', 'addPrimaryKey', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_TIPP_T::ole
CREATE TABLE ole.OLE_GOKB_TIPP_T (GOKB_TIPP_ID NUMBER(10), GOKB_PKG_ID NUMBER(10), GOKB_TITLE_ID NUMBER(10), GOKB_PLTFRM_ID NUMBER(10), TIPP_STATUS VARCHAR2(100), STATUS_REASON VARCHAR2(300), STRT_DT date, STRT_VOL VARCHAR2(100), STRT_ISSUE VARCHAR2(100), END_DT date, END_VOL VARCHAR2(100), END_ISSUE VARCHAR2(100), EMBARGO VARCHAR2(50), PLTFRM_HOST_URL VARCHAR2(300), DATE_CREATED date, DATE_UPDATED date, VER_NBR DECIMAL(8), OBJ_ID VARCHAR2(36))
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_TIPP_T', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 3, '7:4dafadcf4969bd4e6418ad659bf253cf', 'createTable', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_TIPP_T_PK::ole
ALTER TABLE ole.OLE_GOKB_TIPP_T ADD CONSTRAINT OLE_GOKB_TIPP_T_PK PRIMARY KEY (GOKB_TIPP_ID)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_TIPP_T_PK', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 4, '7:920f52704aaf17611883afa292cd9655', 'addPrimaryKey', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_TITLE_T::ole
CREATE TABLE ole.OLE_GOKB_TITLE_T (GOKB_TITLE_ID NUMBER(10), TITLE_NAME VARCHAR2(500), VARIANT_NAME VARCHAR2(4000), MEDIUM VARCHAR2(50), PURE_QA VARCHAR2(50), TI_ISSN_ONLINE VARCHAR2(50), TI_ISSN_PRNT VARCHAR2(50), TI_ISSN_L VARCHAR2(50), OCLC_NUM NUMBER(10), TI_DOI VARCHAR2(50), TI_PROPRIETARY_ID NUMBER(10), TI_SUNCAT VARCHAR2(50), TI_LCCN VARCHAR2(50), PUBLSHR_ID NUMBER(10), IMPRINT NUMBER(10), DATE_CREATED date, DATE_UPDATED date, VER_NBR DECIMAL(8), OBJ_ID VARCHAR2(36))
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_TITLE_T', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 5, '7:49dfdfff17e0160134908fe4de79891a', 'createTable', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_TITLE_T_PK::ole
ALTER TABLE ole.OLE_GOKB_TITLE_T ADD CONSTRAINT OLE_GOKB_TITLE_T_PK PRIMARY KEY (GOKB_TITLE_ID)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_TITLE_T_PK', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 6, '7:00edf027b12b4c5a29a6aea7f1f84fb9', 'addPrimaryKey', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_PLTFRM_T::ole
CREATE TABLE ole.OLE_GOKB_PLTFRM_T (GOKB_PLTFRM_ID NUMBER(10), PLTFRM_NAME VARCHAR2(500), PLTFRM_STATUS VARCHAR2(100), PLTFRM_PRVDR_ID NUMBER(10), AUTH VARCHAR2(50), SOFTWARE_PLTFRM VARCHAR2(50), DATE_CREATED date, DATE_UPDATED date, VER_NBR DECIMAL(8), OBJ_ID VARCHAR2(36))
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_PLTFRM_T', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 7, '7:6e6e6889f08ef1aeda3f365592d9fcc6', 'createTable', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_PLTFRM_T_PK::ole
ALTER TABLE ole.OLE_GOKB_PLTFRM_T ADD CONSTRAINT OLE_GOKB_PLTFRM_T_PK PRIMARY KEY (GOKB_PLTFRM_ID)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_PLTFRM_T_PK', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 8, '7:5ded2aa3468dfde9aa47a9c971060a16', 'addPrimaryKey', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_ORG_T::ole
CREATE TABLE ole.OLE_GOKB_ORG_T (GOKB_ORG_ID NUMBER(10), ORG_NAME VARCHAR2(1000), VARIANT_NAME VARCHAR2(4000), DATE_CREATED date, DATE_UPDATED date, VER_NBR DECIMAL(8), OBJ_ID VARCHAR2(36))
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_ORG_T', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 9, '7:83142384cd09d875a4385c1acacfa749', 'createTable', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_ORG_T_PK::ole
ALTER TABLE ole.OLE_GOKB_ORG_T ADD CONSTRAINT OLE_GOKB_ORG_T_PK PRIMARY KEY (GOKB_ORG_ID)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_ORG_T_PK', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 10, '7:5e1e76142258caa8af2c621bb1f2422d', 'addPrimaryKey', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_UPDATE_LOG_T::ole
CREATE TABLE ole.OLE_GOKB_UPDATE_LOG_T (ID NUMBER(10), NUM_PKGS NUMBER(10), NUM_TIPPS NUMBER(10), NUM_TITLES NUMBER(10), NUM_ORGS NUMBER(10), NUM_PLTFRMS NUMBER(10), USER_NM VARCHAR2(100), STATUS VARCHAR2(20), START_TIME date, END_TIME date, VER_NBR DECIMAL(8), OBJ_ID VARCHAR2(36))
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_UPDATE_LOG_T', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 11, '7:972d3f7bc8a958636cbad3b2a6b78501', 'createTable', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_UPDATE_LOG_T_PK::ole
ALTER TABLE ole.OLE_GOKB_UPDATE_LOG_T ADD CONSTRAINT OLE_GOKB_UPDATE_LOG_T_PK PRIMARY KEY (ID)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_UPDATE_LOG_T_PK', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 12, '7:d39ec8b6f486d38e3881b8b2ec5d51a7', 'addPrimaryKey', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_ORG_ROLE_T::ole
CREATE TABLE ole.OLE_GOKB_ORG_ROLE_T (GOKB_ORG_ROLE_ID NUMBER(10), GOKB_ORG_ID NUMBER(10), ROLE VARCHAR2(100), VER_NBR DECIMAL(8), OBJ_ID VARCHAR2(36))
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_ORG_ROLE_T', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 13, '7:1229c2beb1ab4c324edc169a78fe6f1a', 'createTable', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_ORG_ROLE_T_PK::ole
ALTER TABLE ole.OLE_GOKB_ORG_ROLE_T ADD CONSTRAINT OLE_GOKB_ORG_ROLE_T_PK PRIMARY KEY (GOKB_ORG_ROLE_ID)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_ORG_ROLE_T_PK', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 14, '7:e65f5a4dc037fcc12a8f12b8115cd335', 'addPrimaryKey', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_REVIEW_T::ole
CREATE TABLE ole.OLE_GOKB_REVIEW_T (GOKB_REVIEW_ID NUMBER(10), REVIEW_DT date, E_RESOURCE_ID VARCHAR2(100), E_RESOURCE_NAME VARCHAR2(100), TYPE VARCHAR2(100), DETAILS VARCHAR2(1000), GOKB_TIPP_ID NUMBER(10), VER_NBR DECIMAL(8), OBJ_ID VARCHAR2(36))
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_REVIEW_T', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 15, '7:b4f5f5ba5cdf62fabf49bfeae6a4f2a5', 'createTable', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_REVIEW_T_PK::ole
ALTER TABLE ole.OLE_GOKB_REVIEW_T ADD CONSTRAINT OLE_GOKB_REVIEW_T_PK PRIMARY KEY (GOKB_REVIEW_ID)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_REVIEW_T_PK', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 16, '7:3ca38504bc60b50072105016a45174e9', 'addPrimaryKey', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_DS_DOC_FIELD_T::ole
INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level1Location','390','8','3','Y','N','N','Y','N','Level1Location_display','390','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level2Location','391','8','3','Y','N','N','Y','N','Level2Location_display','391','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level3Location','392','8','3','Y','N','N','Y','N','Level3Location_display','392','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level4Location','393','8','3','Y','N','N','Y','N','Level4Location_display','393','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level5Location','394','8','3','Y','N','N','Y','N','Level5Location_display','394','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level1Location','395','9','4','Y','N','N','Y','N','Level1Location_display','395','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level3Location','396','9','4','Y','N','N','Y','N','Level2Location_display','396','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level3Location','397','9','4','Y','N','N','Y','N','Level3Location_display','397','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level4Location','398','9','4','Y','N','N','Y','N','Level4Location_display','398','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level5Location','399','9','4','Y','N','N','Y','N','Level5Location_display','399','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level1Location','410','10','5','Y','N','N','Y','N','Level1Location_display','410','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level2Location','411','10','5','Y','N','N','Y','N','Level2Location_display','411','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level3Location','412','10','5','Y','N','N','Y','N','Level3Location_display','412','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level4Location','413','10','5','Y','N','N','Y','N','Level4Location_display','413','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level5Location','414','10','5','Y','N','N','Y','N','Level5Location_display','414','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level1Location','404','8','3','N','N','N','Y','Y','Level1Location_search','404','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level2Location','400','8','3','N','N','N','Y','Y','Level2Location_search','400','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level3Location','401','8','3','N','N','N','Y','Y','Level3Location_search','401','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level4Location','402','8','3','N','N','N','Y','Y','Level4Location_search','402','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level5Location','403','8','3','N','N','N','Y','Y','Level5Location_search','404','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level1Location','405','9','4','N','N','N','Y','Y','Level1Location_search','405','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level2Location','406','9','4','N','N','N','Y','Y','Level2Location_search','406','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level3Location','407','9','4','N','N','N','Y','Y','Level3Location_search','407','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level4Location','408','9','4','N','N','N','Y','Y','Level4Location_search','408','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level5Location','409','9','4','N','N','N','Y','Y','Level5Location_search','409','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level1Location','415','10','5','N','N','N','Y','Y','Level1Location_search','415','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level2Location','416','10','5','N','N','N','Y','Y','Level2Location_search','416','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level3Location','417','10','5','N','N','N','Y','Y','Level3Location_search','417','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level4Location','418','10','5','N','N','N','Y','Y','Level4Location_search','418','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Level5Location','419','10','5','N','N','N','Y','Y','Level5Location_search','419','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Item Barcode','420','1','1','N','N','N','N','Y','ItemBarcode_search','420','1')
/

INSERT INTO OLE_DS_DOC_FIELD_T (DISPLAY_LABEL,DOC_FIELD_ID,DOC_FORMAT_ID,DOC_TYPE_ID,IS_DISPLAY,IS_EXPORT,IS_FACET,IS_GLOBAL_EDIT,IS_SEARCH,NAME,OBJ_ID,VER_NBR) VALUES ('Uri','421','1','1','N','N','N','N','Y','Uri_search','421','1')
/

UPDATE OLE_DS_DOC_FIELD_T SET IS_SEARCH='Y' WHERE DOC_FIELD_ID=157
/

UPDATE OLE_DS_DOC_FIELD_T SET IS_SEARCH='Y' WHERE DOC_FIELD_ID=162
/

UPDATE OLE_DS_DOC_FIELD_T SET IS_SEARCH='Y' WHERE DOC_FIELD_ID=243
/

UPDATE OLE_DS_DOC_FIELD_T SET IS_SEARCH='Y' WHERE DOC_FIELD_ID=248
/

UPDATE OLE_DS_DOC_FIELD_T SET IS_SEARCH='Y' WHERE DOC_FIELD_ID=250
/

UPDATE OLE_DS_DOC_FIELD_T SET IS_SEARCH='Y' WHERE DOC_FIELD_ID=257
/

UPDATE OLE_DS_DOC_FIELD_T SET IS_SEARCH='Y' WHERE DOC_FIELD_ID=185
/

UPDATE OLE_DS_DOC_FIELD_T SET IS_SEARCH='Y' WHERE DOC_FIELD_ID=187
/

UPDATE OLE_DS_DOC_FIELD_T SET IS_SEARCH='Y',DISPLAY_LABEL="Donor Code" WHERE DOC_FIELD_ID=292
/

UPDATE OLE_DS_DOC_FIELD_T SET IS_SEARCH='Y' WHERE DOC_FIELD_ID=293
/

UPDATE OLE_DS_DOC_FIELD_T SET IS_SEARCH='Y',DISPLAY_LABEL="Fast Add" WHERE DOC_FIELD_ID=294
/

UPDATE OLE_DS_DOC_FIELD_T SET IS_SEARCH='Y' WHERE DOC_FIELD_ID=298
/

UPDATE OLE_DS_DOC_FIELD_T SET IS_SEARCH='Y',DISPLAY_LABEL="Claims Return Flag" WHERE DOC_FIELD_ID=299
/

UPDATE OLE_DS_DOC_FIELD_T SET IS_SEARCH='Y' WHERE DOC_FIELD_ID=300
/

UPDATE OLE_DS_DOC_FIELD_T SET IS_SEARCH='Y' WHERE DOC_FIELD_ID=301
/

UPDATE OLE_DS_DOC_FIELD_T SET IS_SEARCH='Y' WHERE DOC_FIELD_ID=180
/

UPDATE OLE_DS_DOC_FIELD_T SET IS_SEARCH='Y' WHERE DOC_FIELD_ID=284
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DS_DOC_FIELD_T', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 17, '7:9e4fc28cde26b16cb098b0546e47dbc2', 'sql (x49)', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_E_RES_REC_T::ole
ALTER TABLE OLE_E_RES_REC_T MODIFY TITLE varchar2(200)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_E_RES_REC_T', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 18, '7:d98a7133924f5c458331f4ea10c961e4', 'sql', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_DLVR_RQST_HSTRY_REC_T_CRTE_DT_TIME::ole
ALTER TABLE ole.OLE_DLVR_RQST_HSTRY_REC_T ADD CRTE_DT_TIME date
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_RQST_HSTRY_REC_T_CRTE_DT_TIME', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 19, '7:15649203da8dced86be68718c629c7c6', 'addColumn', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_DLVR_RQST_HSTRY_REC_T_CRTE_DT_TIME_NOT_NULL_CONSTRAINT::ole
ALTER TABLE ole.OLE_DLVR_RQST_HSTRY_REC_T MODIFY CRTE_DT_TIME NOT NULL
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_RQST_HSTRY_REC_T_CRTE_DT_TIME_NOT_NULL_CONSTRAINT', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 20, '7:f722c13041876f8eeae357d94f6d42d0', 'addNotNullConstraint', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_DLVR_CIRC_RECORDS::ole
ALTER TABLE ole.OLE_DLVR_CIRC_RECORD ADD ITM_LOCN VARCHAR2(100)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_CIRC_RECORDS', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 21, '7:6a8c65f4bd93a634389c8d98f08cf84e', 'addColumn', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_DLVR_CIRC_RECORDT::ole
ALTER TABLE ole.OLE_DLVR_CIRC_RECORD ADD HLDNG_LOCN VARCHAR2(100)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_CIRC_RECORDT', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 22, '7:57556d35fa2e017457b08d6e969285c4', 'addColumn', '', 'EXECUTED', '3.2.0')
/

-- Release Database Lock
-- Release Database Lock
