-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: org/kuali/ole/2.0/db.changelog-20141229.xml
-- *********************************************************************

-- Lock Database
-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_PKG_T::ole
CREATE TABLE ole.OLE_GOKB_PKG_T (GOKB_PKG_ID NUMBER(10), PKG_NAME VARCHAR2(1000), VARIANT_NAME VARCHAR2(4000), PKG_STATUS VARCHAR2(20), PKG_SCOPE VARCHAR2(20), BREAKABLE VARCHAR2(10), FXD VARCHAR2(10), AVLBLE VARCHAR2(10), DATE_CREATED date, DATE_UPDATED date, VER_NBR DECIMAL(8), OBJ_ID VARCHAR2(36))
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_PKG_T', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 1, '7:edf59a3f8138bb2ec7caeb0cd9cef297', 'createTable', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_PKG_T_PK::ole
ALTER TABLE ole.OLE_GOKB_PKG_T ADD CONSTRAINT OLE_GOKB_PKG_T_PK PRIMARY KEY (GOKB_PKG_ID)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_PKG_T_PK', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 2, '7:5e78675e903727d7b8951e3e7c356b09', 'addPrimaryKey', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_TIPP_T::ole
CREATE TABLE ole.OLE_GOKB_TIPP_T (GOKB_TIPP_ID NUMBER(10), GOKB_PKG_ID NUMBER(10), GOKB_TITLE_ID NUMBER(10), GOKB_PLTFRM_ID NUMBER(10), TIPP_STATUS VARCHAR2(100), STATUS_REASON VARCHAR2(300), STRT_DT date, STRT_VOL VARCHAR2(100), STRT_ISSUE VARCHAR2(100), END_DT date, END_VOL VARCHAR2(100), END_ISSUE VARCHAR2(100), EMBARGO VARCHAR2(50), PLTFRM_HOST_URL VARCHAR2(300), DATE_CREATED date, DATE_UPDATED date, VER_NBR DECIMAL(8), OBJ_ID VARCHAR2(36))
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_TIPP_T', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 3, '7:4dafadcf4969bd4e6418ad659bf253cf', 'createTable', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_TIPP_T_PK::ole
ALTER TABLE ole.OLE_GOKB_TIPP_T ADD CONSTRAINT OLE_GOKB_TIPP_T_PK PRIMARY KEY (GOKB_TIPP_ID)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_TIPP_T_PK', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 4, '7:920f52704aaf17611883afa292cd9655', 'addPrimaryKey', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_TITLE_T::ole
CREATE TABLE ole.OLE_GOKB_TITLE_T (GOKB_TITLE_ID NUMBER(10), TITLE_NAME VARCHAR2(500), VARIANT_NAME VARCHAR2(4000), MEDIUM VARCHAR2(50), PURE_QA VARCHAR2(50), TI_ISSN_ONLINE VARCHAR2(50), TI_ISSN_PRNT VARCHAR2(50), TI_ISSN_L VARCHAR2(50), OCLC_NUM NUMBER(10), TI_DOI VARCHAR2(50), TI_PROPRIETARY_ID NUMBER(10), TI_SUNCAT VARCHAR2(50), TI_LCCN VARCHAR2(50), PUBLSHR_ID NUMBER(10), IMPRINT NUMBER(10), DATE_CREATED date, DATE_UPDATED date, VER_NBR DECIMAL(8), OBJ_ID VARCHAR2(36))
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_TITLE_T', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 5, '7:49dfdfff17e0160134908fe4de79891a', 'createTable', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_TITLE_T_PK::ole
ALTER TABLE ole.OLE_GOKB_TITLE_T ADD CONSTRAINT OLE_GOKB_TITLE_T_PK PRIMARY KEY (GOKB_TITLE_ID)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_TITLE_T_PK', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 6, '7:00edf027b12b4c5a29a6aea7f1f84fb9', 'addPrimaryKey', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_PLTFRM_T::ole
CREATE TABLE ole.OLE_GOKB_PLTFRM_T (GOKB_PLTFRM_ID NUMBER(10), PLTFRM_NAME VARCHAR2(500), PLTFRM_STATUS VARCHAR2(100), PLTFRM_PRVDR_ID NUMBER(10), AUTH VARCHAR2(50), SOFTWARE_PLTFRM VARCHAR2(50), DATE_CREATED date, DATE_UPDATED date, VER_NBR DECIMAL(8), OBJ_ID VARCHAR2(36))
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_PLTFRM_T', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 7, '7:6e6e6889f08ef1aeda3f365592d9fcc6', 'createTable', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_PLTFRM_T_PK::ole
ALTER TABLE ole.OLE_GOKB_PLTFRM_T ADD CONSTRAINT OLE_GOKB_PLTFRM_T_PK PRIMARY KEY (GOKB_PLTFRM_ID)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_PLTFRM_T_PK', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 8, '7:5ded2aa3468dfde9aa47a9c971060a16', 'addPrimaryKey', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_ORG_T::ole
CREATE TABLE ole.OLE_GOKB_ORG_T (GOKB_ORG_ID NUMBER(10), ORG_NAME VARCHAR2(1000), VARIANT_NAME VARCHAR2(4000), DATE_CREATED date, DATE_UPDATED date, VER_NBR DECIMAL(8), OBJ_ID VARCHAR2(36))
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_ORG_T', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 9, '7:83142384cd09d875a4385c1acacfa749', 'createTable', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_ORG_T_PK::ole
ALTER TABLE ole.OLE_GOKB_ORG_T ADD CONSTRAINT OLE_GOKB_ORG_T_PK PRIMARY KEY (GOKB_ORG_ID)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_ORG_T_PK', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 10, '7:5e1e76142258caa8af2c621bb1f2422d', 'addPrimaryKey', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_UPDATE_LOG_T::ole
CREATE TABLE ole.OLE_GOKB_UPDATE_LOG_T (ID NUMBER(10), NUM_PKGS NUMBER(10), NUM_TIPPS NUMBER(10), NUM_TITLES NUMBER(10), NUM_ORGS NUMBER(10), NUM_PLTFRMS NUMBER(10), USER_NM VARCHAR2(100), STATUS VARCHAR2(20), START_TIME date, END_TIME date, VER_NBR DECIMAL(8), OBJ_ID VARCHAR2(36))
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_UPDATE_LOG_T', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 11, '7:972d3f7bc8a958636cbad3b2a6b78501', 'createTable', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_UPDATE_LOG_T_PK::ole
ALTER TABLE ole.OLE_GOKB_UPDATE_LOG_T ADD CONSTRAINT OLE_GOKB_UPDATE_LOG_T_PK PRIMARY KEY (ID)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_UPDATE_LOG_T_PK', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 12, '7:d39ec8b6f486d38e3881b8b2ec5d51a7', 'addPrimaryKey', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_ORG_ROLE_T::ole
CREATE TABLE ole.OLE_GOKB_ORG_ROLE_T (GOKB_ORG_ROLE_ID NUMBER(10), GOKB_ORG_ID NUMBER(10), ROLE VARCHAR2(100), VER_NBR DECIMAL(8), OBJ_ID VARCHAR2(36))
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_ORG_ROLE_T', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 13, '7:1229c2beb1ab4c324edc169a78fe6f1a', 'createTable', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_ORG_ROLE_T_PK::ole
ALTER TABLE ole.OLE_GOKB_ORG_ROLE_T ADD CONSTRAINT OLE_GOKB_ORG_ROLE_T_PK PRIMARY KEY (GOKB_ORG_ROLE_ID)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_ORG_ROLE_T_PK', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 14, '7:e65f5a4dc037fcc12a8f12b8115cd335', 'addPrimaryKey', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_REVIEW_T::ole
CREATE TABLE ole.OLE_GOKB_REVIEW_T (GOKB_REVIEW_ID NUMBER(10), REVIEW_DT date, E_RESOURCE_ID VARCHAR2(100), E_RESOURCE_NAME VARCHAR2(100), TYPE VARCHAR2(100), DETAILS VARCHAR2(1000), GOKB_TIPP_ID NUMBER(10), VER_NBR DECIMAL(8), OBJ_ID VARCHAR2(36))
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_REVIEW_T', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 15, '7:b4f5f5ba5cdf62fabf49bfeae6a4f2a5', 'createTable', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/2.0/db.changelog-20141229.xml::OLE_GOKB_REVIEW_T_PK::ole
ALTER TABLE ole.OLE_GOKB_REVIEW_T ADD CONSTRAINT OLE_GOKB_REVIEW_T_PK PRIMARY KEY (GOKB_REVIEW_ID)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_GOKB_REVIEW_T_PK', 'ole', 'org/kuali/ole/2.0/db.changelog-20141229.xml', SYSTIMESTAMP, 16, '7:3ca38504bc60b50072105016a45174e9', 'addPrimaryKey', '', 'EXECUTED', '3.2.0')
/

-- Release Database Lock
-- Release Database Lock
