-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: org/kuali/ole/3.0/db.changelog-20160208.xml
-- *********************************************************************

-- Lock Database
-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_KRIM_PERM_T_oracle::ole
INSERT INTO KRIM_PERM_T (PERM_ID, OBJ_ID, VER_NBR, PERM_TMPL_ID, NMSPC_CD, NM, DESC_TXT, ACTV_IND) VALUES ('OLE3010502', 'OLE3010502', '1', '1', 'OLE-CAT', 'MARC_EDITOR_COPY_BIB', 'user to Copy a bibliographic record will be created', 'Y')
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_KRIM_PERM_T_oracle', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 1, '7:79e9abb663948973bb18118bbcad4803', 'loadData', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_KRIM_ROLE_PERM_T_oracle::ole
INSERT INTO KRIM_ROLE_PERM_T (ROLE_PERM_ID, OBJ_ID, ROLE_ID, PERM_ID, ACTV_IND) VALUES ('OLE12506', 'OLE12506', 'OLE10077', 'OLE3010502', 'Y')
/

INSERT INTO KRIM_ROLE_PERM_T (ROLE_PERM_ID, OBJ_ID, ROLE_ID, PERM_ID, ACTV_IND) VALUES ('OLE12507', 'OLE12507', 'OLE10078', 'OLE3010502', 'Y')
/

INSERT INTO KRIM_ROLE_PERM_T (ROLE_PERM_ID, OBJ_ID, ROLE_ID, PERM_ID, ACTV_IND) VALUES ('OLE12508', 'OLE12508', 'OLE10079', 'OLE3010502', 'Y')
/

INSERT INTO KRIM_ROLE_PERM_T (ROLE_PERM_ID, OBJ_ID, ROLE_ID, PERM_ID, ACTV_IND) VALUES ('OLE12509', 'OLE12509', 'OLE10080', 'OLE3010502', 'Y')
/

INSERT INTO KRIM_ROLE_PERM_T (ROLE_PERM_ID, OBJ_ID, ROLE_ID, PERM_ID, ACTV_IND) VALUES ('OLE12510', 'OLE12510', 'OLE10082', 'OLE3010502', 'Y')
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_KRIM_ROLE_PERM_T_oracle', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 2, '7:9e4a6459176d922d41ee8547a9d4bdfb', 'loadData', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_CAT_SHVLG_SCHM_T_UPDATE::ole
UPDATE OLE_CAT_SHVLG_SCHM_T SET SHVLG_SCHM_CD = 'EIGHT', SHVLG_SCHM_ID = '10' WHERE SHVLG_SCHM_ID = 8
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_CAT_SHVLG_SCHM_T_UPDATE', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 3, '7:07bcfea29f570366d060d68cbb549c8f', 'update', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_CAT_SHVLG_SCHM_T_INSERT::ole
INSERT INTO OLE_CAT_SHVLG_SCHM_T (OBJ_ID,ROW_ACT_IND,SHVLG_SCHM_CD,SHVLG_SCHM_ID,SHVLG_SCHM_NM,SRC,SRC_DT,VER_NBR) VALUES ('fb8119a1-eafb-4150-ad72-0f9c67e7d7df','Y','SIX',8,'Shelved separately','MFHD 852 1st Indicator: http://www.loc.gov/marc/holdings/hd852.html',TO_DATE( '20120322000000', 'YYYYMMDDHH24MISS' ),1)
/

INSERT INTO OLE_CAT_SHVLG_SCHM_T (OBJ_ID,ROW_ACT_IND,SHVLG_SCHM_CD,SHVLG_SCHM_ID,SHVLG_SCHM_NM,SRC,SRC_DT,VER_NBR) VALUES ('fb8119a1-eafb-4150-ad72-0f9c67e7d7dg','Y','SEVEN',9,'Source specified in subfield $2','MFHD 852 1st Indicator: http://www.loc.gov/marc/holdings/hd852.html',TO_DATE( '20120322000000', 'YYYYMMDDHH24MISS' ),1)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_CAT_SHVLG_SCHM_T_INSERT', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 4, '7:89c9e831825ee25366aadf60c3e2ab7e', 'sql (x2)', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::PUR_REQS_T_BILL_PHN_NBR_NULL::ole
ALTER TABLE PUR_REQS_T MODIFY BILL_PHN_NBR NULL
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('PUR_REQS_T_BILL_PHN_NBR_NULL', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 5, '7:0c66f770f71c621ab63c8ba4c67c8929', 'dropNotNullConstraint', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::ALERT_OLE_PUR_POBA_T_ORACLE::ole
ALTER TABLE OLE_PUR_POBA_T MODIFY UPLD_FILE_NM varchar2(120)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('ALERT_OLE_PUR_POBA_T_ORACLE', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 6, '7:1ed9edd50adf36556f6b8346b1053e79', 'sql', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_DS_HOLDINGS_T_ADD::ole
ALTER TABLE OLE_DS_HOLDINGS_T ADD MATERIALS_SPECIFIED VARCHAR2(100)
/

ALTER TABLE OLE_DS_HOLDINGS_T ADD FIRST_INDICATOR VARCHAR2(20)
/

ALTER TABLE OLE_DS_HOLDINGS_T ADD SECOND_INDICATOR VARCHAR2(20)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DS_HOLDINGS_T_ADD', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 7, '7:177bc16fdd76c1e15e186a9d2978d739', 'addColumn', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_PTRN_T_ORACLE::ole
ALTER TABLE OLE_PTRN_T ADD COLUMN CHECKOUT_RECEIPT_OPT_OUT VARCHAR(1)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_PTRN_T_ORACLE', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 8, '7:96334e79dcf47a250105011aeac06fa3', 'sql', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::ADD_LOCN_POPUP::ole
ALTER TABLE OLE_CRCL_DSK_LOCN_T ADD LOCN_POPUP VARCHAR2(1)
/

ALTER TABLE OLE_CRCL_DSK_LOCN_T ADD LOCN_POPUP_MSG VARCHAR2(4000)
/

ALTER TABLE OLE_CRCL_DSK_LOCN_T MODIFY LOCN_POPUP DEFAULT 'N'
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('ADD_LOCN_POPUP', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 9, '7:abc8f571e596b27bddbb33333e833f37', 'addColumn, addDefaultValue', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_LOAD_KRCR_PARM_T_oracle::ole
INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'CR_ITEMS_COUNT_TOWARD_LOANED_ITEMS_COUNT', 'OLEAC1002', '1', 'CONFG', 'true', 'This parameter value is used to identify whether to include item in loan count or not', 'A', 'KUALI')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'NOTIFY_CLAIMS_RETURNED_TO_PATRON', 'OLEAC1003', '1', 'CONFG', 'true', 'This parameter value is used to identify whether to notify the patron about claims returned item or not.', 'A', 'OLE')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'CLAIMS_RETURNED_NOTICE_TITLE', 'OLEAC1004', '1', 'CONFG', 'CLAIMS RETURNED NOTICE', 'Claims Returned Notice', 'A', 'KUALI')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'CLAIMS_RETURNED_NOTICE_CONTENT', 'OLEAC1005', '1', 'CONFG', 'Claims returned has been received. Staff will begin searching for item', 'Claims Returned Notice Body', 'A', 'KUALI')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'CLAIMS_RETURNED_FOUND_NO_FEES_NOTICE_TITLE', 'OLEAC1006', '1', 'CONFG', 'CLAIMS RETURNED FOUND NO FEES NOTICE', 'Claims Returned Found - no fees Notice', 'A', 'KUALI')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'CLAIMS_RETURNED_FOUND_NO_FEES_NOTICE_CONTENT', 'OLEAC1007', '1', 'CONFG', 'Claimed Item has been found. Item will NOT be billed to the patron’s account', 'Claims Returned Found - no fees', 'A', 'KUALI')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'CLAIMS_RETURNED_FOUND_FINES_OWED_NOTICE_TITLE', 'OLEAC1008', '1', 'CONFG', 'CLAIMS RETURNED FOUND FINES OWED NOTICE', 'Claims Returned Found - fines owed Notice', 'A', 'KUALI')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'CLAIMS_RETURNED_FOUND_FINES_OWED_NOTICE_CONTENT', 'OLEAC1009', '1', 'CONFG', 'Claimed Item has been found. Item will be billed to the patron’s account', 'Claims Returned Found - fines owed', 'A', 'KUALI')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'CR_ITEM_SEARCH_COUNT_BEFORE_ITEM_BILLED', 'OLEAC1010', '1', 'CONFG', '3', 'This parameter value is used to identify the max search count before item billed', 'A', 'KUALI')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'CLAIMS_RETURNED_NOT_FOUND_FINES_OWED_NOTICE_TITLE', 'OLEAC1011', '1', 'CONFG', 'CLAIMS RETURNED NOT FOUND FINES OWED NOTICE', 'Claims Returned Not Found - fines owed Notice', 'A', 'KUALI')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'CLAIMS_RETURNED_NOT_FOUND_FINES_OWED_NOTICE_CONTENT', 'OLEAC1012', '1', 'CONFG', 'Claimed Item has not been found. Item will be billed to the patron’s account', 'Claims Returned Not Found - fines owed', 'A', 'KUALI')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'CLAIMS_RETURNED_NOT_FOUND_NOTICE_TITLE', 'OLEAC1013', '1', 'CONFG', 'CLAIMS RETURNED NOT FOUND NOTICE', 'Claims Returned Not Found', 'A', 'KUALI')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'CLAIMS_RETURNED_NOT_FOUND_NOTICE_CONTENT', 'OLEAC1014', '1', 'CONFG', 'Claimed Item has not been found. Staff will continue searching', 'Claims Returned Not Found', 'A', 'KUALI')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'CLAIMS_RETURNED_NOT_FOUND_NO_FEES_NOTICE_TITLE', 'OLEAC1015', '1', 'CONFG', 'CLAIMS RETURNED NOT FOUND NO FEES NOTICE', 'Claims Returned Not Found - no fees Notice', 'A', 'KUALI')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'CLAIMS_RETURNED_NOT_FOUND_NO_FEES_NOTICE_CONTENT', 'OLEAC1016', '1', 'CONFG', 'Claimed Item has not been found. Item will NOT be billed to the patron’s account', 'Claims Returned Not Found - no fees', 'A', 'KUALI')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'FORGIVE_LOST_FEES', 'OLEAC1017', '1', 'CONFG', 'REPL_FEE,LOST_ITEM_PRCS_FEE', 'Allows the specified fees to be forgiven while renew/return an lost item.', 'A', 'OLE')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-SELECT', 'E-Resource', 'AGREEMENT_AUTH_USERS', 'OLEER1001', '1', 'CONFG', 'Students,Faculty,Staff,Affiliates,Walk-ins,Retired Staff,Alumni', 'This parameter value is used to get Authorized user for Agreement.', 'A', 'OLE')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-SYS', 'Batch', 'FUND_RECORD_CSV_NAME', '150', '1', 'CONFG', 'FundCode', 'The Name of the csv file ingested for Fund record import document name should ends with the value specified in this parameter', 'A', 'OLE')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-SYS', 'Batch', 'FUND_ACCOUNTING_LINE_RECORD_CSV_NAME', '151', '1', 'CONFG', 'FundCodeAccountingLines', 'The Name of the csv file ingested for FundCode Accounting Lines record import document name should ends with the value specified in this parameter', 'A', 'OLE')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'DELETE_LOAN_NOTICE_HISTORY_TO_DATE', 'OLE1616750', '1', 'CONFG', '01/01/2015', 'Date used by batch job to delete Loan Notice History Record upto the date provided. Use "mm/dd/yyyy" format.', 'A', 'KUALI')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'DELETE_RENEWAL_HISTORY_TO_DATE', 'OLE1616751', '1', 'CONFG', '08/01/2015', 'Date used by batch job to delete Renewal History Record upto the date provided. Use "mm/dd/yyyy" format.', 'A', 'KUALI')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'DELETE_REQUEST_HISTORY_TO_DATE', 'OLE1616752', '1', 'CONFG', '06/01/2015', 'Date used by batch job to delete Request History Record upto the date provided. Use "mm/dd/yyyy" format.', 'A', 'KUALI')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'DELETE_RETURN_HISTORY_TO_DATE', 'OLE1616753', '1', 'CONFG', '06/01/2015', 'Date used by batch job to delete Return History Record upto the date provided. Use "mm/dd/yyyy" format.', 'A', 'KUALI')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DESC', 'Describe', 'SHOW_LOCAL_DATA_MAPPING_SECTION', 'OLE7063', '1', 'CONFG', 'N', 'This parameter value is used for holding value to decide whether need to do show local data mapping section or not in batch process profile screen', 'A', 'OLE')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'ONHOLD_COURTESY_TITLE', 'OLE102112', '1', 'CONFG', 'ONHOLD COURTEST NOTICE', 'Onhold Courtesy Notice', 'A', 'KUALI')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'ONHOLD_COURTESY_NOTICE_CONTENT', 'OLE6550211', '1', 'CONFG', 'Content for Hold Courtest Notice', 'Onhold Courtesy Notice Body', 'A', 'OLE')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'ONHOLD_COURTESY_NOTICE_INTERVAL', 'OLE6550212', '1', 'CONFG', '2', 'Intervals for hold courtesy notice', 'A', 'OLE')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'WHILE_CLAIMS_RETURN_SHOW_CANCEL_REQUEST_POPUP', 'OLE98776566', '1', 'CONFG', 'false', 'This parameter is used to configure popup for cancel request while item claimed', 'A', 'OLE')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'PATRON_NOTE_TYPES_TO_DISPLAY', 'OLE98776567', '1', 'CONFG', 'USER;', 'This parameter is used to configure Patron notes be displayed in Loan and Patron screens based on Patron Note type', 'A', 'OLE')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'OLE_ITEM_STATUS_WITH_SIP_CIRC_STATUS', 'OLE112012', '1', 'CONFG', 'ANAL:01,INTRANSIT:10,INTRANSIT-FOR-HOLD:10,INTRANSIT-PER-STAFF-REQUEST:10,LOANED:04,LOST:12,MISSING:13,MISSING-FROM-MANSUETO:13,ONHOLD:08,ONORDER:02,RECENTLY-RETURNED:01,AVAILABLE:03,RETRIEVING-FROM-MANSUETO:01,RETURNED-DAMAGED:01,RETURNED-WITH-MISSING-ITEMS:01,UNAVAILABLE:01,FLAGGED-FOR-RESERVE:01,DECLARED-LOST:12,WITHDRAWN:01,AVAILABLE-AT-MANSUETO:03,INPROCESS:06,INPROCESS-CRERAR:06,INPROCESS-LAW:06,INPROCESS-MANSUETO:06,INPROCESS-REGENSTEIN:06', 'This parameter used to map the OLE item status with Sip Circulation status', 'A', 'OLE')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-SELECT', 'Select', 'ALLOW_INVOICE_SUFF_FUND_CHECK', 'OLE7100', '1', 'CONFG', 'N', 'The Parameter value set to decide whether Sufficient Fund Checking to be done in Invoice Screen', 'A', 'OLE')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-SELECT', 'Select', 'GOBI_API_USER', 'GOBIAPI123', '1', 'CONFG', 'gobiapi', 'This parameter is used for Gobi api. Please update the principal Id of the Gobi api user', 'A', 'OLE')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'SEND_CHECKOUT_RECEIPT_NOTICE', 'OLE100125', '1', 'CONFG', 'true', 'This parameter value is used for configuring the system to send checkout receipt notice at end of session.', 'A', 'KUALI')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'LOST_PROCESSING_FEE', 'OLE23659874', '1', 'CONFG', '150', 'This Paramater is used to configure processing fee for Lost Replcement copy', 'A', 'OLE')
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'LOST_ITEM_FEE', 'OLE-9200', '1', 'CONFG', 'Lost Item Fee', 'This Parameter is used to get the name of Replacement Fee Type', 'A', 'KUALI')
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_LOAD_KRCR_PARM_T_oracle', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 10, '7:268996a77f05fbcdcf9a3d46275a211d', 'loadData', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_DS_ITEM_T_ADD::ole
ALTER TABLE OLE_DS_ITEM_T ADD VOLUME_NUMBER VARCHAR2(100)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DS_ITEM_T_ADD', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 11, '7:657a752c1a6e90c5459a0b41601e45e3', 'addColumn', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_DLVR_PTRN_BILL_T_ADD_COLUMN::ole
ALTER TABLE OLE_DLVR_PTRN_BILL_T ADD MANUAL_BILL VARCHAR2(1)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_PTRN_BILL_T_ADD_COLUMN', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 12, '7:82fc4155ca39723e00087553b1a87131', 'addColumn', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_DLVR_PTRN_BILL_FEE_TYP_T_ADD_COLUMN::ole
ALTER TABLE OLE_DLVR_PTRN_BILL_FEE_TYP_T ADD MANUAL_BILL VARCHAR2(1)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_PTRN_BILL_FEE_TYP_T_ADD_COLUMN', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 13, '7:d12a93136d3dc7a29c84a9f6e1091072', 'addColumn', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_DLVR_PTRN_BILL_T_DEFAULTVAL::ole
ALTER TABLE OLE_DLVR_PTRN_BILL_T MODIFY MANUAL_BILL DEFAULT 'N'
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_PTRN_BILL_T_DEFAULTVAL', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 14, '7:99c665e531796b7aae20b3fde6361359', 'addDefaultValue', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_DLVR_PTRN_BILL_FEE_TYP_T_DEFAULTVAL::ole
ALTER TABLE OLE_DLVR_PTRN_BILL_FEE_TYP_T MODIFY MANUAL_BILL DEFAULT 'N'
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_PTRN_BILL_FEE_TYP_T_DEFAULTVAL', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 15, '7:2f6930210af495b6e029ab755731cebf', 'addDefaultValue', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_LOCN_T_ROW_IND::ole
ALTER TABLE OLE_LOCN_T ADD ROW_ACT_IND VARCHAR2(1) DEFAULT 'Y'
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_LOCN_T_ROW_IND', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 16, '7:3fbe9ab8e0bbcf7997b5c0d28b158f76', 'addColumn', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_PTRN_PAY_STA_T_ORACLE::ole
INSERT INTO OLE_PTRN_PAY_STA_T (PAY_STA_ID, PAY_STA_CODE, PAY_STA_NAME, OBJ_ID, VER_NBR) VALUES (OLE_PTRN_PAY_STA_S.NEXTVAL, 'PAY_SUSPENDED', 'Suspended', '9j889f30-96nw-5d7j-8d89-7j17cf97520', '1')
/

INSERT INTO OLE_PTRN_PAY_STA_T (PAY_STA_ID, PAY_STA_CODE, PAY_STA_NAME, OBJ_ID, VER_NBR) VALUES (OLE_PTRN_PAY_STA_S.NEXTVAL, 'PAY_REPLACED', 'Replaced', '9j889f30-1234-5d7j-8d89-7j17cf97520', '1')
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_PTRN_PAY_STA_T_ORACLE', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 17, '7:c63bc50e4d13ac07b27de10192e855aa', 'sql (x2)', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_DLVR_ITEM_AVAIL_STAT_T_ORACLE::ole
INSERT INTO OLE_DLVR_ITEM_AVAIL_STAT_T (ITEM_AVAIL_STAT_ID, ITEM_AVAIL_STAT_CD, ITEM_AVAIL_STAT_NM, OBJ_ID, VER_NBR) VALUES (OLE_DLVR_ITEM_AVAIL_STAT_S.NEXTVAL, 'MISSING', 'MISSING', '1abf3de3-2221-4249-a829-2c386ee9f515', '1')
/

INSERT INTO OLE_DLVR_ITEM_AVAIL_STAT_T (ITEM_AVAIL_STAT_ID, ITEM_AVAIL_STAT_CD, ITEM_AVAIL_STAT_NM, OBJ_ID, VER_NBR) VALUES (OLE_DLVR_ITEM_AVAIL_STAT_S.NEXTVAL, 'LOST-AND-PAID', 'Lost and Paid', '1abf3de3-2222-4249-a829-2c386ee9f515', '1')
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_ITEM_AVAIL_STAT_T_ORACLE', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 18, '7:aa7b8c6e47cae332211acae4c19ca47e', 'sql (x2)', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_DLVR_LOAN_T_ADD::ole
ALTER TABLE OLE_DLVR_LOAN_T ADD NUM_CLAIMS_RTRN_NOTICES_SENT NUMBER(10)
/

ALTER TABLE OLE_DLVR_LOAN_T ADD CLAIMS_SEARCH_COUNT NUMBER(10)
/

ALTER TABLE OLE_DLVR_LOAN_T ADD LAST_CLAIMS_RTRN_SEARCH_DT TIMESTAMP
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_LOAN_T_ADD', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 19, '7:8dfecb25130e4189e51807926eaff83d', 'addColumn', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::ALTER_FIELD_SIZE_ORACLE::ole
ALTER TABLE OLE_DLVR_LOAN_NOTICE_T MODIFY NTC_TYP varchar2(100)
/

ALTER TABLE OLE_DLVR_LOAN_NOTICE_HSTRY_T MODIFY NTC_TYP varchar2(100)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('ALTER_FIELD_SIZE_ORACLE', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 20, '7:ab0bfc6e56d8e5fb0525e22c3e22de00', 'sql (x2)', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_DLVR_PTRN_BILL_FEE_TYP_T_RNWL_DT_TIME::ole
ALTER TABLE OLE_DLVR_PTRN_BILL_FEE_TYP_T ADD RNWL_DT_TIME TIMESTAMP
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_PTRN_BILL_FEE_TYP_T_RNWL_DT_TIME', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 21, '7:b64c48dc58f9a984f80081c06826e79a', 'addColumn', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_DLVR_LOAN_NOTICE_T_LOST_ITM_PRCS_FEE_AMNT::ole
ALTER TABLE OLE_DLVR_LOAN_NOTICE_T ADD LOST_ITM_PRCS_FEE_AMNT DECIMAL(8)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_LOAN_NOTICE_T_LOST_ITM_PRCS_FEE_AMNT', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 22, '7:e82077bef114906371dd1cb8f5a61d15', 'addColumn', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_DLVR_PTRN_FEE_TYPE_T_ORACLE::ole
INSERT INTO OLE_DLVR_PTRN_FEE_TYPE_T (FEE_TYP_ID, FEE_TYP_CD, FEE_TYP_NM, OBJ_ID, VER_NBR) VALUES (OLE_DLVR_PTRN_FEE_TYPE_S.NEXTVAL, 'LOST_ITEM_PRCS_FEE', 'Lost Item Processing Fee', '0cc1a894-d34e-4ec2-8479-9adf974fd72H', '1')
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_PTRN_FEE_TYPE_T_ORACLE', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 23, '7:2cfad04ddbd2f957b7cdd1f9788e517e', 'sql', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_BAT_PRCS_PRF_T_ORACLE::ole
INSERT INTO OLE_BAT_PRCS_PRF_T (BAT_PRCS_BIB_OVRL_ADD,BAT_PRCS_BIB_NO_MTCH,BAT_PRCS_INST_OVRL_ADD,BAT_PRCS_INST_NO_MTCH,BAT_PRCS_PRF_DESC,BAT_PRCS_PRF_ID,BAT_PRCS_PRF_NM,OBJ_ID,BAT_PRCS_MARC_ONLY,OLE_BAT_PRCS_TYP,VER_NBR) VALUES ('add','add','keepOldAddNew','add','Default EDI Export Format',OLE_BAT_PRCS_PRF_S.NEXTVAL,'Default_EDI_Format','f6f342ca-d6b6-435f-adea-a6bbc10cey','N','EDI Export',1)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_BAT_PRCS_PRF_T_ORACLE', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 24, '7:e324b6c197714af2b2d69f116c2c9e5b', 'sql', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_BAT_PRCS_PRFLE_CNST_T_oracle::ole
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID, ATT_NM, ATT_VAL, DATA_TYPE, BAT_PRCS_PRF_ID, DEF_VAL, OBJ_ID, VER_NBR) VALUES ('OLE3032', 'Default Segment', 'UNA:+.? ''', 'EDIExport', '22', 'default', 'obj31', '1')
/

INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID, ATT_NM, ATT_VAL, DATA_TYPE, BAT_PRCS_PRF_ID, DEF_VAL, OBJ_ID, VER_NBR) VALUES ('OLE3033', 'Interchange Details', 'UNB+UNOC:3+*:ZZ+*:ZZ+*+*''', 'EDIExport', '22', 'default', 'obj32', '1')
/

INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID, ATT_NM, ATT_VAL, DATA_TYPE, BAT_PRCS_PRF_ID, DEF_VAL, OBJ_ID, VER_NBR) VALUES ('OLE3034', 'Unique Ref Number', 'UNH+*+ORDERS:D:96A:UN:EAN008''', 'EDIExport', '22', 'default', 'obj33', '1')
/

INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID, ATT_NM, ATT_VAL, DATA_TYPE, BAT_PRCS_PRF_ID, DEF_VAL, OBJ_ID, VER_NBR) VALUES ('OLE3035', 'Purap Document Identifier', 'BGM+220+*+9''', 'EDIExport', '22', 'default', 'obj34', '1')
/

INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID, ATT_NM, ATT_VAL, DATA_TYPE, BAT_PRCS_PRF_ID, DEF_VAL, OBJ_ID, VER_NBR) VALUES ('OLE3036', 'Order Date', 'DTM+137:*:102''', 'EDIExport', '22', 'default', 'obj35', '1')
/

INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID, ATT_NM, ATT_VAL, DATA_TYPE, BAT_PRCS_PRF_ID, DEF_VAL, OBJ_ID, VER_NBR) VALUES ('OLE3037', 'Vendor Username', 'NAD+BY+*::31B''', 'EDIExport', '22', 'default', 'obj36', '1')
/

INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID, ATT_NM, ATT_VAL, DATA_TYPE, BAT_PRCS_PRF_ID, DEF_VAL, OBJ_ID, VER_NBR) VALUES ('OLE3038', 'Vendor SAN', 'NAD+SU+*::31B''', 'EDIExport', '22', 'default', 'obj37', '1')
/

INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID, ATT_NM, ATT_VAL, DATA_TYPE, BAT_PRCS_PRF_ID, DEF_VAL, OBJ_ID, VER_NBR) VALUES ('OLE3039', 'Currency Code', 'CUX+2:GBP:9''', 'EDIExport', '22', 'default', 'obj38', '1')
/

INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID, ATT_NM, ATT_VAL, DATA_TYPE, BAT_PRCS_PRF_ID, DEF_VAL, OBJ_ID, VER_NBR) VALUES ('OLE3040', 'Line Item', 'LIN+1++*:EN''', 'EDIExport', '22', 'default', 'obj39', '1')
/

INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID, ATT_NM, ATT_VAL, DATA_TYPE, BAT_PRCS_PRF_ID, DEF_VAL, OBJ_ID, VER_NBR) VALUES ('OLE3041', 'Purchase Line Item', 'PIA+5+*:IB''', 'EDIExport', '22', 'default', 'obj40', '1')
/

INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID, ATT_NM, ATT_VAL, DATA_TYPE, BAT_PRCS_PRF_ID, DEF_VAL, OBJ_ID, VER_NBR) VALUES ('OLE3042', 'Item Price', 'PRI+AAA:*''', 'EDIExport', '22', 'default', 'obj41', '1')
/

INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID, ATT_NM, ATT_VAL, DATA_TYPE, BAT_PRCS_PRF_ID, DEF_VAL, OBJ_ID, VER_NBR) VALUES ('OLE3043', 'Item Author', 'IMD+F+BAU+:::*''', 'EDIExport', '22', 'default', 'obj42', '1')
/

INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID, ATT_NM, ATT_VAL, DATA_TYPE, BAT_PRCS_PRF_ID, DEF_VAL, OBJ_ID, VER_NBR) VALUES ('OLE3044', 'Item Title', 'IMD+F+BTI+:::*''', 'EDIExport', '22', 'default', 'obj43', '1')
/

INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID, ATT_NM, ATT_VAL, DATA_TYPE, BAT_PRCS_PRF_ID, DEF_VAL, OBJ_ID, VER_NBR) VALUES ('OLE3045', 'Item Publisher', 'IMD+F+BPU+:::*''', 'EDIExport', '22', 'default', 'obj44', '1')
/

INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID, ATT_NM, ATT_VAL, DATA_TYPE, BAT_PRCS_PRF_ID, DEF_VAL, OBJ_ID, VER_NBR) VALUES ('OLE3046', 'Item Publisher Date', 'IMD+F+BPD+:::*''', 'EDIExport', '22', 'default', 'obj45', '1')
/

INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID, ATT_NM, ATT_VAL, DATA_TYPE, BAT_PRCS_PRF_ID, DEF_VAL, OBJ_ID, VER_NBR) VALUES ('OLE3047', 'Item Quantity', 'QTY+21:*''', 'EDIExport', '22', 'default', 'obj46', '1')
/

INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID, ATT_NM, ATT_VAL, DATA_TYPE, BAT_PRCS_PRF_ID, DEF_VAL, OBJ_ID, VER_NBR) VALUES ('OLE3048', 'Reference Qualifier 1', 'RFF+BFN:*''', 'EDIExport', '22', 'default', 'obj47', '1')
/

INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID, ATT_NM, ATT_VAL, DATA_TYPE, BAT_PRCS_PRF_ID, DEF_VAL, OBJ_ID, VER_NBR) VALUES ('OLE3049', 'Reference Qualifier 2', 'RFF+LI:*''', 'EDIExport', '22', 'default', 'obj48', '1')
/

INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID, ATT_NM, ATT_VAL, DATA_TYPE, BAT_PRCS_PRF_ID, DEF_VAL, OBJ_ID, VER_NBR) VALUES ('OLE3050', 'Item Location', 'LOC+7+*::92''', 'EDIExport', '22', 'default', 'obj49', '1')
/

INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID, ATT_NM, ATT_VAL, DATA_TYPE, BAT_PRCS_PRF_ID, DEF_VAL, OBJ_ID, VER_NBR) VALUES ('OLE3051', 'Delivery Address', 'NAD+DP+*::31B+*''', 'EDIExport', '22', 'default', 'obj50', '1')
/

INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID, ATT_NM, ATT_VAL, DATA_TYPE, BAT_PRCS_PRF_ID, DEF_VAL, OBJ_ID, VER_NBR) VALUES ('OLE3052', 'Other Address', 'NAD+OB+*::31B+*''', 'EDIExport', '22', 'default', 'obj51', '1')
/

INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID, ATT_NM, ATT_VAL, DATA_TYPE, BAT_PRCS_PRF_ID, DEF_VAL, OBJ_ID, VER_NBR) VALUES ('OLE3053', 'Section Identification', 'UNS+S''', 'EDIExport', '22', 'default', 'obj52', '1')
/

INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID, ATT_NM, ATT_VAL, DATA_TYPE, BAT_PRCS_PRF_ID, DEF_VAL, OBJ_ID, VER_NBR) VALUES ('OLE3054', 'Control Qualifier 1', 'CNT+1:*''', 'EDIExport', '22', 'default', 'obj53', '1')
/

INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID, ATT_NM, ATT_VAL, DATA_TYPE, BAT_PRCS_PRF_ID, DEF_VAL, OBJ_ID, VER_NBR) VALUES ('OLE3055', 'Control Qualifier 2', 'CNT+2:*''', 'EDIExport', '22', 'default', 'obj54', '1')
/

INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID, ATT_NM, ATT_VAL, DATA_TYPE, BAT_PRCS_PRF_ID, DEF_VAL, OBJ_ID, VER_NBR) VALUES ('OLE3056', 'Note', 'FTX+LIN++::+*''', 'EDIExport', '22', 'default', 'obj55', '1')
/

INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID, ATT_NM, ATT_VAL, DATA_TYPE, BAT_PRCS_PRF_ID, DEF_VAL, OBJ_ID, VER_NBR) VALUES ('OLE3057', 'Number of Segments', 'UNT+*+*''', 'EDIExport', '22', 'default', 'obj56', '1')
/

INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID, ATT_NM, ATT_VAL, DATA_TYPE, BAT_PRCS_PRF_ID, DEF_VAL, OBJ_ID, VER_NBR) VALUES ('OLE3058', 'Interchange Control count', 'UNZ+1+*''', 'EDIExport', '22', 'default', 'obj57', '1')
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_BAT_PRCS_PRFLE_CNST_T_oracle', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 25, '7:0301bc6139255ee915826e78dc08a978', 'loadData', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::LAST_UPDATE_COLUMN_ADD::ole
ALTER TABLE OLE_DS_BIB_INFO_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_DS_BIB_HOLDINGS_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_DS_ITEM_HOLDINGS_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_CAT_SHVLG_SCHM_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_CAT_RCPT_STAT_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_DS_HOLDINGS_URI_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_DS_EXT_OWNERSHIP_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_CAT_TYPE_OWNERSHIP_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_DS_EXT_OWNERSHIP_NOTE_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_DS_HOLDINGS_NOTE_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_CAT_STAT_SRCH_CD_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_CAT_ITM_TYP_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_DLVR_ITEM_AVAIL_STAT_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_DS_HIGH_DENSITY_STORAGE_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_DS_ITEM_NOTE_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_DS_ITM_FORMER_IDENTIFIER_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_DS_LOC_CHECKIN_COUNT_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_DS_HOLDINGS_COVERAGE_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_DS_PERPETUAL_ACCESS_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_DS_ACCESS_LOCATION_CODE_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_DS_ACCESS_LOCATION_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_DS_HOLDINGS_STAT_SEARCH_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_DS_ITEM_STAT_SEARCH_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_DS_AUTHENTICATION_TYPE_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_DS_ITEM_DONOR_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_DS_HOLDINGS_DONOR_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_DS_DOC_TYPE_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_DS_DOC_FORMAT_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_DS_DOC_FIELD_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_DS_SEARCH_RESULT_PAGE_T ADD DATE_UPDATED TIMESTAMP
/

ALTER TABLE OLE_DS_SEARCH_FACET_SIZE_T ADD DATE_UPDATED TIMESTAMP
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('LAST_UPDATE_COLUMN_ADD', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 26, '7:47504cd85e337acd70ece26f923e6a74', 'addColumn (x31)', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::LAST_UPDATE_TRIGGER_ORACLE::ole
CREATE OR REPLACE TRIGGER BIB_INFO_TR_INSERT BEFORE INSERT ON OLE_DS_BIB_INFO_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER BIB_INFO_TR_UPDATE BEFORE UPDATE ON OLE_DS_BIB_INFO_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER BIB_HLD_TR_INSERT BEFORE INSERT ON OLE_DS_BIB_HOLDINGS_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER BIB_HLD_TR_UPDATE BEFORE UPDATE ON OLE_DS_BIB_HOLDINGS_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER ITM_HLD_TR_INSERT BEFORE INSERT ON OLE_DS_ITEM_HOLDINGS_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER ITM_HLD_TR_UPDATE BEFORE UPDATE ON OLE_DS_ITEM_HOLDINGS_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER SHVLG_SCHM_TR_INSERT BEFORE INSERT ON OLE_CAT_SHVLG_SCHM_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER SHVLG_SCHM_TR_UPDATE BEFORE UPDATE ON OLE_CAT_SHVLG_SCHM_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER RCPT_STAT_TR_INSERT BEFORE INSERT ON OLE_CAT_RCPT_STAT_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER RCPT_STAT_TR_UPDATE BEFORE UPDATE ON OLE_CAT_RCPT_STAT_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER HLD_URI_TR_INSERT BEFORE INSERT ON OLE_DS_HOLDINGS_URI_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER HLD_URI_TR_UPDATE BEFORE UPDATE ON OLE_DS_HOLDINGS_URI_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER EXT_OWNR_TR_INSERT BEFORE INSERT ON OLE_DS_EXT_OWNERSHIP_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER EXT_OWNR_TR_UPDATE BEFORE UPDATE ON OLE_DS_EXT_OWNERSHIP_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER TYP_OWNR_TR_INSERT BEFORE INSERT ON OLE_CAT_TYPE_OWNERSHIP_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER TYP_OWNR_TR_UPDATE BEFORE UPDATE ON OLE_CAT_TYPE_OWNERSHIP_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER EXT_OWNR_NOTE_TR_INSERT BEFORE INSERT ON OLE_DS_EXT_OWNERSHIP_NOTE_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER EXT_OWNR_NOTE_TR_UPDATE BEFORE UPDATE ON OLE_DS_EXT_OWNERSHIP_NOTE_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER HLD_NOTE_TR_INSERT BEFORE INSERT ON OLE_DS_HOLDINGS_NOTE_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER HLD_NOTE_TR_UPDATE BEFORE UPDATE ON OLE_DS_HOLDINGS_NOTE_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER STAT_SRCH_CD_TR_INSERT BEFORE INSERT ON OLE_CAT_STAT_SRCH_CD_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER STAT_SRCH_CD_TR_UPDATE BEFORE UPDATE ON OLE_CAT_STAT_SRCH_CD_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER ITM_TYP_TR_INSERT BEFORE INSERT ON OLE_CAT_ITM_TYP_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER ITM_TYP_TR_UPDATE BEFORE UPDATE ON OLE_CAT_ITM_TYP_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER ITEM_AVAIL_STAT_TR_INSERT BEFORE INSERT ON OLE_DLVR_ITEM_AVAIL_STAT_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER ITEM_AVAIL_STAT_TR_UPDATE BEFORE UPDATE ON OLE_DLVR_ITEM_AVAIL_STAT_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER HIGH_DEN_STRG_TR_INSERT BEFORE INSERT ON OLE_DS_HIGH_DENSITY_STORAGE_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER HIGH_DEN_STRG_TR_UPDATE BEFORE UPDATE ON OLE_DS_HIGH_DENSITY_STORAGE_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER ITEM_NOTE_TR_INSERT BEFORE INSERT ON OLE_DS_ITEM_NOTE_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER ITEM_NOTE_TR_UPDATE BEFORE UPDATE ON OLE_DS_ITEM_NOTE_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER ITM_FRMR_ID_TR_INSERT BEFORE INSERT ON OLE_DS_ITM_FORMER_IDENTIFIER_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER ITM_FRMR_ID_TR_UPDATE BEFORE UPDATE ON OLE_DS_ITM_FORMER_IDENTIFIER_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER LOC_CHKIN_CNT_TR_INSERT BEFORE INSERT ON OLE_DS_LOC_CHECKIN_COUNT_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER LOC_CHKIN_CNT_TR_UPDATE BEFORE UPDATE ON OLE_DS_LOC_CHECKIN_COUNT_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER HLD_COVERAGE_TR_INSERT BEFORE INSERT ON OLE_DS_HOLDINGS_COVERAGE_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER HLD_COVERAGE_TR_UPDATE BEFORE UPDATE ON OLE_DS_HOLDINGS_COVERAGE_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER PERPETUAL_ACCESS_TR_INSERT BEFORE INSERT ON OLE_DS_PERPETUAL_ACCESS_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER PERPETUAL_ACCESS_TR_UPDATE BEFORE UPDATE ON OLE_DS_PERPETUAL_ACCESS_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER ACS_LOCN_CODE_TR_INSERT BEFORE INSERT ON OLE_DS_ACCESS_LOCATION_CODE_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER ACS_LOCN_CODE_TR_UPDATE BEFORE UPDATE ON OLE_DS_ACCESS_LOCATION_CODE_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER ACS_LOCN_TR_INSERT BEFORE INSERT ON OLE_DS_ACCESS_LOCATION_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER ACS_LOCN_TR_UPDATE BEFORE UPDATE ON OLE_DS_ACCESS_LOCATION_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER HLD_STAT_SEARCH_TR_INSERT BEFORE INSERT ON OLE_DS_HOLDINGS_STAT_SEARCH_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER HLD_STAT_SEARCH_TR_UPDATE BEFORE UPDATE ON OLE_DS_HOLDINGS_STAT_SEARCH_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER ITEM_STAT_SEARCH_TR_INSERT BEFORE INSERT ON OLE_DS_ITEM_STAT_SEARCH_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER ITEM_STAT_SEARCH_TR_UPDATE BEFORE UPDATE ON OLE_DS_ITEM_STAT_SEARCH_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER AUTH_TYPE_TR_INSERT BEFORE INSERT ON OLE_DS_AUTHENTICATION_TYPE_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER AUTH_TYPE_TR_UPDATE BEFORE UPDATE ON OLE_DS_AUTHENTICATION_TYPE_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER ITEM_DONOR_TR_INSERT BEFORE INSERT ON OLE_DS_ITEM_DONOR_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER ITEM_DONOR_TR_UPDATE BEFORE UPDATE ON OLE_DS_ITEM_DONOR_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER HLD_DONOR_TR_INSERT BEFORE INSERT ON OLE_DS_HOLDINGS_DONOR_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER HLD_DONOR_TR_UPDATE BEFORE UPDATE ON OLE_DS_HOLDINGS_DONOR_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER DOC_TYPE_TR_INSERT BEFORE INSERT ON OLE_DS_DOC_TYPE_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER DOC_TYPE_TR_UPDATE BEFORE UPDATE ON OLE_DS_DOC_TYPE_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER DOC_FORMAT_TR_INSERT BEFORE INSERT ON OLE_DS_DOC_FORMAT_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER DOC_FORMAT_TR_UPDATE BEFORE UPDATE ON OLE_DS_DOC_FORMAT_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER DOC_FIELD_TR_INSERT BEFORE INSERT ON OLE_DS_DOC_FIELD_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER DOC_FIELD_TR_UPDATE BEFORE UPDATE ON OLE_DS_DOC_FIELD_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER SRCH_RESULT_PAGE_TR_INSERT BEFORE INSERT ON OLE_DS_SEARCH_RESULT_PAGE_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER SRCH_RESULT_PAGE_TR_UPDATE BEFORE UPDATE ON OLE_DS_SEARCH_RESULT_PAGE_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER SRCH_FACET_SIZE_TR_INSERT BEFORE INSERT ON OLE_DS_SEARCH_FACET_SIZE_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

CREATE OR REPLACE TRIGGER SRCH_FACET_SIZE_TR_UPDATE BEFORE UPDATE ON OLE_DS_SEARCH_FACET_SIZE_T FOR EACH ROW  BEGIN :new.DATE_UPDATED := sysdate; END; --
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('LAST_UPDATE_TRIGGER_ORACLE', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 27, '7:179ac729f23282d798db8cfbc59002d1', 'sql (x62)', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_BAT_PRCS_TYP_T_ORACLE::ole
INSERT INTO OLE_BAT_PRCS_TYP_T (OLE_BAT_PRCS_TYP_ID,OLE_BAT_PRCS_TYP_CODE,OLE_BAT_PRCS_TYP_NM,ACTIVE_IND,OBJ_ID,VER_NBR) VALUES(OLE_BAT_PRCS_TYP_S.NEXTVAL,'edi_exp','EDI Export','Y','13','1')
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_BAT_PRCS_TYP_T_ORACLE', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 28, '7:d863148ff2449d5d04e4cb59b9003add', 'sql', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_DS_HOLDINGS_T_MODIFY::ole
ALTER TABLE OLE_DS_HOLDINGS_T MODIFY MATERIALS_SPECIFIED VARCHAR(200) NULL
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DS_HOLDINGS_T_MODIFY', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 29, '7:afb9e39dbe5e8b9bc61b2fc1ac864eb7', 'sql', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_AGREEMENT_T::ole
CREATE TABLE OLE_AGREEMENT_T (AGR_ID VARCHAR2(40) NOT NULL, AGR_LICENCE_TITLE VARCHAR2(250), AGR_CONTRACT_NBR VARCHAR2(20), PO_ID NUMBER(10), AGR_STATUS_ID VARCHAR2(40), AGR_CODINGD_STATUS_ID VARCHAR2(40), AGR_LICENSOR_ID VARCHAR2(40), AGR_LICENSEE_ID VARCHAR2(40), AGR_GENERAL_NTE VARCHAR2(250), AGR_LICENSE_SITE VARCHAR2(250), AGR_FEE_SCHDLE VARCHAR2(250), AGR_INFLATION_CAP VARCHAR2(250), AGR_PAYMENT_TERM VARCHAR2(250), AGR_GOVRNING_LAW VARCHAR2(250), AGR_NEW_TITLE_ACCESS VARCHAR2(250), AGR_CANCELLATION_RIGHTS VARCHAR2(250), AGR_ADDITIONAL_TERM VARCHAR2(250), AGR_NTC_PER_FOR_TERMN VARCHAR2(250), AGR_PERP_ACCESS VARCHAR2(1), AGR_PERP_ACC_NTE VARCHAR2(250), AGR_AUTH_USRS VARCHAR2(250), AGR_AUTH_USRS_GEN_NTE VARCHAR2(250), AGR_DEP_IN_JR VARCHAR2(1), AGR_FAIR_USE VARCHAR2(1), AGR_RTS_NT_GR_DE VARCHAR2(1), AGR_ILL_PR VARCHAR2(1), AGR_ILL_EL VARCHAR2(1), AGR_ILL_LON_DOC_PERM VARCHAR2(1), AGR_ILL_NON_PRFT_ONLY VARCHAR2(1), AGR_ILL_SAM_CNTRY_RES VARCHAR2(1), AGR_ILL_NTE VARCHAR2(250), AGR_LIB_RES_ELEC VARCHAR2(1), AGR_LIB_RES_PRI VARCHAR2(1), AGR_LIB_RES_CMS_NTE VARCHAR2(250), AGR_SCOH_SHA VARCHAR2(1), AGR_TXT_MIN VARCHAR2(1), AGR_PERM_RIGHTS VARCHAR2(1), AGR_STR_RIGHTS VARCHAR2(1), AGR_MUL_RIGHTS_NTE VARCHAR2(250), AGR_APC_OFFST VARCHAR2(1), AGR_APC_OFFST_NTE VARCHAR2(250), AGR_START_DT date, AGR_END_DT date, CONSTRAINT PK_OLE_AGREEMENT_T PRIMARY KEY (AGR_ID))
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_AGREEMENT_T', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 30, '7:d3da38960e1f12c84865c78061826a81', 'createTable', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_AGREEMENT_S_ORACLE::ole
CREATE SEQUENCE OLE_AGREEMENT_S START WITH 1 INCREMENT BY 1 ORDER
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_AGREEMENT_S_ORACLE', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 31, '7:f09683fedf33b507cf5d2a8e9f807761', 'createSequence', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_BAT_PRCS_PRFLE_CNST_S_ALTER1_ORACLE::ole
ALTER SEQUENCE OLE_BAT_PRCS_PRFLE_CNST_S INCREMENT BY 38
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_BAT_PRCS_PRFLE_CNST_S_ALTER1_ORACLE', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 32, '7:bbdcebb5e7f35e43e584a76290d52b18', 'sql', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_BAT_PRCS_PRFLE_CNST_S_ALTER2_ORACLE::ole
SELECT OLE_BAT_PRCS_PRFLE_CNST_S.NEXTVAL FROM DUAL
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_BAT_PRCS_PRFLE_CNST_S_ALTER2_ORACLE', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 33, '7:381a69bb1bb258dde6c9ce62bcc8a55f', 'sql', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_BAT_PRCS_PRFLE_CNST_S_ALTER3_ORACLE::ole
ALTER SEQUENCE OLE_BAT_PRCS_PRFLE_CNST_S INCREMENT BY 1
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_BAT_PRCS_PRFLE_CNST_S_ALTER3_ORACLE', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 34, '7:237955d9d0a863cf4b2b2dd4ac58dd90', 'sql', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_DLVR_BATCH_JOB_T_Insert::ole
INSERT INTO OLE_DLVR_BATCH_JOB_T (JOB_CRON_EXPRSN,JOB_ID,JOB_TRG_NM,OBJ_ID,ROW_ACT_IND,VER_NBR) VALUES ('0 0 3 15 * ?','13','deleteLoanNoticeHistoryJob','13','Y',1)
/

INSERT INTO OLE_DLVR_BATCH_JOB_T (JOB_CRON_EXPRSN,JOB_ID,JOB_TRG_NM,OBJ_ID,ROW_ACT_IND,VER_NBR) VALUES ('0 0 4 15 * ?','14','deleteRenewalHistoryJob','14','Y',1)
/

INSERT INTO OLE_DLVR_BATCH_JOB_T (JOB_CRON_EXPRSN,JOB_ID,JOB_TRG_NM,OBJ_ID,ROW_ACT_IND,VER_NBR) VALUES ('0 0 5 15 * ?','15','deleteRequestHistoryJob','15','Y',1)
/

INSERT INTO OLE_DLVR_BATCH_JOB_T (JOB_CRON_EXPRSN,JOB_ID,JOB_TRG_NM,OBJ_ID,ROW_ACT_IND,VER_NBR) VALUES ('0 0 6 15 * ?','16','deleteReturnHistoryJob','16','Y',1)
/

INSERT INTO OLE_DLVR_BATCH_JOB_T (JOB_CRON_EXPRSN,JOB_ID,JOB_TRG_NM,OBJ_ID,ROW_ACT_IND,VER_NBR) VALUES ('0 0 4 15 * ?','17','generateHoldExpirationNoticeJob','17','N',1)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_BATCH_JOB_T_Insert', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 35, '7:bf277ca32b736c2a5845dc9039c104a6', 'sql (x5)', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_DLVR_BATCH_JOB_T_Update_Oracle::ole
UPDATE OLE_DLVR_BATCH_JOB_T SET ROW_ACT_IND = 'N' WHERE JOB_ID IN ('13','14','15','16')
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_BATCH_JOB_T_Update_Oracle', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 36, '7:32be2338a45facedabac63aee45ed522', 'sql', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_DS_DELETED_BIB_T_ORACLE::ole
CREATE TABLE OLE_DS_DELETED_BIB_T (ID NUMBER(38, 0) NOT NULL, DELETED_BIB_ID VARCHAR2(11), IS_BIB_DELETED VARCHAR2(1), DELETED_HOLDINGS_ID VARCHAR2(11), IS_HOLDINGS_DELETED VARCHAR2(1), DELETED_ITEM_ID VARCHAR2(11), IS_ITEM_DELETED VARCHAR2(1), DATE_UPDATED TIMESTAMP, CONTENT CLOB, CONSTRAINT PK_OLE_DS_DELETED_BIB_T PRIMARY KEY (ID))
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DS_DELETED_BIB_T_ORACLE', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 37, '7:76437b0006e1fab4aa8b83ae406d70fa', 'createTable', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_DS_DELETED_BIB_S_ORACLE::ole
CREATE SEQUENCE OLE_DS_DELETED_BIB_S START WITH 1 INCREMENT BY 1 ORDER
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DS_DELETED_BIB_S_ORACLE', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 38, '7:8d0ada862d61f7b458fb976698bc2bda', 'createSequence', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_KRIM_ROLE_MBR_T_oracle::ole
INSERT INTO KRIM_ROLE_MBR_T (ROLE_MBR_ID, OBJ_ID, ROLE_ID, MBR_ID, MBR_TYP_CD) VALUES ('OLEGOBIAPI1', 'OLEGOBIAPI1', 'OLE10058', 'gobiapi', 'P')
/

INSERT INTO KRIM_ROLE_MBR_T (ROLE_MBR_ID, OBJ_ID, ROLE_ID, MBR_ID, MBR_TYP_CD) VALUES ('OLEGOBIAPI2', 'OLEGOBIAPI2', 'OLE10077', 'gobiapi', 'P')
/

INSERT INTO KRIM_ROLE_MBR_T (ROLE_MBR_ID, OBJ_ID, ROLE_ID, MBR_ID, MBR_TYP_CD) VALUES ('OLEGOBIAPI3', 'OLEGOBIAPI3', 'OLE10085', 'gobiapi', 'P')
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_KRIM_ROLE_MBR_T_oracle', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 39, '7:def0da70381fa7bce2e472a5a4cde3d4', 'loadData', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::KRIM_ENTITY_T_Insert::ole
INSERT INTO krim_entity_t (entity_id, obj_id, actv_ind) VALUES ('gobiapi', 'gobiapi', 'Y')
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('KRIM_ENTITY_T_Insert', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 40, '7:639c4082b588bca06955da8c88a4d117', 'sql', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::KRIM_PRNCPL_T_Insert::ole
INSERT INTO krim_prncpl_t (PRNCPL_ID, OBJ_ID, PRNCPL_NM, ENTITY_ID, ACTV_IND) VALUES ('gobiapi', 'gobiapi', 'gobi-api', 'gobiapi', 'Y')
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('KRIM_PRNCPL_T_Insert', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 41, '7:18992efca2d6cee5ed427f84f5206058', 'sql', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::KRIM_ENTITY_NM_T_Insert::ole
INSERT INTO krim_entity_nm_t (ENTITY_NM_ID, OBJ_ID, ENTITY_ID, NM_TYP_CD, FIRST_NM, MIDDLE_NM, LAST_NM, SUFFIX_NM, TITLE_NM, DFLT_IND, ACTV_IND) VALUES ('gobiapi', 'gobiapi', 'gobiapi', 'PRFR', 'gobi', '', 'api', '', '', 'Y', 'Y')
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('KRIM_ENTITY_NM_T_Insert', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 42, '7:6e50b331eb0be0cf37b398bdfe13161c', 'sql', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::KRIM_ENTITY_ENT_TYP_T_Insert::ole
INSERT INTO krim_entity_ent_typ_t (ent_typ_cd, entity_id, obj_id, actv_ind) VALUES ('PERSON', 'gobiapi', 'gobiapi', 'Y')
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('KRIM_ENTITY_ENT_TYP_T_Insert', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 43, '7:16da836ba3ee0e69c7871d735e309b40', 'sql', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/3.0/db.changelog-20160208.xml::OLE_DLVR_PTRN_FEE_TYPE_T_Update_Oracle::ole
UPDATE  OLE_DLVR_PTRN_FEE_TYPE_T SET FEE_TYP_NM = 'Lost Item Fee' WHERE FEE_TYP_ID = '2'
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_PTRN_FEE_TYPE_T_Update_Oracle', 'ole', 'org/kuali/ole/3.0/db.changelog-20160208.xml', SYSTIMESTAMP, 44, '7:769cd221970aaf1f80e7966986e292a5', 'sql', '', 'EXECUTED', '3.2.0')
/

-- Release Database Lock
-- Release Database Lock
