package org.kuali.ole.deliver.checkout

import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.deliver.drools.DroolsConstants


rule "Check out Circ Policy Set ACCESS only"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()

$d: DroolsResponse()
$p: OlePatronDocument(getBorrowerTypeCode() in ("ACCESS"))


then
$d.addErrorMessage("ACCESS only patrons may not check out any items");

 end