package org.kuali.ole.deliver.checkout

import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.deliver.drools.DroolsConstants


rule "Check out Circ Policy Set ASR/MANB"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument();

$p: OlePatronDocument(getBorrowerTypeCode() in ("MANB"))

$i: OleItemRecordForCirc(getItemType() in ("stks","mus","games","stks7","stks14"),
getItemLibraryLocation() in ("ASR"))

then
$l.setCirculationPolicyId("Check out Circ Policy Set ASR/MANB");
$l.loanPeriod("1-D",null); // This method takes due date and recall period as arguments.
 end