package org.kuali.ole.deliver.checkout

import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc


import org.kuali.ole.deliver.util.DroolsResponse


rule "Check out Circ Policy Set ITS CNF"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument();



$p: OlePatronDocument(getBorrowerTypeCode() in ("QCOL","QGRAD","QDEPT","QNONDEG","QSTF","QOTHER",
"QUNLIM_ACD","QUNLIM_PHD","INDEF_FAC","INDEF_ACD","INDEF_DEPT","INDEF_TRU"))

$i: OleItemRecordForCirc(getItemType() in ("its8cnf"),
getItemLibraryLocation() in ("ITS"))

then
$l.setCirculationPolicyId("Check out Circ Policy Set ITS CNF");
$l.loanPeriod("8-H",null); // This method takes due date and recall period as arguments.
 end
