CREATE SEQUENCE OLE_DS_BIB_S
  INCREMENT BY 1
  START WITH 10000001
  MAXVALUE 9999999999999999999999999999
  NOMINVALUE
  NOCYCLE
  CACHE 20
  NOORDER
/

CREATE TABLE OLE_DS_BIB_T (
  BIB_ID INTEGER NOT NULL,
  FORMER_ID VARCHAR2(45) DEFAULT NULL,
  FAST_ADD CHAR(1) DEFAULT NULL,
  STAFF_ONLY CHAR(1) DEFAULT NULL,
  UPDATED_BY VARCHAR2(40),
  CREATED_BY VARCHAR2(40),
  DATE_CREATED TIMESTAMP DEFAULT NULL,
  DATE_ENTERED TIMESTAMP DEFAULT NULL,
  CONTENT CLOB DEFAULT NULL,
  STATUS VARCHAR2(20),
  STATUS_UPDATED_BY VARCHAR2(40),
  STATUS_UPDATED_DATE TIMESTAMP DEFAULT NULL,
  UNIQUE_ID_PREFIX VARCHAR2(10),
  PRIMARY KEY (BIB_ID)
 )
/

CREATE SEQUENCE OLE_DS_CALL_NUMBER_TYPE_S
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  NOMINVALUE
  NOCYCLE
  CACHE 20
  NOORDER
/

CREATE  TABLE OLE_DS_CALL_NUMBER_TYPE_T (
  CALL_NUMBER_TYPE_ID INTEGER NOT NULL ,
  CODE VARCHAR2(100) DEFAULT NULL ,
  NAME VARCHAR2(500) DEFAULT NULL ,
  PRIMARY KEY (CALL_NUMBER_TYPE_ID)
)
/

CREATE SEQUENCE OLE_DS_RECEIPT_STATUS_S
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  NOMINVALUE
  NOCYCLE
  CACHE 20
  NOORDER
/

CREATE  TABLE OLE_DS_RECEIPT_STATUS_T (
  RECEIPT_STATUS_ID INTEGER NOT NULL,
  CODE VARCHAR2(100)  DEFAULT NULL ,
  NAME VARCHAR2(500)  DEFAULT NULL ,
  PRIMARY KEY (RECEIPT_STATUS_ID)
)
/

CREATE SEQUENCE OLE_DS_HOLDINGS_S
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  NOMINVALUE
  NOCYCLE
  CACHE 20
  NOORDER
/


CREATE  TABLE OLE_DS_HOLDINGS_T (
  HOLDINGS_ID INTEGER NOT NULL ,
  HOLDINGS_TYPE VARCHAR2 (10) DEFAULT NULL ,
  BIB_ID INTEGER NOT NULL,
  FORMER_HOLDINGS_ID VARCHAR2(45)  DEFAULT NULL ,
  STAFF_ONLY CHAR(1) DEFAULT NULL ,
  LOCATION VARCHAR2(300)  DEFAULT NULL ,
  LOCATION_LEVEL VARCHAR2(300)  DEFAULT NULL ,
  SOURCE_HOLDINGS_CONTENT CLOB DEFAULT NULL ,
  CALL_NUMBER_PREFIX VARCHAR2(100) DEFAULT NULL ,
  CALL_NUMBER VARCHAR2(300) DEFAULT NULL ,
  SHELVING_ORDER VARCHAR2(300) DEFAULT NULL ,
  CALL_NUMBER_TYPE_ID INTEGER DEFAULT NULL ,
  RECEIPT_STATUS_ID INTEGER DEFAULT NULL ,
  HOLDINGS_STAT_SEARCH_ID INTEGER DEFAULT NULL ,
  HOLDINGS_ACCESS_LOCATION_ID INTEGER DEFAULT NULL ,
  COPY_NUMBER VARCHAR2(20)  DEFAULT NULL ,
  PUBLISHER VARCHAR2(100) DEFAULT NULL ,
  ACC_STATUS VARCHAR2(40) DEFAULT  NULL ,
  PLATFORM VARCHAR2(100)  DEFAULT NULL,
  IMPRINT VARCHAR2(100)  DEFAULT NULL,
  STAT_SRC_CD VARCHAR2(40)  DEFAULT NULL,
  SUB_STATUS VARCHAR2(40)  DEFAULT NULL,
  LOCAL_PERSISTENT_LINK VARCHAR2(400)  DEFAULT NULL,
  ILL_ALLOW CHAR (1) ,
  AUTHENTICATION_TYPE_ID INTEGER  DEFAULT NULL,
  PROXIED_RESOURCE VARCHAR2(10)  DEFAULT NULL,
  NO_SIMULT_USERS VARCHAR2(40)  DEFAULT NULL,
  ACC_LOC VARCHAR2(40)  DEFAULT NULL,
  ACC_USERNM VARCHAR2(40)  DEFAULT NULL,
  ACC_PWD VARCHAR2(100)  DEFAULT NULL,
  STATUS_DATE TIMESTAMP DEFAULT NULL,
  ADMIN_USERNM VARCHAR2(400)  DEFAULT NULL,
  ADMIN_PWD VARCHAR2(400)  DEFAULT NULL,
  ADMIN_URL VARCHAR2(400)  DEFAULT NULL,
  LINK VARCHAR2(400)  DEFAULT NULL,
  LINK_TEXT VARCHAR2(400)  DEFAULT NULL,
  E_RES_ID VARCHAR2(400)  DEFAULT NULL,
  DATE_ENTERED TIMESTAMP DEFAULT NULL ,
  DATE_LAST_UPDATED TIMESTAMP DEFAULT NULL ,
  UPDATED_BY VARCHAR2(40),
  CREATED_BY VARCHAR2(40),
  UNIQUE_ID_PREFIX VARCHAR2(10)  DEFAULT NULL ,
  PRIMARY KEY (HOLDINGS_ID) ,
  CONSTRAINT HOLDINGS_BIB_CONSTRAINT FOREIGN KEY (BIB_ID) REFERENCES OLE_DS_BIB_T (BIB_ID) ,
  CONSTRAINT CALL_NUMBER_TYPE_CONSTRAINT FOREIGN KEY (CALL_NUMBER_TYPE_ID) REFERENCES OLE_DS_CALL_NUMBER_TYPE_T (CALL_NUMBER_TYPE_ID) ,
  CONSTRAINT RECEIPT_CONSTRAINT FOREIGN KEY (RECEIPT_STATUS_ID) REFERENCES OLE_DS_RECEIPT_STATUS_T (RECEIPT_STATUS_ID)
)
/


CREATE SEQUENCE OLE_DS_BIB_HOLDINGS_S
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999999999999999999999999
NOMINVALUE
NOCYCLE
CACHE 20
NOORDER
/

CREATE TABLE  OLE_DS_BIB_HOLDINGS_T (
  BIB_HOLDINGS_ID INTEGER ,
  HOLDINGS_ID INTEGER NOT NULL ,
  BIB_ID INTEGER NOT NULL ,
  PRIMARY KEY (BIB_HOLDINGS_ID) ,
  CONSTRAINT BIB_HOL_BIB_CNSTRT FOREIGN KEY (BIB_ID) REFERENCES OLE_DS_BIB_T (BIB_ID),
  CONSTRAINT BIB_HOLD_HOLD_CNSTRT FOREIGN KEY (HOLDINGS_ID) REFERENCES OLE_DS_HOLDINGS_T (HOLDINGS_ID)
)
/

CREATE SEQUENCE OLE_DS_HOLDINGS_ACCESS_URI_S
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  NOMINVALUE
  NOCYCLE
  CACHE 20
  NOORDER
/

CREATE  TABLE OLE_DS_HOLDINGS_ACCESS_URI_T (
  ACCESS_URI_ID INTEGER NOT NULL ,
  TEXT VARCHAR2(500) DEFAULT NULL ,
  URI VARCHAR2(500) DEFAULT NULL ,
  HOLDINGS_ID INTEGER NOT NULL ,
  PRIMARY KEY (ACCESS_URI_ID),
  CONSTRAINT ACCESS_URI_CONSTRAINT FOREIGN KEY (HOLDINGS_ID) REFERENCES OLE_DS_HOLDINGS_T (HOLDINGS_ID)
)
/

CREATE SEQUENCE OLE_DS_EXT_OWNERSHIP_TYPE_S
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  NOMINVALUE
  NOCYCLE
  CACHE 20
  NOORDER
/

CREATE  TABLE OLE_DS_EXT_OWNERSHIP_TYPE_T (
  EXT_OWNERSHIP_TYPE_ID INTEGER NOT NULL,
  CODE VARCHAR2(100)  DEFAULT NULL ,
  NAME VARCHAR2(500)  DEFAULT NULL ,
  PRIMARY KEY (EXT_OWNERSHIP_TYPE_ID)
)
/

CREATE SEQUENCE OLE_DS_EXT_OWNERSHIP_S
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  NOMINVALUE
  NOCYCLE
  CACHE 20
  NOORDER
/

CREATE  TABLE OLE_DS_EXT_OWNERSHIP_T (
  EXT_OWNERSHIP_ID INTEGER NOT NULL,
  EXT_OWNERSHIP_TYPE_ID INTEGER DEFAULT NULL,
  TEXT VARCHAR2(1000)  DEFAULT NULL ,
  HOLDINGS_ID INTEGER  DEFAULT NULL ,
  ORD INTEGER  DEFAULT NULL ,
   PRIMARY KEY (EXT_OWNERSHIP_ID),
   CONSTRAINT EXT_OWNERSHIP_CONSTRAINT FOREIGN KEY (HOLDINGS_ID) REFERENCES OLE_DS_HOLDINGS_T (HOLDINGS_ID),
   CONSTRAINT EXT_OWNERSHIP_TYPE_CONSTRAINT FOREIGN KEY (EXT_OWNERSHIP_TYPE_ID) REFERENCES OLE_DS_EXT_OWNERSHIP_TYPE_T (EXT_OWNERSHIP_TYPE_ID)
)
/

CREATE SEQUENCE OLE_DS_EXT_NOTE_S
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  NOMINVALUE
  NOCYCLE
  CACHE 20
  NOORDER
/

CREATE  TABLE OLE_DS_EXT_NOTE_T (
  EXT_NOTE_ID INTEGER NOT NULL,
  TYPE VARCHAR2(20)  DEFAULT NULL ,
  NOTE VARCHAR2(3000)  DEFAULT NULL ,
  EXT_OWNERSHIP_ID INTEGER  NOT NULL ,
  PRIMARY KEY (EXT_NOTE_ID),
  CONSTRAINT EXT_NOTE_CONSTRAINT FOREIGN KEY (EXT_OWNERSHIP_ID) REFERENCES OLE_DS_EXT_OWNERSHIP_T (EXT_OWNERSHIP_ID)
)
/

CREATE SEQUENCE OLE_DS_HOLDINGS_NOTE_S
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  NOMINVALUE
  NOCYCLE
  CACHE 20
  NOORDER
/

CREATE  TABLE OLE_DS_HOLDINGS_NOTE_T (
  HOLDINGS_NOTE_ID INTEGER NOT NULL ,
  TYPE VARCHAR2(100) DEFAULT NULL ,
  NOTE VARCHAR2(3000) DEFAULT NULL ,
  HOLDINGS_ID INTEGER NOT NULL ,
  PRIMARY KEY (HOLDINGS_NOTE_ID),
  CONSTRAINT HOLDINGS_NOTE_CONSTRAINT FOREIGN KEY (HOLDINGS_ID) REFERENCES OLE_DS_HOLDINGS_T (HOLDINGS_ID)
)
/





CREATE SEQUENCE OLE_DS_STAT_SEARCH_CODE_S
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  NOMINVALUE
  NOCYCLE
  CACHE 20
  NOORDER
/

CREATE  TABLE OLE_DS_STAT_SEARCH_CODE_T (
  STAT_SEARCH_CODE_ID INTEGER NOT NULL,
  CODE VARCHAR2(100) DEFAULT NULL ,
  NAME VARCHAR2(500) DEFAULT NULL ,
  PRIMARY KEY (STAT_SEARCH_CODE_ID)
)
/

CREATE SEQUENCE OLE_DS_ITEM_TYPE_S
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  NOMINVALUE
  NOCYCLE
  CACHE 20
  NOORDER
/

CREATE  TABLE OLE_DS_ITEM_TYPE_T (
  ITEM_TYPE_ID INTEGER NOT NULL ,
  CODE VARCHAR2(100) NULL ,
  NAME VARCHAR2(500) NULL ,
  PRIMARY KEY (ITEM_TYPE_ID)
)
/

CREATE SEQUENCE OLE_DS_ITEM_STATUS_S
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  NOMINVALUE
  NOCYCLE
  CACHE 20
  NOORDER
/

CREATE  TABLE OLE_DS_ITEM_STATUS_T (
  ITEM_STATUS_ID INTEGER NOT NULL  ,
  CODE VARCHAR2(100)  DEFAULT NULL ,
  NAME VARCHAR2(500)  DEFAULT NULL ,
  PRIMARY KEY (ITEM_STATUS_ID)
)
/


CREATE SEQUENCE OLE_DS_ITEM_S
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  NOMINVALUE
  NOCYCLE
  CACHE 20
  NOORDER
/

CREATE  TABLE OLE_DS_ITEM_T (
  ITEM_ID INTEGER NOT NULL ,
  STAFF_ONLY CHAR(1) ,
  BARCODE VARCHAR2(20) DEFAULT NULL ,
  BARCODE_ARSL VARCHAR2(300) DEFAULT NULL ,
  TEMP_ITEM_TYPE_ID INTEGER  DEFAULT NULL ,
  ENUMERATION VARCHAR2(100)  DEFAULT NULL ,
  CHRONOLOGY VARCHAR2(100)  DEFAULT NULL ,
  COPY_NUMBER VARCHAR2(20)  DEFAULT NULL ,
  URI VARCHAR2(400)  DEFAULT NULL ,
  ITEM_TYPE_ID INTEGER  DEFAULT NULL ,
  NUM_PIECES VARCHAR2(10)  DEFAULT NULL ,
  UNIQUE_ID_PREFIX VARCHAR2(10)  DEFAULT NULL ,
  HOLDINGS_ID INTEGER NOT NULL ,
  PURCHASE_ORDER_LINE_ITEM_ID VARCHAR2(45)  DEFAULT NULL ,
  VENDOR_LINE_ITEM_ID VARCHAR2(45)  DEFAULT NULL ,
  FUND VARCHAR2(300)  DEFAULT NULL ,
  PRICE VARCHAR(20) DEFAULT NULL ,
  ITEM_STATUS_ID INTEGER  DEFAULT NULL ,
  ITEM_STAT_SEARCH_ID INTEGER  DEFAULT NULL ,
  CHECK_IN_NOTE VARCHAR2(255)  DEFAULT NULL ,
  EFFECTIVE_DATE TIMESTAMP DEFAULT NULL ,
  FAST_ADD CHAR(1) DEFAULT NULL ,
  LOCATION VARCHAR2(600)  DEFAULT NULL ,
  LOCATION_LEVEL VARCHAR2(600)  DEFAULT NULL ,
  CALL_NUMBER_PREFIX VARCHAR2(100) DEFAULT NULL ,
  CALL_NUMBER VARCHAR2(300) DEFAULT NULL ,
  SHELVING_ORDER VARCHAR2(300) DEFAULT NULL ,
  CALL_NUMBER_TYPE_ID INTEGER DEFAULT NULL ,
  CLMS_RET_FLAG  CHAR(1) ,
  CLMS_RET_FLAG_CRE_DATE  TIMESTAMP  DEFAULT NULL ,
  CLMS_RET_NOTE VARCHAR2(255) DEFAULT  NULL,
  CURRENT_BORROWER VARCHAR2(30) DEFAULT NULL,
  PROXY_BORROWER VARCHAR2(30)  DEFAULT NULL,
  DUE_DATE_TIME TIMESTAMP DEFAULT NULL,
  ITEM_DMG_STATUS CHAR(1) ,
  ITEM_MISING_PICS_FLAG CHAR(1) ,
  ITEM_DMG_NOTE VARCHAR2(600)  DEFAULT NULL ,
  MISING_PICS_EFFECTIVE_DATE TIMESTAMP ,
  MISING_PICS_COUNT INTEGER DEFAULT NULL,
  MISING_PICS_NOTE VARCHAR2(600)  DEFAULT NULL ,
  DATE_ENTERED TIMESTAMP DEFAULT NULL ,
  DATE_LAST_UPDATED TIMESTAMP DEFAULT NULL ,
  UPDATED_BY VARCHAR2(40),
  CREATED_BY VARCHAR2(40),

  PRIMARY KEY (ITEM_ID) ,
  CONSTRAINT ITEM_STATUS_CONSTRAINT FOREIGN KEY (ITEM_STATUS_ID) REFERENCES OLE_DS_ITEM_STATUS_T (ITEM_STATUS_ID),
  CONSTRAINT ITEM_HOLDINGS_CONSTRAINT FOREIGN KEY (HOLDINGS_ID) REFERENCES OLE_DS_HOLDINGS_T (HOLDINGS_ID),
  CONSTRAINT ITEM_TYPE_CONSTRAINT FOREIGN KEY (ITEM_TYPE_ID) REFERENCES OLE_DS_ITEM_TYPE_T (ITEM_TYPE_ID),
  CONSTRAINT ITEM_TEMP_TYPE_CONSTRAINT FOREIGN KEY (TEMP_ITEM_TYPE_ID) REFERENCES OLE_DS_ITEM_TYPE_T (ITEM_TYPE_ID),
  CONSTRAINT CALLNUMBER_TYPE_CONSTRAINT FOREIGN KEY (CALL_NUMBER_TYPE_ID) REFERENCES OLE_DS_CALL_NUMBER_TYPE_T (CALL_NUMBER_TYPE_ID)
)
/


CREATE SEQUENCE OLE_DS_FORMER_IDENTIFIER_S
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  NOMINVALUE
  NOCYCLE
  CACHE 20
  NOORDER
/

CREATE  TABLE OLE_DS_FORMER_IDENTIFIER_T (
  FORMER_IDENTIFIER_ID INTEGER NOT NULL  ,
  VALUE VARCHAR2(100)  DEFAULT NULL ,
  TYPE VARCHAR2(500)  DEFAULT NULL ,
  ITEM_ID INTEGER  DEFAULT NULL ,
  PRIMARY KEY (FORMER_IDENTIFIER_ID),
  CONSTRAINT FORMER_CONSTRAINT FOREIGN KEY (ITEM_ID) REFERENCES OLE_DS_ITEM_T (ITEM_ID)
)
/

CREATE SEQUENCE OLE_DS_ITEM_NOTE_S
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  NOMINVALUE
  NOCYCLE
  CACHE 20
  NOORDER
/

CREATE  TABLE OLE_DS_ITEM_NOTE_T (
  ITEM_NOTE_ID INTEGER NOT NULL,
  TYPE VARCHAR2(50)  DEFAULT NULL ,
  NOTE VARCHAR2(3000)  DEFAULT NULL ,
  ITEM_ID INTEGER  DEFAULT NULL ,
  PRIMARY KEY (ITEM_NOTE_ID) ,
  CONSTRAINT ITEM_NOTE_CONSTRAINT FOREIGN KEY (ITEM_ID) REFERENCES OLE_DS_ITEM_T (ITEM_ID)
)
/

CREATE SEQUENCE OLE_DS_LOC_CHECKIN_COUNT_S
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  NOMINVALUE
  NOCYCLE
  CACHE 20
  NOORDER
/

CREATE  TABLE OLE_DS_LOC_CHECKIN_COUNT_T (
  CHECK_IN_LOCATION_ID INTEGER NOT NULL  ,
  LOCATION_NAME VARCHAR2(200)  DEFAULT NULL ,
  LOCATION_COUNT VARCHAR2(20)  DEFAULT NULL ,
  LOCATION_IN_HOUSE_COUNT VARCHAR2(20)  DEFAULT NULL ,
  ITEM_ID INTEGER  DEFAULT NULL ,
  PRIMARY KEY (CHECK_IN_LOCATION_ID),
  CONSTRAINT LOCATION_COUNT_CONSTRAINT FOREIGN KEY (ITEM_ID) REFERENCES OLE_DS_ITEM_T (ITEM_ID)
)
/


CREATE SEQUENCE OLE_DS_COVERAGE_S
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  NOMINVALUE
  NOCYCLE
  CACHE 20
  NOORDER
/
 CREATE TABLE OLE_DS_COVERAGE_T (
  EHOLDINGS_COVERAGE_ID INTEGER NOT NULL,
  HOLDINGS_ID INTEGER DEFAULT NULL,
  COVERAGE_START_DATE DATE DEFAULT NULL,
  COVERAGE_START_VOLUME VARCHAR2(40) DEFAULT NULL,
  COVERAGE_START_ISSUE VARCHAR2(40) DEFAULT NULL,
  COVERAGE_END_DATE DATE DEFAULT NULL,
  COVERAGE_END_VOLUME VARCHAR2(40) DEFAULT NULL,
  COVERAGE_END_ISSUE VARCHAR2(40) DEFAULT NULL,
  PRIMARY KEY (EHOLDINGS_COVERAGE_ID),
  CONSTRAINT EHOLDINGS_COVERAGE_CONSTRAINT FOREIGN KEY (HOLDINGS_ID) REFERENCES OLE_DS_HOLDINGS_T (HOLDINGS_ID)
)
 /
 CREATE SEQUENCE OLE_DS_PERPETUAL_ACCESS_S
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  NOMINVALUE
  NOCYCLE
  CACHE 20
  NOORDER
/
 CREATE TABLE OLE_DS_PERPETUAL_ACCESS_T (
  EHOLDINGS_PERPETUAL_ACCESS_ID INTEGER NOT NULL,
  HOLDINGS_ID INTEGER DEFAULT NULL,
  PERPETUAL_ACCESS_START_DATE DATE DEFAULT NULL,
  PERPETUAL_ACCESS_START_VOLUME VARCHAR2(40) DEFAULT NULL,
  PERPETUAL_ACCESS_START_ISSUE VARCHAR2(40) DEFAULT NULL,
  PERPETUAL_ACCESS_END_DATE DATE DEFAULT NULL,
  PERPETUAL_ACCESS_END_VOLUME VARCHAR2(40) DEFAULT NULL,
  PERPETUAL_ACCESS_END_ISSUE VARCHAR2(40) DEFAULT NULL,
  PRIMARY KEY (EHOLDINGS_PERPETUAL_ACCESS_ID),
  CONSTRAINT EHOLDINGS_PER_ACC_CONSTRAINT FOREIGN KEY (HOLDINGS_ID) REFERENCES OLE_DS_HOLDINGS_T (HOLDINGS_ID)
)
/

CREATE SEQUENCE OLE_DS_AUTHENTICATION_S
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  NOMINVALUE
  NOCYCLE
  CACHE 20
  NOORDER
/
CREATE TABLE OLE_DS_AUTHENTICATION_T (
  AUTHENTICATION_TYPE_ID INTEGER  NOT NULL,
  CODE VARCHAR2(100) DEFAULT NULL ,
  NAME VARCHAR2(500) DEFAULT NULL ,
  PRIMARY KEY (AUTHENTICATION_TYPE_ID)
)
/
CREATE SEQUENCE OLE_DS_ACCESS_LOCATION_S
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  NOMINVALUE
  NOCYCLE
  CACHE 20
  NOORDER
/
CREATE TABLE OLE_DS_ACCESS_LOCATION_T (
  ACCESS_LOCATION_ID INTEGER  NOT NULL,
  CODE VARCHAR(100) DEFAULT NULL ,
  NAME VARCHAR(500) DEFAULT NULL ,
  PRIMARY KEY (ACCESS_LOCATION_ID)
)
/
CREATE SEQUENCE OLE_DS_HOLDINGS_ACCESS_LOC_S
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  NOMINVALUE
  NOCYCLE
  CACHE 20
  NOORDER
/
CREATE TABLE OLE_DS_HOLDINGS_ACCESS_LOC_T (
  HOLDINGS_ACCESS_LOCATION_ID INTEGER  NOT NULL,
  HOLDINGS_ID INTEGER DEFAULT NULL ,
  ACCESS_LOCATION_ID INTEGER DEFAULT NULL ,
  PRIMARY KEY (HOLDINGS_ACCESS_LOCATION_ID)
)
/
CREATE SEQUENCE OLE_DS_HOLDINGS_STAT_SEARCH_S
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  NOMINVALUE
  NOCYCLE
  CACHE 20
  NOORDER
/
CREATE TABLE OLE_DS_HOLDINGS_STAT_SEARCH_T (
  HOLDINGS_STAT_SEARCH_ID INTEGER  NOT NULL,
  HOLDINGS_ID INTEGER DEFAULT NULL ,
  STAT_SEARCH_CODE_ID INTEGER DEFAULT NULL ,
  PRIMARY KEY (HOLDINGS_STAT_SEARCH_ID) ,
  CONSTRAINT HOLDINGS_STAT_CONSTRAINT FOREIGN KEY (STAT_SEARCH_CODE_ID) REFERENCES OLE_DS_STAT_SEARCH_CODE_T (STAT_SEARCH_CODE_ID)
)
/
CREATE SEQUENCE OLE_DS_ITEM_STAT_SEARCH_S
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  NOMINVALUE
  NOCYCLE
  CACHE 20
  NOORDER
/
CREATE TABLE OLE_DS_ITEM_STAT_SEARCH_T (
  ITEM_STAT_SEARCH_ID INTEGER  NOT NULL,
  ITEM_ID INTEGER DEFAULT NULL ,
  STAT_SEARCH_CODE_ID INTEGER DEFAULT NULL ,
  PRIMARY KEY (ITEM_STAT_SEARCH_ID) ,
  CONSTRAINT ITEM_STAT_CONSTRAINT FOREIGN KEY (STAT_SEARCH_CODE_ID) REFERENCES OLE_DS_STAT_SEARCH_CODE_T (STAT_SEARCH_CODE_ID)
)
/
 CREATE SEQUENCE OLE_DS_ITEM_DONOR_S
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  NOMINVALUE
  NOCYCLE
  CACHE 20
  NOORDER
/

CREATE  TABLE OLE_DS_ITEM_DONOR_T (
  ITEM_DONOR_ID INTEGER NOT NULL,
  DONOR_CODE VARCHAR2(10)  DEFAULT NULL ,
  DONOR_PUBLIC_DISPLAY VARCHAR2(50)  DEFAULT NULL ,
  DONOR_NOTE VARCHAR2(50)  DEFAULT NULL ,
  ITEM_ID INTEGER  DEFAULT NULL ,
  PRIMARY KEY (ITEM_DONOR_ID) ,
  CONSTRAINT ITEM_DONOR_CONSTRAINT FOREIGN KEY (ITEM_ID) REFERENCES OLE_DS_ITEM_T (ITEM_ID)
)
/
CREATE SEQUENCE OLE_DS_HOLDINGS_DONOR_S
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  NOMINVALUE
  NOCYCLE
  CACHE 20
  NOORDER
/

CREATE  TABLE OLE_DS_HOLDINGS_DONOR_T (
  HOLDINGS_DONOR_ID INTEGER NOT NULL,
  DONOR_CODE VARCHAR2(10)  DEFAULT NULL ,
  DONOR_PUBLIC_DISPLAY VARCHAR2(50)  DEFAULT NULL ,
  DONOR_NOTE VARCHAR2(50)  DEFAULT NULL ,
  HOLDINGS_ID INTEGER  DEFAULT NULL ,
  PRIMARY KEY (HOLDINGS_DONOR_ID) ,
  CONSTRAINT HOLDINGS_DONOR_CONSTRAINT FOREIGN KEY (HOLDINGS_ID) REFERENCES OLE_DS_HOLDINGS_T (HOLDINGS_ID)
)
/