package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ErrorMessage
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "Check out Circ Policy Set 28-DAYS-DKU"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("FACULTY","GRAD","DUKESTAFF","UG","FQGRAD"))
$i: OleItemRecordForCirc (getItemType() in ("STANDARDLOAN"),
getItemLibraryLocation() in ("DKU"))
then
$l.setCirculationPolicyId("Check out Circ Policy Set 28-DAYS-DKU");
$l.loanPeriod("28-D","7-D");
$n.setNoticeType(DroolsConstants.REGULAR_LOANS_NOTICE_CONFIG);
 end