package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ErrorMessage
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "Check out Circ Policy Set 28-DAYS-PS-LESS-THAN-10"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("ALUMNI","PL4WK"),
getLoanedItemsCountByItemType($i.getItemType()) < 10)
$i: OleItemRecordForCirc (getItemType() in ("STANDARDLOAN"),
getItemLibraryLocation() in ("PERKINS","LILLY","LSC","MARINE","MUSIC"))
then
$l.setCirculationPolicyId("Check out Circ Policy Set 28-DAYS-PS-LESS-THAN-10");
$l.loanPeriod("28-D","7-D");
$n.setNoticeType(DroolsConstants.REGULAR_LOANS_NOTICE_CONFIG);
end

rule "Check out Circ Policy Set 28-DAYS-PS-GREATER-THAN-10"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("ALUMNI","PL4WK"),
getLoanedItemsCountByItemType($i.getItemType()) >= 10)
$i: OleItemRecordForCirc (getItemType() in ("STANDARDLOAN"),
getItemLibraryLocation() in ("PERKINS","LILLY","LSC","MARINE","MUSIC"))

$e: ErrorMessage()

then
$e.setErrorMessage("Patron has more than 10 standard loan items checked out");
$e.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION);
$l.setCirculationPolicyId("Check out Circ Policy Set 28-DAYS-PS-LESS-THAN-10");
$l.loanPeriod("28-D","7-D"); // This method takes due date and recall period as arguments.
$n.setNoticeType(DroolsConstants.REGULAR_LOANS_NOTICE_CONFIG);
 end