package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ErrorMessage
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "Check out Circ Policy Set 28-DAYS-LINK-WEBCAM"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("FACULTY","FQFACULTY","LWFACULTY","MDFACULTY","GRADST","DIVGRAD","DUKESTAFF","UG","FQGRAD","FQST","FQPHD"))
$i: OleItemRecordForCirc (getItemType() in ("WEBCAM"),
getItemLibraryLocation() in ("LINK"))
then
$l.setCirculationPolicyId("Check out Circ Policy Set 28-DAYS-LINK-WEBCAM");
$l.loanPeriod("28-D","7-D");
$n.setNoticeType(DroolsConstants.REGULAR_LOANS_NOTICE_CONFIG);
 end