package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ErrorMessage
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "Check out Circ Policy Set 28-DAYS-DIV-LESS-THAN-25"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("DUKE4WKGOLD","FRIENDSDUL"))
getLoanedItemsCountByItemType($i.getItemType()) < 25)
$i: OleItemRecordForCirc (getItemType() in ("STANDARDLOAN"),
getItemLibraryLocation() in ("DIV"))
then
$l.setCirculationPolicyId("Check out Circ Policy Set 28-DAYS-DIV-LESS-THAN-25");
$l.loanPeriod("28-D","7-D");
$n.setNoticeType(DroolsConstants.REGULAR_LOANS_NOTICE_CONFIG);

rule "Check out Circ Policy Set 28-DAYS-DIV-GREATER-THAN-25"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("DUKE4WKGOLD","FRIENDSDUL"))
getLoanedItemsCountByItemType($i.getItemType()) >= 25)
$i: OleItemRecordForCirc (getItemType() in ("STANDARDLOAN"),
getItemLibraryLocation() in ("DIV"))

$e: ErrorMessage()

then
$e.setErrorMessage("Patron has more than 25 standard loan items checked out");
$e.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION);
$l.setCirculationPolicyId("Check out Circ Policy Set 28-DAYS-DIV-LESS-THAN-25");
$l.loanPeriod("28-D","7-D"); // This method takes due date and recall period as arguments.
$n.setNoticeType(DroolsConstants.REGULAR_LOANS_NOTICE_CONFIG);
 end