package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "Check out Circ Policy Set 28-DAYS-FORD-LESS-THAN-10"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("FQALUMNI"),
getLoanedItemsCountByItemType($i.getItemType()) < 10)
$i: OleItemRecordForCirc (getItemType() in ("STANDARDLOAN"),
getItemLibraryLocation() in ("FORD"))
then
$l.setCirculationPolicyId("Check out Circ Policy Set 28-DAYS-FORD-10-MAX");
$l.loanPeriod("28-D","7-D");
$n.setNoticeType(DroolsConstants.REGULAR_LOANS_NOTICE_CONFIG);
 end

rule "Check out Circ Policy Set 28-DAYS-FORD-GREATER-THAN-10"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("FQALUMNI"),
getLoanedItemsCountByItemType($i.getItemType()) >= 10)
$i: OleItemRecordForCirc (getItemType() in ("STANDARDLOAN"),
getItemLibraryLocation() in ("FORD"))

$d: DroolsResponse()

then
$d.addErrorMessage("Patron has more than 10 standard loan items checked out");
$d.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION);
$l.setCirculationPolicyId("Check out Circ Policy Set 28-DAYS-FORD-LESS-THAN-10");
$l.loanPeriod("28-D","7-D"); // This method takes due date and recall period as arguments.
$n.setNoticeType(DroolsConstants.SHORT_TERM_LOANS_NOTICE_CONFIG);
 end