package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ErrorMessage
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "Check out Circ Policy Set 3HR-FORD-DIV"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$i: OleItemRecordForCirc (getItemType() in ("3HR"),
getItemLibraryLocation() in ("DIV","FORD"))
then
$l.setCirculationPolicyId("Check out Circ Policy Set 3HR-FORD-DIV");
$l.loanPeriod("3-H",null);
$n.setNoticeType(DroolsConstants.SHORT_TERM_LOANS_NOTICE_CONFIG);
 end