package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ErrorMessage
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "Check out Circ Policy Set 3HR-LILLY-LIMITED"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("DUKESTAFF","UG","FQST","FQPARTNER"))
$i: OleItemRecordForCirc (getItemType() in ("LIMITEDCIRC"),
getItemLibraryLocation() in ("LILLY"))
then
$l.setCirculationPolicyId("Check out Circ Policy Set 3HR-LILLY-LIMITED");
$l.loanPeriod("3-H",null);
$n.setNoticeType(DroolsConstants.SHORT_TERM_LOANS_NOTICE_CONFIG);
 end