package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ErrorMessage
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "Check out Circ Policy Set 4HR-PERKINS"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("GRAD","UG"))
$i: OleItemRecordForCirc (getItemType() in ("4HR"),
getItemLibraryLocation() in ("PERKINS"))
then
$l.setCirculationPolicyId("Check out Circ Policy Set 4HR-PERKINS");
$l.loanPeriod("4-H",null);
$n.setNoticeType(DroolsConstants.SHORT_TERM_LOANS_NOTICE_CONFIG);
 end