package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ErrorMessage
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "Check out Circ Policy Set 5-31-FIXED-MUSIC"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("FACULTY","FQFACULTY","LWFACULTY","MDFACULTY","GRADST","FQPHD","RETLIB"))
$i: OleItemRecordForCirc (getItemType() in ("SOUNDCD","MICROFORM","AUDIOVISUAL","COMPMEDIA"),
getItemLibraryLocation() in ("MUSIC"))
then
$l.setCirculationPolicyId("Check out Circ Policy Set 5-31-FIXED-MUSIC");
$l.loanPeriod(OLEConstants.FIXED_DUE_DATE, "7-D");
$n.setNoticeType(DroolsConstants.REGULAR_LOANS_NOTICE_CONFIG);
 end