package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ErrorMessage
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "Check out Circ Policy Set 8-WK-MCL"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("GRADST"))
$i: OleItemRecordForCirc (getItemType() in ("8WK"),
getItemLibraryLocation() in ("MCL"))
then
$l.setCirculationPolicyId("Check out Circ Policy Set 8-WK-MCL");
$l.loanPeriod("56-D","7-D");
$n.setNoticeType(DroolsConstants.REGULAR_LOANS_NOTICE_CONFIG);
 end