package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ErrorMessage
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "Check out Circ Policy Set 84-DAYS-PS-BORDIR"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("FACULTY","GRADST","DIVGRAD","DUKESTAFF","UG"))
$i: OleItemRecordForCirc (getItemType() in ("BORDIR"),
getItemLibraryLocation() in ("PERKINS","LILLY","LSC","MUSIC"))
then
$l.setCirculationPolicyId("Check out Circ Policy Set 84-DAYS-PS-BORDIR");
$l.loanPeriod("84-D",null);
$n.setNoticeType(DroolsConstants.REGULAR_LOANS_NOTICE_CONFIG);
 end