package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants


rule "CO-1DAY-MARINE-MICROFORM"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()

$p: OlePatronDocument(getBorrowerTypeCode() in ("FACULTY","FQFACULTY","LWFACULTY","MDFACULTY","GRADST","UG","FQGRAD","FQST","FQPHD","RETLIB","FQPARTNER"))
$i: OleItemRecordForCirc (getItemType() in ("MICROFORM"),
getItemLibraryLocation() in ("MARINE"))
then
$l.setCirculationPolicyId("CO-1DAY-MARINE-MICROFORM");
$l.loanPeriod("1-D",null);

 end