package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "CO-1-DAY MUSIC"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("FACULTY","FQFACULTY","LWFACULTY","MDFACULTY","GRADST","DIVGRAD","ALUMNI","FQALUMNI","UNCGFS","PL4WK","DUKE4WKGOLD","TRLN","DUKESTAFF","HEALTHPROF","UG","FQGRAD","FQST","FQPHD","RETLIB","FQPARTNER","LWALUMNI"))
$i: OleItemRecordForCirc (getItemType() in ("1DAY"),
getItemLibraryLocation() in ("MUSIC"))
then
$l.setCirculationPolicyId("CO-1-DAY MUSIC");
$l.loanPeriod("1-D","1-D");
$n.setNoticeType("NO-PS-STDLOAN");
 end