package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "CO-1WK-MUSIC"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("UG","FQGRAD","FQST","DIVGRAD","DUKESTAFF"))
$i: OleItemRecordForCirc (getItemType() in ("1WK","MICROFORM","AUDIOVISUAL","COMPMEDIA"),
getItemLibraryLocation() in ("MUSIC"))
then
$l.setCirculationPolicyId("CO-1WK-MUSIC");
$l.loanPeriod("7-D",null);
$n.setNoticeType("NO-PS-STDLOAN");
 end