package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants


rule "CO-1WK-LSC-MATHJOURN"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()


$i: OleItemRecordForCirc (getItemType() in ("MATHJOURN"),
getItemLibraryLocation() in ("LSC"))
then
$l.setCirculationPolicyId("CO-1WK-LSC-MATHJOURN");
$l.loanPeriod("7-D",null);

 end