package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants


rule "CO-28-DAYS-MCL-LSCGEN"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()

$p: OlePatronDocument(getBorrowerTypeCode() in ("DUKESTAFF","HEALTHPROF","UG"))
$i: OleItemRecordForCirc (getItemType() in ("LSCGEN"),
getItemLibraryLocation() in ("MCL"))
then
$l.setCirculationPolicyId("CO-28-DAYS-MCL-LSCGEN");
$l.loanPeriod("28-D","14-D");
 end