package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "CO-2WK-FORD"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$d:DroolsResponse()
$p: OlePatronDocument(getBorrowerTypeCode() in ("FACULTY","FQFACULTY","LWFACULTY","MDFACULTY","GRADST","DIVGRAD","FQALUMNI","DUKESTAFF","UG","FQGRAD","FQST","FQPHD"))
$i: OleItemRecordForCirc (getItemType() in ("2WK"),
getItemLibraryLocation() in ("FORD"))
then
$l.setCirculationPolicyId("CO-2WK-FORD");
$l.loanPeriod("14-D",null);
$n.setNoticeType("NO-FORD-SHORT-LOANS");
 end
 
 rule "CO-2WK-FORD-NOT-ALLOWED"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$d:DroolsResponse()

$p: OlePatronDocument(getBorrowerTypeCode() not in ("FACULTY","FQFACULTY","LWFACULTY","MDFACULTY","GRADST","DIVGRAD","FQALUMNI","DUKESTAFF","UG","FQGRAD","FQST","FQPHD"))
$i: OleItemRecordForCirc (getItemType() in ("2WK"),
getItemLibraryLocation() in ("FORD"))
then

$d.addErrorMessage("Patron may not check out Ford 2-week items.");
 end