package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "CO-28DAY-EREADER-FORD"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("FACULTY","FQFACULTY","LWFACULTY","MDFACULTY","GRADST","DIVGRAD","DUKESTAFF","UG","FQGRAD","FQST","FQPHD","RETLIB"))
$i: OleItemRecordForCirc (getItemType() in ("EREADER"),
getItemLibraryLocation() in ("FORD"))
then
$l.setCirculationPolicyId("CO-28DAY-EREADER-FORD");
$l.loanPeriod("28-D",null);
$n.setNoticeType("NO-FORD-EREADER");
 end