package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "CO-28-DAYS-MUSIC-SOUNDCD"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("DUKESTAFF","UG","FQGRAD","FQST"))
$i: OleItemRecordForCirc (getItemType() in ("SOUNDCD"),
getItemLibraryLocation() in ("MUSIC"))
then
$l.setCirculationPolicyId("CO-28-DAYS-MUSIC-SOUNDCD");
$l.loanPeriod("28-D","7-D");
$n.setNoticeType(DroolsConstants.REGULAR_LOANS_NOTICE_CONFIG);
 end