package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "CO-2HR-FORD"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("FQFACULTY","GRADST","FQGRAD","FQST","FQPHD"))
$i: OleItemRecordForCirc (getItemType() in ("2HR"),
getItemLibraryLocation() in ("FORD"))
then
$l.setCirculationPolicyId("CO-2HR-FORD");
$l.loanPeriod("2-H",null);
$n.setNoticeType("NO-FORD-SHORT-LOANS");
 end