package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "CO-28-DAYS-LINK-SLIDEFLIP"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("FACULTY","FQFACULTY","LWFACULTY","MDFACULTY","GRADST","DIVGRAD","DUKESTAFF","UG","FQGRAD","FQST","FQPHD"))
$i: OleItemRecordForCirc (getItemType() in ("SLIDEFLIP"),
getItemLibraryLocation() in ("LINK"))
then
$l.setCirculationPolicyId("CO-28-DAYS-LINK-SLIDEFLIP");
$l.loanPeriod("28-D","7-D");
$n.setNoticeType("NO-LINK-SLIDEFLIP");
 end