package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants


rule "CO-3HR-LILLY-MUSIC-HEADPHONES"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()

$p: OlePatronDocument(getBorrowerTypeCode() not in ("FACULTY","FQFACULTY","LWFACULTY","MDFACULTY","GRADST","ALUMNI","FQALUMNI","UNCGFS","PL4WK","DUKE4WKGOLD","TRLN","DUKESTAFF","HEALTHPROF","UG","FQGRAD","FQST","FQPHD","RETLIB","FQPARTNER","LWALUMNI"))
$i: OleItemRecordForCirc (getItemType() in ("HEADPHMIC"),
getItemLibraryLocation() in ("LILLY","MUSIC"))
then
$l.setCirculationPolicyId("CO-3HR-LILLY-MUSIC-HEADPHONES");
$l.loanPeriod("3-H",null);
 end