package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "CO-3DAY-LILLY-AV"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("FACULTY","FQFACULTY","LWFACULTY","MDFACULTY","GRADST","DIVGRAD","DUKESTAFF","UG","FQST","FQPHD","FQGRAD","RETLIB"))
$i: OleItemRecordForCirc (getItemType() in ("AUDIOVISUAL"),
getItemLibraryLocation() in ("LILLY"))
then
$l.setCirculationPolicyId("CO-3DAY-LILLY-AV");
$l.loanPeriod("3-D",null);
$n.setNoticeType("NO-LILLY-AV-STDNT3DAY");
 end