package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants


rule "CO-3HR-EREADER-DKU"
agenda-group "checkout validation"
activation-group "checkout validation"

when
$l: OleLoanDocument()

$p: OlePatronDocument(getBorrowerTypeCode() in ("FACULTY","GRADST","UG","FQGRAD"))
$i: OleItemRecordForCirc (getItemType() in ("EREADER"),
getItemLibraryLocation() in ("DKU"))

then
$l.setCirculationPolicyId("CO-3HR-EREADER-DKU");
$l.loanPeriod("3-H",null);
 end