package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "CO-4WCL-PERKINS-FRIENDS"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("FRIENDSDUL"))
$i: OleItemRecordForCirc (getItemType() in ("4WKCL"),
getItemLibraryLocation() in ("PERKINS"))
then
$l.setCirculationPolicyId("CO-4WCL-PERKINS-FRIENDS");
$l.loanPeriod("28-D","7-D");
$n.setNoticeType("NO-PS-STDLOAN");
 end