package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "CO-5-31-FIXED-LAW"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("LWFACULTY"))
$i: OleItemRecordForCirc (getItemType() in ("STANDARDLOAN","LIBUSEONLY","3DAY","4HR","24HR"),
getItemLibraryLocation() in ("LAW"))
then
$l.setCirculationPolicyId("CO-5-31-FIXED-LAW");
$l.loanPeriod(OLEConstants.FIXED_DUE_DATE, "7-D");
$n.setNoticeType("NO-LAW-ALL");
 end