package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "CO-90-DAYS-LAW"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("FACULTY","FQFACULTY","MDFACULTY","GRADST","DIVGRAD","DUKESTAFF","FQST","FQPHD","FQMBA","FQGRAD"))
$i: OleItemRecordForCirc (getItemType() in ("8WK"),
getItemLibraryLocation() in ("LAW"))
then
$l.setCirculationPolicyId("CO-90-DAYS-LAW");
$l.loanPeriod("90-D","7-D");
$n.setNoticeType("NO-LAW-ALL");
 end