package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "CO-DIV-NONCIRC"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("FACULTY","FQFACULTY","LWFACULTY","MDFACULTY"))
$i: OleItemRecordForCirc (getItemType() in ("NONCIRC"),
getItemLibraryLocation() in ("DIV"))
then
$l.setCirculationPolicyId("CO-DIV-NONCIRC");
$l.loanPeriod("3-H", "7-D");
$n.setNoticeType("NO-PS-STDLOAN");
 end