package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "CO-OVERNIGHT-PK-LILLY"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("FACULTY","GRADST","DIVGRAD","DUKESTAFF","UG","FQGRAD","FQST"))
$i: OleItemRecordForCirc (getItemType() in ("OVERNIGHT"),
getItemLibraryLocation() in ("PERKINS","LILLY"))
then
$l.setCirculationPolicyId("CO-OVERNIGHT-PK-LILLY");
$l.loanPeriod("12-H",null);
$n.setNoticeType("NO-PS-SHORT-LOANS");
 end