package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "CO-PERKINS-NONCIRC"
agenda-group "checkout validation"
activation-group "checkout validation"
when

$l: OleLoanDocument()
$n: NoticeInfo()
$d: DroolsResponse()

$i: OleItemRecordForCirc (getItemType() in ("NONCIRC"),
getItemLibraryLocation() in ("PERKINS"))

then

$d.addErrorMessage("Non-circulating items may not be checked out.");
$d.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION);

$l.setCirculationPolicyId("null");
$l.loanPeriod(null,null);
$n.setNoticeType("NO-PS-STDLOAN");

 end