package org.kuali.ole.docstore.model.repopojo;

import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Created by IntelliJ IDEA.
 * User: Pranitha
 * Date: 2/28/12
 * Time: 3:13 PM
 * To change this template use File | Settings | File Templates.
 */
public class RepositoryData_UT {
    private static final Logger LOG = LoggerFactory.getLogger(RepositoryData_UT.class);

    @Test
    public void testGetRepositoryDump() {
        String dump = "/\n" + "/jcr:primaryType = rep:root\n" + "/jcr:system\n" + "/work\n"
                + "/work/jcr:uuid = 455cb5bb-c973-4f2b-ac86-66269e2a8a98\n"
                + "/work/jcr:mixinTypes = mix:referenceable\n" + "/work/nodeType = folder\n"
                + "/work/jcr:primaryType = nt:unstructured\n" + "/work/bibliographic\n"
                + "/work/bibliographic/jcr:uuid = d74e0fc3-5810-41e1-9de4-74729ac88b76\n"
                + "/work/bibliographic/jcr:mixinTypes = mix:referenceable\n"
                + "/work/bibliographic/nodeType = folder\n"
                + "/work/bibliographic/jcr:primaryType = nt:unstructured\n" + "/work/bibliographic/marc\n"
                + "/work/bibliographic/marc/jcr:uuid = 8e2c602c-9383-4526-9066-44539481c169\n"
                + "/work/bibliographic/marc/jcr:mixinTypes = mix:referenceable\n"
                + "/work/bibliographic/marc/nodeType = folder\n"
                + "/work/bibliographic/marc/jcr:primaryType = nt:unstructured\n" + "/work/bibliographic/marc/l1\n"
                + "/work/bibliographic/marc/l1/jcr:uuid = 0ec7e55d-2c25-4571-83cd-5286ebf2a45d\n"
                + "/work/bibliographic/marc/l1/jcr:mixinTypes = mix:referenceable\n"
                + "/work/bibliographic/marc/l1/nodeType = folder\n"
                + "/work/bibliographic/marc/l1/jcr:primaryType = nt:unstructured\n"
                + "/work/bibliographic/marc/l1/marcFile\n"
                + "/work/bibliographic/marc/l1/marcFile/lastUpdated = 12-11-2011\n"
                + "/work/bibliographic/marc/l1/marcFile/jcr:uuid = cec0e2ba-bce3-411d-aeae-85b817d81f2b\n"
                + "/work/bibliographic/marc/l1/marcFile/jcr:mixinTypes = mix:referenceable\n"
                + "/work/bibliographic/marc/l1/marcFile/jcr:createdBy = ole-khuntley\n"
                + "/work/bibliographic/marc/l1/marcFile/instanceIdentifier = 0d3ae26d-03c4-4c0a-9c1b-39e62865cb12\n"
                + "/work/bibliographic/marc/l1/marcFile/fastAddFlag = true\n"
                + "/work/bibliographic/marc/l1/marcFile/status = n\n"
                + "/work/bibliographic/marc/l1/marcFile/dateEntered = 12-12-2-2010\n"
                + "/work/bibliographic/marc/l1/marcFile/supressFromPublic = false\n"
                + "/work/bibliographic/marc/l1/marcFile/jcr:created = 2012-12-15T11:45:31.132+05:30\n"
                + "/work/bibliographic/marc/l1/marcFile/harvestable = false\n"
                + "/work/bibliographic/marc/l1/marcFile/jcr:primaryType = olefile\n"
                + "/work/bibliographic/marc/l1/marcFile/jcr:content\n"
                + "/work/bibliographic/marc/l1/marcFile/jcr:content/jcr:lastModifiedBy = ole-khuntley\n"
                + "/work/bibliographic/marc/l1/marcFile/jcr:content/jcr:uuid = 5c59c6fe-2e46-45ac-abce-7db9205f9ad8\n"
                + "/work/bibliographic/marc/l1/marcFile/jcr:content/jcr:data = \n"
                + "\t\t\t<collection><record>\n"
                + "\t\t\t\t<leader>00315nam  2200109z  4500</leader><controlfield tag=\"001\">cec0e2ba-bce3-411d-aeae-85b817d81f2b</controlfield>\t\t\t\t<controlfield tag=\"008\">110630n    1400xx |         u||| ||und u</controlfield>\n"
                + "\t\t\t\t<datafield tag=\"100\" ind1=\"1\" ind2=\" \">\n"
                + "\t\t\t\t\t<subfield code=\"a\">John </subfield>\n"
                + "\t\t\t\t\t<subfield code=\"d\">1878-1967.</subfield>\n" + "\t\t\t\t</datafield>\n"
                + "\t\t\t\t<datafield tag=\"245\" ind1=\"1\" ind2=\"0\">\n"
                + "\t\t\t\t\t<subfield code=\"a\">test </subfield>\n"
                + "\t\t\t\t\t<subfield code=\"c\">Carl Sandburg ; illustrated as an anamorphic adventure by Ted Rand.\n"
                + "\t\t\t\t\t</subfield>\n" + "\t\t\t\t</datafield>\n"
                + "\t\t\t\t<datafield tag=\"260\" ind1=\"1\" ind2=\"0\">\n"
                + "\t\t\t\t\t<subfield code=\"c\">1999</subfield>\n" + "\t\t\t\t</datafield></record>\n"
                + "\t\t\t</collection>\n" + "\t\t\t\n" + "\t\t\t   \n"
                + "/work/bibliographic/marc/l1/marcFile/jcr:content/jcr:encoding = \n"
                + "/work/bibliographic/marc/l1/marcFile/jcr:content/jcr:mimeType = application/xml\n"
                + "/work/bibliographic/marc/l1/marcFile/jcr:content/jcr:lastModified = 2012-12-15T11:45:31.132+05:30\n"
                + "/work/bibliographic/marc/l1/marcFile/jcr:content/jcr:primaryType = nt:resource\n"
                + "/work/license\n" + "/work/license/jcr:uuid = 40e63cf6-d305-41d7-bd8e-dc877e11d7af\n"
                + "/work/license/jcr:mixinTypes = mix:referenceable\n" + "/work/license/nodeType = folder\n"
                + "/work/license/jcr:primaryType = nt:unstructured\n" + "/work/instance\n"
                + "/work/instance/jcr:uuid = 094f3348-2954-44b3-be54-963848628f26\n"
                + "/work/instance/jcr:mixinTypes = mix:referenceable\n" + "/work/instance/nodeType = folder\n"
                + "/work/instance/jcr:primaryType = nt:unstructured\n" + "/work/instance/oleml\n"
                + "/work/instance/oleml/jcr:uuid = ccce7b8c-c641-4c15-8791-4e026c26ba4f\n"
                + "/work/instance/oleml/jcr:mixinTypes = mix:referenceable\n"
                + "/work/instance/oleml/nodeType = folder\n"
                + "/work/instance/oleml/jcr:primaryType = nt:unstructured\n" + "/work/instance/oleml/l1\n"
                + "/work/instance/oleml/l1/jcr:uuid = 01cb3670-7e5c-40e1-ac01-9f200dd665e7\n"
                + "/work/instance/oleml/l1/jcr:mixinTypes = mix:referenceable\n"
                + "/work/instance/oleml/l1/nodeType = folder\n"
                + "/work/instance/oleml/l1/jcr:primaryType = nt:unstructured\n" + "/work/instance/oleml/l1/l2\n"
                + "/work/instance/oleml/l1/l2/jcr:uuid = 5469bfd8-cffd-4eb8-8455-0d14c4c7ccb9\n"
                + "/work/instance/oleml/l1/l2/jcr:mixinTypes = mix:referenceable\n"
                + "/work/instance/oleml/l1/l2/nodeType = folder\n"
                + "/work/instance/oleml/l1/l2/jcr:primaryType = nt:unstructured\n"
                + "/work/instance/oleml/l1/l2/instanceNode\n"
                + "/work/instance/oleml/l1/l2/instanceNode/jcr:uuid = 0d3ae26d-03c4-4c0a-9c1b-39e62865cb12\n"
                + "/work/instance/oleml/l1/l2/instanceNode/jcr:mixinTypes = mix:referenceable\n"
                + "/work/instance/oleml/l1/l2/instanceNode/bibIdentifier = cec0e2ba-bce3-411d-aeae-85b817d81f2b\n"
                + "/work/instance/oleml/l1/l2/instanceNode/jcr:primaryType = nt:unstructured\n"
                + "/work/instance/oleml/l1/l2/instanceNode/nodeType = folder\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/jcr:uuid = f70cebe1-0106-4f71-b108-fb234d9ebb46\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/jcr:mixinTypes = mix:referenceable\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/nodeType = folder\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/jcr:primaryType = nt:unstructured\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/holdingsFile\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/holdingsFile/lastUpdated = 2012-12-15T11:45:31.382+05:30\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/holdingsFile/jcr:uuid = 4855c36f-3361-4733-83bd-bf518d520f67\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/holdingsFile/jcr:createdBy = ole-khuntley\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/holdingsFile/jcr:mixinTypes = mix:referenceable\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/holdingsFile/dateEntered = 2012-12-15T11:45:31.382+05:30\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/holdingsFile/jcr:created = 2012-12-15T11:45:31.382+05:30\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/holdingsFile/jcr:primaryType = olefile\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/holdingsFile/jcr:content\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/holdingsFile/jcr:content/jcr:lastModifiedBy = ole-khuntley\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/holdingsFile/jcr:content/jcr:uuid = b2e6b1e1-3021-45c1-baaa-2e07f898fb69\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/holdingsFile/jcr:content/jcr:data = <oleHoldings primary=\"string\">\n"
                + "  <holdingsIdentifier>4855c36f-3361-4733-83bd-bf518d520f67</holdingsIdentifier>\n"
                + "  <extentOfOwnership>\n" + "    <textualHoldings>string</textualHoldings>\n"
                + "    <note type=\"string\">string</note>\n" + "    <type>string</type>\n"
                + "  </extentOfOwnership>\n" + "  <receiptStatus>string</receiptStatus>\n"
                + "  <uri resolvable=\"string\">string</uri>\n" + "  <note type=\"string\">string</note>\n"
                + "  <location>\n" + "    <locationLevel>\n" + "      <name>string</name>\n"
                + "      <level>string</level>\n" + "      <locationLevel/>\n" + "    </locationLevel>\n"
                + "  </location>\n" + "  <extension displayLabel=\"string\"/>\n" + "  <callNumber>\n"
                + "    <type>string</type>\n" + "    <prefix>string</prefix>\n" + "    <number>string</number>\n"
                + "    <classificationPart>string</classificationPart>\n" + "    <itemPart>string</itemPart>\n"
                + "    <shelvingScheme>\n" + "      <codeValue>string</codeValue>\n"
                + "      <fullValue>string</fullValue>\n" + "      <typeOrSource>\n"
                + "        <pointer>http://www.your.com/tempestatesque/e</pointer>\n"
                + "        <text>string</text>\n" + "      </typeOrSource>\n" + "    </shelvingScheme>\n"
                + "    <shelvingOrder>\n" + "      <codeValue>string</codeValue>\n"
                + "      <fullValue>string</fullValue>\n" + "      <typeOrSource>\n"
                + "        <pointer>http://www.your.com/tempestatesque/e</pointer>\n"
                + "        <text>string</text>\n" + "      </typeOrSource>\n" + "    </shelvingOrder>\n"
                + "  </callNumber>\n" + "</oleHoldings>\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/holdingsFile/jcr:content/jcr:encoding = \n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/holdingsFile/jcr:content/jcr:mimeType = application/xml\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/holdingsFile/jcr:content/jcr:lastModified = 2012-12-15T11:45:31.382+05:30\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/holdingsFile/jcr:content/jcr:primaryType = nt:resource\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/sourceHoldingsFile\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/sourceHoldingsFile/lastUpdated = 2012-12-15T11:45:31.382+05:30\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/sourceHoldingsFile/jcr:uuid = badbabde-57bd-418d-95e0-4afc0aa7a3de\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/sourceHoldingsFile/jcr:createdBy = ole-khuntley\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/sourceHoldingsFile/jcr:mixinTypes = mix:referenceable\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/sourceHoldingsFile/dateEntered = 2012-12-15T11:45:31.382+05:30\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/sourceHoldingsFile/jcr:created = 2012-12-15T11:45:31.382+05:30\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/sourceHoldingsFile/jcr:primaryType = olefile\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/sourceHoldingsFile/jcr:content\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/sourceHoldingsFile/jcr:content/jcr:lastModifiedBy = ole-khuntley\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/sourceHoldingsFile/jcr:content/jcr:uuid = 9fa0cd37-f5d0-47dd-9bc6-0fc9978e3f4c\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/sourceHoldingsFile/jcr:content/jcr:data = <sourceHoldings primary=\"string\">\n"
                + "  <holdingsIdentifier>badbabde-57bd-418d-95e0-4afc0aa7a3de</holdingsIdentifier>\n"
                + "  <name>string</name>\n" + "  <holdings/>\n" + "  <extension displayLabel=\"string\"/>\n"
                + "</sourceHoldings>\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/sourceHoldingsFile/jcr:content/jcr:encoding = \n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/sourceHoldingsFile/jcr:content/jcr:mimeType = application/xml\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/sourceHoldingsFile/jcr:content/jcr:lastModified = 2012-12-15T11:45:31.382+05:30\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/sourceHoldingsFile/jcr:content/jcr:primaryType = nt:resource\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/itemFile\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/itemFile/lastUpdated = 2012-12-15T11:45:31.382+05:30\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/itemFile/jcr:uuid = a500a6ed-41fd-4225-adaf-52fb6b60f8ce\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/itemFile/jcr:createdBy = ole-khuntley\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/itemFile/jcr:mixinTypes = mix:referenceable\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/itemFile/dateEntered = 2012-12-15T11:45:31.382+05:30\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/itemFile/jcr:created = 2012-12-15T11:45:31.382+05:30\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/itemFile/jcr:primaryType = olefile\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/itemFile/jcr:content\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/itemFile/jcr:content/jcr:lastModifiedBy = ole-khuntley\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/itemFile/jcr:content/jcr:uuid = 9de25d21-a0c3-4f80-b443-ec68533c7866\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/itemFile/jcr:content/jcr:data = <item analytic=\"string\" resourceIdentifier=\"string\">\n"
                + "  <itemIdentifier>a500a6ed-41fd-4225-adaf-52fb6b60f8ce</itemIdentifier>\n"
                + "  <purchaseOrderLineItemIdentifier>string</purchaseOrderLineItemIdentifier>\n"
                + "  <vendorLineItemIdentifier>string</vendorLineItemIdentifier>\n" + "  <accessInformation>\n"
                + "    <barcode>string</barcode>\n" + "    <uri resolvable=\"string\">string</uri>\n"
                + "  </accessInformation>\n" + "  <barcodeARSL>string</barcodeARSL>\n" + "  <formerIdentifier>\n"
                + "    <identifier source=\"string\">\n" + "      <identifierValue>string</identifierValue>\n"
                + "    </identifier>\n" + "    <identifierType>string</identifierType>\n"
                + "  </formerIdentifier>\n" + "  <statisticalSearchingCode>\n"
                + "    <codeValue>string</codeValue>\n" + "    <fullValue>string</fullValue>\n"
                + "    <typeOrSource>\n" + "      <pointer>http://www.your.com/tempestatesque/e</pointer>\n"
                + "      <text>string</text>\n" + "    </typeOrSource>\n" + "  </statisticalSearchingCode>\n"
                + "  <itemType>\n" + "    <codeValue>string</codeValue>\n" + "    <fullValue>string</fullValue>\n"
                + "    <typeOrSource>\n" + "      <pointer>http://www.test.com/gero/nimborum</pointer>\n"
                + "      <text>string</text>\n" + "    </typeOrSource>\n" + "  </itemType>\n" + "  <location>\n"
                + "    <locationLevel>\n" + "      <name>string</name>\n" + "      <level>string</level>\n"
                + "      <locationLevel/>\n" + "    </locationLevel>\n" + "  </location>\n"
                + "  <copyNumber>string</copyNumber>\n" + "  <copyNumberLabel>string</copyNumberLabel>\n"
                + "  <volumeNumber>string</volumeNumber>\n" + "  <volumeNumberLabel>string</volumeNumberLabel>\n"
                + "  <note type=\"string\">string</note>\n" + "  <enumeration>string</enumeration>\n"
                + "  <chronology>string</chronology>\n" + "  <temporaryItemType>\n" + "    <codeValue>string</codeValue>\n"
                + "    <fullValue>string</fullValue>\n" + "    <typeOrSource>\n"
                + "      <pointer>http://www.test.org/montis/flammato</pointer>\n" + "      <text>string</text>\n"
                + "    </typeOrSource>\n" + "  </temporaryItemType>\n" + "  <fund>string</fund>\n"
                + "  <donorPublicDisplay>string</donorPublicDisplay>\n" + "  <donorNote>string</donorNote>\n"
                + "  <callNumber>\n" + "    <type>string</type>\n" + "    <prefix>string</prefix>\n"
                + "    <number>string</number>\n" + "    <classificationPart>string</classificationPart>\n"
                + "    <itemPart>string</itemPart>\n" + "    <shelvingScheme>\n"
                + "      <codeValue>string</codeValue>\n" + "      <fullValue>string</fullValue>\n"
                + "      <typeOrSource>\n" + "        <pointer>http://www.test.com/gero/nimborum</pointer>\n"
                + "        <text>string</text>\n" + "      </typeOrSource>\n" + "    </shelvingScheme>\n"
                + "    <shelvingOrder>\n" + "      <codeValue>string</codeValue>\n"
                + "      <fullValue>string</fullValue>\n" + "      <typeOrSource>\n"
                + "        <pointer>http://www.test.com/metuens/montis</pointer>\n"
                + "        <text>string</text>\n" + "      </typeOrSource>\n" + "    </shelvingOrder>\n"
                + "  </callNumber>\n" + "  <price>string</price>\n"
                + "  <numberOfPieces>string</numberOfPieces>\n" + "  <itemStatus>string</itemStatus>\n"
                + "  <itemStatusEffectiveDate>string</itemStatusEffectiveDate>\n"
                + "  <checkinNote>string</checkinNote>\n" + "  <staffOnlyFlag>true</staffOnlyFlag>\n"
                + "  <fastAddFlag>false</fastAddFlag>\n" + "  <extension displayLabel=\"string\"/>\n"
                + "</item>\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/itemFile/jcr:content/jcr:encoding = \n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/itemFile/jcr:content/jcr:mimeType = application/xml\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/itemFile/jcr:content/jcr:lastModified = 2012-12-15T11:45:31.382+05:30\n"
                + "/work/instance/oleml/l1/l2/instanceNode/holdingsNode/itemFile/jcr:content/jcr:primaryType = nt:resource\n"
                + "/work/instance/oleml/l1/l2/instanceNode/instanceFile\n"
                + "/work/instance/oleml/l1/l2/instanceNode/instanceFile/lastUpdated = 2012-12-15T11:45:31.366+05:30\n"
                + "/work/instance/oleml/l1/l2/instanceNode/instanceFile/jcr:uuid = 4d2a1328-1935-4c51-9514-13dbea776557\n"
                + "/work/instance/oleml/l1/l2/instanceNode/instanceFile/jcr:createdBy = ole-khuntley\n"
                + "/work/instance/oleml/l1/l2/instanceNode/instanceFile/jcr:mixinTypes = mix:referenceable\n"
                + "/work/instance/oleml/l1/l2/instanceNode/instanceFile/dateEntered = 2012-12-15T11:45:31.366+05:30\n"
                + "/work/instance/oleml/l1/l2/instanceNode/instanceFile/jcr:created = 2012-12-15T11:45:31.366+05:30\n"
                + "/work/instance/oleml/l1/l2/instanceNode/instanceFile/jcr:primaryType = olefile\n"
                + "/work/instance/oleml/l1/l2/instanceNode/instanceFile/jcr:content\n"
                + "/work/instance/oleml/l1/l2/instanceNode/instanceFile/jcr:content/jcr:lastModifiedBy = ole-khuntley\n"
                + "/work/instance/oleml/l1/l2/instanceNode/instanceFile/jcr:content/jcr:uuid = 8110849f-e65f-4da1-ae21-cbda5af00bd6\n"
                + "/work/instance/oleml/l1/l2/instanceNode/instanceFile/jcr:content/jcr:data = <instanceCollection>\n"
                + "  <instance>\n"
                + "    <instanceIdentifier>0d3ae26d-03c4-4c0a-9c1b-39e62865cb12</instanceIdentifier>\n"
                + "    <resourceIdentifier>cec0e2ba-bce3-411d-aeae-85b817d81f2b</resourceIdentifier>\n"
                + "    <formerResourceIdentifier>\n" + "      <identifier source=\"string\">\n"
                + "        <identifierValue>string</identifierValue>\n" + "      </identifier>\n"
                + "      <identifierType>string</identifierType>\n" + "    </formerResourceIdentifier>\n"
                + "    <extension displayLabel=\"string\"/>\n" + "  </instance>\n" + "</instanceCollection>\n"
                + "/work/instance/oleml/l1/l2/instanceNode/instanceFile/jcr:content/jcr:encoding = \n"
                + "/work/instance/oleml/l1/l2/instanceNode/instanceFile/jcr:content/jcr:mimeType = application/xml\n"
                + "/work/instance/oleml/l1/l2/instanceNode/instanceFile/jcr:content/jcr:lastModified = 2012-12-15T11:45:31.382+05:30\n"
                + "/work/instance/oleml/l1/l2/instanceNode/instanceFile/jcr:content/jcr:primaryType = nt:resource\n"
                + "/security\n" + "/security/jcr:uuid = 531b5df1-e7bd-4a83-a7ba-bb3fdf1e8002\n"
                + "/security/jcr:mixinTypes = mix:referenceable\n" + "/security/nodeType = folder\n"
                + "/security/jcr:primaryType = nt:unstructured";
        RepositoryData repositoryData = new RepositoryData();
        RepositoryData repositoryData1 = repositoryData.loadDump(dump);
        repositoryData.getRepositoryDump(repositoryData1);
    }

}
