TRUNCATE TABLE AP_ELCTRNC_INV_RJT_REAS_TYP_T
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('AGUV','571BED533A4BD43AE0404F8189D80FA4',1.0,'Invoice item unit cost is greater than the allowed upper variance','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('ALLV','571BED533A4CD43AE0404F8189D80FA4',1.0,'Invoice item unit cost is lower than the allowed lower variance','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('CSEM','571BED533A4AD43AE0404F8189D80FA4',1.0,'Both upper and lower variance unit price is empty','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('DSAM','571BED533A37D43AE0404F8189D80FA4',1.0,'Invoice item total discount amount does not match with the summary discount amount','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('EASC','571BED533A52D43AE0404F8189D80FA4',1.0,'Error adding namespace to the invoice file','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('EIDU','571BED533A4DD43AE0404F8189D80FA4',1.0,'Invoice has potential duplicate for the invoice number','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('HIIO','571BED533A2CD43AE0404F8189D80FA4',1.0,'File is in CXML Header Format','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('ICSL','571BED533A41D43AE0404F8189D80FA4',1.0,'More than one Invoice item contains the same item line number','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('IDAG','571BED533A32D43AE0404F8189D80FA4',1.0,'Invoice date is greater than the current date','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('IDIV','571BED533A31D43AE0404F8189D80FA4',1.0,'Invalid invoice Date','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('IICN','571BED533A43D43AE0404F8189D80FA4',1.0,'Invoice item catalog number does not match with Kuali item catalog number','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('IIDE','571BED533A30D43AE0404F8189D80FA4',1.0,'Invalid Invoice ID','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('IIQE','571BED533A46D43AE0404F8189D80FA4',1.0,'Purchase order item has outstanding encumbered quantity but invoice quantity is empty','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('ILIA','571BED533A42D43AE0404F8189D80FA4',1.0,'Purchase Order Document has inactive line item due to Amendment','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('IMLI','571BED533A40D43AE0404F8189D80FA4',1.0,'Invoice item does not have a matching line item in Purchase Order document','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('IMNA','571BED533A35D43AE0404F8189D80FA4',1.0,'Invoice Item Mapping Table does not have record for Invoice Item Type Code','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('INDU','571BED533A2DD43AE0404F8189D80FA4',1.0,'Invalid Duns','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('INFF','571BED533A2ED43AE0404F8189D80FA4',1.0,'File is in invalid format','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('INFO','571BED533A2FD43AE0404F8189D80FA4',1.0,'Information only flag set','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('ITNA','571BED533A4ED43AE0404F8189D80FA4',1.0,'Invoice Item Mapping not available for the kuali item type code','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('IUOM','571BED533A44D43AE0404F8189D80FA4',1.0,'Invoice item UOM does not match with Purchase Order line item UOM','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('NFEX','571BED533A3AD43AE0404F8189D80FA4',1.0,'Invoice has an invalid number field data','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('NODU','571BED533A34D43AE0404F8189D80FA4',1.0,'DUNS number not found','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('NOIV','571BED533A33D43AE0404F8189D80FA4',1.0,'File does not contain any Invoice information','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('PAIA','571BED533A49D43AE0404F8189D80FA4',1.0,'Purchase order item outstanding encumbered amount is less than invoice item amount','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('PILI','571BED533A47D43AE0404F8189D80FA4',1.0,'Purchase order item outstanding encumbered order quantity is less than invoice item quantity','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('POIE','571BED533A3BD43AE0404F8189D80FA4',1.0,'Invoice Purchase Order Number is empty','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('POII','571BED533A3CD43AE0404F8189D80FA4',1.0,'Invoice Purchase Order Number is an Invalid Number','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('PONE','571BED533A3DD43AE0404F8189D80FA4',1.0,'Purchase order document does not exists for the Invoice Purchase Order Number','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('PONO','571BED533A3FD43AE0404F8189D80FA4',1.0,'Purchase Order Document is not open and is not processible','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('PRDE','571BED533A51D43AE0404F8189D80FA4',1.0,'E-Invoice Matching Succeeded but PREQ creation failed due to E-Invoice discount processing on incorrect item (contact development team)','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('PRRF','571BED533A4FD43AE0404F8189D80FA4',1.0,'Invoice Matching Succeeded but PREQ routing failed','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('PRVE','571BED533A53D43AE0404F8189D80FA4',1.0,'E-Invoice Matching Succeeded but PREQ creation failed due to PREQ validation error(s)','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('PRWE','571BED533A50D43AE0404F8189D80FA4',1.0,'Workflow Error creating PREQ','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('PVNM','571BED533A3ED43AE0404F8189D80FA4',1.0,'Vendor from Kuali PO does not match with Electronic Invoice file vendor','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('SHSA','571BED533A38D43AE0404F8189D80FA4',1.0,'Invoice item total shipping amount does not match with the summary shipping amount','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('SSAM','571BED533A39D43AE0404F8189D80FA4',1.0,'Invoice item special handling tax amount does not match with the summary special handling amount','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('STLV','5975FDBC9EDD5371E0404F8189D86217',1.0,'Invoice item sales tax amount is lesser than the allowed lower variance sales tax amount','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('STNV','73DAB9B68F95F9BBE0404F8189D87C87',1.0,'Invoice summary sales tax amount was greater than zero, but sales tax is not allowed for this document ','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('STUV','5975FDBC9EDE5371E0404F8189D86217',1.0,'Invoice item sales tax amount is greater than the allowed upper variance sales tax amount','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('TSAM','571BED533A36D43AE0404F8189D80FA4',1.0,'Invoice item total tax amount does not match with the summary tax amount','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('UEAA','571BED533A48D43AE0404F8189D80FA4',1.0,'Purchase order item has outstanding encumbered amount','Y','Y','Y')
/
INSERT INTO AP_ELCTRNC_INV_RJT_REAS_TYP_T (INV_RJT_REAS_TYP_CD,OBJ_ID,VER_NBR,INV_RJT_REAS_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,INV_FAIL_IND,INV_RJT_REAS_PERF_MTCH_IND)
  VALUES ('UEOQ','571BED533A45D43AE0404F8189D80FA4',1.0,'Purchase order item has outstanding encumbered order quantity','Y','Y','Y')
/
