TRUNCATE TABLE CA_BALANCE_TYPE_T
/
INSERT INTO CA_BALANCE_TYPE_T (FIN_BALANCE_TYP_CD,OBJ_ID,VER_NBR,FIN_BALANCE_TYP_NM,FIN_BALTYP_SHRT_NM,FIN_OFFST_GNRTN_CD,FIN_BALTYP_ENC_CD,ROW_ACTV_IND)
  VALUES ('A2','014F3DAF83BCA448E043814FD28EA448',1.0,'A21 BALANCES - LABOR LEDGER ONLY','A21 BALANCES','Y','N','Y')
/
INSERT INTO CA_BALANCE_TYPE_T (FIN_BALANCE_TYP_CD,OBJ_ID,VER_NBR,FIN_BALANCE_TYP_NM,FIN_BALTYP_SHRT_NM,FIN_OFFST_GNRTN_CD,FIN_BALTYP_ENC_CD,ROW_ACTV_IND)
  VALUES ('AC','014F3DAF83BDA448E043814FD28EA448',1.0,'ACTUALS (BALANCE SHEET)','ACTUALS','Y','N','Y')
/
INSERT INTO CA_BALANCE_TYPE_T (FIN_BALANCE_TYP_CD,OBJ_ID,VER_NBR,FIN_BALANCE_TYP_NM,FIN_BALTYP_SHRT_NM,FIN_OFFST_GNRTN_CD,FIN_BALTYP_ENC_CD,ROW_ACTV_IND)
  VALUES ('BB','014F3DAF83BFA448E043814FD28EA448',1.0,'ADJUSTED BASE BUDGET','ADJ BSE BUDG','N','N','Y')
/
INSERT INTO CA_BALANCE_TYPE_T (FIN_BALANCE_TYP_CD,OBJ_ID,VER_NBR,FIN_BALANCE_TYP_NM,FIN_BALTYP_SHRT_NM,FIN_OFFST_GNRTN_CD,FIN_BALTYP_ENC_CD,ROW_ACTV_IND)
  VALUES ('CB','014F3DAF83C1A448E043814FD28EA448',1.0,'CURRENT BUDGET','CURRENT BUDG','N','N','Y')
/
INSERT INTO CA_BALANCE_TYPE_T (FIN_BALANCE_TYP_CD,OBJ_ID,VER_NBR,FIN_BALANCE_TYP_NM,FIN_BALTYP_SHRT_NM,FIN_OFFST_GNRTN_CD,FIN_BALTYP_ENC_CD,ROW_ACTV_IND)
  VALUES ('CE','014F3DAF83C2A448E043814FD28EA448',1.0,'COST SHARE ENCUMBRANCES','CST SHR ENCS','Y','Y','Y')
/
INSERT INTO CA_BALANCE_TYPE_T (FIN_BALANCE_TYP_CD,OBJ_ID,VER_NBR,FIN_BALANCE_TYP_NM,FIN_BALTYP_SHRT_NM,FIN_OFFST_GNRTN_CD,FIN_BALTYP_ENC_CD,ROW_ACTV_IND)
  VALUES ('EX','014F3DAF83C3A448E043814FD28EA448',1.0,'EXTERNAL ENCUMBRANCE','EXTERNAL ENC','Y','Y','Y')
/
INSERT INTO CA_BALANCE_TYPE_T (FIN_BALANCE_TYP_CD,OBJ_ID,VER_NBR,FIN_BALANCE_TYP_NM,FIN_BALTYP_SHRT_NM,FIN_OFFST_GNRTN_CD,FIN_BALTYP_ENC_CD,ROW_ACTV_IND)
  VALUES ('IE','014F3DAF83C4A448E043814FD28EA448',1.0,'INTERNAL ENCUMBRANCE','INTERNAL ENC','Y','Y','Y')
/
INSERT INTO CA_BALANCE_TYPE_T (FIN_BALANCE_TYP_CD,OBJ_ID,VER_NBR,FIN_BALANCE_TYP_NM,FIN_BALTYP_SHRT_NM,FIN_OFFST_GNRTN_CD,FIN_BALTYP_ENC_CD,ROW_ACTV_IND)
  VALUES ('MB','014F3DAF83C6A448E043814FD28EA448',1.0,'MONTHLY BUDGET','MONTHLY BUDG','N','N','Y')
/
INSERT INTO CA_BALANCE_TYPE_T (FIN_BALANCE_TYP_CD,OBJ_ID,VER_NBR,FIN_BALANCE_TYP_NM,FIN_BALTYP_SHRT_NM,FIN_OFFST_GNRTN_CD,FIN_BALTYP_ENC_CD,ROW_ACTV_IND)
  VALUES ('NB','014F3DAF83C7A448E043814FD28EA448',1.0,'CLOSE NOMINAL BALANCE','NOMINAL BAL','Y','N','Y')
/
INSERT INTO CA_BALANCE_TYPE_T (FIN_BALANCE_TYP_CD,OBJ_ID,VER_NBR,FIN_BALANCE_TYP_NM,FIN_BALTYP_SHRT_NM,FIN_OFFST_GNRTN_CD,FIN_BALTYP_ENC_CD,ROW_ACTV_IND)
  VALUES ('PE','014F3DAF83C8A448E043814FD28EA448',1.0,'PRE-ENCUMBRANCE','PRE-ENCUM','Y','Y','Y')
/
INSERT INTO CA_BALANCE_TYPE_T (FIN_BALANCE_TYP_CD,OBJ_ID,VER_NBR,FIN_BALANCE_TYP_NM,FIN_BALTYP_SHRT_NM,FIN_OFFST_GNRTN_CD,FIN_BALTYP_ENC_CD,ROW_ACTV_IND)
  VALUES ('RE','014F3DAF83C9A448E043814FD28EA448',1.0,'YEAR END BUDGET REVERSION','BUDG REVERT','N','N','Y')
/
INSERT INTO CA_BALANCE_TYPE_T (FIN_BALANCE_TYP_CD,OBJ_ID,VER_NBR,FIN_BALANCE_TYP_NM,FIN_BALTYP_SHRT_NM,FIN_OFFST_GNRTN_CD,FIN_BALTYP_ENC_CD,ROW_ACTV_IND)
  VALUES ('TR','014F3DAF83CAA448E043814FD28EA448',1.0,'TRANSFERS','TRANSFERS','Y','N','Y')
/
