TRUNCATE TABLE CA_HIGHR_ED_FUNC_T
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('AA','014F3DAF81ECA448E043814FD28EA448',1.0,'ACADEMIC ADMINISTRATION','AA','AS','IUR','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('AAOI','014F3DAF81EDA448E043814FD28EA448',1.0,'ACADEMIC ADMIN. OTHER INSTITUTIONAL ACTI','AA','AS','OIA','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('AC','014F3DAF81EEA448E043814FD28EA448',1.0,'ACADEMIC COMPUTING','AC','AS','OIA','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('AD','014F3DAF81EFA448E043814FD28EA448',1.0,'ACADEMIC DEVELOPMENT','AD','AS','IUR','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('AUX','014F3DAF81F0A448E043814FD28EA448',1.0,'AUXILIARY & SERVICES','AUX','AUX','OIA','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('AVS','014F3DAF81F1A448E043814FD28EA448',1.0,'AUDIO VISUAL SERVICES','AVS','AS','OIA','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('BS','014F3DAF81F2A448E043814FD28EA448',1.0,'BALANCE SHEET ACCOUNTS','IS','IS','GA','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('CS','014F3DAF81F3A448E043814FD28EA448',1.0,'COMMUNITY SERVICES','CS','PS','OIA','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('CSSR','014F3DAF81F4A448E043814FD28EA448',1.0,'COMMUNITY SERVICES-SPONSORED PROGRAMS','CS','PS','SPS','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('DR','309958D8D0E9011CE043814FD881011C',1.0,'DEPARTMENTAL RESEARCH','IN','IN','IUR','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('IN','014F3DAF81F5A448E043814FD28EA448',1.0,'INSTRUCTION','IN','IN','IUR','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('IPR','014F3DAF81F6A448E043814FD28EA448',1.0,'INDIVIDUAL OR PROJECT RESEARCH','IPR','RE','SR','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('IRC','014F3DAF81F7A448E043814FD28EA448',1.0,'INSTITUTES AND RESEARCH CENTERS','IRC','RE','IUR','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('IS','014F3DAF81F8A448E043814FD28EA448',1.0,'INSTITUTIONAL SUPPORT','IS','IS','GA','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('ISOI','014F3DAF81F9A448E043814FD28EA448',1.0,'INSTITUTIONAL SUPPORT-UNALLOW FED EXPENS','IS','IS','OIA','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('ISPP','014F3DAF81FAA448E043814FD28EA448',1.0,'INSTITUTIONAL SUPPORT PHYSICAL PLANT','IS','IS','PP','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('LIB','014F3DAF81FBA448E043814FD28EA448',1.0,'LIBRARIES','LIB','AS','LIB','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('M&G','014F3DAF81FCA448E043814FD28EA448',1.0,'MUSEUMS AND GALLERIES','M&G','AS','IUR','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('NA','014F3DAF81FDA448E043814FD28EA448',1.0,'NOT APPLICABLE TO ACCOUNT','NA','NA','NA','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('PBS','014F3DAF81FEA448E043814FD28EA448',1.0,'PUBLIC BROADCASTING SERVICES','PBS','PS','IUR','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('PBSP','014F3DAF81FFA448E043814FD28EA448',1.0,'PUBLIC BROADCASTING-SPONSORED PROGRAMS','PBS','PS','SPS','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('PP','014F3DAF8200A448E043814FD28EA448',1.0,'PHYSICAL PLANT','PP','PP','PP','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('PRD','014F3DAF8201A448E043814FD28EA448',1.0,'PUBLIC RELATIONS AND DEVELOPMENT','PRD','IS','OIA','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('PS','014F3DAF8202A448E043814FD28EA448',1.0,'PATIENT SERVICES','PS','PS','OIA','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('PSSR','014F3DAF8203A448E043814FD28EA448',1.0,'PATIENT SERVICES-SPONSORED PROGRAMS','PS','PS','SPS','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('S&F','014F3DAF8204A448E043814FD28EA448',1.0,'SCHOLARSHIPS & FELLOWSHIPS','S&F','S&F','SA','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('SCD','014F3DAF8205A448E043814FD28EA448',1.0,'SOCIAL AND CULTURAL DEVELOPMENT','SCD','SS','OIA','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('SPA','014F3DAF8206A448E043814FD28EA448',1.0,'SPONSORED PROGRAM AD.','SPA','IS','SPA','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('SRA','014F3DAF8207A448E043814FD28EA448',1.0,'STUDENT RECRUITMENT ADMISSIONS AND RECOR','SRA','IS','SAS','Y')
/
INSERT INTO CA_HIGHR_ED_FUNC_T (FIN_HGH_ED_FUNC_CD,OBJ_ID,VER_NBR,FIN_HGH_ED_FUNC_NM,FIN_UBO_FUNC_CD,FIN_AICPA_FUNC_CD,FIN_FED_FUNC_CD,ROW_ACTV_IND)
  VALUES ('SS','014F3DAF8208A448E043814FD28EA448',1.0,'STUDENT SERVICES','SS','SS','SAS','Y')
/
