TRUNCATE TABLE CA_SUB_FND_GRP_TYP_T
/
INSERT INTO CA_SUB_FND_GRP_TYP_T (SUB_FUNDGRP_TYP_CD,OBJ_ID,VER_NBR,SUB_FND_GRP_TYP_DESC,SUB_FND_GRP_TYP_ACTV_IND)
  VALUES ('A','18660FE81BDCA0EEE043814FD881A0EE',1.0,'AUXILIARY','Y')
/
INSERT INTO CA_SUB_FND_GRP_TYP_T (SUB_FUNDGRP_TYP_CD,OBJ_ID,VER_NBR,SUB_FND_GRP_TYP_DESC,SUB_FND_GRP_TYP_ACTV_IND)
  VALUES ('I','18660FE81BDDA0EEE043814FD881A0EE',1.0,'INTERNAL SERVICE ORGANIZATION','Y')
/
INSERT INTO CA_SUB_FND_GRP_TYP_T (SUB_FUNDGRP_TYP_CD,OBJ_ID,VER_NBR,SUB_FND_GRP_TYP_DESC,SUB_FND_GRP_TYP_ACTV_IND)
  VALUES ('N','18660FE81BDEA0EEE043814FD881A0EE',1.0,'NEITHER','Y')
/
