TRUNCATE TABLE OLE_PUR_PO_ERR_CDS_T
/
INSERT INTO OLE_PUR_PO_ERR_CDS_T (ERR_ID,ERROR,OBJ_ID,VER_NBR,ROW_ACT_IND)
  VALUES (1.0,'Duplicate Purchase Order Found','1',1.0,'Y')
/
INSERT INTO OLE_PUR_PO_ERR_CDS_T (ERR_ID,ERROR,OBJ_ID,VER_NBR,ROW_ACT_IND)
  VALUES (2.0,'Duplicate Bibliographic Description Found','2',1.0,'Y')
/
INSERT INTO OLE_PUR_PO_ERR_CDS_T (ERR_ID,ERROR,OBJ_ID,VER_NBR,ROW_ACT_IND)
  VALUES (3.0,'General Load Failure','3',1.0,'Y')
/
INSERT INTO OLE_PUR_PO_ERR_CDS_T (ERR_ID,ERROR,OBJ_ID,VER_NBR,ROW_ACT_IND)
  VALUES (4.0,'Title Not Found','4',1.0,'Y')
/
INSERT INTO OLE_PUR_PO_ERR_CDS_T (ERR_ID,ERROR,OBJ_ID,VER_NBR,ROW_ACT_IND)
  VALUES (5.0,'Duplicate Isbn Found','5',1.0,'Y')
/
INSERT INTO OLE_PUR_PO_ERR_CDS_T (ERR_ID,ERROR,OBJ_ID,VER_NBR,ROW_ACT_IND)
  VALUES (6.0,'Purchase Order Not Found','6',1.0,'Y')
/
INSERT INTO OLE_PUR_PO_ERR_CDS_T (ERR_ID,ERROR,OBJ_ID,VER_NBR,ROW_ACT_IND)
  VALUES (7.0,'BAD_BFN_NUMBER','7',1.0,'Y')
/
INSERT INTO OLE_PUR_PO_ERR_CDS_T (ERR_ID,ERROR,OBJ_ID,VER_NBR,ROW_ACT_IND)
  VALUES (8.0,'BAD_CONTROL_LINE','8',1.0,'Y')
/
INSERT INTO OLE_PUR_PO_ERR_CDS_T (ERR_ID,ERROR,OBJ_ID,VER_NBR,ROW_ACT_IND)
  VALUES (9.0,'APO_RULE_FAILED','9',1.0,'Y')
/
