TRUNCATE TABLE OLE_CURR_TYP_T
/
INSERT INTO OLE_CURR_TYP_T (OLE_CURR_TYP_ID,OLE_CURR_TYP,OLE_CURR_CNTRY,OLE_CURR_ALPHA_CD,OLE_CURR_NUM_CD,OLE_CURR_MIN_UN,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (1.0,'US Dollar','UNITED STATES','USD',840.0,'2',1.0,'1','Y')
/
INSERT INTO OLE_CURR_TYP_T (OLE_CURR_TYP_ID,OLE_CURR_TYP,OLE_CURR_CNTRY,OLE_CURR_ALPHA_CD,OLE_CURR_NUM_CD,OLE_CURR_MIN_UN,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (2.0,'Australian Dollar','AUSTRALIA','AUD',36.0,'2',1.0,'2','Y')
/
INSERT INTO OLE_CURR_TYP_T (OLE_CURR_TYP_ID,OLE_CURR_TYP,OLE_CURR_CNTRY,OLE_CURR_ALPHA_CD,OLE_CURR_NUM_CD,OLE_CURR_MIN_UN,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (3.0,'Brazilian Real','BRAZIL','BRL',986.0,'2',1.0,'3','Y')
/
INSERT INTO OLE_CURR_TYP_T (OLE_CURR_TYP_ID,OLE_CURR_TYP,OLE_CURR_CNTRY,OLE_CURR_ALPHA_CD,OLE_CURR_NUM_CD,OLE_CURR_MIN_UN,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (4.0,'Canadian Dollar','CANADA','CAD',124.0,'2',1.0,'4','Y')
/
INSERT INTO OLE_CURR_TYP_T (OLE_CURR_TYP_ID,OLE_CURR_TYP,OLE_CURR_CNTRY,OLE_CURR_ALPHA_CD,OLE_CURR_NUM_CD,OLE_CURR_MIN_UN,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (5.0,'Yuan Renminbi','CHINA','CNY',156.0,'2',1.0,'5','Y')
/
INSERT INTO OLE_CURR_TYP_T (OLE_CURR_TYP_ID,OLE_CURR_TYP,OLE_CURR_CNTRY,OLE_CURR_ALPHA_CD,OLE_CURR_NUM_CD,OLE_CURR_MIN_UN,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (6.0,'Danish Krone','DENMARK','DKK',208.0,'2',1.0,'6','Y')
/
INSERT INTO OLE_CURR_TYP_T (OLE_CURR_TYP_ID,OLE_CURR_TYP,OLE_CURR_CNTRY,OLE_CURR_ALPHA_CD,OLE_CURR_NUM_CD,OLE_CURR_MIN_UN,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (7.0,'Hong Kong Dollar','HONG KONG','HKD',344.0,'2',1.0,'7','Y')
/
INSERT INTO OLE_CURR_TYP_T (OLE_CURR_TYP_ID,OLE_CURR_TYP,OLE_CURR_CNTRY,OLE_CURR_ALPHA_CD,OLE_CURR_NUM_CD,OLE_CURR_MIN_UN,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (8.0,'Indian Rupee','INDIA','INR',356.0,'2',1.0,'8','Y')
/
INSERT INTO OLE_CURR_TYP_T (OLE_CURR_TYP_ID,OLE_CURR_TYP,OLE_CURR_CNTRY,OLE_CURR_ALPHA_CD,OLE_CURR_NUM_CD,OLE_CURR_MIN_UN,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (9.0,'Yen','JAPAN','JPY',392.0,'0',1.0,'9','Y')
/
INSERT INTO OLE_CURR_TYP_T (OLE_CURR_TYP_ID,OLE_CURR_TYP,OLE_CURR_CNTRY,OLE_CURR_ALPHA_CD,OLE_CURR_NUM_CD,OLE_CURR_MIN_UN,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (10.0,'Mexican Peso','MEXICO','MXN',484.0,'2',1.0,'11','Y')
/
INSERT INTO OLE_CURR_TYP_T (OLE_CURR_TYP_ID,OLE_CURR_TYP,OLE_CURR_CNTRY,OLE_CURR_ALPHA_CD,OLE_CURR_NUM_CD,OLE_CURR_MIN_UN,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (11.0,'New Zealand Dollar','NEW ZEALAND','NZD',554.0,'2',1.0,'12','Y')
/
INSERT INTO OLE_CURR_TYP_T (OLE_CURR_TYP_ID,OLE_CURR_TYP,OLE_CURR_CNTRY,OLE_CURR_ALPHA_CD,OLE_CURR_NUM_CD,OLE_CURR_MIN_UN,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (12.0,'Norwegian Krone','NORWAY','NOK',578.0,'2',1.0,'13','Y')
/
INSERT INTO OLE_CURR_TYP_T (OLE_CURR_TYP_ID,OLE_CURR_TYP,OLE_CURR_CNTRY,OLE_CURR_ALPHA_CD,OLE_CURR_NUM_CD,OLE_CURR_MIN_UN,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (13.0,'Singapore Dollar','SINGAPORE','SGD',702.0,'2',1.0,'14','Y')
/
INSERT INTO OLE_CURR_TYP_T (OLE_CURR_TYP_ID,OLE_CURR_TYP,OLE_CURR_CNTRY,OLE_CURR_ALPHA_CD,OLE_CURR_NUM_CD,OLE_CURR_MIN_UN,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (14.0,'Rand','SOUTH AFRICA','ZAR',710.0,'2',1.0,'15','Y')
/
INSERT INTO OLE_CURR_TYP_T (OLE_CURR_TYP_ID,OLE_CURR_TYP,OLE_CURR_CNTRY,OLE_CURR_ALPHA_CD,OLE_CURR_NUM_CD,OLE_CURR_MIN_UN,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (15.0,'Swedish Krona','SWEDEN','SEK',752.0,'2',1.0,'17','Y')
/
INSERT INTO OLE_CURR_TYP_T (OLE_CURR_TYP_ID,OLE_CURR_TYP,OLE_CURR_CNTRY,OLE_CURR_ALPHA_CD,OLE_CURR_NUM_CD,OLE_CURR_MIN_UN,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (16.0,'Swiss Franc','SWITZERLAND','CHF',756.0,'2',1.0,'18','Y')
/
INSERT INTO OLE_CURR_TYP_T (OLE_CURR_TYP_ID,OLE_CURR_TYP,OLE_CURR_CNTRY,OLE_CURR_ALPHA_CD,OLE_CURR_NUM_CD,OLE_CURR_MIN_UN,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (17.0,'New Taiwan Dollar','TAIWAN, PROVINCE OF CHINA','TWD',901.0,'2',1.0,'19','Y')
/
INSERT INTO OLE_CURR_TYP_T (OLE_CURR_TYP_ID,OLE_CURR_TYP,OLE_CURR_CNTRY,OLE_CURR_ALPHA_CD,OLE_CURR_NUM_CD,OLE_CURR_MIN_UN,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (18.0,'Baht','THAILAND','THB',764.0,'2',1.0,'20','Y')
/
INSERT INTO OLE_CURR_TYP_T (OLE_CURR_TYP_ID,OLE_CURR_TYP,OLE_CURR_CNTRY,OLE_CURR_ALPHA_CD,OLE_CURR_NUM_CD,OLE_CURR_MIN_UN,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (19.0,'Pound Sterling','UNITED KINGDOM','GBP',826.0,'2',1.0,'21','Y')
/
INSERT INTO OLE_CURR_TYP_T (OLE_CURR_TYP_ID,OLE_CURR_TYP,OLE_CURR_CNTRY,OLE_CURR_ALPHA_CD,OLE_CURR_NUM_CD,OLE_CURR_MIN_UN,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (20.0,'Euro','EUROPEAN UNION','EUR',978.0,'2',1.0,'23','Y')
/
