TRUNCATE TABLE PUR_AP_RECUR_PMT_TYP_T
/
INSERT INTO PUR_AP_RECUR_PMT_TYP_T (RECUR_PMT_TYP_CD,OBJ_ID,VER_NBR,RECUR_PMT_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND)
  VALUES ('FIXD','2D6D987C-8141-912E-BC34-EB204477CB33',1.0,'FIXED SCHEDULE, FIXED AMOUNT','Y')
/
INSERT INTO PUR_AP_RECUR_PMT_TYP_T (RECUR_PMT_TYP_CD,OBJ_ID,VER_NBR,RECUR_PMT_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND)
  VALUES ('FVAR','B06FD9B2-F852-8EEA-7A62-AD8DBC695D28',1.0,'FIXED SCHEDULE, VARIABLE AMOUNT','Y')
/
INSERT INTO PUR_AP_RECUR_PMT_TYP_T (RECUR_PMT_TYP_CD,OBJ_ID,VER_NBR,RECUR_PMT_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND)
  VALUES ('VARV','08FD73AE-8160-2FE2-D9CF-7241A9649C4A',1.0,'VARIABLE SCHEDULE, VARIABLE AMOUNT','Y')
/
