TRUNCATE TABLE PUR_PO_VNDR_CHC_T
/
INSERT INTO PUR_PO_VNDR_CHC_T (PO_VNDR_CHC_CD,OBJ_ID,VER_NBR,PO_VNDR_CHC_DESC,DOBJ_MAINT_CD_ACTV_IND)
  VALUES ('CNST','posdifiri87if784369743ioeru',0.0,'Construction','Y')
/
INSERT INTO PUR_PO_VNDR_CHC_T (PO_VNDR_CHC_CD,OBJ_ID,VER_NBR,PO_VNDR_CHC_DESC,DOBJ_MAINT_CD_ACTV_IND)
  VALUES ('CONF','posdifiri87if784xe9743ioeru',0.0,'Conference/Hospitality','Y')
/
INSERT INTO PUR_PO_VNDR_CHC_T (PO_VNDR_CHC_CD,OBJ_ID,VER_NBR,PO_VNDR_CHC_DESC,DOBJ_MAINT_CD_ACTV_IND)
  VALUES ('CONT','posdifiri87if784479743ioeru',0.0,'Contracted Price','Y')
/
INSERT INTO PUR_PO_VNDR_CHC_T (PO_VNDR_CHC_CD,OBJ_ID,VER_NBR,PO_VNDR_CHC_DESC,DOBJ_MAINT_CD_ACTV_IND)
  VALUES ('DESN','posdifiri87if784e49743ioeru',0.0,'Design Required by Department','Y')
/
INSERT INTO PUR_PO_VNDR_CHC_T (PO_VNDR_CHC_CD,OBJ_ID,VER_NBR,PO_VNDR_CHC_DESC,DOBJ_MAINT_CD_ACTV_IND)
  VALUES ('FCLR','posdifiri87if784ld9743ioeru',0.0,'Franchise, Copyright, License','Y')
/
INSERT INTO PUR_PO_VNDR_CHC_T (PO_VNDR_CHC_CD,OBJ_ID,VER_NBR,PO_VNDR_CHC_DESC,DOBJ_MAINT_CD_ACTV_IND)
  VALUES ('GRAN','posdifiri87if7844i9743ioeru',0.0,'Grant Specified','Y')
/
INSERT INTO PUR_PO_VNDR_CHC_T (PO_VNDR_CHC_CD,OBJ_ID,VER_NBR,PO_VNDR_CHC_DESC,DOBJ_MAINT_CD_ACTV_IND)
  VALUES ('INTG','posdifiri87if7849o9743ioeru',0.0,'Integrate with Existing Facility','Y')
/
INSERT INTO PUR_PO_VNDR_CHC_T (PO_VNDR_CHC_CD,OBJ_ID,VER_NBR,PO_VNDR_CHC_DESC,DOBJ_MAINT_CD_ACTV_IND)
  VALUES ('LPRC','posdifiri87if7843z9743ioeru',0.0,'Lowest Price','Y')
/
INSERT INTO PUR_PO_VNDR_CHC_T (PO_VNDR_CHC_CD,OBJ_ID,VER_NBR,PO_VNDR_CHC_DESC,DOBJ_MAINT_CD_ACTV_IND)
  VALUES ('ONLY','posdifiri87if7845c9743ioeru',0.0,'Only Known Source','Y')
/
INSERT INTO PUR_PO_VNDR_CHC_T (PO_VNDR_CHC_CD,OBJ_ID,VER_NBR,PO_VNDR_CHC_DESC,DOBJ_MAINT_CD_ACTV_IND)
  VALUES ('OTHR','posdifiri87if784799743ioeru',0.0,'Other','Y')
/
INSERT INTO PUR_PO_VNDR_CHC_T (PO_VNDR_CHC_CD,OBJ_ID,VER_NBR,PO_VNDR_CHC_DESC,DOBJ_MAINT_CD_ACTV_IND)
  VALUES ('PROF','posdifiri87if784fl9743ioeru',0.0,'Professional Service','Y')
/
INSERT INTO PUR_PO_VNDR_CHC_T (PO_VNDR_CHC_CD,OBJ_ID,VER_NBR,PO_VNDR_CHC_DESC,DOBJ_MAINT_CD_ACTV_IND)
  VALUES ('SMAI','posdifiri87if784qr9743ioeru',0.0,'Service, Maintenance, Parts','Y')
/
INSERT INTO PUR_PO_VNDR_CHC_T (PO_VNDR_CHC_CD,OBJ_ID,VER_NBR,PO_VNDR_CHC_DESC,DOBJ_MAINT_CD_ACTV_IND)
  VALUES ('SMAL','posdifiri87if784y09743ioeru',0.0,'Small Order (under $5,000)','Y')
/
INSERT INTO PUR_PO_VNDR_CHC_T (PO_VNDR_CHC_CD,OBJ_ID,VER_NBR,PO_VNDR_CHC_DESC,DOBJ_MAINT_CD_ACTV_IND)
  VALUES ('SRVC','posdifiri87if784ry9743ioeru',0.0,'Services Maintenance by Manufacturer','Y')
/
INSERT INTO PUR_PO_VNDR_CHC_T (PO_VNDR_CHC_CD,OBJ_ID,VER_NBR,PO_VNDR_CHC_DESC,DOBJ_MAINT_CD_ACTV_IND)
  VALUES ('SUBC','posdifiri87if784u89743ioeru',0.0,'Subcontract','Y')
/
INSERT INTO PUR_PO_VNDR_CHC_T (PO_VNDR_CHC_CD,OBJ_ID,VER_NBR,PO_VNDR_CHC_DESC,DOBJ_MAINT_CD_ACTV_IND)
  VALUES ('UTIL','posdifiri87if784rm9743ioeru',0.0,'Utility','Y')
/
