TRUNCATE TABLE PUR_SHP_SPCL_COND_T
/
INSERT INTO PUR_SHP_SPCL_COND_T (VNDR_SHP_SPCL_COND_CD,OBJ_ID,VER_NBR,VNDR_SHP_SPCL_COND_DESC,DOBJ_MAINT_CD_ACTV_IND)
  VALUES ('EX','3D7B56B1-57E7-3FEC-BCBC-140E442B8CCE',7.0,'EXPRESS','Y')
/
INSERT INTO PUR_SHP_SPCL_COND_T (VNDR_SHP_SPCL_COND_CD,OBJ_ID,VER_NBR,VNDR_SHP_SPCL_COND_DESC,DOBJ_MAINT_CD_ACTV_IND)
  VALUES ('IN','07B10B5F-8065-CFA7-3D1C-5FB6DD77E343',1.0,'INSURED','Y')
/
