TRUNCATE TABLE PUR_AP_ITM_TYP_T
/
INSERT INTO PUR_AP_ITM_TYP_T (ITM_TYP_CD,OBJ_ID,VER_NBR,ITM_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,QTY_BSD_GL_IND,ITM_TYP_ADDL_CHRG_IND,TAXABLE_IND)
  VALUES ('DISC','2140BCA5-2D8D-F8EE-F29A-5231DE6EFFB7',1.0,'Payment Terms Discount','Y','N','Y','Y')
/
INSERT INTO PUR_AP_ITM_TYP_T (ITM_TYP_CD,OBJ_ID,VER_NBR,ITM_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,QTY_BSD_GL_IND,ITM_TYP_ADDL_CHRG_IND,TAXABLE_IND)
  VALUES ('EXMT','17',1.0,'Exempt','Y','Y','N','N')
/
INSERT INTO PUR_AP_ITM_TYP_T (ITM_TYP_CD,OBJ_ID,VER_NBR,ITM_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,QTY_BSD_GL_IND,ITM_TYP_ADDL_CHRG_IND,TAXABLE_IND)
  VALUES ('FDGR','9A040B34-B954-0ABC-DF59-6521DEB0919C',1.0,'Federal Tax Gross-Up','Y','N','Y','Y')
/
INSERT INTO PUR_AP_ITM_TYP_T (ITM_TYP_CD,OBJ_ID,VER_NBR,ITM_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,QTY_BSD_GL_IND,ITM_TYP_ADDL_CHRG_IND,TAXABLE_IND)
  VALUES ('FDTX','3F1E1EBA-AC7D-72D8-2532-5705C399D8E0',3.0,'Federal Tax','Y','N','Y','Y')
/
INSERT INTO PUR_AP_ITM_TYP_T (ITM_TYP_CD,OBJ_ID,VER_NBR,ITM_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,QTY_BSD_GL_IND,ITM_TYP_ADDL_CHRG_IND,TAXABLE_IND)
  VALUES ('FRHT','F9DCA11A-CD24-F961-EE26-12B1C31D0360',1.0,'Freight','Y','N','Y','Y')
/
INSERT INTO PUR_AP_ITM_TYP_T (ITM_TYP_CD,OBJ_ID,VER_NBR,ITM_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,QTY_BSD_GL_IND,ITM_TYP_ADDL_CHRG_IND,TAXABLE_IND)
  VALUES ('INSU','19',1.0,'Insurance','Y','N','Y','Y')
/
INSERT INTO PUR_AP_ITM_TYP_T (ITM_TYP_CD,OBJ_ID,VER_NBR,ITM_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,QTY_BSD_GL_IND,ITM_TYP_ADDL_CHRG_IND,TAXABLE_IND)
  VALUES ('ITEM','F7C44E14-1128-60C6-71BA-151F4E113733',2.0,'Qty','Y','Y','N','Y')
/
INSERT INTO PUR_AP_ITM_TYP_T (ITM_TYP_CD,OBJ_ID,VER_NBR,ITM_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,QTY_BSD_GL_IND,ITM_TYP_ADDL_CHRG_IND,TAXABLE_IND)
  VALUES ('MISC','4511536F-C4FE-7C47-D3D9-3CD2D755C920',1.0,'Miscellaneous or Overhead','Y','N','Y','Y')
/
INSERT INTO PUR_AP_ITM_TYP_T (ITM_TYP_CD,OBJ_ID,VER_NBR,ITM_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,QTY_BSD_GL_IND,ITM_TYP_ADDL_CHRG_IND,TAXABLE_IND)
  VALUES ('MNOR','4145ED99-905A-9CD0-202F-44F79B34BF9B',1.0,'Minimum Order','Y','N','Y','Y')
/
INSERT INTO PUR_AP_ITM_TYP_T (ITM_TYP_CD,OBJ_ID,VER_NBR,ITM_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,QTY_BSD_GL_IND,ITM_TYP_ADDL_CHRG_IND,TAXABLE_IND)
  VALUES ('MSCR','26BF335C-A987-6244-0262-84E6C2DCEF03',1.0,'Miscellaneous Credit','Y','N','Y','Y')
/
INSERT INTO PUR_AP_ITM_TYP_T (ITM_TYP_CD,OBJ_ID,VER_NBR,ITM_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,QTY_BSD_GL_IND,ITM_TYP_ADDL_CHRG_IND,TAXABLE_IND)
  VALUES ('ORDS','BF44B7E5-D9E2-215A-55BE-7619F9614426',1.0,'Full Order Discount','Y','N','Y','Y')
/
INSERT INTO PUR_AP_ITM_TYP_T (ITM_TYP_CD,OBJ_ID,VER_NBR,ITM_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,QTY_BSD_GL_IND,ITM_TYP_ADDL_CHRG_IND,TAXABLE_IND)
  VALUES ('OVER','18',1.0,'Overhead','Y','N','Y','Y')
/
INSERT INTO PUR_AP_ITM_TYP_T (ITM_TYP_CD,OBJ_ID,VER_NBR,ITM_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,QTY_BSD_GL_IND,ITM_TYP_ADDL_CHRG_IND,TAXABLE_IND)
  VALUES ('RSTO','745F4C4C-08C4-B568-0206-CD6AA34C8D96',1.0,'Less Restocking Fee','Y','N','Y','Y')
/
INSERT INTO PUR_AP_ITM_TYP_T (ITM_TYP_CD,OBJ_ID,VER_NBR,ITM_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,QTY_BSD_GL_IND,ITM_TYP_ADDL_CHRG_IND,TAXABLE_IND)
  VALUES ('SPHD','15BD285E-34F7-5AF4-5B73-0E99840CE750',1.0,'Shipping and Handling','Y','N','Y','Y')
/
INSERT INTO PUR_AP_ITM_TYP_T (ITM_TYP_CD,OBJ_ID,VER_NBR,ITM_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,QTY_BSD_GL_IND,ITM_TYP_ADDL_CHRG_IND,TAXABLE_IND)
  VALUES ('SRVC','247F9EB07E9C6134E043814FD8816134',1.0,'No Qty','Y','N','N','Y')
/
INSERT INTO PUR_AP_ITM_TYP_T (ITM_TYP_CD,OBJ_ID,VER_NBR,ITM_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,QTY_BSD_GL_IND,ITM_TYP_ADDL_CHRG_IND,TAXABLE_IND)
  VALUES ('STGR','4F1A90CC-6FA0-DBD9-4AF7-396FB41A1499',1.0,'State Tax Gross-Up','Y','N','Y','Y')
/
INSERT INTO PUR_AP_ITM_TYP_T (ITM_TYP_CD,OBJ_ID,VER_NBR,ITM_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,QTY_BSD_GL_IND,ITM_TYP_ADDL_CHRG_IND,TAXABLE_IND)
  VALUES ('STTX','F026215A-B174-7418-34E3-A742B5EFEB0B',1.0,'State Tax','Y','N','Y','Y')
/
INSERT INTO PUR_AP_ITM_TYP_T (ITM_TYP_CD,OBJ_ID,VER_NBR,ITM_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,QTY_BSD_GL_IND,ITM_TYP_ADDL_CHRG_IND,TAXABLE_IND)
  VALUES ('TRDI','6C5EE90A-AAAF-701A-CFBB-B3CADBC62506',1.0,'Trade In','Y','N','Y','Y')
/
INSERT INTO PUR_AP_ITM_TYP_T (ITM_TYP_CD,OBJ_ID,VER_NBR,ITM_TYP_DESC,DOBJ_MAINT_CD_ACTV_IND,QTY_BSD_GL_IND,ITM_TYP_ADDL_CHRG_IND,TAXABLE_IND)
  VALUES ('UNOR','48163B1F312FA0C5E0404F8189D81E00',1.0,'Unordered','Y','Y','N','Y')
/
