TRUNCATE TABLE PUR_SHP_PMT_TERM_T
/
INSERT INTO PUR_SHP_PMT_TERM_T (VNDR_SHP_PMT_TERM_CD,OBJ_ID,VER_NBR,VNDR_SHP_PMT_TERM_DESC,VNDR_SHP_PMT_TERM_PAY_IND,DOBJ_MAINT_CD_ACTV_IND)
  VALUES ('AL','39F17A7F-7D98-AC92-C7FB-C922D20475EF',1.0,'VENDOR PAYS ("ALLOWED")','Y','Y')
/
INSERT INTO PUR_SHP_PMT_TERM_T (VNDR_SHP_PMT_TERM_CD,OBJ_ID,VER_NBR,VNDR_SHP_PMT_TERM_DESC,VNDR_SHP_PMT_TERM_PAY_IND,DOBJ_MAINT_CD_ACTV_IND)
  VALUES ('CL','BA763DBD-4E1A-86C5-37AC-55EB72CD3ED2',2.0,'INST PAYS, SEPARATE BILL ("COLLECT")','Y','Y')
/
INSERT INTO PUR_SHP_PMT_TERM_T (VNDR_SHP_PMT_TERM_CD,OBJ_ID,VER_NBR,VNDR_SHP_PMT_TERM_DESC,VNDR_SHP_PMT_TERM_PAY_IND,DOBJ_MAINT_CD_ACTV_IND)
  VALUES ('PA','777F543C-C5CD-F29C-91CF-A30F4F41EAEC',2.0,'INST PAYS, PART OF PO ("PREPAID AND ADD")','Y','Y')
/
INSERT INTO PUR_SHP_PMT_TERM_T (VNDR_SHP_PMT_TERM_CD,OBJ_ID,VER_NBR,VNDR_SHP_PMT_TERM_DESC,VNDR_SHP_PMT_TERM_PAY_IND,DOBJ_MAINT_CD_ACTV_IND)
  VALUES ('PD','4FFB4620-ECB0-FEE0-A489-80F5E4684291',1.0,'PAID BY 3RD PARTY','Y','Y')
/
