package org.kuali.ole.deliver.rules.general

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.ErrorMessage
import org.kuali.ole.deliver.bo.OleAddressBo
import org.kuali.ole.deliver.drools.DroolsExchange
import java.util.Date
import java.text.SimpleDateFormat
import org.kuali.ole.service.OleCirculationPolicyServiceImpl
import org.kuali.ole.deliver.drools.DroolsConstants


rule "Is Patron Active"
agenda-group "General Checks for Patron"
when
$p : OlePatronDocument(!isActiveIndicator())
$e : ErrorMessage()
then
$e.setErrorMessage("Patron is Inactive");
 end

 rule "Is Patron with General Block"
agenda-group "General Checks for Patron"
when
$p : OlePatronDocument(isGeneralBlock())
$e : ErrorMessage()
then
$e.setErrorMessage("Patron is blocked");
$e.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION);
 end

rule "Is Patron's address verified"
agenda-group "General Checks for Patron"
when
$p : OlePatronDocument(!isAddressVerified())
$e : ErrorMessage()
then
$e.setErrorMessage("Address is not verified");
 end

 rule "Is Patron Expired"
 agenda-group "General Checks for Patron"
 when
 $p : OlePatronDocument(getExpirationDate() != null, getExpirationDate() < today())
 $e : ErrorMessage()
 then
$e.setErrorMessage("Patron has expired");
$e.addOverridePermissions("Patron record expired");
  end

  rule "Activation Date for Patron"
   agenda-group "General Checks for Patron"
   when
   $p : OlePatronDocument(getActivationDate()!= null,getActivationDate() > today())
   $e : ErrorMessage()
   then
$e.setErrorMessage("Patron has an invalid activation date");
    end


 rule "Check All Charges"
  agenda-group "General Checks for Patron"
  when
  $p: OlePatronDocument(getAllCharges() > 49 )
  $e: ErrorMessage()
  then
  $e.setErrorMessage("Patron's overall charges are $50 or more");
 $e.addOverridePermissions(DroolsConstants.MAX_CHARGES_PERMISSION);
  end

 rule "Check Overdue fine"
  agenda-group "General Checks for Patron"
 when
 $p: OlePatronDocument(getOverdueFineAmount() > 49 )
 $e: ErrorMessage()
 then
 $e.setErrorMessage("Patron has overdue fines greater than $50");
 //$p.addErrorsAndPermission("Patron has max amount of overdue fines");
 end

 rule "Check Replacement fine"
agenda-group "General Checks for Patron"
 when
 $p: OlePatronDocument(getReplacementFineAmount() > 149 )
 $e: ErrorMessage()
 then
 $e.setErrorMessage("Patron has replacement fees of $150 or more");
 //$p.addErrorsAndPermission("Patron has max amount of replacement fees");
  end


 rule "Patron Has Atleast One Item which is over the allow due limit"
agenda-group "General Checks for Patron"
 when
 $p: OlePatronDocument(isOverDueDays(3000))
 $e: ErrorMessage()
 then
 $e.setErrorMessage("Patron Has Atleast One Item which is over the allowed due limit");
 //$p.addErrorsAndPermission("Patron has max amount of replacement fees");
  end

 rule "Patron Has Atleast One Item which has been recalled and has exceeded the overdue limit"
agenda-group "General Checks for Patron"
 when
 $p: OlePatronDocument(isRecalledAndOverDue(3))
 $e: ErrorMessage()
 then
 $e.setErrorMessage("Patron Has Atleast One Item which has been recalled and is overdue");
 //$p.addErrorsAndPermission("Patron has max amount of replacement fees");
  end


 function Date today(){
 Date date = new Date(System.currentTimeMillis());
 return date;
 }
