package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "RN-28-DAYS-10-MAX-DIV-LS-THAN-2-RN"
agenda-group "renewal validation"
activation-group "renewal validation"

when
$l: OleLoanDocument(Integer.valueOf(getNumberOfRenewals()) < 2)
$d: DroolsResponse()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("ALUMNI","PL4WK"))

$i: OleItemRecordForCirc (getItemType() in ("STANDARDLOAN","AUDIOVISUAL"),
getItemLibraryLocation() in ("DIVINITY"))
then

$l.setCirculationPolicyId("RN-28-DAYS-10-MAX-DIV-LS-THAN-2-RN");
$l.loanPeriod("28-D","7-D");
 end
 
 rule "RN-28-DAYS-10-MAX-DIV-GR-THAN-2-RN"
agenda-group "renewal validation"
activation-group "renewal validation"
when
 $l: OleLoanDocument(Integer.valueOf(getNumberOfRenewals()) >= 2)
$d: DroolsResponse()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("ALUMNI","PL4WK"))

$i: OleItemRecordForCirc (getItemType() in ("STANDARDLOAN","AUDIOVISUAL"),
getItemLibraryLocation() in ("DIVINITY"))
then

$d.addErrorMessage("Patron has more than allowed limit of renewals");
$d.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION);
$l.setCirculationPolicyId("RN-28-DAYS-10-MAX-DIV-GR-THAN-2-RN");
$l.loanPeriod("28-D","7-D");
 end