package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.NoticeInfo

rule "RN-2WK-EREADER-FORD-NO-RENEWALS"
agenda-group "renewal validation"
activation-group "renewal validation"
when
 $l: OleLoanDocument(Integer.valueOf(getNumberOfRenewals()) >= 0)
$d: DroolsResponse()
$n: NoticeInfo()

$p: OlePatronDocument(getBorrowerTypeCode() in ("FACULTY","FQFACULTY","LWFACULTY","MDFACULTY","GRADST","DUKESTAFF","UG","FQGRAD","FQST","FQPHD","RETLIB"))

$i: OleItemRecordForCirc (getItemType() in ("EREADER"),
getItemLibraryLocation() in ("FORD"))
then

$d.addErrorMessage("Patrons may not renew EReaders.");
$d.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION);
$l.setCirculationPolicyId("RN-2WK-EREADER-FORD-NO-RENEWALS");
$l.loanPeriod(null,null);
$n.setNoticeType("NO-FORD-EREADER");
 end