package org.kuali.ole.deliver.checkout

import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.util.NoticeInfo
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.deliver.drools.DroolsConstants


rule "RN-3HR-LSC-AV"
agenda-group "renewal validation"
activation-group "renewal validation"
when

$l: OleLoanDocument()
$n: NoticeInfo()
$d: DroolsResponse()

$p: OlePatronDocument(getBorrowerTypeCode() in ("ALUMNI","FQALUMNI","UNCGFS","PL4WK","DUKE4WKGOLD","TRLN","HEALTHPROF","FQPARTNER","LWALUMNI","FRIENDSDUL"))
$i: OleItemRecordForCirc(getItemType() in ("AUDIOVISUAL"),
getItemLibraryLocation() in ("LSC"))

then
$l.loanPeriod("3-H",null); // This method takes due date and recall period as arguments.
$l.setCirculationPolicyId("RN-3HR-LSC-AV");
$d.setRuleMatched(true);
 end

