package org.kuali.ole.deliver.checkout

import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.util.NoticeInfo
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.deliver.drools.DroolsConstants


rule "RN-5-31-FIXED-LAW"
agenda-group "renewal validation"
activation-group "renewal validation"
when

$l: OleLoanDocument()
$n: NoticeInfo()
$d: DroolsResponse()

$p: OlePatronDocument(getBorrowerTypeCode() in ("LWFACULTY"))
$i: OleItemRecordForCirc(getItemType() in ("STANDARDLOAN","LIBUSEONLY","3DAY","4HR","24HR"),
getItemLibraryLocation() in ("LAW"))

then
$l.loanPeriod(OLEConstants.FIXED_DUE_DATE,"14-D"); // This method takes due date and recall period as arguments.
$l.setCirculationPolicyId("RN-5-31-FIXED-LAW");
$d.setRuleMatched(true);
 end

