package org.kuali.ole.deliver.checkout

import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.util.NoticeInfo
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.deliver.drools.DroolsConstants


rule "RN-90-DAYS-LAW"
agenda-group "renewal validation"
activation-group "renewal validation"
when

$l: OleLoanDocument()
$n: NoticeInfo()
$d: DroolsResponse()

$p: OlePatronDocument(getBorrowerTypeCode() in ("FACULTY","FQFACULTY","MDFACULTY","GRADST","DUKESTAFF","FQST","FQPHD","FQMBA","FQGRAD"))
$i: OleItemRecordForCirc(getItemType() in ("STANDARDLOAN"),
getItemLibraryLocation() in ("LAW"))

then
$l.loanPeriod("90-D","7-D"); // This method takes due date and recall period as arguments.
$l.setCirculationPolicyId("RN-90-DAYS-LAW");
$d.setRuleMatched(true);
 end

