package org.kuali.ole.deliver.checkout

import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.util.NoticeInfo
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.deliver.drools.DroolsConstants


rule "RN-DIV-SEMESTER-FIXED"
agenda-group "renewal validation"
activation-group "renewal validation"
when

$l: OleLoanDocument()
$n: NoticeInfo()
$d: DroolsResponse()

$p: OlePatronDocument(getBorrowerTypeCode() in ("UNCGFS"))
$i: OleItemRecordForCirc(getItemType() in ("STANDARDLOAN","SOUNDCD","AUDIOVISUAL"),
getItemLibraryLocation() in ("DIVINITY"))

then
$l.loanPeriod(OLEConstants.FIXED_DUE_DATE,"7-D"); // This method takes due date and recall period as arguments.
$l.setCirculationPolicyId("RN-DIV-SEMESTER-FIXED");
$d.setRuleMatched(true);
 end

