package org.kuali.ole.deliver.checkout

import org.kuali.ole.OLEConstants

import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.DroolsResponse

rule "RN-LINK-NO-RENEWALS"
agenda-group "renewal validation"
activation-group "renewal validation"
when

$d: DroolsResponse()
$i: OleItemRecordForCirc(getItemLibraryLocation() in ("LINK"))

then
$d.setRuleMatched(true);
$d.addErrorMessage("Equipment from the Link may not be renewed");
 end
