package org.kuali.ole.deliver.checkout

import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.util.NoticeInfo
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.deliver.drools.DroolsConstants


rule "RN-PK-STDLOAN-NOT-DUKE-AFFL-LS-THAN-2-RN"
agenda-group "renewal validation"
activation-group "renewal validation"
when

$l: OleLoanDocument(Integer.valueOf(getNumberOfRenewals()) < 2)

$n: NoticeInfo()
$d : DroolsResponse()

$p: OlePatronDocument(getBorrowerTypeCode() in
("ALUMNI","PL4WK","DUKE4WKGOLD","LWALUMNI","FRIENDSDUL"))

$i: OleItemRecordForCirc(getItemType() in ("STANDARDLOAN"))

then
$l.loanPeriod("1-D",null); // This method takes due date and recall period as arguments.
$l.setCirculationPolicyId("RN-PK-STDLOAN-NOT-DUKE-AFFL-LS-THAN-2-RN");
$d.setRuleMatched(true);
$n.setNoticeType("NO-PS-STDLOAN");
 end

rule "RN-PK-STDLOAN-NOT-DUKE-AFFL-GR-THAN-2-RN"
agenda-group "renewal validation"
activation-group "renewal validation"
when

$l: OleLoanDocument(Integer.valueOf(getNumberOfRenewals()) >= 2)
$d: DroolsResponse()
$n: NoticeInfo()

$p: OlePatronDocument(getBorrowerTypeCode() in
("ALUMNI","PL4WK","DUKE4WKGOLD","LWALUMNI","FRIENDSDUL"))

$i: OleItemRecordForCirc(getItemType() in ("STANDARDLOAN"))

then
$d.addErrorMessage("Patron has more than allowed limit of renewals.");
$d.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION);
$l.setCirculationPolicyId("RN-PK-STDLOAN-NOT-DUKE-AFFL-GR-THAN-2-RN");
$l.loanPeriod("28-D",null); // This method takes due date and recall period as arguments.
$n.setNoticeType("NO-PS-STDLOAN");
end
