package org.kuali.ole.deliver.checkout

import org.kuali.ole.OLEConstants

import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.DroolsResponse

rule "RN-PERKINS-NO-RENEWALS"
agenda-group "renewal validation"
activation-group "renewal validation"
when

$d: DroolsResponse()
$i: OleItemRecordForCirc(getItemType() in ("1WK","3DAY","1DAY","4HR","3HR","OVERNIGHT","ELECTRONICEQUIP","2WK"),
getItemLibraryLocation() in ("PERKINS"))

then
$d.setRuleMatched(true);
$d.addErrorMessage("Reserve items and short-term loans may not be renewed");
 end
