TRUNCATE TABLE OLE_BAT_PRCS_DT_MAP_OPT_T DROP STORAGE
/
INSERT INTO OLE_BAT_PRCS_DT_MAP_OPT_T (BATCH_PRCS_DT_MAP_OPT_ID,BAT_PRCS_DT_MAP_DATA_TYP,DATA_TYP_DEST_FLD,SRC_FLD,SRC_VAL,DEST_FLD,DEST_VAL,PRIORITY,IS_LOOKUP,OBJ_ID,VER_NBR,OLE_BAT_PRCS_DT_MAP_ID)
  VALUES ('1','Holdings','Bibmarc','Call Number Type','','099$t','',0,'','1',1,'1')
/
INSERT INTO OLE_BAT_PRCS_DT_MAP_OPT_T (BATCH_PRCS_DT_MAP_OPT_ID,BAT_PRCS_DT_MAP_DATA_TYP,DATA_TYP_DEST_FLD,SRC_FLD,SRC_VAL,DEST_FLD,DEST_VAL,PRIORITY,IS_LOOKUP,OBJ_ID,VER_NBR,OLE_BAT_PRCS_DT_MAP_ID)
  VALUES ('2','Item','Bibmarc','Call Number','','099$a','',0,'','1',1,'1')
/
INSERT INTO OLE_BAT_PRCS_DT_MAP_OPT_T (BATCH_PRCS_DT_MAP_OPT_ID,BAT_PRCS_DT_MAP_DATA_TYP,DATA_TYP_DEST_FLD,SRC_FLD,SRC_VAL,DEST_FLD,DEST_VAL,PRIORITY,IS_LOOKUP,OBJ_ID,VER_NBR,OLE_BAT_PRCS_DT_MAP_ID)
  VALUES ('3','Holdings','Bibmarc','Call Number','','099$a','',0,'','1',1,'1')
/
INSERT INTO OLE_BAT_PRCS_DT_MAP_OPT_T (BATCH_PRCS_DT_MAP_OPT_ID,BAT_PRCS_DT_MAP_DATA_TYP,DATA_TYP_DEST_FLD,SRC_FLD,SRC_VAL,DEST_FLD,DEST_VAL,PRIORITY,IS_LOOKUP,OBJ_ID,VER_NBR,OLE_BAT_PRCS_DT_MAP_ID)
  VALUES ('4','Holdings','Bibmarc','Call Number Type','','099$t','',1,'','1',1,'2')
/
INSERT INTO OLE_BAT_PRCS_DT_MAP_OPT_T (BATCH_PRCS_DT_MAP_OPT_ID,BAT_PRCS_DT_MAP_DATA_TYP,DATA_TYP_DEST_FLD,SRC_FLD,SRC_VAL,DEST_FLD,DEST_VAL,PRIORITY,IS_LOOKUP,OBJ_ID,VER_NBR,OLE_BAT_PRCS_DT_MAP_ID)
  VALUES ('5','Holdings','Bibmarc','Call Number','','099$a','',0,'','1',1,'2')
/
INSERT INTO OLE_BAT_PRCS_DT_MAP_OPT_T (BATCH_PRCS_DT_MAP_OPT_ID,BAT_PRCS_DT_MAP_DATA_TYP,DATA_TYP_DEST_FLD,SRC_FLD,SRC_VAL,DEST_FLD,DEST_VAL,PRIORITY,IS_LOOKUP,OBJ_ID,VER_NBR,OLE_BAT_PRCS_DT_MAP_ID)
  VALUES ('6','Holdings','Bibmarc','Call Number Type','','099$t','',0,'','1',1,'3')
/
INSERT INTO OLE_BAT_PRCS_DT_MAP_OPT_T (BATCH_PRCS_DT_MAP_OPT_ID,BAT_PRCS_DT_MAP_DATA_TYP,DATA_TYP_DEST_FLD,SRC_FLD,SRC_VAL,DEST_FLD,DEST_VAL,PRIORITY,IS_LOOKUP,OBJ_ID,VER_NBR,OLE_BAT_PRCS_DT_MAP_ID)
  VALUES ('7','Holdings','Bibmarc','Call Number Type','','099$t','',1,'','1',1,'4')
/
INSERT INTO OLE_BAT_PRCS_DT_MAP_OPT_T (BATCH_PRCS_DT_MAP_OPT_ID,BAT_PRCS_DT_MAP_DATA_TYP,DATA_TYP_DEST_FLD,SRC_FLD,SRC_VAL,DEST_FLD,DEST_VAL,PRIORITY,IS_LOOKUP,OBJ_ID,VER_NBR,OLE_BAT_PRCS_DT_MAP_ID)
  VALUES ('8','Holdings','Bibmarc','Call Number Type','','099$t','',1,'','1',1,'5')
/
INSERT INTO OLE_BAT_PRCS_DT_MAP_OPT_T (BATCH_PRCS_DT_MAP_OPT_ID,BAT_PRCS_DT_MAP_DATA_TYP,DATA_TYP_DEST_FLD,SRC_FLD,SRC_VAL,DEST_FLD,DEST_VAL,PRIORITY,IS_LOOKUP,OBJ_ID,VER_NBR,OLE_BAT_PRCS_DT_MAP_ID)
  VALUES ('9','Item','Bibmarc','Call Number Type','','099$t','',1,'','1',1,'6')
/
INSERT INTO OLE_BAT_PRCS_DT_MAP_OPT_T (BATCH_PRCS_DT_MAP_OPT_ID,DATA_TYP_DEST_FLD,SRC_FLD,SRC_VAL,DEST_FLD,DEST_VAL,PRIORITY,IS_LOOKUP,OBJ_ID,VER_NBR,OLE_BAT_PRCS_DT_MAP_ID)
  VALUES ('10','OrderImport','960 $s','','vendorNumber','12106-0',0,'N','1',1,'7')
/
INSERT INTO OLE_BAT_PRCS_DT_MAP_OPT_T (BATCH_PRCS_DT_MAP_OPT_ID,DATA_TYP_DEST_FLD,SRC_FLD,SRC_VAL,DEST_FLD,DEST_VAL,PRIORITY,IS_LOOKUP,OBJ_ID,VER_NBR,OLE_BAT_PRCS_DT_MAP_ID)
  VALUES ('11','OrderImport','980 $m','','listPrice','25.00',0,'N','1',1,'7')
/
INSERT INTO OLE_BAT_PRCS_DT_MAP_OPT_T (BATCH_PRCS_DT_MAP_OPT_ID,DATA_TYP_DEST_FLD,SRC_FLD,SRC_VAL,DEST_FLD,DEST_VAL,PRIORITY,IS_LOOKUP,OBJ_ID,VER_NBR,OLE_BAT_PRCS_DT_MAP_ID)
  VALUES ('12','InvoiceImport','980 $q','','quantity','1',0,'N','1',1,'8')
/
INSERT INTO OLE_BAT_PRCS_DT_MAP_OPT_T (BATCH_PRCS_DT_MAP_OPT_ID,DATA_TYP_DEST_FLD,SRC_FLD,SRC_VAL,DEST_FLD,DEST_VAL,PRIORITY,IS_LOOKUP,OBJ_ID,VER_NBR,OLE_BAT_PRCS_DT_MAP_ID)
  VALUES ('13','InvoiceImport','980 $m','','listPrice','25.00',0,'N','1',1,'8')
/
INSERT INTO OLE_BAT_PRCS_DT_MAP_OPT_T (BATCH_PRCS_DT_MAP_OPT_ID,DATA_TYP_DEST_FLD,SRC_FLD,SRC_VAL,DEST_FLD,DEST_VAL,PRIORITY,IS_LOOKUP,OBJ_ID,VER_NBR,OLE_BAT_PRCS_DT_MAP_ID)
  VALUES ('14','InvoiceImport','980 $g','','invoiceNumber','446246',0,'N','1',1,'8')
/
INSERT INTO OLE_BAT_PRCS_DT_MAP_OPT_T (BATCH_PRCS_DT_MAP_OPT_ID,DATA_TYP_DEST_FLD,SRC_FLD,SRC_VAL,DEST_FLD,DEST_VAL,PRIORITY,IS_LOOKUP,OBJ_ID,VER_NBR,OLE_BAT_PRCS_DT_MAP_ID)
  VALUES ('15','InvoiceImport','990 $i','','invoiceDate','20130822',0,'N','1',1,'8')
/
INSERT INTO OLE_BAT_PRCS_DT_MAP_OPT_T (BATCH_PRCS_DT_MAP_OPT_ID,DATA_TYP_DEST_FLD,SRC_FLD,SRC_VAL,DEST_FLD,DEST_VAL,PRIORITY,IS_LOOKUP,OBJ_ID,VER_NBR,OLE_BAT_PRCS_DT_MAP_ID)
  VALUES ('16','InvoiceImport','980 $z','','vendorNumber','12106-0',0,'N','1',1,'8')
/
INSERT INTO OLE_BAT_PRCS_DT_MAP_OPT_T (BATCH_PRCS_DT_MAP_OPT_ID,DATA_TYP_DEST_FLD,SRC_FLD,SRC_VAL,DEST_FLD,DEST_VAL,PRIORITY,IS_LOOKUP,OBJ_ID,VER_NBR,OLE_BAT_PRCS_DT_MAP_ID)
  VALUES ('17','InvoiceImport','245 $a','','itemDescription','A bible stories reader in Hadiyya ',0,'N','1',1,'8')
/
INSERT INTO OLE_BAT_PRCS_DT_MAP_OPT_T (BATCH_PRCS_DT_MAP_OPT_ID,BAT_PRCS_DT_MAP_DATA_TYP,DATA_TYP_DEST_FLD,SRC_FLD,SRC_VAL,DEST_FLD,DEST_VAL,PRIORITY,IS_LOOKUP,OBJ_ID,VER_NBR,OLE_BAT_PRCS_DT_MAP_ID)
  VALUES ('18','Bibmarc','Holdings','099$t','','Call Number','',0,'','1',1,'9')
/
