TRUNCATE TABLE OLE_DLVR_LOAN_STAT_T DROP STORAGE
/
INSERT INTO OLE_DLVR_LOAN_STAT_T (LOAN_STAT_CD,LOAN_STAT_ID,LOAN_STAT_NM,OBJ_ID,VER_NBR)
  VALUES ('LOANED','1','Loaned','4dcdf94f-fc19-40f4-86b6-9a3a66d42bda',1)
/
INSERT INTO OLE_DLVR_LOAN_STAT_T (LOAN_STAT_CD,LOAN_STAT_ID,LOAN_STAT_NM,OBJ_ID,VER_NBR)
  VALUES ('RETURNED','2','returned','4dcdf94f-fc19-40f4-86b6-9a3a66d42bda',1)
/
