TRUNCATE TABLE OLE_PTRN_NTE_TYP_T DROP STORAGE
/
INSERT INTO OLE_PTRN_NTE_TYP_T (ACTV_IND,OLE_PTRN_NTE_TYPE_CD,OLE_PTRN_NTE_TYP_ID,OLE_PTRN_NTE_TYP_NM)
  VALUES ('Y','GENERAL','1','General')
/
INSERT INTO OLE_PTRN_NTE_TYP_T (ACTV_IND,OLE_PTRN_NTE_TYPE_CD,OLE_PTRN_NTE_TYP_ID,OLE_PTRN_NTE_TYP_NM)
  VALUES ('Y','BLOCK','2','Block')
/
INSERT INTO OLE_PTRN_NTE_TYP_T (ACTV_IND,OLE_PTRN_NTE_TYPE_CD,OLE_PTRN_NTE_TYP_ID,OLE_PTRN_NTE_TYP_NM)
  VALUES ('Y','CHECKIN','3','Checkin')
/
INSERT INTO OLE_PTRN_NTE_TYP_T (ACTV_IND,OLE_PTRN_NTE_TYPE_CD,OLE_PTRN_NTE_TYP_ID,OLE_PTRN_NTE_TYP_NM)
  VALUES ('Y','STAFF','4','Staff')
/
INSERT INTO OLE_PTRN_NTE_TYP_T (ACTV_IND,OLE_PTRN_NTE_TYPE_CD,OLE_PTRN_NTE_TYP_ID,OLE_PTRN_NTE_TYP_NM)
  VALUES ('Y','USER','5','User')
/
