TRUNCATE TABLE OLE_CODE_T DROP STORAGE
/
INSERT INTO OLE_CODE_T (CD_ID,INPUT_VAL,ITM_STAT_CD,ITM_TYP,OBJ_ID,PROFILE_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('2','NCCP','BOOK','Circulating','01ea3339-4a85-4acf-8745-4bbcb0757da4','MY-TEST-INGEST','Y',1)
/
INSERT INTO OLE_CODE_T (CD_ID,INPUT_VAL,ITM_STAT_CD,ITM_TYP,OBJ_ID,PROFILE_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('3','NCCP','VIDEO','Non-Circ','01ea3339-4a85-4acf-8745-4bbcb0757da4','YBP','Y',1)
/
