TRUNCATE TABLE OLE_PROFILE_ATTR_T DROP STORAGE
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',1,'orderPerFile','SINGLE-ORDER')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',2,'vendorProfileCode','YBP')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',3,'contractMgr','John Doe')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',4,'assignToUser','Jane Doe')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',5,'chartCode','UA')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',6,'itemChartCode','BL')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',7,'orgCode','VPIT')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',8,'receivingRequired','false')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',9,'itemStatus','a values goes here')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',10,'locationStatus','Permanent')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',11,'useTaxInd','true')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',12,'orderType','firm_fixed_ybp')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',13,'payReqPositiveApprovalReq','true')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',14,'deliveryCampus','BL')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',15,'building','BL209')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',16,'publicView','false')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',17,'internalPurchasingLimit','null')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',18,'costSource','EST')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',19,'recordType','x')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',20,'encodingLevel','1')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',21,'receiptStatus','3')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',22,'acquisitionMethod','3')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',23,'generalRetentionPolicy','u')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',24,'specificRetentionPolicy-PolicyType','')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',25,'fundingSource','INST')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',26,'purchaseorderconfirmationindicator','true')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',27,'requisitionSource','AUTO')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',28,'vendorchoice','vendorchoice')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',29,'itemType','ITEM')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',30,'routeRequester','false')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',31,'publicView','true')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',32,'percent','100')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',33,'poTransmissionMethod','NOPR')
/
INSERT INTO OLE_PROFILE_ATTR_T (AGENDA_NAME,ID,NAME,VALUE)
  VALUES ('YBP',34,'internalPurchasingLimit','2')
/
