TRUNCATE TABLE OLE_BAT_PRCS_PRFLE_CNST_T DROP STORAGE
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('1','chartCode','UA','OrderImport','6','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('2','orgCode','VPIT','OrderImport','6','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('3','receivingRequired','false','OrderImport','6','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('4','contractManager','WILLIE PARKE','OrderImport','6','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('5','assignToUser','ole-jumonica','OrderImport','6','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('6','useTaxIndicator','true','OrderImport','6','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('7','orderType','Firm, Fixed','OrderImport','6','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('8','fundingSource','INST','OrderImport','6','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('9','payReqPositiveApprovalReq','true','OrderImport','6','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('10','purchaseOrderConfirmationIndicator','true','OrderImport','6','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('11','deliveryCampusCode','BL','OrderImport','6','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('12','buildingCode','BL209','OrderImport','6','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('13','vendorChoice','CNST','OrderImport','6','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('14','itemType','ITEM','OrderImport','6','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('15','routeToRequestor','false','OrderImport','6','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('16','methodOfPOTransmission','NOPR','OrderImport','6','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('17','costSource','EST','OrderImport','6','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('18','percent','100','OrderImport','6','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('19','defaultLocation','ARCH/PSAP','OrderImport','6','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('20','quantity','1','OrderImport','6','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('21','vendorReferenceNumber','40022554293','OrderImport','6','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('22','requestorName','Sample, Stephanie','OrderImport','6','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('23','itemStatus','AVAILABLE','OrderImport','6','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('24','discount','10','OrderImport','6','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('25','discountType','%','OrderImport','6','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('26','accountNumber','2947430','OrderImport','6','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('27','financialObjectCode','7112','OrderImport','6','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('28','itemNoOfParts','1','OrderImport','6','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('29','vendorProfileCode','YBP','OrderImport','6','constant','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('30','vendorNumber','12106-0','InvoiceImport','5','default','1',1)
/
INSERT INTO OLE_BAT_PRCS_PRFLE_CNST_T (OLE_USR_DEF_VAL_ID,ATT_NM,ATT_VAL,DATA_TYPE,BAT_PRCS_PRF_ID,DEF_VAL,OBJ_ID,VER_NBR)
  VALUES ('31','caption','caption','OrderImport','6','default','1',1)
/
