TRUNCATE TABLE OLE_PROFILE_FACT_T DROP STORAGE
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,INCOMING_FIELD,TERM_NAME)
  VALUES ('YBP',1,'020a','incomingField-020a')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,EXISTING_FIELD,ID,TERM_NAME)
  VALUES ('YBP','020a',2,'existingField-020a')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('General Checks',3,'generalBlock')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('General Checks',4,'expirationDate')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('General Checks',5,'isAddressVerified')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('General Checks',6,'digitRoutine')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('General Checks',7,'patronBarcode')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('General Checks',8,'pattern')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('General Checks',9,'isProxyPatron')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('General Checks',10,'proxyExpirationDate')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',11,'itemStatus')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',12,'isPatronInPositionOne')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',13,'requestType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',14,'itemStatus')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',15,'itemStatus')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',16,'digitRoutine')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',17,'itemBarcode')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',18,'pattern')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',19,'itemLocation')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',20,'operatorsCirculationLocation')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',21,'isCirculationPolicyNotFound')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',22,'borrowerType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',23,'itemType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',24,'itemLibrary')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',25,'numberOfClaimsReturned')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',26,'overdueFineAmt')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',27,'replacementFeeAmt')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',28,'allCharges')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',29,'numberOfItemsCheckedOut')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',30,'numberOfOverDueItemsCheckedOut')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',31,'numberOfOverDueRecalledItemsCheckedOut')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',32,'isCirculationPolicyNotFound')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',33,'itemLibrary')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',34,'itemShelving')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',35,'borrowerType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',36,'itemType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',37,'numberOfClaimsReturned')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',38,'overdueFineAmt')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',39,'replacementFeeAmt')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',40,'allCharges')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',41,'numberOfItemsCheckedOut')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',42,'numberOfOverDueItemsCheckedOut')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',43,'numberOfOverDueRecalledItemsCheckedOut')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',44,'isCirculationPolicyNotFound')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',45,'borrowerType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',46,'itemType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',47,'itemShelving')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',48,'numberOfClaimsReturned')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',49,'overdueFineAmt')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',50,'replacementFeeAmt')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',51,'allCharges')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',52,'numberOfItemsCheckedOut')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',53,'numberOfOverDueItemsCheckedOut')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',54,'numberOfOverDueRecalledItemsCheckedOut')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('CheckOut Validation',55,'isCirculationPolicyNotFound')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Renewal Validation',56,'digitRoutine')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Renewal Validation',57,'itemBarcode')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Renewal Validation',58,'pattern')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Renewal Validation',59,'itemLocation')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Renewal Validation',60,'operatorsCirculationLocation')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Renewal Validation',61,'isCirculationPolicyNotFound')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Renewal Validation',62,'borrowerType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Renewal Validation',63,'itemType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Renewal Validation',64,'numberOfClaimsReturned')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Renewal Validation',65,'overdueFineAmt')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Renewal Validation',66,'replacementFeeAmt')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Renewal Validation',67,'allCharges')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Renewal Validation',68,'numberOfRenewals')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Renewal Validation',69,'itemDueDateString')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Renewal Validation',70,'itemDueDate')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Renewal Validation',71,'isCirculationPolicyNotFound')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',72,'digitRoutine')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',73,'itemBarcode')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',74,'pattern')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',75,'itemLocation')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',76,'operatorsCirculationLocation')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',77,'shelvingLagTime')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',78,'itemPickUpLocation')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',79,'operatorsCirculationLocation')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',80,'itemStatus')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',81,'destinationLocation')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',82,'operatorsCirculationLocation')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',83,'itemStatus')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',84,'shelvingLagTime')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',85,'requestType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',86,'requestType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',87,'itemPickUpLocation')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',88,'operatorsCirculationLocation')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',89,'isCirculationPolicyNotFound')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',90,'borrowerType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',91,'itemType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',92,'itemLibrary')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',93,'itemDueDate')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',94,'requestType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',95,'isCirculationPolicyNotFound')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',96,'itemLibrary')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',97,'itemShelving')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',98,'borrowerType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',99,'itemType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',100,'itemDueDate')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',101,'requestType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',102,'isCirculationPolicyNotFound')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',103,'borrowerType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',104,'itemType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',105,'itemShelving')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',106,'itemDueDate')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',107,'requestType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Check-in Validation',108,'isCirculationPolicyNotFound')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Request Validation',109,'requestType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Request Validation',110,'requestType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Request Validation',111,'isCirculationPolicyNotFound')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Request Validation',112,'borrowerType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Request Validation',113,'itemType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Request Validation',114,'itemLibrary')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Request Validation',115,'requestType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Request Validation',116,'maxNumberOfRecallRequest')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Request Validation',117,'requestType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Request Validation',118,'maxNumberOfHoldRequest')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Request Validation',119,'requestType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Request Validation',120,'maxNumberOfPageRequest')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Request Validation',121,'isCirculationPolicyNotFound')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Notice Validation',122,'dueDateDiffInterval')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Notice Validation',123,'configurableInterval')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Notice Validation',124,'isCirculationPolicyNotFound')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Notice Validation',125,'borrowerType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Notice Validation',126,'itemType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Notice Validation',127,'itemLibrary')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Notice Validation',128,'itemStatus')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Notice Validation',129,'numberOfDaysOnHold')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Notice Validation',130,'maxNumberOfDaysOnHold')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Notice Validation',131,'claimsReturned')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Notice Validation',132,'replacementFeePatronBill')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Notice Validation',133,'numberOfOverdueSent')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Notice Validation',134,'dueDateSumInterval')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Notice Validation',135,'intervalWithNoticeCount')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Notice Validation',136,'isCirculationPolicyNotFound')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Batch Program Agenda',137,'isTemporaryHistoryRecord')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Batch Program Agenda',138,'borrowerType')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Batch Program Agenda',139,'deskLocation')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Batch Program Agenda',140,'notice')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Batch Program Agenda',141,'notice')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Batch Program Agenda',142,'notice')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Batch Program Agenda',143,'notice')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Batch Program Agenda',144,'notice')
/
INSERT INTO OLE_PROFILE_FACT_T (AGENDA_NAME,ID,TERM_NAME)
  VALUES ('Batch Program Agenda',145,'notice')
/
