TRUNCATE TABLE OLE_DLVR_ADDR_SRC_T DROP STORAGE
/
INSERT INTO OLE_DLVR_ADDR_SRC_T (OBJ_ID,OLE_DLVR_ADDR_SRC_CD,OLE_DLVR_ADDR_SRC_DESC,OLE_DLVR_ADDR_SRC_ID,OLE_DLVR_ADDR_SRC_NM,ROW_ACT_IND,VER_NBR)
  VALUES ('de745hdc-eead-4548-85fe-ed72bf85cf35','REGL','Registrar Load','1','Registrar Load','Y',1)
/
INSERT INTO OLE_DLVR_ADDR_SRC_T (OBJ_ID,OLE_DLVR_ADDR_SRC_CD,OLE_DLVR_ADDR_SRC_DESC,OLE_DLVR_ADDR_SRC_ID,OLE_DLVR_ADDR_SRC_NM,ROW_ACT_IND,VER_NBR)
  VALUES ('de745hdc-eead-4548-85fe-ed72gh85cf35','MF','Master Feed','2','Master Feed','Y',1)
/
INSERT INTO OLE_DLVR_ADDR_SRC_T (OBJ_ID,OLE_DLVR_ADDR_SRC_CD,OLE_DLVR_ADDR_SRC_DESC,OLE_DLVR_ADDR_SRC_ID,OLE_DLVR_ADDR_SRC_NM,ROW_ACT_IND,VER_NBR)
  VALUES ('ddfgs92c-esf4-4548-85fe-edbah44ef37','OPT','Operator','3','Operator','Y',1)
/
INSERT INTO OLE_DLVR_ADDR_SRC_T (OBJ_ID,OLE_DLVR_ADDR_SRC_CD,OLE_DLVR_ADDR_SRC_DESC,OLE_DLVR_ADDR_SRC_ID,OLE_DLVR_ADDR_SRC_NM,ROW_ACT_IND,VER_NBR)
  VALUES ('ddsa862c-esf4-4956-85sg-esnr5bj543nk','BORR','Borrower','4','Borrower','Y',1)
/
