TRUNCATE TABLE OLE_DS_DOC_TYPE_T DROP STORAGE
/
INSERT INTO OLE_DS_DOC_TYPE_T (DISPLAY_LABEL,DESCRIPTION,DOC_TYPE_ID,NAME,OBJ_ID,VER_NBR)
  VALUES ('Bibliographic','',1,'bibliographic','8a1e31e8-e5aa-4edd-aab5-4h3e49fe5e1c',1)
/
INSERT INTO OLE_DS_DOC_TYPE_T (DISPLAY_LABEL,DESCRIPTION,DOC_TYPE_ID,NAME,OBJ_ID,VER_NBR)
  VALUES ('License','',2,'license','8a2e31e8-e5aa-4edd-aab5-4g3e49fe5e1c',1)
/
INSERT INTO OLE_DS_DOC_TYPE_T (DISPLAY_LABEL,DESCRIPTION,DOC_TYPE_ID,NAME,OBJ_ID,VER_NBR)
  VALUES ('Holdings','',3,'holdings','8a3e31e8-e5aa-4edd-aab5-3h3e49fe5e1c',1)
/
INSERT INTO OLE_DS_DOC_TYPE_T (DISPLAY_LABEL,DESCRIPTION,DOC_TYPE_ID,NAME,OBJ_ID,VER_NBR)
  VALUES ('Item','',4,'item','8a4e31e8-e5aa-4edd-aab5-3d3e49fe5e1c',1)
/
INSERT INTO OLE_DS_DOC_TYPE_T (DISPLAY_LABEL,DESCRIPTION,DOC_TYPE_ID,NAME,OBJ_ID,VER_NBR)
  VALUES ('EHoldings','',5,'eHoldings','8a4e31e8-e5aa-4edd-aab5-3d3e49fe5e1c',1)
/
