TRUNCATE TABLE OLE_BAT_PRCS_FILTER_T DROP STORAGE
/
INSERT INTO OLE_BAT_PRCS_FILTER_T (OLE_BAT_PRCS_FILTER_ID,OLE_BAT_PRCS_FILTER_NM,OLE_BAT_PRCS_FILTER_VAL,OLE_BAT_PRCS_FILTER_RANGE_FROM,OBJ_ID,VER_NBR,OLE_BAT_PRCS_FILTER_RANGE_TO,BAT_PRCS_PRF_ID,BAT_PRCS_DATA_TYP)
  VALUES ('1','dateUpdated','','08/28/2013','1',1,'','8','Bibmarc')
/
INSERT INTO OLE_BAT_PRCS_FILTER_T (OLE_BAT_PRCS_FILTER_ID,OLE_BAT_PRCS_FILTER_NM,OLE_BAT_PRCS_FILTER_VAL,OLE_BAT_PRCS_FILTER_RANGE_FROM,OBJ_ID,VER_NBR,OLE_BAT_PRCS_FILTER_RANGE_TO,BAT_PRCS_PRF_ID,BAT_PRCS_DATA_TYP)
  VALUES ('2','dateUpdated','','08/28/2013','1',1,'','10','Bibmarc')
/
INSERT INTO OLE_BAT_PRCS_FILTER_T (OLE_BAT_PRCS_FILTER_ID,OLE_BAT_PRCS_FILTER_NM,OLE_BAT_PRCS_FILTER_VAL,OLE_BAT_PRCS_FILTER_RANGE_FROM,OBJ_ID,VER_NBR,OLE_BAT_PRCS_FILTER_RANGE_TO,BAT_PRCS_PRF_ID,BAT_PRCS_DATA_TYP)
  VALUES ('3','dateUpdated','','08/28/2013','1',1,'','11','Bibmarc')
/
INSERT INTO OLE_BAT_PRCS_FILTER_T (OLE_BAT_PRCS_FILTER_ID,OLE_BAT_PRCS_FILTER_NM,OLE_BAT_PRCS_FILTER_VAL,OLE_BAT_PRCS_FILTER_RANGE_FROM,OBJ_ID,VER_NBR,OLE_BAT_PRCS_FILTER_RANGE_TO,BAT_PRCS_PRF_ID,BAT_PRCS_DATA_TYP)
  VALUES ('4','dateUpdated','','08/28/2013','1',1,'','12','Bibmarc')
/
