TRUNCATE TABLE OLE_CAT_TYPE_OWNERSHIP_T DROP STORAGE
/
INSERT INTO OLE_CAT_TYPE_OWNERSHIP_T (OBJ_ID,ROW_ACT_IND,SRC,SRC_DT,TYPE_OWNERSHIP_CD,TYPE_OWNERSHIP_ID,TYPE_OWNERSHIP_NM,VER_NBR)
  VALUES ('4dcdf94f-fc19-40f4-86b6-9a3a66d42bda','Y','(enumeration in schema) http://www.loc.gov/marc/holdings/hd008.html',TO_DATE( '20120506120000', 'YYYYMMDDHH24MISS' ),'Basic Bibliographic Unit',1,'Basic Bibliographic Unit',3)
/
INSERT INTO OLE_CAT_TYPE_OWNERSHIP_T (OBJ_ID,ROW_ACT_IND,SRC,SRC_DT,TYPE_OWNERSHIP_CD,TYPE_OWNERSHIP_ID,TYPE_OWNERSHIP_NM,VER_NBR)
  VALUES ('5d1f9f6f-a53e-4ffc-b65c-91ace3d84fd3','Y','(enumeration in schema) http://www.loc.gov/marc/holdings/hd008.html',TO_DATE( '20120506120000', 'YYYYMMDDHH24MISS' ),'Supplementary Material',2,'Supplementary Material',3)
/
INSERT INTO OLE_CAT_TYPE_OWNERSHIP_T (OBJ_ID,ROW_ACT_IND,SRC,SRC_DT,TYPE_OWNERSHIP_CD,TYPE_OWNERSHIP_ID,TYPE_OWNERSHIP_NM,VER_NBR)
  VALUES ('ff6aa12d-beec-4a09-a526-bc215aa1c9bf','Y','(enumeration in schema) http://www.loc.gov/marc/holdings/hd008.html',TO_DATE( '20120506120000', 'YYYYMMDDHH24MISS' ),'Indexes',3,'Indexes',3)
/
