TRUNCATE TABLE OLE_CLNDR_WK_T DROP STORAGE
/
INSERT INTO OLE_CLNDR_WK_T (OLE_CLNDR_WK_ID,OPN_TIM,CLOS_TIM,FROM_DAY,TO_DAY,OPN_TIM_SESS,CLOS_TIM_SESS,OLE_CLNDR_ID,WEEK_ACTIVE)
  VALUES ('100','09:00','17:00','0','6','AM','PM','100','false')
/
