TRUNCATE TABLE OLE_DLVR_BORR_TYP_T DROP STORAGE
/
INSERT INTO OLE_DLVR_BORR_TYP_T (DLVR_BORR_TYP_CD,DLVR_BORR_TYP_DESC,DLVR_BORR_TYP_ID,DLVR_BORR_TYP_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('FAC','Use for current Faculty','1','Faculty','d91f80e5-4340-462d-9b57-04f2d6ac005f','Y',1)
/
INSERT INTO OLE_DLVR_BORR_TYP_T (DLVR_BORR_TYP_CD,DLVR_BORR_TYP_DESC,DLVR_BORR_TYP_ID,DLVR_BORR_TYP_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('FACR','User for retired Faculty','2','FacultyRetired','501eca3d-452f-41e7-9611-108f882c4be4','Y',1)
/
INSERT INTO OLE_DLVR_BORR_TYP_T (DLVR_BORR_TYP_CD,DLVR_BORR_TYP_DESC,DLVR_BORR_TYP_ID,DLVR_BORR_TYP_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('STAFF','Use for Staff','3','Staff','474ba932-fd89-469d-86de-0a805f7bbb27','Y',1)
/
INSERT INTO OLE_DLVR_BORR_TYP_T (DLVR_BORR_TYP_CD,DLVR_BORR_TYP_DESC,DLVR_BORR_TYP_ID,DLVR_BORR_TYP_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('AVR','Use for Affiliates, Visiting borrowers, Reciprocal users','4','AffVisRecip','2a932ae6-1fa0-4bde-aaab-e3a4abd75316','Y',1)
/
INSERT INTO OLE_DLVR_BORR_TYP_T (DLVR_BORR_TYP_CD,DLVR_BORR_TYP_DESC,DLVR_BORR_TYP_ID,DLVR_BORR_TYP_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('RES','Use for Researcher','5','Researcher','c467eb0b-a237-489d-9c7f-1a17f1737e1a','Y',1)
/
INSERT INTO OLE_DLVR_BORR_TYP_T (DLVR_BORR_TYP_CD,DLVR_BORR_TYP_DESC,DLVR_BORR_TYP_ID,DLVR_BORR_TYP_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('GRAD','Use for Graduate Students','6','Graduate','140618ab-eac5-4e3f-ba32-3b2e5015cd03','Y',1)
/
INSERT INTO OLE_DLVR_BORR_TYP_T (DLVR_BORR_TYP_CD,DLVR_BORR_TYP_DESC,DLVR_BORR_TYP_ID,DLVR_BORR_TYP_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('UGRAD','Use for Undergraduate Students','7','UnderGrad','9837236f-ab3a-4353-bf25-508780126bdb','Y',1)
/
INSERT INTO OLE_DLVR_BORR_TYP_T (DLVR_BORR_TYP_CD,DLVR_BORR_TYP_DESC,DLVR_BORR_TYP_ID,DLVR_BORR_TYP_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('ALUM','Use for Alumni','8','Alumni','72fb5c45-0c11-421c-bbbe-eebaeb5bbe16','Y',1)
/
INSERT INTO OLE_DLVR_BORR_TYP_T (DLVR_BORR_TYP_CD,DLVR_BORR_TYP_DESC,DLVR_BORR_TYP_ID,DLVR_BORR_TYP_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('GUEST','Use for Courtesy, Non-Affiliated, Public, Guest borrowers','9','Guest','1b3eb90d-01a8-412c-9132-d6221b70b943','Y',2)
/
