TRUNCATE TABLE OLE_DLVR_ITEM_AVAIL_STAT_T DROP STORAGE
/
INSERT INTO OLE_DLVR_ITEM_AVAIL_STAT_T (ITEM_AVAIL_STAT_CD,ITEM_AVAIL_STAT_ID,ITEM_AVAIL_STAT_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('AVAILABLE','1','Available','1abf3de3-2221-4249-a829-2c386ee9f514','Y',1)
/
INSERT INTO OLE_DLVR_ITEM_AVAIL_STAT_T (ITEM_AVAIL_STAT_CD,ITEM_AVAIL_STAT_ID,ITEM_AVAIL_STAT_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('ONORDER','2','On Order','1abf3de3-2221-4249-a829-2c386ee9f514','Y',1)
/
INSERT INTO OLE_DLVR_ITEM_AVAIL_STAT_T (ITEM_AVAIL_STAT_CD,ITEM_AVAIL_STAT_ID,ITEM_AVAIL_STAT_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('LOANED','3','Loaned','1abf3de3-2221-4249-a829-2c386ee9f514','Y',1)
/
INSERT INTO OLE_DLVR_ITEM_AVAIL_STAT_T (ITEM_AVAIL_STAT_CD,ITEM_AVAIL_STAT_ID,ITEM_AVAIL_STAT_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('INPROCESS','4','In Process','1abf3de3-2221-4249-a829-2c386ee9f514','Y',1)
/
INSERT INTO OLE_DLVR_ITEM_AVAIL_STAT_T (ITEM_AVAIL_STAT_CD,ITEM_AVAIL_STAT_ID,ITEM_AVAIL_STAT_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('INTRANSIT','5','In Transit','1abf3de3-2221-4249-a829-2c386ee9f514','Y',1)
/
INSERT INTO OLE_DLVR_ITEM_AVAIL_STAT_T (ITEM_AVAIL_STAT_CD,ITEM_AVAIL_STAT_ID,ITEM_AVAIL_STAT_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('UNAVAILABLE','6','Unavailable','1abf3de3-2221-4249-a829-2c386ee9f514','Y',1)
/
INSERT INTO OLE_DLVR_ITEM_AVAIL_STAT_T (ITEM_AVAIL_STAT_CD,ITEM_AVAIL_STAT_ID,ITEM_AVAIL_STAT_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('LOST','7','Lost','1abf3de3-2221-4249-a829-2c386ee9f514','Y',1)
/
INSERT INTO OLE_DLVR_ITEM_AVAIL_STAT_T (ITEM_AVAIL_STAT_CD,ITEM_AVAIL_STAT_ID,ITEM_AVAIL_STAT_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('INTRANSIT-FOR-HOLD','8','In Transit for Hold','1abf3de3-2221-4249-a829-2c386ee9f514','Y',1)
/
INSERT INTO OLE_DLVR_ITEM_AVAIL_STAT_T (ITEM_AVAIL_STAT_CD,ITEM_AVAIL_STAT_ID,ITEM_AVAIL_STAT_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('INTRANSIT-PER-STAFF-REQUEST','9','In Transit per staff request','1abf3de3-2221-4249-a829-2c386ee9f514','Y',1)
/
INSERT INTO OLE_DLVR_ITEM_AVAIL_STAT_T (ITEM_AVAIL_STAT_CD,ITEM_AVAIL_STAT_ID,ITEM_AVAIL_STAT_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('RECENTLY-RETURNED','10','Recently Returned','1abf3de3-2221-4249-a829-2c386ee9f514','Y',1)
/
INSERT INTO OLE_DLVR_ITEM_AVAIL_STAT_T (ITEM_AVAIL_STAT_CD,ITEM_AVAIL_STAT_ID,ITEM_AVAIL_STAT_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('ONHOLD','11','On Hold','1abf3de3-2221-4249-a829-2c386ee9f514','Y',1)
/
INSERT INTO OLE_DLVR_ITEM_AVAIL_STAT_T (ITEM_AVAIL_STAT_CD,ITEM_AVAIL_STAT_ID,ITEM_AVAIL_STAT_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('csa','12','csa','10','Y',1)
/
INSERT INTO OLE_DLVR_ITEM_AVAIL_STAT_T (ITEM_AVAIL_STAT_CD,ITEM_AVAIL_STAT_ID,ITEM_AVAIL_STAT_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('csn','13','csn','11','Y',1)
/
INSERT INTO OLE_DLVR_ITEM_AVAIL_STAT_T (ITEM_AVAIL_STAT_CD,ITEM_AVAIL_STAT_ID,ITEM_AVAIL_STAT_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('csp','14','csp','12','Y',1)
/
INSERT INTO OLE_DLVR_ITEM_AVAIL_STAT_T (ITEM_AVAIL_STAT_CD,ITEM_AVAIL_STAT_ID,ITEM_AVAIL_STAT_NM,OBJ_ID,ROW_ACT_IND,VER_NBR)
  VALUES ('MISSING','15','MISSING','1abf3de3-2221-4249-a829-2c386ee9f515','Y',1)
/
