TRUNCATE TABLE OLE_BAT_PRF_RNM_FLD_T DROP STORAGE
/
INSERT INTO OLE_BAT_PRF_RNM_FLD_T (BAT_PRF_RNM_ID,BAT_PRCS_PRF_ID,BAT_PRF_ORGNL_TAG,BAT_PRF_ORGNL_IND1,BAT_PRF_ORGNL_IND2,BAT_PRF_ORGNL_SUBFLD,BAT_PRF_ORG_SUB_CNTN,BAT_PRF_RNM_TAG,BAT_PRF_RNM_IND1,BAT_PRF_RNM_IND2,BAT_PRF_RNM_SUBFLD,BAT_PRF_RNM_SUB_CNTN,OBJ_ID,VER_NBR)
  VALUES ('1','10','200','','','','','300','','','','','1',1)
/
INSERT INTO OLE_BAT_PRF_RNM_FLD_T (BAT_PRF_RNM_ID,BAT_PRCS_PRF_ID,BAT_PRF_ORGNL_TAG,BAT_PRF_ORGNL_IND1,BAT_PRF_ORGNL_IND2,BAT_PRF_ORGNL_SUBFLD,BAT_PRF_ORG_SUB_CNTN,BAT_PRF_RNM_TAG,BAT_PRF_RNM_IND1,BAT_PRF_RNM_IND2,BAT_PRF_RNM_SUBFLD,BAT_PRF_RNM_SUB_CNTN,OBJ_ID,VER_NBR)
  VALUES ('2','11','240','','','a','','300','','','b','','1',1)
/
INSERT INTO OLE_BAT_PRF_RNM_FLD_T (BAT_PRF_RNM_ID,BAT_PRCS_PRF_ID,BAT_PRF_ORGNL_TAG,BAT_PRF_ORGNL_IND1,BAT_PRF_ORGNL_IND2,BAT_PRF_ORGNL_SUBFLD,BAT_PRF_ORG_SUB_CNTN,BAT_PRF_RNM_TAG,BAT_PRF_RNM_IND1,BAT_PRF_RNM_IND2,BAT_PRF_RNM_SUBFLD,BAT_PRF_RNM_SUB_CNTN,OBJ_ID,VER_NBR)
  VALUES ('3','12','240','','','a','','300','','','b','','1',1)
/
INSERT INTO OLE_BAT_PRF_RNM_FLD_T (BAT_PRF_RNM_ID,BAT_PRCS_PRF_ID,BAT_PRF_ORGNL_TAG,BAT_PRF_ORGNL_IND1,BAT_PRF_ORGNL_IND2,BAT_PRF_ORGNL_SUBFLD,BAT_PRF_ORG_SUB_CNTN,BAT_PRF_RNM_TAG,BAT_PRF_RNM_IND1,BAT_PRF_RNM_IND2,BAT_PRF_RNM_SUBFLD,BAT_PRF_RNM_SUB_CNTN,OBJ_ID,VER_NBR)
  VALUES ('4','12','300','1','3','a','','310','','','b','','1',1)
/
INSERT INTO OLE_BAT_PRF_RNM_FLD_T (BAT_PRF_RNM_ID,BAT_PRCS_PRF_ID,BAT_PRF_ORGNL_TAG,BAT_PRF_ORGNL_IND1,BAT_PRF_ORGNL_IND2,BAT_PRF_ORGNL_SUBFLD,BAT_PRF_ORG_SUB_CNTN,BAT_PRF_RNM_TAG,BAT_PRF_RNM_IND1,BAT_PRF_RNM_IND2,BAT_PRF_RNM_SUBFLD,BAT_PRF_RNM_SUB_CNTN,OBJ_ID,VER_NBR)
  VALUES ('5','12','800','','','a','','300','','','b','','1',1)
/
INSERT INTO OLE_BAT_PRF_RNM_FLD_T (BAT_PRF_RNM_ID,BAT_PRCS_PRF_ID,BAT_PRF_ORGNL_TAG,BAT_PRF_ORGNL_IND1,BAT_PRF_ORGNL_IND2,BAT_PRF_ORGNL_SUBFLD,BAT_PRF_ORG_SUB_CNTN,BAT_PRF_RNM_TAG,BAT_PRF_RNM_IND1,BAT_PRF_RNM_IND2,BAT_PRF_RNM_SUBFLD,BAT_PRF_RNM_SUB_CNTN,OBJ_ID,VER_NBR)
  VALUES ('6','13','440','','','a','','350','','','b','','1',1)
/
INSERT INTO OLE_BAT_PRF_RNM_FLD_T (BAT_PRF_RNM_ID,BAT_PRCS_PRF_ID,BAT_PRF_ORGNL_TAG,BAT_PRF_ORGNL_IND1,BAT_PRF_ORGNL_IND2,BAT_PRF_ORGNL_SUBFLD,BAT_PRF_ORG_SUB_CNTN,BAT_PRF_RNM_TAG,BAT_PRF_RNM_IND1,BAT_PRF_RNM_IND2,BAT_PRF_RNM_SUBFLD,BAT_PRF_RNM_SUB_CNTN,OBJ_ID,VER_NBR)
  VALUES ('7','14','250','','','a','','340','','','b','','1',1)
/
INSERT INTO OLE_BAT_PRF_RNM_FLD_T (BAT_PRF_RNM_ID,BAT_PRCS_PRF_ID,BAT_PRF_ORGNL_TAG,BAT_PRF_ORGNL_IND1,BAT_PRF_ORGNL_IND2,BAT_PRF_ORGNL_SUBFLD,BAT_PRF_ORG_SUB_CNTN,BAT_PRF_RNM_TAG,BAT_PRF_RNM_IND1,BAT_PRF_RNM_IND2,BAT_PRF_RNM_SUBFLD,BAT_PRF_RNM_SUB_CNTN,OBJ_ID,VER_NBR)
  VALUES ('8','15','330','','','a','','540','','','b','','1',1)
/
INSERT INTO OLE_BAT_PRF_RNM_FLD_T (BAT_PRF_RNM_ID,BAT_PRCS_PRF_ID,BAT_PRF_ORGNL_TAG,BAT_PRF_ORGNL_IND1,BAT_PRF_ORGNL_IND2,BAT_PRF_ORGNL_SUBFLD,BAT_PRF_ORG_SUB_CNTN,BAT_PRF_RNM_TAG,BAT_PRF_RNM_IND1,BAT_PRF_RNM_IND2,BAT_PRF_RNM_SUBFLD,BAT_PRF_RNM_SUB_CNTN,OBJ_ID,VER_NBR)
  VALUES ('9','16','430','','','a','','450','','','b','','1',1)
/
INSERT INTO OLE_BAT_PRF_RNM_FLD_T (BAT_PRF_RNM_ID,BAT_PRCS_PRF_ID,BAT_PRF_ORGNL_TAG,BAT_PRF_ORGNL_IND1,BAT_PRF_ORGNL_IND2,BAT_PRF_ORGNL_SUBFLD,BAT_PRF_ORG_SUB_CNTN,BAT_PRF_RNM_TAG,BAT_PRF_RNM_IND1,BAT_PRF_RNM_IND2,BAT_PRF_RNM_SUBFLD,BAT_PRF_RNM_SUB_CNTN,OBJ_ID,VER_NBR)
  VALUES ('10','17','340','','','a','','420','','','b','','1',1)
/
INSERT INTO OLE_BAT_PRF_RNM_FLD_T (BAT_PRF_RNM_ID,BAT_PRCS_PRF_ID,BAT_PRF_ORGNL_TAG,BAT_PRF_ORGNL_IND1,BAT_PRF_ORGNL_IND2,BAT_PRF_ORGNL_SUBFLD,BAT_PRF_ORG_SUB_CNTN,BAT_PRF_RNM_TAG,BAT_PRF_RNM_IND1,BAT_PRF_RNM_IND2,BAT_PRF_RNM_SUBFLD,BAT_PRF_RNM_SUB_CNTN,OBJ_ID,VER_NBR)
  VALUES ('11','18','600','','','a','','500','','','b','','1',1)
/
