TRUNCATE TABLE CA_OBJ_TYPE_T DROP STORAGE
/
INSERT INTO CA_OBJ_TYPE_T (FIN_OBJ_TYP_CD,OBJ_ID,VER_NBR,FIN_OBJ_TYP_NM,FIN_OBJTYP_DBCR_CD,FIN_OBJ_TYP_ICR_CD,FUND_BALANCE_CD,FIN_REPORT_SORT_CD,ACCTG_CTGRY_CD,ROW_ACTV_IND)
  VALUES ('AS','014F3DAF6EDBA448E043814FD28EA448',1.0,'ASSET','D','N','N','C1','AS','Y')
/
INSERT INTO CA_OBJ_TYPE_T (FIN_OBJ_TYP_CD,OBJ_ID,VER_NBR,FIN_OBJ_TYP_NM,FIN_OBJTYP_DBCR_CD,FIN_OBJ_TYP_ICR_CD,FUND_BALANCE_CD,FIN_REPORT_SORT_CD,ACCTG_CTGRY_CD,ROW_ACTV_IND)
  VALUES ('CH','014F3DAF6EDCA448E043814FD28EA448',1.0,'CASH NOT INCOME','C','N','N','A3','IN','Y')
/
INSERT INTO CA_OBJ_TYPE_T (FIN_OBJ_TYP_CD,OBJ_ID,VER_NBR,FIN_OBJ_TYP_NM,FIN_OBJTYP_DBCR_CD,FIN_OBJ_TYP_ICR_CD,FUND_BALANCE_CD,FIN_REPORT_SORT_CD,ACCTG_CTGRY_CD,ROW_ACTV_IND)
  VALUES ('EE','014F3DAF6EDDA448E043814FD28EA448',1.0,'EXPENDITURE NOT EXPENSE','D','Y','N','B2','EX','Y')
/
INSERT INTO CA_OBJ_TYPE_T (FIN_OBJ_TYP_CD,OBJ_ID,VER_NBR,FIN_OBJ_TYP_NM,FIN_OBJTYP_DBCR_CD,FIN_OBJ_TYP_ICR_CD,FUND_BALANCE_CD,FIN_REPORT_SORT_CD,ACCTG_CTGRY_CD,ROW_ACTV_IND)
  VALUES ('ES','014F3DAF6EDEA448E043814FD28EA448',1.0,'EXPENSE NOT EXPENDITURE','D','N','N','B3','EX','Y')
/
INSERT INTO CA_OBJ_TYPE_T (FIN_OBJ_TYP_CD,OBJ_ID,VER_NBR,FIN_OBJ_TYP_NM,FIN_OBJTYP_DBCR_CD,FIN_OBJ_TYP_ICR_CD,FUND_BALANCE_CD,FIN_REPORT_SORT_CD,ACCTG_CTGRY_CD,ROW_ACTV_IND)
  VALUES ('EX','014F3DAF6EDFA448E043814FD28EA448',1.0,'EXPENSE EXPENDITURE','D','Y','N','B1','EX','Y')
/
INSERT INTO CA_OBJ_TYPE_T (FIN_OBJ_TYP_CD,OBJ_ID,VER_NBR,FIN_OBJ_TYP_NM,FIN_OBJTYP_DBCR_CD,FIN_OBJ_TYP_ICR_CD,FUND_BALANCE_CD,FIN_REPORT_SORT_CD,ACCTG_CTGRY_CD,ROW_ACTV_IND)
  VALUES ('FB','014F3DAF6EE0A448E043814FD28EA448',1.0,'FUND BALANCE','C','N','Y','F1','FB','Y')
/
INSERT INTO CA_OBJ_TYPE_T (FIN_OBJ_TYP_CD,OBJ_ID,VER_NBR,FIN_OBJ_TYP_NM,FIN_OBJTYP_DBCR_CD,FIN_OBJ_TYP_ICR_CD,FUND_BALANCE_CD,FIN_REPORT_SORT_CD,ACCTG_CTGRY_CD,ROW_ACTV_IND)
  VALUES ('IC','014F3DAF6EE1A448E043814FD28EA448',1.0,'INCOME NOT CASH','C','N','N','A2','IN','Y')
/
INSERT INTO CA_OBJ_TYPE_T (FIN_OBJ_TYP_CD,OBJ_ID,VER_NBR,FIN_OBJ_TYP_NM,FIN_OBJTYP_DBCR_CD,FIN_OBJ_TYP_ICR_CD,FUND_BALANCE_CD,FIN_REPORT_SORT_CD,ACCTG_CTGRY_CD,ROW_ACTV_IND)
  VALUES ('IN','014F3DAF6EE2A448E043814FD28EA448',1.0,'INCOME-CASH','C','N','N','A1','IN','Y')
/
INSERT INTO CA_OBJ_TYPE_T (FIN_OBJ_TYP_CD,OBJ_ID,VER_NBR,FIN_OBJ_TYP_NM,FIN_OBJTYP_DBCR_CD,FIN_OBJ_TYP_ICR_CD,FUND_BALANCE_CD,FIN_REPORT_SORT_CD,ACCTG_CTGRY_CD,ROW_ACTV_IND)
  VALUES ('LI','014F3DAF6EE3A448E043814FD28EA448',1.0,'LIABILITY','C','N','N','D1','LI','Y')
/
INSERT INTO CA_OBJ_TYPE_T (FIN_OBJ_TYP_CD,OBJ_ID,VER_NBR,FIN_OBJ_TYP_NM,FIN_OBJTYP_DBCR_CD,FIN_OBJ_TYP_ICR_CD,FUND_BALANCE_CD,FIN_REPORT_SORT_CD,ACCTG_CTGRY_CD,ROW_ACTV_IND)
  VALUES ('TE','014F3DAF6EE4A448E043814FD28EA448',1.0,'TRANSFER OF FUNDS - EXPENSE','D','N','N','B4','EX','Y')
/
INSERT INTO CA_OBJ_TYPE_T (FIN_OBJ_TYP_CD,OBJ_ID,VER_NBR,FIN_OBJ_TYP_NM,FIN_OBJTYP_DBCR_CD,FIN_OBJ_TYP_ICR_CD,FUND_BALANCE_CD,FIN_REPORT_SORT_CD,ACCTG_CTGRY_CD,ROW_ACTV_IND)
  VALUES ('TI','014F3DAF6EE5A448E043814FD28EA448',1.0,'TRANSFER OF FUNDS - INCOME','C','N','N','A4','IN','Y')
/
