TRUNCATE TABLE CA_SUB_FUND_GRP_T DROP STORAGE
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('AUXAMB','015D880780746C10E043814FD8816C10',1.0,'AE','AUXILIARY AMBULATORY SERVICES','Y','A','21','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('AUXCOM','015D880780756C10E043814FD8816C10',1.0,'AE','AUXILIARY COMPUTER SERVICES','Y','I','23','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('AUXENT','015D880780766C10E043814FD8816C10',1.0,'AE','AUXILIARY ENTERPRISES','Y','A','20','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('AUXHOS','015D880780776C10E043814FD8816C10',1.0,'AE','AUXILIARY HOSPITALS','Y','A','22','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('AUXSER','015D880780786C10E043814FD8816C10',1.0,'AE','AUXILIARY SERVICE FUNDS','Y','I','24','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('CLEAR','015D880780796C10E043814FD8816C10',1.0,'CL','CLEARING AND ROTATING FUNDS','Y','N','25','N','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('DEPOSI','ED250FEB-7333-380F-A418-84C20E71E89F',1.0,'DP','DEPOSIT ACCOUNT','Y','N','50','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMEA','015D8807807A6C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMEB','015D8807807B6C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMEC','015D8807807C6C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMED','015D8807807D6C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMEE','015D8807807E6C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMEF','015D8807807F6C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMEG','015D880780806C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMEH','015D880780816C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMEJ','015D880780826C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMEK','015D880780836C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMEM','015D880780846C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMEN','015D880780856C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMEP','015D880780866C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMEQ','015D880780876C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMER','015D880780886C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMEX','015D880780896C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','N','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMXA','015D8807808A6C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMXB','015D8807808B6C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMXC','015D8807808C6C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMXD','015D8807808D6C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMXE','015D8807808E6C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMXF','015D8807808F6C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMXG','015D880780906C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMXH','015D880780916C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMXJ','015D880780926C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMXK','015D880780936C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMXM','015D880780946C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMXN','015D880780956C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMXP','015D880780966C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMXQ','015D880780976C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('COMMXR','015D880780986C10E043814FD8816C10',1.0,'CG','COMMERCIAL/FOR PROFIT','Y','N','15','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('DCEDU','015D880780996C10E043814FD8816C10',1.0,'DS','CONTINUING EDUCATION','Y','N','03','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('DFRES','015D8807809A6C10E043814FD8816C10',1.0,'DS','FACULTY RESEARCH','Y','N','05','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('DOFDS','015D8807809B6C10E043814FD8816C10',1.0,'DS','DESIGNATED OTHER FUNDS','Y','N','06','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('DPSA','015D8807809C6C10E043814FD8816C10',1.0,'DS','PUBLIC SERVICE ACTIVITY','Y','N','04','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('DSCFE','015D8807809D6C10E043814FD8816C10',1.0,'DS','SCHOLARSHIP & FELLOWSHIPS - UNRESTRICTED','Y','N','07','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('ENDOW','015D8807809E6C10E043814FD8816C10',1.0,'EN','ENDOWMENTS','Y','N','27','N','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('EXTAGY','015D8807809F6C10E043814FD8816C10',1.0,'AF','EXTERNAL AGENCY FUNDS','Y','N','38','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FEDERA','015D880780A06C10E043814FD8816C10',1.0,'CG','FEDERAL','Y','N','14','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FEDERB','015D880780A16C10E043814FD8816C10',1.0,'CG','FEDERAL','Y','N','14','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FEDERC','015D880780A26C10E043814FD8816C10',1.0,'CG','FEDERAL','Y','N','14','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FEDERD','015D880780A36C10E043814FD8816C10',1.0,'CG','FEDERAL','Y','N','14','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FEDERE','015D880780A46C10E043814FD8816C10',1.0,'CG','FEDERAL','Y','N','14','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FEDERF','015D880780A56C10E043814FD8816C10',1.0,'CG','FEDERAL','Y','N','14','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FEDERG','015D880780A66C10E043814FD8816C10',1.0,'CG','FEDERAL','Y','N','14','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FEDERH','015D880780A76C10E043814FD8816C10',1.0,'CG','FEDERAL','Y','N','14','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FEDERJ','015D880780A86C10E043814FD8816C10',1.0,'CG','FEDERAL','Y','N','14','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FEDERK','015D880780A96C10E043814FD8816C10',1.0,'CG','FEDERAL','Y','N','14','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FEDERM','015D880780AA6C10E043814FD8816C10',1.0,'CG','FEDERAL','Y','N','14','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FEDERN','015D880780AB6C10E043814FD8816C10',1.0,'CG','FEDERAL','Y','N','14','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FEDERP','015D880780AC6C10E043814FD8816C10',1.0,'CG','FEDERAL','Y','N','14','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FEDERQ','015D880780AD6C10E043814FD8816C10',1.0,'CG','FEDERAL','Y','N','14','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FEDERR','015D880780AE6C10E043814FD8816C10',1.0,'CG','FEDERAL','Y','N','14','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FEDERX','015D880780AF6C10E043814FD8816C10',1.0,'CG','FEDERAL','N','N','14','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FEMP','015D880780B06C10E043814FD8816C10',1.0,'RF','ENDOWMENT MATCH PROGRAMS','Y','N','11','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FFEND','015D880780B16C10E043814FD8816C10',1.0,'EN','FUNDS FUNCTIONING AS ENDOWMENTS','Y','N','28','N','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FOUNDA','015D880780B26C10E043814FD8816C10',1.0,'CG','FOUNDATIONS','Y','N','17','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FOUNDB','015D880780B36C10E043814FD8816C10',1.0,'CG','FOUNDATIONS','Y','N','17','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FOUNDC','015D880780B46C10E043814FD8816C10',1.0,'CG','FOUNDATIONS','Y','N','17','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FOUNDD','015D880780B56C10E043814FD8816C10',1.0,'CG','FOUNDATIONS','Y','N','17','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FOUNDE','015D880780B66C10E043814FD8816C10',1.0,'CG','FOUNDATIONS','Y','N','17','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FOUNDF','015D880780B76C10E043814FD8816C10',1.0,'CG','FOUNDATIONS','Y','N','17','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FOUNDG','015D880780B86C10E043814FD8816C10',1.0,'CG','FOUNDATIONS','Y','N','17','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FOUNDH','015D880780B96C10E043814FD8816C10',1.0,'CG','FOUNDATIONS','Y','N','17','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FOUNDJ','015D880780BA6C10E043814FD8816C10',1.0,'CG','FOUNDATIONS','Y','N','17','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FOUNDK','015D880780BB6C10E043814FD8816C10',1.0,'CG','FOUNDATIONS','Y','N','17','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FOUNDM','015D880780BC6C10E043814FD8816C10',1.0,'CG','FOUNDATIONS','Y','N','17','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FOUNDN','015D880780BD6C10E043814FD8816C10',1.0,'CG','FOUNDATIONS','Y','N','17','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FOUNDP','015D880780BE6C10E043814FD8816C10',1.0,'CG','FOUNDATIONS','Y','N','17','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FOUNDQ','015D880780BF6C10E043814FD8816C10',1.0,'CG','FOUNDATIONS','Y','N','17','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FOUNDR','015D880780C06C10E043814FD8816C10',1.0,'CG','FOUNDATIONS','Y','N','17','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('FOUNDX','015D880780C16C10E043814FD8816C10',1.0,'CG','FOUNDATIONS','N','N','17','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('GENFND','015D880780C26C10E043814FD8816C10',1.0,'GF','GENERAL FUNDS','Y','N','01','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('HIEDUA','015D880780C36C10E043814FD8816C10',1.0,'CG','HIGHER EDUCATION','Y','N','13','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('HIEDUB','015D880780C46C10E043814FD8816C10',1.0,'CG','HIGHER EDUCATION','Y','N','13','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('HIEDUC','015D880780C56C10E043814FD8816C10',1.0,'CG','HIGHER EDUCATION','Y','N','13','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('HIEDUD','015D880780C66C10E043814FD8816C10',1.0,'CG','HIGHER EDUCATION','Y','N','13','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('HIEDUE','015D880780C76C10E043814FD8816C10',1.0,'CG','HIGHER EDUCATION','Y','N','13','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('HIEDUF','015D880780C86C10E043814FD8816C10',1.0,'CG','HIGHER EDUCATION','Y','N','13','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('HIEDUG','015D880780C96C10E043814FD8816C10',1.0,'CG','HIGHER EDUCATION','Y','N','13','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('HIEDUH','015D880780CA6C10E043814FD8816C10',1.0,'CG','HIGHER EDUCATION','Y','N','13','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('HIEDUJ','015D880780CB6C10E043814FD8816C10',1.0,'CG','HIGHER EDUCATION','Y','N','13','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('HIEDUK','015D880780CC6C10E043814FD8816C10',1.0,'CG','HIGHER EDUCATION','Y','N','13','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('HIEDUM','015D880780CD6C10E043814FD8816C10',1.0,'CG','HIGHER EDUCATION','Y','N','13','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('HIEDUN','015D880780CE6C10E043814FD8816C10',1.0,'CG','HIGHER EDUCATION','Y','N','13','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('HIEDUP','015D880780CF6C10E043814FD8816C10',1.0,'CG','HIGHER EDUCATION','Y','N','13','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('HIEDUQ','015D880780D06C10E043814FD8816C10',1.0,'CG','HIGHER EDUCATION','Y','N','13','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('HIEDUR','015D880780D16C10E043814FD8816C10',1.0,'CG','HIGHER EDUCATION','Y','N','13','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('HIEDUX','015D880780D26C10E043814FD8816C10',1.0,'CG','HIGHER EDUCATION','N','N','13','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('INTAGY','015D880780D36C10E043814FD8816C10',1.0,'AF','INTERNAL AGENCY FUNDS','Y','N','37','N','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('INTLOA','015D880780D46C10E043814FD8816C10',1.0,'LF','INTERNAL LOAN FUND','Y','N','26','N','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('LEEND','015D880780D56C10E043814FD8816C10',1.0,'EN','LIFE ESTATE ENDOWMENTS','Y','N','29','N','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('LOANFD','015D880780D66C10E043814FD8816C10',1.0,'LF','LOAN FUNDS','Y','N','26','N','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('MCLAR','015D880781196C10E043814FD8816C10',1.0,'AE','CLARIAN HEALTH PARTNER FUNDS','Y','A','21','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('MHOUSE','015D880780D76C10E043814FD8816C10',1.0,'GF','HOUSESTAFF SERVICES','Y','N','01','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('MLABS','015D8807811A6C10E043814FD8816C10',1.0,'AE','MEDICAL LABORATORY SERVICES','Y','A','21','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('MPPLAN','015D8807811B6C10E043814FD8816C10',1.0,'AE','MEDICAL PRACTICE PLAN FUNDS','Y','A','21','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('MPRACT','015D880780D86C10E043814FD8816C10',1.0,'GF','MEDICAL PRACTICE FUNDS','Y','N','01','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('MPROF','015D880780D96C10E043814FD8816C10',1.0,'GF','MEDICAL PROFESSIONAL SERVICES','Y','N','01','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('MSERV','015D8807811C6C10E043814FD8816C10',1.0,'AE','MEDICAL SERVICES','Y','A','21','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('MWISH','015D880780DA6C10E043814FD8816C10',1.0,'GF','WISHARD PROFESSIONAL SERVICES','Y','N','01','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('NONPRA','015D880780DB6C10E043814FD8816C10',1.0,'CG','NON-PROFIT','Y','N','18','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('NONPRB','015D880780DC6C10E043814FD8816C10',1.0,'CG','NON-PROFIT','Y','N','18','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('NONPRC','015D880780DD6C10E043814FD8816C10',1.0,'CG','NON-PROFIT','Y','N','18','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('NONPRD','015D880780DE6C10E043814FD8816C10',1.0,'CG','NON-PROFIT','Y','N','18','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('NONPRE','015D880780DF6C10E043814FD8816C10',1.0,'CG','NON-PROFIT','Y','N','18','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('NONPRF','015D880780E06C10E043814FD8816C10',1.0,'CG','NON-PROFIT','Y','N','18','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('NONPRG','015D880780E16C10E043814FD8816C10',1.0,'CG','NON-PROFIT','Y','N','18','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('NONPRH','015D880780E26C10E043814FD8816C10',1.0,'CG','NON-PROFIT','Y','N','18','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('NONPRJ','015D880780E36C10E043814FD8816C10',1.0,'CG','NON-PROFIT','Y','N','18','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('NONPRK','015D880780E46C10E043814FD8816C10',1.0,'CG','NON-PROFIT','Y','N','18','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('NONPRM','015D880780E56C10E043814FD8816C10',1.0,'CG','NON-PROFIT','Y','N','18','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('NONPRN','015D880780E66C10E043814FD8816C10',1.0,'CG','NON-PROFIT','Y','N','18','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('NONPRP','015D880780E76C10E043814FD8816C10',1.0,'CG','NON-PROFIT','Y','N','18','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('NONPRQ','015D880780E86C10E043814FD8816C10',1.0,'CG','NON-PROFIT','Y','N','18','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('NONPRR','015D880780E96C10E043814FD8816C10',1.0,'CG','NON-PROFIT','Y','N','18','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('NONPRX','015D880780EA6C10E043814FD8816C10',1.0,'CG','NON-PROFIT','N','N','18','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('OTGOVA','015D880780EB6C10E043814FD8816C10',1.0,'CG','OTHER GOVERNMENTAL','Y','N','19','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('OTGOVB','015D880780EC6C10E043814FD8816C10',1.0,'CG','OTHER GOVERNMENTAL','Y','N','19','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('OTGOVC','015D880780ED6C10E043814FD8816C10',1.0,'CG','OTHER GOVERNMENTAL','Y','N','19','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('OTGOVD','015D880780EE6C10E043814FD8816C10',1.0,'CG','OTHER GOVERNMENTAL','Y','N','19','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('OTGOVE','015D880780EF6C10E043814FD8816C10',1.0,'CG','OTHER GOVERNMENTAL','Y','N','19','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('OTGOVF','015D880780F06C10E043814FD8816C10',1.0,'CG','OTHER GOVERNMENTAL','Y','N','19','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('OTGOVG','015D880780F16C10E043814FD8816C10',1.0,'CG','OTHER GOVERNMENTAL','Y','N','19','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('OTGOVH','015D880780F26C10E043814FD8816C10',1.0,'CG','OTHER GOVERNMENTAL','Y','N','19','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('OTGOVJ','015D880780F36C10E043814FD8816C10',1.0,'CG','OTHER GOVERNMENTAL','Y','N','19','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('OTGOVK','015D880780F46C10E043814FD8816C10',1.0,'CG','OTHER GOVERNMENTAL','Y','N','19','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('OTGOVM','015D880780F56C10E043814FD8816C10',1.0,'CG','OTHER GOVERNMENTAL','Y','N','19','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('OTGOVN','015D880780F66C10E043814FD8816C10',1.0,'CG','OTHER GOVERNMENTAL','Y','N','19','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('OTGOVP','015D880780F76C10E043814FD8816C10',1.0,'CG','OTHER GOVERNMENTAL','Y','N','19','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('OTGOVQ','015D880780F86C10E043814FD8816C10',1.0,'CG','OTHER GOVERNMENTAL','Y','N','19','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('OTGOVR','015D880780F96C10E043814FD8816C10',1.0,'CG','OTHER GOVERNMENTAL','Y','N','19','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('OTGOVX','015D880780FA6C10E043814FD8816C10',1.0,'CG','OTHER GOVERNMENTAL','N','N','19','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('OTHFDS','015D880780FB6C10E043814FD8816C10',1.0,'OF','OTHER FUNDS','Y','N','40','N','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('PFCMR','015D880780FC6C10E043814FD8816C10',1.0,'PF','CONSTRUCTION & MAJOR REMODELING','Y','N','33','N','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('PFIP','015D880780FD6C10E043814FD8816C10',1.0,'PF','INVESTMENT IN PLANT','Y','N','36','N','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('PFRI','015D880780FE6C10E043814FD8816C10',1.0,'PF','RETIREMENT OF INDEBTEDNESS','Y','N','34','N','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('PFRR','015D880780FF6C10E043814FD8816C10',1.0,'PF','RENEWAL AND REPLACEMENT','Y','N','35','N','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('RESFEL','015D880781006C10E043814FD8816C10',1.0,'RF','FELLOWSHIPS','Y','N','09','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('RESSCH','015D880781016C10E043814FD8816C10',1.0,'RF','SCHOLARSHIPS','Y','N','08','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('RHAFNB','015D880781026C10E043814FD8816C10',1.0,'EN','RILEY HOSPITAL AGENCY TRUST-AFNB','Y','N','30','N','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('RHINB','015D880781036C10E043814FD8816C10',1.0,'EN','RILEY HOSPITAL AGENCY TRUST-INB','Y','N','31','N','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('RHMNB','015D880781046C10E043814FD8816C10',1.0,'EN','RILEY HOSPITAL AGENCY TRUST-MNB','Y','N','32','N','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('ROFDS','015D880781056C10E043814FD8816C10',1.0,'RF','RESTRICTED OTHER FUNDS','Y','N','12','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('RSSAPP','015D880781066C10E043814FD8816C10',1.0,'RF','SPECIAL STATE APPROPRIATIONS','Y','N','10','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('SDCI','015D880781076C10E043814FD8816C10',1.0,'DS','OTHER DESIGNATED: IU INITIATIVES','Y','N','02','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('STATEA','015D880781086C10E043814FD8816C10',1.0,'CG','STATE FUNDS','Y','N','16','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('STATEB','015D880781096C10E043814FD8816C10',1.0,'CG','STATE FUNDS','Y','N','16','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('STATEC','015D8807810A6C10E043814FD8816C10',1.0,'CG','STATE FUNDS','Y','N','16','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('STATED','015D8807810B6C10E043814FD8816C10',1.0,'CG','STATE FUNDS','Y','N','16','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('STATEE','015D8807810C6C10E043814FD8816C10',1.0,'CG','STATE FUNDS','Y','N','16','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('STATEF','015D8807810D6C10E043814FD8816C10',1.0,'CG','STATE FUNDS','Y','N','16','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('STATEG','015D8807810E6C10E043814FD8816C10',1.0,'CG','STATE FUNDS','Y','N','16','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('STATEH','015D8807810F6C10E043814FD8816C10',1.0,'CG','STATE FUNDS','Y','N','16','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('STATEJ','015D880781106C10E043814FD8816C10',1.0,'CG','STATE FUNDS','Y','N','16','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('STATEK','015D880781116C10E043814FD8816C10',1.0,'CG','STATE FUNDS','Y','N','16','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('STATEM','015D880781126C10E043814FD8816C10',1.0,'CG','STATE FUNDS','Y','N','16','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('STATEN','015D880781136C10E043814FD8816C10',1.0,'CG','STATE FUNDS','Y','N','16','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('STATEP','015D880781146C10E043814FD8816C10',1.0,'CG','STATE FUNDS','Y','N','16','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('STATEQ','015D880781156C10E043814FD8816C10',1.0,'CG','STATE FUNDS','Y','N','16','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('STATER','015D880781166C10E043814FD8816C10',1.0,'CG','STATE FUNDS','Y','N','16','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('STATEX','015D880781176C10E043814FD8816C10',1.0,'CG','STATE FUNDS','N','N','16','Y','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('STUFF','196D4AE5469B6008E043814FD8816008',1.0,'GF','STUFF FOR TESTING','Y','N','30','N','N')
/
INSERT INTO CA_SUB_FUND_GRP_T (SUB_FUND_GRP_CD,OBJ_ID,VER_NBR,FUND_GRP_CD,SUB_FUND_GRP_DESC,SUBFUNDGRP_ACTV_CD,SUB_FUNDGRP_TYP_CD,FIN_REPORT_SORT_CD,SUB_FUND_GRP_WAGE_IND,FND_GRP_BA_RSTR_LVL_CD)
  VALUES ('WSAGY','015D880781186C10E043814FD8816C10',1.0,'AF','WORK STUDY AGENCY FUNDS','Y','N','39','Y','N')
/
