TRUNCATE TABLE GOKB_DATA_ELMNT_T DROP STORAGE
/
INSERT INTO GOKB_DATA_ELMNT_T (DATA_ELMNT_ID,DATA_ELMNT_NM,REC_TYP,OBJ_ID,VER_NBR)
  VALUES ('1','coverageStartDate','E-Instance','1',1)
/
INSERT INTO GOKB_DATA_ELMNT_T (DATA_ELMNT_ID,DATA_ELMNT_NM,REC_TYP,OBJ_ID,VER_NBR)
  VALUES ('2','coverageStartIssue','E-Instance','2',1)
/
INSERT INTO GOKB_DATA_ELMNT_T (DATA_ELMNT_ID,DATA_ELMNT_NM,REC_TYP,OBJ_ID,VER_NBR)
  VALUES ('3','coverageStartVolume','E-Instance','3',1)
/
INSERT INTO GOKB_DATA_ELMNT_T (DATA_ELMNT_ID,DATA_ELMNT_NM,REC_TYP,OBJ_ID,VER_NBR)
  VALUES ('4','coverageEndDate','E-Instance','4',1)
/
INSERT INTO GOKB_DATA_ELMNT_T (DATA_ELMNT_ID,DATA_ELMNT_NM,REC_TYP,OBJ_ID,VER_NBR)
  VALUES ('5','coverageEndIssue','E-Instance','5',1)
/
INSERT INTO GOKB_DATA_ELMNT_T (DATA_ELMNT_ID,DATA_ELMNT_NM,REC_TYP,OBJ_ID,VER_NBR)
  VALUES ('6','coverageEndVolume','E-Instance','6',1)
/
INSERT INTO GOKB_DATA_ELMNT_T (DATA_ELMNT_ID,DATA_ELMNT_NM,REC_TYP,OBJ_ID,VER_NBR)
  VALUES ('7','url','E-Instance','7',1)
/
INSERT INTO GOKB_DATA_ELMNT_T (DATA_ELMNT_ID,DATA_ELMNT_NM,REC_TYP,OBJ_ID,VER_NBR)
  VALUES ('8','gokbId','E-Instance','8',1)
/
INSERT INTO GOKB_DATA_ELMNT_T (DATA_ELMNT_ID,DATA_ELMNT_NM,REC_TYP,OBJ_ID,VER_NBR)
  VALUES ('9','title','E-Resource','9',1)
/
INSERT INTO GOKB_DATA_ELMNT_T (DATA_ELMNT_ID,DATA_ELMNT_NM,REC_TYP,OBJ_ID,VER_NBR)
  VALUES ('10','Publisher','E-Resource','10',1)
/
INSERT INTO GOKB_DATA_ELMNT_T (DATA_ELMNT_ID,DATA_ELMNT_NM,REC_TYP,OBJ_ID,VER_NBR)
  VALUES ('11','PackageScope','E-Resource','11',1)
/
INSERT INTO GOKB_DATA_ELMNT_T (DATA_ELMNT_ID,DATA_ELMNT_NM,REC_TYP,OBJ_ID,VER_NBR)
  VALUES ('12','Breakable','E-Resource','12',1)
/
INSERT INTO GOKB_DATA_ELMNT_T (DATA_ELMNT_ID,DATA_ELMNT_NM,REC_TYP,OBJ_ID,VER_NBR)
  VALUES ('13','FixedTitleList','E-Resource','13',1)
/
INSERT INTO GOKB_DATA_ELMNT_T (DATA_ELMNT_ID,DATA_ELMNT_NM,REC_TYP,OBJ_ID,VER_NBR)
  VALUES ('14','PackageType','E-Resource','14',1)
/
INSERT INTO GOKB_DATA_ELMNT_T (DATA_ELMNT_ID,DATA_ELMNT_NM,REC_TYP,OBJ_ID,VER_NBR)
  VALUES ('15','eResourceGokbId','E-Resource','15',1)
/
INSERT INTO GOKB_DATA_ELMNT_T (DATA_ELMNT_ID,DATA_ELMNT_NM,REC_TYP,OBJ_ID,VER_NBR)
  VALUES ('16','VariantName','E-Resource','16',1)
/
