TRUNCATE TABLE OLE_PUR_PO_ITM_ORDR_STAT_T DROP STORAGE
/
INSERT INTO OLE_PUR_PO_ITM_ORDR_STAT_T (OLE_PO_ITM_ORDR_STAT_ID,OLE_PO_ITM_ORDR_STAT,VER_NBR,OBJ_ID,ROW_ACTV_IND,DESC_TXT)
  VALUES (1.0,'On order',1.0,'1','Y','PO has been sent to vendor; awaiting receipt')
/
INSERT INTO OLE_PUR_PO_ITM_ORDR_STAT_T (OLE_PO_ITM_ORDR_STAT_ID,OLE_PO_ITM_ORDR_STAT,VER_NBR,OBJ_ID,ROW_ACTV_IND,DESC_TXT)
  VALUES (2.0,'Received',1.0,'2','Y','Title has been received from vendor')
/
INSERT INTO OLE_PUR_PO_ITM_ORDR_STAT_T (OLE_PO_ITM_ORDR_STAT_ID,OLE_PO_ITM_ORDR_STAT,VER_NBR,OBJ_ID,ROW_ACTV_IND,DESC_TXT)
  VALUES (3.0,'In process',1.0,'3','Y','Title has been received from vendor and awaits action by a staff member')
/
