TRUNCATE TABLE OLE_PUR_REQ_RCPT_STATUS_T DROP STORAGE
/
INSERT INTO OLE_PUR_REQ_RCPT_STATUS_T (OLE_REQ_RCPT_STATUS_ID,OLE_REQ_RCPT_STATUS_DOC_TYP,OLE_REQ_RCPT_STATUS_CD,OLE_REQ_RCPT_STATUS_NM,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (1.0,'REQ','PR','Partially Received',1.0,'1','Y')
/
INSERT INTO OLE_PUR_REQ_RCPT_STATUS_T (OLE_REQ_RCPT_STATUS_ID,OLE_REQ_RCPT_STATUS_DOC_TYP,OLE_REQ_RCPT_STATUS_CD,OLE_REQ_RCPT_STATUS_NM,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (2.0,'REQ','FR','Fully Received',1.0,'2','Y')
/
INSERT INTO OLE_PUR_REQ_RCPT_STATUS_T (OLE_REQ_RCPT_STATUS_ID,OLE_REQ_RCPT_STATUS_DOC_TYP,OLE_REQ_RCPT_STATUS_CD,OLE_REQ_RCPT_STATUS_NM,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (3.0,'REQ','NR','NOT Received',1.0,'3','Y')
/
INSERT INTO OLE_PUR_REQ_RCPT_STATUS_T (OLE_REQ_RCPT_STATUS_ID,OLE_REQ_RCPT_STATUS_DOC_TYP,OLE_REQ_RCPT_STATUS_CD,OLE_REQ_RCPT_STATUS_NM,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (4.0,'PO','PR','Partially Received',1.0,'4','Y')
/
INSERT INTO OLE_PUR_REQ_RCPT_STATUS_T (OLE_REQ_RCPT_STATUS_ID,OLE_REQ_RCPT_STATUS_DOC_TYP,OLE_REQ_RCPT_STATUS_CD,OLE_REQ_RCPT_STATUS_NM,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (5.0,'PO','FR','Fully Received',1.0,'5','Y')
/
INSERT INTO OLE_PUR_REQ_RCPT_STATUS_T (OLE_REQ_RCPT_STATUS_ID,OLE_REQ_RCPT_STATUS_DOC_TYP,OLE_REQ_RCPT_STATUS_CD,OLE_REQ_RCPT_STATUS_NM,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (6.0,'PO','NR','NOT Received',1.0,'6','Y')
/
INSERT INTO OLE_PUR_REQ_RCPT_STATUS_T (OLE_REQ_RCPT_STATUS_ID,OLE_REQ_RCPT_STATUS_DOC_TYP,OLE_REQ_RCPT_STATUS_CD,OLE_REQ_RCPT_STATUS_NM,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (7.0,'RCV','NON','None',1.0,'7','Y')
/
INSERT INTO OLE_PUR_REQ_RCPT_STATUS_T (OLE_REQ_RCPT_STATUS_ID,OLE_REQ_RCPT_STATUS_DOC_TYP,OLE_REQ_RCPT_STATUS_CD,OLE_REQ_RCPT_STATUS_NM,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (8.0,'RCV','EXP','Expected',1.0,'8','Y')
/
INSERT INTO OLE_PUR_REQ_RCPT_STATUS_T (OLE_REQ_RCPT_STATUS_ID,OLE_REQ_RCPT_STATUS_DOC_TYP,OLE_REQ_RCPT_STATUS_CD,OLE_REQ_RCPT_STATUS_NM,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (9.0,'RCV','RCVD','Received',1.0,'9','Y')
/
