TRUNCATE TABLE SH_UOM_T DROP STORAGE
/
INSERT INTO SH_UOM_T (ITM_UOM_CD,OBJ_ID,VER_NBR,ITM_UOM_DESC,DOBJ_MAINT_CD_ACTV_IND)
  VALUES ('CO','2',1.0,'COPY','Y')
/
INSERT INTO SH_UOM_T (ITM_UOM_CD,OBJ_ID,VER_NBR,ITM_UOM_DESC,DOBJ_MAINT_CD_ACTV_IND)
  VALUES ('EA','1',1.0,'EACH','Y')
/
INSERT INTO SH_UOM_T (ITM_UOM_CD,OBJ_ID,VER_NBR,ITM_UOM_DESC,DOBJ_MAINT_CD_ACTV_IND)
  VALUES ('YR','3',1.0,'YEAR','Y')
/
